### ISSUE TITLE
Functional Testing 500 Error establishing a database connection

### ISSUE THREAD

**Issue by ajgagnon** [lucatume/wp-browser#101]
I'm having an issue with functional tests that I can't seem to figure out. It seems they can't run as it's having issues connecting to the database. I already have acceptance testing setup and it's working perfectly, however the same credentials don't seem to be working for functional testing. 

Any reason why it would work in one and not the other? I feel like I'm missing something simple. Any insight would be appreciated!

acceptance.suite.yml
```
# Codeception Test Suite Configuration
#
# Suite for acceptance tests.
# Perform tests in browser using the WPWebDriver or WPBrowser.
# Use WPDb to set up your initial database fixture.
# If you need both WPWebDriver and WPBrowser tests - create a separate suite.

actor: AcceptanceTester
modules:
    enabled:
        - WPDb
        - WPWebDriver
        - \Helper\Acceptance
    config:
        WPDb:
            dsn: mysql:host=192.168.75.100:4030;dbname=local
            user: root
            password: root
            dump: tests/_data/dump.sql
            populate: true #import the dump before the tests
            cleanup: true #import the dump between tests
            url: http://ph-test.dev
            urlReplacement: true #replace the hardcoded dump URL with the one above
            tablePrefix: wp_
        WPBrowser:
            url: http://ph-test.dev
            adminUsername: admin
            adminPassword: password
            adminPath: /wp-admin
        WPWebDriver:
            url: http://ph-test.dev
            browser: chrome
            port: 9515
            restart: false
            log_js_errors: true
            wait: 1
            adminUsername: admin
            adminPassword: password
            adminPath: /wp-admin
```
functional.suite.yml:

```
# Codeception Test Suite Configuration
#
# Suite for functional tests
# Emulate web requests and make WordPress process them

actor: FunctionalTester
modules:
    enabled:
        - WPDb
        - WordPress
        - Asserts
        - \Helper\Functional
    config:
        WPDb:
            dsn: mysql:host=192.168.75.100:4030;dbname=local
            user: root
            password: root
            dump: tests/_data/dump.sql
            populate: true #import the dump before the tests
            cleanup: true #import the dump between tests
            url: http://ph-test.dev
            urlReplacement: true #replace the hardcoded dump URL with the one above
            tablePrefix: wp_
        WordPress:
            depends: WPDb
            wpRootFolder: '/Users/andre/Local Sites/projecthuddle-test/app/public'
            adminUsername: 'admin'
            adminPassword: 'password'
```

Output with --debug:

```
WebsiteNewCest: Create a website
Signature: WebsiteNewCest:createAWebsite
Test: tests/functional/admin/WebsiteNewCest.php:createAWebsite
Scenario --
 I login as admin 
  [Cookie Jar] ["wordpress_test_cookie=WP%20Cookie%20check; path=/; httponly"]
  [Request Headers] []
  [Page] /wp-login.php
  [Response] 500
  [Request Cookies] {"wordpress_test_cookie":"WP Cookie check"}
  [Response Headers] {"Content-type":"text/html; charset=UTF-8","Set-Cookie":["wordpress_test_cookie=WP Cookie check"]}
 FAIL 

```
