### ISSUE TITLE
WPUnit Test with WordPress from another location

### ISSUE THREAD

**Issue by swashata** [lucatume/wp-browser#107]
I have been using WP CLI generated PHPUnit tests for developing WordPress plugins. Recently I switched to codeception for the acceptance tests happening in real browsers, so though about using wpunit tests for the existing unit tests too. So my setup is like this

* WordPress installation directory sits at `/home/swashata/dev/wptest/wordpress`
* My plugin development is happening at `/home/swashata/dev/vagrant/www/socialpress/public_html/wp-content/plugins/wpq-social-press` which as you might have guessed, is being used through [VVV](https://github.com/Varying-Vagrant-Vagrants/VVV)
* I run all tests and automation stuff from my host OS (Ubuntu 16.04) and NOT from my guest OS (VVV uses Ubuntu trusty 14.04). This is why I have a separate mariadb and PHP running within my host OS.

When I was using WP CLI generated PHPUnit for testing my WordPress, it would usually create a bootstrap file which would just include my plugin as a `mu-plugin` for the WordPress.

```php
$_tests_dir = getenv( 'WP_TESTS_DIR' );
if ( ! $_tests_dir ) {
	$_tests_dir = '/tmp/wordpress-tests-lib';
}

// Give access to tests_add_filter() function.
require_once $_tests_dir . '/includes/functions.php';

/**
 * Manually load the plugin being tested.
 */
function _manually_load_plugin() {
	require dirname( dirname( dirname( __FILE__ ) ) ) . '/wpq-social-press.php';
}
tests_add_filter( 'muplugins_loaded', '_manually_load_plugin' );

// Start up the WP testing environment.
require $_tests_dir . '/includes/bootstrap.php';
```

This is good because it keeps the development WordPress environment separate from Unit Test WordPress environments.

But when going through the setup of wp-browser/codeception wpunit suits, I have found that I can not do that (or maybe I am missing something). The setup needs to satisfy either of two options

1. I can use the same WordPress environment, thereby same db and stuff that I use for the actual development of the plugin (the one residing at `/home/swashata/dev/vagrant/www/socialpress/public_html/`)
2. I can instruct wp-browser to use WordPress installation from elsewhere like this
```yml
# Codeception Test Suite Configuration
#
# Suite for unit or integration tests that require WordPress functions and classes.

actor: WpunitTester
modules:
    enabled:
        - WPLoader
        - \Helper\Wpunit
    config:
        WPLoader:
            wpRootFolder: '/home/swashata/dev/wptest/wp-cc-sp'
            dbName: "wpsp"
            dbHost: "localhost"
            dbUser: "wpsp"
            dbPassword: "wpsp"
            tablePrefix: "wp_"
            domain: "wpsp.local"
            adminEmail: "admin@wpsp.local"
            title: "Test"
```
But then, I have to manually load the main plugin file through the `_bootstrap.php` file in a hackish way.
```php
<?php
/**
 * Manually load the plugin being tested.
 */
require dirname( dirname( dirname( __FILE__ ) ) ) . '/wpq-social-press.php';
```

Option 1 is not feasible. Not only would it break my local development environment by resetting all data (and also I don't want to change wp-config.php everytime to use a separate db when testing and when developing), but also it is not suitable for CI environment. I use gitlab CI and there manually copying the plugin files to a WordPress installation, editing `wp-config.php` etc would be a pain. I have a [docker](https://hub.docker.com/r/wpquark/wptest-php-nodejs-grunt/) that has all the needed stuff.

Option 2 works, but I find it hackish. First of all, because `tests_add_filter` is not available in the bootstrap file. If I do

```php
function _manually_load_plugin() {
	require dirname( dirname( dirname( __FILE__ ) ) ) . '/wpq-social-press.php';
}
tests_add_filter( 'muplugins_loaded', '_manually_load_plugin' );
```
In the `_bootstrap.php` file, it doesn't work. But at some stage, the tests library are loaded. So within `_bootstrap.php` file, if I try to manually include the WordPress test library

```php
$_tests_dir = getenv( 'WP_TESTS_DIR' );
if ( ! $_tests_dir ) {
	$_tests_dir = '/tmp/wordpress-tests-lib';
}

// Give access to tests_add_filter() function.
require_once $_tests_dir . '/includes/functions.php';
```

Then it dies with error because same functions are declared twice.
```
Fatal error: Cannot redeclare tests_reset__SERVER() (previously declared in /home/swashata/dev/vagrant/www/socialpress/public_html/wp-content/plugins/wpq-social-press/vendor/lucatume/wp-browser/src/includes/functions.php:9) in /home/swashata/dev/wptest/wordpress-tests-lib/includes/functions.php on line 20
```

So my questions are

1. How can I access the `tests_add_filter` before WordPress is loaded, so that I can load my plugin in the same way WP CLI PHPUnit does?
2. Is there any other preferred method that I am missing?

**Comment by lucatume** [comment]
Hi there, thanks for opening an issue and taking the time to provide so much detail.
I'm labeling it a "question" for the time being and replying to the last 2 questions immediately; later I will take the time to read the whole issue.

1. using the `plugins` and `activatePlugins` parameters of the [WPLoader module](https://github.com/lucatume/wp-browser#wploader-configuration); the first will `include` the plugin code before the tests; the second will `include` and activate the plugins code during the bootstrap installation process. PHPUnit-based tests should be run in the context of a suite that uses the `WPLoader` module, of course.d
2. I'd say no; take the time to read the documentation and look at [an example plugin](https://github.com/lucatume/idlikethis) doing what you want to do; the [integration suite configuration file](https://github.com/lucatume/idlikethis/blob/master/tests/integration.suite.dist.yml) and [an example test case](https://github.com/lucatume/idlikethis/blob/master/tests/integration/idlikethis/Repositories/CommentsRepositoryTest.php); mind that each test case is extending the `\Codeception\TestCase\WPTestCase` class provided by wp-browser

**Comment by swashata** [comment]
Hi,

I have actually gone through the example plugin. From my understanding the example plugin (or plugin under test) has to be inside a WordPress installation (`wp-content`). But for my unit test setup, this is not the case. I will try to explain it better.

Let us assume the following scenario:

1. I have wordpress installation (specifically for tests) with all needed db and stuff residing at `/home/swashata/dev/wptest/wordpress`. Note that there isn't any `wp-content/plugins/my-plugin` directory inside the mentioned wordpress installation directory.

2. The plugin which I am willing to test is under `/home/swashata/dev/some-dir/my-plugin/`.

Now what I essentially need is a way to, tell WordPress at `/home/swashata/dev/wptest/wordpress` to include and activate plugin from `/home/swashata/dev/some-dir/my-plugin/` without having to copy the directory `/home/swashata/dev/some-dir/my-plugin/` to `/home/swashata/dev/wptest/wordpress/wp-content/plugins/my-plugin`.

I hope I am being clear here. Both the `plugins` and `activatePlugins` parameters would need `my-plugin/my-plugin.php` to be inside `/home/swashata/dev/wptest/wordpress/wp-content/plugins/`. This is not what I want. Like in WP CLI driven PHPUnit tests, we can have the plugin anywhere outside the WordPress test directory and the module would still load the plugin through some filter.

**Comment by lucatume** [comment]
Symbolically linking plugins from a repository folder to a local WordPress installation folder is a common setup that I use too; either do it by hand or [use the Symlinker extension](https://github.com/lucatume/wp-browser#symlinker).

**Comment by swashata** [comment]
Sorry for the delay. The symlink seems to be a solution. I will test it out and let you know.

**Comment by swashata** [comment]
Hi,

I have tried with symlink extension and it works just great. I can finally move from PHPUnit package. I do have a question though.

When I use the `plugins` in the `WPLoader` module, it works just fine. But if I use `activatePlugins` then tests fails complaining about missing classes (so plugin files are not loaded). Is the `activatePlugins` meant for activating dependency plugins and not the core plugin (under development) itself?

**Comment by swashata** [comment]
One last thing is, is it possible at all to load the Symlink extension in the `wpunit.suite.yml` file? I have the following as `wpunit.suite.yml` and it doesn't seem to work. The extension is never loaded and thereby symlinking is never done.

```yml
actor: WpunitTester
extensions:
  enabled:
    - tad\WPBrowser\Extension\Symlinker
  config:
    tad\WPBrowser\Extension\Symlinker:
      mode: plugin
      destination: '%WP_CORE_DIR%/wp-content/plugins'
modules:
  enabled:
    - WPLoader
    - \Helper\Wpunit
  config:
    WPLoader:
      wpRootFolder: '%WP_CORE_DIR%'
      dbName: "wpsp"
      dbHost: "localhost"
      dbUser: "wpsp"
      dbPassword: "wpsp"
      tablePrefix: "wp_"
      domain: "wpsp.local"
      adminEmail: "admin@wpsp.local"
      title: "Test"
      plugins: [ "wpq-social-press/wpq-social-press.php" ]
```

However, as suggested in the [doc](https://github.com/lucatume/wp-browser#symlinker), if I add the extension in the `codeception.yml` file then it works just fine (although then it breaks my acceptance tests, because that happens in a docker and I don't need symlinking there, I just copy using `docker cp`).

Going through the official codeception [documentation](http://codeception.com/docs/08-Customization#Enabling-Extension), it seems to be possible to add the extensions block in the `wpunit.suite.yml` file, but I don't know why this is not working.

Right now, my workaround is to have something like this in the `codeception.yml` file.

```yml
paths:
  tests: tests
  output: tests/_output
  data: tests/_data
  support: tests/_support
  envs: tests/_envs
settings:
  bootstrap: _bootstrap.php
  colors: true
  memory_limit: 1024M
actor_suffix: Tester
params:
  - env
coverage:
  enabled: true
  include:
    - includes/*
extensions:
  enabled:
    - Codeception\Extension\RunFailed
  commands:
    - Codeception\Command\GenerateWPUnit
    - Codeception\Command\GenerateWPRestApi
    - Codeception\Command\GenerateWPRestController
    - Codeception\Command\GenerateWPRestPostTypeController
    - Codeception\Command\GenerateWPAjax
    - Codeception\Command\GenerateWPCanonical
    - Codeception\Command\GenerateWPXMLRPC
    - Codeception\Command\DbSnapshot
    - tad\Codeception\Command\SearchReplace
  config:
    tad\WPBrowser\Extension\Symlinker:
      mode: plugin
      destination: '%WP_CORE_DIR%/wp-content/plugins'
```

Then call the wpunit suite specifically with the extension

```bash
vendor/bin/codecept run wpunit --coverage --ext "tad\WPBrowser\Extension\Symlinker"
```

This all is very strange, because in my `acceptance.suite.yml` file I am loading extensions which is working just great.

```yml
actor: AcceptanceTester
modules:
  enabled:
    - WPWebDriver
    - \Helper\Acceptance
  config:
    WPWebDriver:
      url: 'http://localhost'
      wait: 5
      browser: chrome
      port: 9515
      adminUsername: 'user'
      adminPassword: 'bitnami'
      adminPath: '/wp-admin'
      window_size: false
      capabilities:
        useAutomationExtension: false
        chromeOptions:
          args: ["window-size=1920x1080", "--ignore-certificate-errors", "--no-sandbox"]
          binary: "/usr/bin/chromium-browser"
extensions:
  enabled:
    - Codeception\Extension\Recorder
  config:
    Codeception\Extension\Recorder:
      module: WPWebDriver # enable for Angular
      delete_successful: false # keep screenshots of successful tests
```
