### ISSUE TITLE
mysqli_query(): Couldn't fetch mysqli

### ISSUE THREAD

**Issue by sky4git** [lucatume/wp-browser#164]
I am running WPUnit tests and I am always getting mysqli_query(): Couldn't fetch mysqli error when I run a test case which interacts with database.

For non database interacting test cases, it works fine.

![image](https://user-images.githubusercontent.com/8438024/40091867-8afa0cba-58fd-11e8-9972-c17cb9f8a304.png)

I cannot figure out that it is a bug with codeception or something i need to pur into wpunit.suite.yml file.

Following is my wpunit.suite.yml file.
```
# Codeception Test Suite Configuration

actor: WpunitTester
modules:
    enabled:
        - WPLoader
        - \Helper\Wpunit
    config:
        WPLoader:
            multisite: false
            wpRootFolder: "M:/wordpress"
            dbName: "wordpress_dev_loader_2"
            dbHost: "localhost"
            dbUser: "root"
            dbPassword: "admin"
            title: "Test blog"
            wpDebug: true
            phpBinary: "php"
            theme: mytheme
            configFile: "tests/wp-config-tests.php"
            tablePrefix: 'wp_'
```

FYI: wp-config-tests.php just deine few wordpress globals so there is no issue with that.
