### ISSUE TITLE
WPLoader not bringing up database

### ISSUE THREAD

**Issue by discoinfiltrator** [lucatume/wp-browser#165]
When running my integration test suite with an empty database, WPLoader isn't creating any database tables. The database 'wordpress_codeception' does exist. Sample output:

```
$ vendor/bin/codecept run integration
Codeception PHP Testing Framework v2.3.9
Powered by PHPUnit 6.5.8 by Sebastian Bergmann and contributors.
WordPress database error Table 'wordpress_codeception.wp_options' doesn't exist for query INSERT INTO `wp_options`
```

Running on PHP 7.1.14 with package versions:

```
"lucatume/codeception-setup-local" => 1.0.3
"lucatume/wp-browser" => 2.1.4
"lucatume/wp-browser-commons" => 1.2.8.2
"lucatume/wp-snaphot-assertions" => 1.0.0
"codeception/codeception" => 2.3.9
"phpunit/phpunit" => 6.5.8
```

Here's my integration.suite.yml file:

```
class_name: IntegrationTester
modules:
    enabled:
        - \Helper\Integration
        - WPLoader
    config:
        WPLoader:
            wpRootFolder: web/
            multisite: true
            loadOnly: false
            dbName: wordpress_codeception
            dbHost: 127.0.0.1
            dbUser: root
            dbPassword: root
            wpDebug: false
            tablePrefix: wp_
            domain: example.com
            theme: my-theme
            configFile: app/wp-config/wp-config-codeception.php
            isolatedInstall: true
```

Any idea what might be the cause?
