### ISSUE TITLE
Trouble using wp_query in a wpunit test through a class

### ISSUE THREAD

**Issue by svwielga4** [lucatume/wp-browser#184]
I am trying to setup a test to count the number of a custom post in the db as the first step to a more robust test, but it's not working properly. I've been trying to get it to work for a few days and I could use some help (please!) Here's a copy of what I have:

``` php
<?php
// codecept run wpunit RWA:CourseModelsTest

namespace RWA;

require_once get_template_directory() . '/models/course.php';

class CourseModelsTest extends \Codeception\TestCase\WPTestCase {
    /**
     * @var \WpunitTester
     */
    protected $tester;

    protected function _before() {

    }

    protected function _after() {
    }

    // tests
    public function testSomeFeature() {

        $query = \Course::count();
        $this->assertEquals( 53, $query );
    }
}
```
Inside my model, here is what the function looks like
``` php
    public static function count() {
        $args = array(
            'posts_per_page' => -1,
            'offset' => 0,
            'post_type' => 'courses',
            'post_status' => 'all',
            'suppress_filters' => true,
        );
        $query = new \WP_Query( $args );
        return $query->post_count;
    }
```
But when it gets to the assertion, it says that 53 is not equal to 0. If i try to return 53 from the method, the test will pass. So it looks like wp query isnt doing what I expect.

Locally I'm running a multisite wordpress instance, and I'm not sure how to setup the config to target the right table / db.

I found a useBlog method in the module files of wploader, and a multisite option, but having trouble getting it to do what i want -- use wp_query through my class, on blog 2. If anyone has any spare time I would greatly appreciate help 🙏🏼.

Here's the rest of my config, what I'm assuming is relevant. Thank you.

```
paths:
tests: tests
output: tests/_output
data: tests/_data
support: tests/_support
envs: tests/_envs
actor_suffix: Tester
modules:
config:
    WPDb:
        dsn: 'mysql:host=%DB_HOST%;dbname=%DB_NAME%'
        user: '%DB_USER%'
        password: '%DB_PASSWORD%'
        dump: 'tests/_data/dump.sql'
        populate: true #import the dump before the tests
        cleanup: false #import the dump between tests
        url: '%WP_URL%'
        urlReplacement: true #replace the hardcoded dump URL with the one above
        tablePrefix: '%TABLE_PREFIX%'
        waitlock: 0
    WPBrowser:
        url: '%WP_URL%'
        adminUsername: '%ADMIN_USERNAME%'
        adminPassword: '%ADMIN_PASSWORD%'
        adminPath: '%WP_ADMIN_PATH%'
    WPFilesystem:
        wpRootFolder: '%WP_ROOT_FOLDER%'
        plugins: '/wp-content/plugins'
        mu-plugins: '/wp-content/mu-plugins'
        themes: '/wp-content/themes'
        uploads: '/wp-content/uploads'
    WPLoader:
        wpRootFolder: "%WP_ROOT_FOLDER%"
        dbName: "%TEST_DB_NAME%"
        dbHost: "%TEST_DB_HOST%"
        dbUser: "%TEST_DB_USER%"
        dbPassword: "%TEST_DB_PASSWORD%"
        tablePrefix: "%TEST_TABLE_PREFIX%"
        domain: "%WP_DOMAIN%"
        adminEmail: "%ADMIN_EMAIL%"
        title: "Test"
        theme: retirement-wealth-academy
        plugins: ['']
        activatePlugins: ['']
    WPWebDriver:
        url: '%WP_URL%'
        adminUsername: '%ADMIN_USERNAME%'
        adminPassword: '%ADMIN_PASSWORD%'
        adminPath: '%WP_ADMIN_PATH%'
        capabilities:
            browserName: "chrome"
            javascriptEnabled: true
            webStorageEnabled: true
            nativeEvents: true
extensions:
enabled:
    - Codeception\Extension\RunFailed
commands:
    - Codeception\Command\GenerateWPUnit
    - Codeception\Command\GenerateWPRestApi
    - Codeception\Command\GenerateWPRestController
    - Codeception\Command\GenerateWPRestPostTypeController
    - Codeception\Command\GenerateWPAjax
    - Codeception\Command\GenerateWPCanonical
    - Codeception\Command\GenerateWPXMLRPC
    - Codeception\Command\DbSnapshot
    - tad\Codeception\Command\SearchReplace
params:
- .env
```
And for my specific suite

```
actor: WpunitTester
modules:
    enabled:
        - WPLoader
        - \Helper\Wpunit
        - WPDb
```
