### ISSUE TITLE
WPDb havePostInDatabase modifies table structure and returns Post ID zero

### ISSUE THREAD

**Issue by Luc45** [lucatume/wp-browser#188]
I have a Functional test which calls havePostInDatabase:

```
$content = 'Lorem ipsum [test_shortcode_124]';
$post_id = $I->havePostInDatabase(['post_name' => 'Foo', 'post_content' => $content]);
```

However, $post_id returns (int) 0. The query doesn't thrown an PDOException.

Upon further debugging, I see that running the test modifies the wp_posts structure, like so:

Before running the test:
https://www.lucasbustamante.com.br/uploads/u/2018/11/dia-01_12h49m20s_chrome.png

After running the test:
https://www.lucasbustamante.com.br/uploads/u/2018/11/dia-01_12h49m57s_chrome.png

As you can see, it removed PRIMARY_KEY, AUTO_INCREMENT, etc. Is this behavior expected?

This is my functional.suite.yml
```
# Codeception Test Suite Configuration
#
# Suite for functional tests
# Emulate web requests and make WordPress process them

actor: FunctionalTester
modules:
    enabled:
        - WPDb
        - WPBrowser
        - WPFilesystem
        - Asserts
        - \Helper\Functional
    config:
        WPDb:
            dsn: 'mysql:host=%DB_HOST%;dbname=%DB_NAME%'
            user: '%DB_USER%'
            password: '%DB_PASSWORD%'
            dump: 'tests/_data/dump.sql'
            populate: true
            cleanup: true
            waitlock: 0
            url: '%WP_URL%'
            urlReplacement: true
            tablePrefix: '%TABLE_PREFIX%'
        WPBrowser:
            url: '%WP_URL%'
            adminUsername: '%ADMIN_USERNAME%'
            adminPassword: '%ADMIN_PASSWORD%'
            adminPath: '%WP_ADMIN_PATH%'
        WPFilesystem:
            wpRootFolder: '%WP_ROOT_FOLDER%'
            plugins: '/wp-content/plugins'
            mu-plugins: '/wp-content/mu-plugins'
            themes: '/wp-content/themes'
            uploads: '/wp-content/uploads'
```

Also, I would expect it to run tests from %TEST_DB_NAME%, shouldn't that be the default behavior?

All the best,
Lucas
