### ISSUE TITLE
Ability to flush permalinks on functional tests?

### ISSUE THREAD

**Issue by ryanshoover** [lucatume/wp-browser#190]
We're trying to write tests to ensure that WordPress will render our pretty permalinks correctly. We've got a number of complex structures that can overlap, so we don't just want to confirm that regex exists in the database.

Right now I've written a test that looks for the pretty permalink URL. The DB dump I'm importing doesn't include the `rewrite_rules` option populated as I want to test that WP will generate the correct rewrite rules and the page will render at the correct path. Is there a way to call `flush_rewrite_rules` or some equivalent inside a functional test?

Test code
```php
$I->havePostInDatabase(
	[
		'post_title'  => 'Test Support Post',
		'post_name'   => 'test-support-post',
		'post_type'   => 'support',
		'post_status' => 'publish',
	]
);

$I->amOnPage( '/support/test-support-post/' );
$I->see( 'Test Support Post' );
```

functional.suite.yml
```yaml
actor: FunctionalTester
modules:
    enabled:
        - WPDb
        - WordPress
        - Asserts
        - \Helper\Functional
    config:
        WPDb:
            dsn: 'mysql:host=%DB_HOST%;dbname=%DB_NAME%'
            user: '%DB_USER%'
            password: '%DB_PASSWORD%'
            dump: 'tests/_data/minimal.sql'
            populate: true #import the dump before the tests
            cleanup: true #import the dump between tests
            reconnect: true
            waitlock: 0
            url: '%WP_URL%'
            urlReplacement: true #replace the hardcoded dump URL with the one above
            tablePrefix: '%WP_TABLE_PREFIX%'
        WordPress:
            depends: WPDb
            wpRootFolder: '/var/www/html'
            adminUsername: 'admin'
            adminPassword: 'admin'
```

**Comment by ryanshoover** [comment]
@Luc45 Good call! I missed the obvious. I've changed my test's `_before` hook to visit the permalinks page. ([Just visiting the page will flush the rewrite rules](https://github.com/WordPress/WordPress/blob/master/wp-admin/options-permalink.php#L162))

```php
public function _before( FunctionalTester $I ) {
	// Set up our rewrite rules.
	$I->haveOptionInDatabase( 'permalink_structure', '/blog/%postname%/' );
	$I->loginAs('admin', 'admin');
	$I->amOnAdminPage('options-permalink.php');
}
```

I assume that WordPress is loaded when using the `WordPress` module. But I just don't know how to access its methods. It would be faster to call `flush_rewrite_rules` in the code, but at least I can get the tests passing.

**Comment by lucatume** [comment]
@ryanshoover the fastest way to do it, and an alternative to the correct method proposed by @Luc45 is to:
1. add the `WPLoader` module to the suite setting it to `loadOnly`; WordPress will be loaded in the same context as your tests too
2. from your tests call the `lush_rewrite_rules()` function; in this case the effect will be saved to the database and the test site will use it.

**Comment by ryanshoover** [comment]
Fantastic! For future reference, I'm including my setup below for anyone else who may be interested.

These are excerpts of the files

`functional.suite.yml`
```yml
actor: FunctionalTester
modules:
    enabled:
        - WPDb
        - WordPress
        - WPLoader
        - Asserts
        - \Helper\Functional
    config:
        WPDb:
            dsn:            'mysql:host=%DB_HOST%;dbname=%DB_NAME%'
            user:           '%DB_USER%'
            password:       '%DB_PASSWORD%'
            dump:           'tests/_data/minimal.sql'
            populate:       true
            cleanup:        true
            reconnect:      true
            waitlock:       0
            url:            '%WP_URL%'
            urlReplacement: true
            tablePrefix:    '%WP_TABLE_PREFIX%'
        WordPress:
            depends:        WPDb
            wpRootFolder:   '.'
            adminUsername:  'admin'
            adminPassword:  'admin'
            permalink:      '/blog/%postname%/'
        WPLoader:
            loadOnly:       true
            wpRootFolder:   '.'
            dbName:         '%DB_NAME%'
            dbHost:         '%DB_HOST%'
            dbUser:         '%DB_USER%'
            dbPassword:     '%DB_PASSWORD%'
```

`tests/_support/Helper/Functional.php`
```php

/**
 * Add our permalink structure and setup rewrite rules
 *
 * @link https://github.com/lucatume/wp-browser/issues/190
 */
public function haveRewriteRules() {
	update_option( 'permalink_structure', $this->config['permalink_structure'] );
	flush_rewrite_rules();
}
```

`tests/functional/PostTypesCest.php`
```php
/**
 * Set up the pages before we run our tests.
 *
 * @param FunctionalTester $I Instance of FunctionalTester.
 */
public function _before( FunctionalTester $I ) {
	$I->haveRewriteRules();
}
