### ISSUE TITLE
Error after running tests upon exiting

### ISSUE THREAD

**Issue by unfulvio** [lucatume/wp-browser#195]
I am able to run any test with `codecept run...`, however after all tests I see an error message in console:

```shell
In ErrorHandler.php line 83:
                                                                       
  unlink(/srv/www/`<site-name>`/public_html/wp-content/plugins/`<plugin-name-I-am-testing>`): Is a directory    
```

I tried to trace the cause of the error but couldn't determine it.

Mind I'm running the tests from a VVV (Varying Vagrant Vagrants) instance and the plugin source is shared from my local machine to the Vagrant box using Vagrant NFS shares.

Sort of semi-unrelated, to run tests successfully I had to remove rerferences to helpers from the `.yml` files as Codeception would always complain it couldn't find them. I was not using those helpers and they were empty classes, so I just removed them, but thought I'd mention to you here.

Cheers

**Comment by lucatume** [comment]
Hi,

removing helpers is part of the customization Codeception, and by extension, wp-browser, allows so it's all fine and planned there.

From the look of the error it seems like you are symbolically linking the plugin into the `plugins` folder of the WordPress installation; could you provide your configuration (with anonymization) and more details about your setup?
Ideally, using XDebug, a trace of that error too.

Keep me posted,

**Comment by unfulvio** [comment]
Hi,

I've enabled xdebug on VVV but running the tests I don't see an output from xdebug (at least I'm not sure if I'm looking in the right places...). I may have an output if I browse the site with a browser in case of errors, which I don't have at the moment...

To sync the folder in the virtual machine with my local machine I'm merely using a Customfile provided by VVV, by adding:

```shell
config.vm.synced_folder "/path/to/my/local/plugin-dir", "/srv/www/vvv-site/public_html/wp-content/plugins/plugin-dir", type: "nfs"
```

I've enabled NFS shares but there's no difference with regular Virtualbox shares.

This setup allows me to run development locally from a git repo and pick up changes instantly on a development site running on VVV. Ideally, I'd like to maintain this while running tests. I run tests after ssh'ing into VVV. The error appears there.

Then, inside the plugin project I'm testing, this is what `codeception.yml` looks like:

```yml
paths:
    tests: tests
    output: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
actor_suffix: Tester
extensions:
    enabled:
        - Codeception\Extension\RunFailed
    commands:
        - Codeception\Command\GenerateWPUnit
        - Codeception\Command\GenerateWPRestApi
        - Codeception\Command\GenerateWPRestController
        - Codeception\Command\GenerateWPRestPostTypeController
        - Codeception\Command\GenerateWPAjax
        - Codeception\Command\GenerateWPCanonical
        - Codeception\Command\GenerateWPXMLRPC
        - Codeception\Command\DbSnapshot
params:
    - codeception.env
```

I have a bunch of envs inside `codeception.env` and that's all about it - tests (integration, acceptance) run, so I'd assume WP Browser is set up correctly.

**Comment by lucatume** [comment]
Hi, 

what you provided is the Codeception global configuration, not the suite configuration.
That's more telling; it should be a file called `tests/integration.suite.yml` or something in the format `tests/<suite>.suite.yml`.
Run the test(s) that is generating the error adding verbosity to Codeception output:
```bash
codecept run <suite_or_test> -vvv
```

That should provide a back-trace.
Furthermore, on VVV are you sure you have activated XDebug on the CLI too? You can find out with `php -v`: if XDebug is activated it should show something like this:
```
PHP 7.2.9 (cli) (built: Aug 23 2018 02:08:27) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.9, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.6.0, Copyright (c) 2002-2018, by Derick Rethans
```

**Comment by unfulvio** [comment]
yes xdebug is on, and thanks I didn't think of the verbose option - now I have:

```txt

In ErrorHandler.php line 83:
                                                                       
  [PHPUnit\Framework\Exception (2)]                                    
  unlink(/srv/www/my-plugin-dir/public_html/wp-content/plugins/my-plugin): Is a directory                                     
                                                                       

Exception trace:
 Codeception\Subscriber\ErrorHandler->errorHandler() at n/a:n/a
 unlink() at /srv/www/my-plugin-dir/public_html/wp-content/plugins/my-plugin/vendor/lucatume/wp-browser-commons/src/tad/WPBrowser/Filesystem/Filesystem.php:40
 tad\WPBrowser\Filesystem\Filesystem->unlink() at /srv/www/my-plugin-dir/public_html/wp-content/plugins/my-plugin/vendor/lucatume/wp-browser/src/tad/WPBrowser/Extension/Symlinker.php:100
 tad\WPBrowser\Extension\Symlinker->unlink() at /srv/www/my-plugin-dir/public_html/wp-content/plugins/my-plugin/vendor/symfony/event-dispatcher/EventDispatcher.php:212
 Symfony\Component\EventDispatcher\EventDispatcher->doDispatch() at /srv/www/my-plugin-dir/public_html/wp-content/plugins/my-plugin/vendor/symfony/event-dispatcher/EventDispatcher.php:44
 Symfony\Component\EventDispatcher\EventDispatcher->dispatch() at /srv/www/my-plugin-dir/public_html/wp-content/plugins/my-plugin/vendor/codeception/codeception/src/Codeception/SuiteManager.php:158
 Codeception\SuiteManager->run() at /srv/www/my-plugin-dir/public_html/wp-content/plugins/my-plugin/vendor/codeception/codeception/src/Codeception/Codecept.php:189
 Codeception\Codecept->runSuite() at /srv/www/my-plugin-dir/public_html/wp-content/plugins/my-plugin/vendor/codeception/codeception/src/Codeception/Codecept.php:158
 Codeception\Codecept->run() at /srv/www/my-plugin-dir/public_html/wp-content/plugins/my-plugin/vendor/codeception/codeception/src/Codeception/Command/Run.php:466
 Codeception\Command\Run->runSuites() at /srv/www/my-plugin-dir/public_html/wp-content/plugins/my-plugin/vendor/codeception/codeception/src/Codeception/Command/Run.php:361
 Codeception\Command\Run->execute() at /srv/www/my-plugin-dir/public_html/wp-content/plugins/my-plugin/vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at /srv/www/my-plugin-dir/public_html/wp-content/plugins/my-plugin/vendor/symfony/console/Application.php:946
 Symfony\Component\Console\Application->doRunCommand() at /srv/www/my-plugin-dir/public_html/wp-content/plugins/my-plugin/vendor/symfony/console/Application.php:248
 Symfony\Component\Console\Application->doRun() at /srv/www/my-plugin-dir/public_html/wp-content/plugins/my-plugin/vendor/symfony/console/Application.php:148
 Symfony\Component\Console\Application->run() at /srv/www/my-plugin-dir/public_html/wp-content/plugins/my-plugin/vendor/codeception/codeception/src/Codeception/Application.php:108
 Codeception\Application->run() at /srv/www/my-plugin-dir/public_html/wp-content/plugins/my-plugin/vendor/codeception/codeception/codecept:42

```

As for the suite config, I have:

acceptance.suite.yml:

```yml
actor: AcceptanceTester
modules:
    enabled:
        - WPDb
        - WPBrowser
    config:
        WPDb:
            dsn: 'mysql:host=%DB_HOST%;dbname=%DB_NAME%'
            user: '%DB_USER%'
            password: '%DB_PASSWORD%'
            dump: 'tests/_data/dump.sql'
            populate: true #import the dump before the tests
            cleanup: true #import the dump between tests
            waitlock: 0
            url: '%WP_URL%'
            urlReplacement: true #replace the hardcoded dump URL with the one above
            tablePrefix: '%TABLE_PREFIX%'
        WPBrowser:
            url: '%WP_URL%'
            adminUsername: '%ADMIN_USERNAME%'
            adminPassword: '%ADMIN_PASSWORD%'
            adminPath: '%WP_ADMIN_PATH%'
```

and integration.suite.yml:

```yml

actor: IntegrationTester
modules:
    enabled:
        - WPLoader
    config:
        WPLoader:
            wpRootFolder: "%WP_ROOT_FOLDER%"
            dbName: "%TEST_DB_NAME%"
            dbHost: "%TEST_DB_HOST%"
            dbUser: "%TEST_DB_USER%"
            dbPassword: "%TEST_DB_PASSWORD%"
            tablePrefix: "%TEST_TABLE_PREFIX%"
            domain: "%WP_DOMAIN%"
            adminEmail: "%ADMIN_EMAIL%"
			title: "Test"
            plugins: ['my-plugin-dir/my-plugin.php']
            activatePlugins: ['my-plugin-dir/my-plugin.php']

```

**Comment by Luc45** [comment]
Just a sidenote: often when I kill the test I have to restart mysql service due to WordPress database lock timeout. `sudo service mysql restart` - But I don't think that's the issue here.

Luca, how does Codeception handles interruptions with Cntrl+C? If I write to a database or to a file during a test, will it be cleaned up, like a transaction?

**Comment by lucatume** [comment]
Ok, the exception is coming from the `Symlinker` extension but I cannot see that in any of the configuration files you posted.
Is there any other configuration file codeception might be loading? E.g. `codeception.dist.yml` in the root folder or `tests/integraion.suite.dist.yml` or `tests/acceptance.suite.dist.yml`?

**Comment by unfulvio** [comment]
I have functional.suite.yml:

```yml
actor: FunctionalTester
modules:
    enabled:
        - WPDb
        - WPBrowser
        - Asserts
        # - WPFilesystem
    config:
        WPDb:
            dsn: 'mysql:host=%DB_HOST%;dbname=%DB_NAME%'
            user: '%DB_USER%'
            password: '%DB_PASSWORD%'
            dump: 'tests/_data/dump.sql'
            populate: true
            cleanup: true
            waitlock: 0
            url: '%WP_URL%'
            urlReplacement: true
            tablePrefix: '%TABLE_PREFIX%'
        WPBrowser:
            url: '%WP_URL%'
            adminUsername: '%ADMIN_USERNAME%'
            adminPassword: '%ADMIN_PASSWORD%'
            adminPath: '%WP_ADMIN_PATH%'
        WPFilesystem:
            wpRootFolder: '%WP_ROOT_FOLDER%'
            plugins: '/wp-content/plugins'
            mu-plugins: '/wp-content/mu-plugins'
            themes: '/wp-content/themes'
            uploads: '/wp-content/uploads'
```

and unit.suite.yml:

```yml
actor: UnitTester
modules:
    enabled:
        - Asserts
```

I don't have any tests for these two.

I have though a codeception.dist.yml which I'm supposed to override with the codeception.yml which I posted earlier:

```yml
paths:
    tests: tests
    output: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
actor_suffix: Tester
extensions:
    enabled:
        - Codeception\Extension\RunFailed
        - tad\WPBrowser\Extension\Symlinker
    commands:
        - Codeception\Command\GenerateWPUnit
        - Codeception\Command\GenerateWPRestApi
        - Codeception\Command\GenerateWPRestController
        - Codeception\Command\GenerateWPRestPostTypeController
        - Codeception\Command\GenerateWPAjax
        - Codeception\Command\GenerateWPCanonical
        - Codeception\Command\GenerateWPXMLRPC
        - Codeception\Command\DbSnapshot
        - tad\Codeception\Command\SearchReplace
    config:
      tad\WPBrowser\Extension\Symlinker:
        mode: plugin
        destination: '%WP_ROOT_FOLDER%/wp-content/plugins'
params:
    - env
```

This is because my colleagues are using a different test site which doesn't run on VVV and in their case they do symlink via Codeception's Symlinker.

codeception.dist.env and codeception.env.yml are identical for now

I looked for references to Symlinker in my tests folder, but none was found...
