### ISSUE TITLE
Using WPBootstrapper with any activated plugin generates an error

### ISSUE THREAD

**Issue by unfulvio** [lucatume/wp-browser#197]
I have WooCommerce and the plugin I'm testing in my WordPress install used in acceptance tests database dump. 

I wanted to try using the WPBootstrapper module to access some Wordpress functions to build some helper methods in AcceptanceTester.

Even though I want only to use WordPress functions, an error is thrown as soon as I call `$I->bootstrapWp()`:

```shell
1) LifecycleCept: 
 Test  tests/acceptance/Admin/LifecycleCept.php
                                                                          
  [ReflectionException] Function WC_Shortcodes::product() does not exist  
                                                                          

Scenario Steps:

 1. $I->bootstrapWp() at tests/_support/AcceptanceTester.php:48

/srv/www/wordpress/public_html/wp-content/plugins/my-plugin/vendor/lucatume/wp-browser/src/Codeception/Module/WPBootstrapper.php:184
/srv/www/wordpress/public_html/wp-content/plugins/my-plugin/vendor/lucatume/wp-browser/src/Codeception/Module/WPBootstrapper.php:172
/srv/www/wordpress/public_html/wp-content/plugins/my-plugin/vendor/lucatume/wp-browser/src/Codeception/Module/WPBootstrapper.php:169
/srv/www/wordpress/public_html/wp-content/plugins/my-plugin/vendor/lucatume/wp-browser/src/Codeception/Module/WPBootstrapper.php:154
/srv/www/wordpress/public_html/wp-content/plugins/my-plugin/vendor/lucatume/wp-browser/src/Codeception/Module/WPBootstrapper.php:100
/srv/www/wordpress/public_html/wp-content/plugins/my-plugin/vendor/codeception/codeception/src/Codeception/Step.php:264
/srv/www/wordpress/public_html/wp-content/plugins/my-plugin/vendor/codeception/codeception/src/Codeception/Scenario.php:72
/srv/www/wordpress/public_html/wp-content/plugins/my-plugin/tests/_support/_generated/AcceptanceTesterActions.php:5340
/srv/www/wordpress/public_html/wp-content/plugins/my-plugin/tests/_support/AcceptanceTester.php:48
/srv/www/wordpress/public_html/wp-content/plugins/my-plugin/tests/acceptance/Admin/LifecycleCept.php:30
/srv/www/wordpress/public_html/wp-content/plugins/my-plugin/vendor/codeception/codeception/src/Codeception/Test/Cept.php:42
/srv/www/wordpress/public_html/wp-content/plugins/my-plugin/vendor/codeception/codeception/src/Codeception/Test/Test.php:89
/srv/www/wordpress/public_html/wp-content/plugins/my-plugin/vendor/phpunit/phpunit/src/Framework/TestSuite.php:750
/srv/www/wordpress/public_html/wp-content/plugins/my-plugin/vendor/codeception/phpunit-wrapper/src/Runner.php:114
/srv/www/wordpress/public_html/wp-content/plugins/my-plugin/vendor/codeception/codeception/src/Codeception/SuiteManager.php:157
/srv/www/wordpress/public_html/wp-content/plugins/my-plugin/vendor/codeception/codeception/src/Codeception/Codecept.php:189
/srv/www/wordpress/public_html/wp-content/plugins/my-plugin/vendor/codeception/codeception/src/Codeception/Codecept.php:158
/srv/www/wordpress/public_html/wp-content/plugins/my-plugin/vendor/codeception/codeception/src/Codeception/Command/Run.php:355
/srv/www/wordpress/public_html/wp-content/plugins/my-plugin/vendor/symfony/console/Command/Command.php:255
/srv/www/wordpress/public_html/wp-content/plugins/my-plugin/vendor/symfony/console/Application.php:946
/srv/www/wordpress/public_html/wp-content/plugins/my-plugin/vendor/symfony/console/Application.php:248
/srv/www/wordpress/public_html/wp-content/plugins/my-plugin/vendor/symfony/console/Application.php:148
/srv/www/wordpress/public_html/wp-content/plugins/my-plugin/vendor/codeception/codeception/src/Codeception/Application.php:108
/srv/www/wordpress/public_html/wp-content/plugins/my-plugin/vendor/codeception/codeception/codecept:42
```

In this case the error comes from the presence of a WooCommerce shortcode. If I activate my plugin, another similar error originating from one of my plugin's shortcodes appears instead.

This is my `acceptance.suite.yml` config:

```yml

actor: AcceptanceTester
modules:
    enabled:
        - WPDb
        - WPBrowser
        - WPCLI
        - WPBootstrapper
    config:
        WPDb:
            dsn: 'mysql:host=%DB_HOST%;dbname=%DB_NAME%'
            user: '%DB_USER%'
            password: '%DB_PASSWORD%'
            dump: 'tests/_data/dump.sql'
            populate: true #import the dump before the tests
            cleanup: true #import the dump between tests
            waitlock: 0
            url: '%WP_URL%'
            urlReplacement: true #replace the hardcoded dump URL with the one above
            tablePrefix: '%TABLE_PREFIX%'
        WPBrowser:
            url: '%WP_URL%'
            browser: phantomjs
            window_size: '1024x768'
            adminUsername: '%ADMIN_USERNAME%'
            adminPassword: '%ADMIN_PASSWORD%'
            adminPath: '%WP_ADMIN_PATH%'
        WPCLI:
            path: '%WP_ROOT_FOLDER%'
            throw: true
        WPBootstrapper:
            wpRootFolder: '%WP_ROOT_FOLDER%'
```

I am using VVV to share the plugin folder from my localmachine with the Vagrant box. However, WooCommerce lives in the Vagrant box and it's not a shared/symlinked folder.

I suspect this may have to do with the fact plugins can't be bootstrapped at all... I suppose it's fine, so the only way around this is to disable plugins while the I perform some code logic using bootstraped WP? And is correct to re-enable them afterwards to continue with acceptance testing? Just want to check if I'm doing it right, thanks.

**Comment by lucatume** [comment]
The `WPBootstrapper` module will be removed in the next version of `wp-browser`: replace it with thte `WPLoader` one in `loadOnly` mode; see the README for this.
In the case of your specific configuration the `acceptance.suite.yml` file would change to:

```yaml
actor: AcceptanceTester
modules:
    enabled:
        - WPDb
        - WPBrowser
        - WPCLI
        - WPLoader
    config:
        WPDb:
            dsn: 'mysql:host=%DB_HOST%;dbname=%DB_NAME%'
            user: '%DB_USER%'
            password: '%DB_PASSWORD%'
            dump: 'tests/_data/dump.sql'
            populate: true #import the dump before the tests
            cleanup: true #import the dump between tests
            waitlock: 0
            url: '%WP_URL%'
            urlReplacement: true #replace the hardcoded dump URL with the one above
            tablePrefix: '%TABLE_PREFIX%'
        WPBrowser:
            url: '%WP_URL%'
            browser: phantomjs
            window_size: '1024x768'
            adminUsername: '%ADMIN_USERNAME%'
            adminPassword: '%ADMIN_PASSWORD%'
            adminPath: '%WP_ADMIN_PATH%'
        WPCLI:
            path: '%WP_ROOT_FOLDER%'
            throw: true
        WPLoader:
	    loadOnly: true 
            wpRootFolder: '%WP_ROOT_FOLDER%'
	    dbName: "%DB_NAME%"
	    dbHost: "%DB_HOST%"
	    dbUser: "%DB_USER%"
	    dbPassword: "%DB_PASSWORD%"
```

WPLoader will only load WordPress in the scope of your tests along-side the other modules. Provided your staring database fixture, the dump, does activate all the required plugins and/or themes their code will be available in the tests as it would in the code.  

Let me know if this works, thanks for taking the time to open an issue and provide the details.
