### ISSUE TITLE
Preserving database when using WPLoader with loadOnly and WPDb?

### ISSUE THREAD

**Issue by Luc45** [lucatume/wp-browser#205]
Hi Luca,

I'm facing some problems trying to create REST tests.

I didn't use **WPRestApiTestCase**, because I didn't see how I would send a GET request it with. Should I do it on my own, with CURL or Guzzle?

I then proceeded to use [REST module](https://codeception.com/docs/modules/REST) from Codeception in a functional test.

My REST test looks like this right now:

```php
public function should_return_successful_response_for_valid_product(FunctionalTester $I)
{
    $product = Product::generate_simple_product(30, 30, 30, 30);

    $url = 'calculate/' . $product->get_id() . '/30360230';

    $I->sendGET($url);

    $I->dontHaveInDatabase('wp_postmeta', ['post_id' => $product->get_id()]);
    $I->dontHaveInDatabase('wp_posts', ['ID' => $product->get_id()]);
    $I->dontHaveInDatabase('wp_posts', ['ID' => get_post_thumbnail_id($product->get_id())]);

    $I->seeResponseCodeIsSuccessful();
}   
```

And this is my functional.suite.yml:

```yml
actor: FunctionalTester
modules:
    enabled:
        - WPDb
        - WPBrowser
        - Asserts
        - \Helper\Functional
        - REST:
           depends: WPBrowser
           url: 'http://cfpp.localhost/wp-json/cfpp/v1/'
        - WPLoader
    config:
        WPLoader:
            loadOnly: true
            wpRootFolder: '%WP_ROOT_FOLDER%'
            dbName: '%TEST_SITE_DB_NAME%'
            dbHost: '%TEST_SITE_DB_HOST%'
            dbUser: '%TEST_SITE_DB_USER%'
            dbPassword: '%TEST_SITE_DB_PASSWORD%'
        WPDb:
            dsn: 'mysql:host=%TEST_SITE_DB_HOST%;dbname=%TEST_SITE_DB_NAME%'
            user: '%TEST_SITE_DB_USER%'
            password: '%TEST_SITE_DB_PASSWORD%'
            dump: 'tests/_data/dump.sql'
            populate: false
            cleanup: false
            waitlock: 0
            url: '%WP_URL%'
            urlReplacement: false
            tablePrefix: '%TEST_SITE_TABLE_PREFIX%'
        WPBrowser:
            url: '%WP_URL%'
            adminUsername: '%ADMIN_USERNAME%'
            adminPassword: '%ADMIN_PASSWORD%'
            adminPath: '%WP_ADMIN_PATH%'
        WPFilesystem:
            wpRootFolder: '%WP_ROOT_FOLDER%'
            plugins: '/wp-content/plugins'
            mu-plugins: '/wp-content/mu-plugins'
            themes: '/wp-content/themes'
            uploads: '/wp-content/uploads'
```

As you can see in my example, I'm manually deleting everything created during the test, but I have to modify the database more agressively for further testing, such as deleting all shipping zones, creating new ones, etc.

How can I configure the suite to cleanup and populate the database based on the dump, while still having access to WordPress functions?

Thanks a lot,
Lucas
