### ISSUE TITLE
Support for dontSeeElementInDOM?

### ISSUE THREAD

**Issue by raptor235** [lucatume/wp-browser#214]
I'm sure I must be doing something wrong... Just experimenting for the first time

But I can't get 

```
$I->dontSeeElementInDOM('.author-other .edit');

```

to fire... I'm seeing 

RuntimeException] Call to undefined method AcceptanceTester::dontSeeElementInDOM

my config for acceptance is as follows

```
# Codeception Test Suite Configuration
#
# Suite for acceptance tests.
# Perform tests in browser using the WPWebDriver or WPBrowser.
# Use WPDb to set up your initial database fixture.
# If you need both WPWebDriver and WPBrowser tests - create a separate suite.

actor: AcceptanceTester
modules:
    enabled:
        - WPDb
        - WPBrowser
        - \Helper\Acceptance
    config:
        WPDb:
            dsn: 'mysql:host=%TEST_SITE_DB_HOST%;dbname=%TEST_SITE_DB_NAME%'
            user: '%TEST_SITE_DB_USER%'
            password: '%TEST_SITE_DB_PASSWORD%'
            dump: 'tests/_data/dump.sql'
            #import the dump before the tests; this means the test site database will be repopulated before the tests.
            populate: true 
            # re-import the dump between tests; this means the test site database will be repopulated between the tests.
            cleanup: true 
            waitlock: 0
            url: '%TEST_SITE_WP_URL%'
            urlReplacement: true #replace the hardcoded dump URL with the one above
            tablePrefix: '%TEST_SITE_TABLE_PREFIX%'
        WPBrowser:
            url: '%TEST_SITE_WP_URL%'
            adminUsername: '%TEST_SITE_ADMIN_USERNAME%'
            adminPassword: '%TEST_SITE_ADMIN_PASSWORD%'
            adminPath: '%TEST_SITE_WP_ADMIN_PATH%'

```

```
<?php 

// use \Codeception\Util\Locator;


class WPFirstCest
{
    public function _before(AcceptanceTester $I)
    {
    }

    // tests
    public function tryToTest(AcceptanceTester $I)
    {

        // $I = new AcceptanceTester($scenario);
        $I->wantTo('access the homepage of the site');
        $I->amOnPage('/');
        $I->seeElement('body.home');

        // $I->seeElement('body.bart');

    }

    public function contributorTest0(AcceptanceTester $I)
    {

        $I->wantTo('As contributor I should not be able to edit forms.');
        $I->amOnPage('/');
        $I->loginAs('contributor', 'contributor');
        // $I->dontSeeElement('div.wp-menu-name', Ninja Forms);
        $I->dontSeeElement('div.wp-menu-name:contains(Ninja Forms)');

    }

    public function contributorTest(AcceptanceTester $I){

        $I->wantTo('As contributor I should not be able to access other\'s post_types');
        $I->loginAs('contributor','contributor');
        $I->amOnPage('/wp-admin/edit.php?post_type=story&all_posts=1');
        $I->see('Story', 'h1');   
        $I->seeElement('body.post-type-story');
        // $I->dontSeeElement('.author-other .edit');
        $I->dontSeeElementInDOM('.author-other .edit');

        // $queries = $this->getModule('WPQueries');

        // $I->module->_saveScreenshot(codecept_output_dir() . 'screenshot_1.png');
        // `$this->webDriverModule->_saveScreenshot($this->dir . DIRECTORY_SEPARATOR . $filename);`


    }
}

```
<img src='http://www.flowpress.com/screenshots/screenshot%202019-02-21%20at%208.58.13%20AM.png'/>

Any ideas?
