### ISSUE TITLE
mysqli_query(): Couldn't fetch mysqli

### ISSUE THREAD

**Issue by lots0logs** [lucatume/wp-browser#217]
Any idea on what could be causing this error when using WPLoader for unit testing?
```
Exception trace:
 () at /workspace/core-products/Divi/core/vendor/codeception/codeception/src/Codeception/Subscriber/ErrorHandler.php:83
 Codeception\Subscriber\ErrorHandler->errorHandler() at n/a:n/a
 mysqli_query() at /workspace/wordpress/5.0.3/wp-includes/wp-db.php:1924
 wpdb->_do_query() at /workspace/wordpress/5.0.3/wp-includes/wp-db.php:1813
 wpdb->query() at /workspace/core-products/Divi/core/vendor/lucatume/wp-browser/src/includes/functions.php:65
 _delete_all_data() at /workspace/core-products/Divi/core/vendor/lucatume/wp-browser/src/Codeception/TestCase/WPTestCase.php:100
 Codeception\TestCase\WPTestCase::tearDownAfterClass() at n/a:n/a
 call_user_func() at /workspace/core-products/Divi/core/vendor/codeception/codeception/src/Codeception/Subscriber/BeforeAfterTest.php:47
 Codeception\Subscriber\BeforeAfterTest->runHooks() at /workspace/core-products/Divi/core/vendor/codeception/codeception/src/Codeception/Subscriber/BeforeAfterTest.php:39
 Codeception\Subscriber\BeforeAfterTest->afterClass() at /workspace/core-products/Divi/core/vendor/symfony/event-dispatcher/EventDispatcher.php:212
 Symfony\Component\EventDispatcher\EventDispatcher->doDispatch() at /workspace/core-products/Divi/core/vendor/symfony/event-dispatcher/EventDispatcher.php:44
 Symfony\Component\EventDispatcher\EventDispatcher->dispatch() at /workspace/core-products/Divi/core/vendor/codeception/codeception/src/Codeception/SuiteManager.php:160
 Codeception\SuiteManager->run() at /workspace/core-products/Divi/core/vendor/codeception/codeception/src/Codeception/Codecept.php:192
 Codeception\Codecept->runSuite() at /workspace/core-products/Divi/core/vendor/codeception/codeception/src/Codeception/Codecept.php:159
 Codeception\Codecept->run() at /workspace/core-products/Divi/core/vendor/codeception/codeception/src/Codeception/Command/Run.php:495
 Codeception\Command\Run->runSuites() at /workspace/core-products/Divi/core/vendor/codeception/codeception/src/Codeception/Command/Run.php:390
 Codeception\Command\Run->execute() at /workspace/core-products/Divi/core/vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at /workspace/core-products/Divi/core/vendor/symfony/console/Application.php:953
 Symfony\Component\Console\Application->doRunCommand() at /workspace/core-products/Divi/core/vendor/symfony/console/Application.php:248
 Symfony\Component\Console\Application->doRun() at /workspace/core-products/Divi/core/vendor/symfony/console/Application.php:148
 Symfony\Component\Console\Application->run() at /workspace/core-products/Divi/core/vendor/codeception/codeception/src/Codeception/Application.php:108
 Codeception\Application->run() at /workspace/core-products/Divi/core/vendor/codeception/codeception/codecept:43
```

wpunit.suite.yml:
```
# Codeception Test Suite Configuration
#
# Suite for unit or integration tests that require WordPress functions and classes.

actor: WPUnitTester
modules:
    enabled:
        - WPLoader
        - \Helper\WPUnit
    config:
        WPLoader:
            loadOnly: false
            multisite: false
            wpRootFolder: "/workspace/wordpress/%WP_VERSION%"
            dbName: "wordpress-test"
            dbHost: "%DB_HOST%"
            dbUser: "root"
            dbPassword: "password"
            tablePrefix: "wp_"
            domain: "%VIRTUAL_HOST%"
            adminEmail: "dustin@elegantthemes.com"
            title: "ETDev Test"
            plugins: []
            activatePlugins: []
            theme: Divi
            bootstrapActions:
                - wp
```

**Note:** Probably the same as or related to #164
