### ISSUE TITLE
Config Issue: Can't Find Database Host

### ISSUE THREAD

**Issue by iworkinpixels** [lucatume/wp-browser#221]
I have required wp-browser in my composer file, run a composer update, and run "vendor/bin/codecept init wpbrowser"... everything went fine with no error messages.

Following that, I've edited the codeception.yml file to contain all the connection information, and verified that it's also in .envwp and I've sourced all the lines in .envwp to make sure that the environment variables are actually set. 

But when I run "vendor/bin/codecept run -vvv" to test if everything is configured correctly, I get the following error message: 

```
[user]@[host]:[/path/to/site]$ vendor/bin/codecept run -vvv
Codeception PHP Testing Framework v2.5.5
Powered by PHPUnit 5.7.27 by Sebastian Bergmann and contributors.
Running with seed:


  [Connecting To Db] {"config":{"tablePrefix":"%TEST_SITE_TABLE_PREFIX%","populate":true,"cleanup":true,"reconnect":false,"dump":"tests/_data/dump.sql","populator":null,"urlReplacement":true,"waitlock":0,"dsn":"mysql:host=%TEST_SITE_DB_HOST%;dbname=%TEST_SITE_DB_NAME%","user":"%TEST_SITE_DB_USER%","password":"%TEST_SITE_DB_PASSWORD%","url":"%TEST_SITE_WP_URL%"},"options":[]}

In Db.php line 555:

  [Codeception\Exception\ModuleException]
  Db: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known while creating PDO connection
```

I am unsure of whether the error message is telling me that those variables never got filled in, or if it's supposed to look like that... and additionally I found out one other thing that seems odd. If I attempt to run just the unit tests with "vendor/bin/codecept run unit" then I get an error message complaining about being unable to load the bootstrap file:

```
  [Codeception\Exception\ConfigurationException]
  Bootstrap file [path_to_site]/tests/unit/_bootstrap.php can't be loaded
```

Looking into that directory, it's empty, so it seems like something didn't create that bootstrap file, though there were no errors or warnings during wp-browser init. 

Is there any way I can verify that my configuration options aren't the issue to help get the database connection working?

**Comment by lucatume** [comment]
Hi,
thanks for reporting the issue.

The first error and its output show the `%PLACEHOLDERS%` are not being replaced. Could you post your `codeception.yml` file?

>  I've sourced all the lines in .envwp to make sure that the environment 

Codeception will do that for you if you [set the configuration file to use parameters from an env file](https://codeception.com/docs/06-ModulesAndHelpers.html#Dynamic-Configuration-With-Parameters); why do you need to do that?

The second message says the `tests/unit/_bootstrap.php` file is missing; is it?

P.S. Do not run **all** suites using `codecept run`, run them one by one using `codecept run <suite>` to avoid issues related to WordPress side-effects.

**Comment by iworkinpixels** [comment]
Ok, let me try to go through all the questions here so I get you all the information you need... 

Here's the codeception.yml file:
```
actor: Tester
paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    helpers: tests/_support
settings:
    bootstrap: _bootstrap.php
    colors: true
    memory_limit: 1024M
modules:
    config:
        Db:
            dsn: 'mysql:host=127.0.0.1;dbname=[redacted]'
            user: [redacted]
            password: [redacted]
            dump: tests/_data/dump.sql
        WPBrowser:
            url: '[redacted]'
            adminUsername: [redacted]
            adminPassword: [redacted]
            adminUrl: /wp/wp-admin
        WPDb:
            dsn: 'mysql:host=127.0.0.1;dbname=[redacted]'
            user: [redacted]
            password: [redacted]
            dump: tests/_data/dump.sql
            populate: true
            cleanup: true
            url: '[redacted]'
            tablePrefix: wp_
        WPLoader:
            wpRootFolder: /srv/www/[redacted]/current/web/wp
            dbName: [redacted]
            dbHost: 127.0.0.1
            dbUser: [redacted]
            dbPassword: [redacted]
            wpDebug: true
            dbCharset: utf8
            dbCollate: ''
            tablePrefix: wp_
            domain: [redacted]
            adminEmail: [redacted]
            title: 'WP Tests'
            phpBinary: php
            language: ''
            configFile: test-config.php
            plugins:
              - wpjobboard/index.php
            activatePlugins:
              - wpjobboard/index.php
        WPWebDriver:
            url: '[redacted]'
            browser: phantomjs
            port: 443
            restart: true
            wait: 2
            adminUsername: [redacted]
            adminPassword: [redacted]
            adminUrl: /wp/wp-admin
extensions:
    commands:
        - 'Codeception\Command\GenerateWPUnit'
        - 'Codeception\Command\GenerateWPRestApi'
        - 'Codeception\Command\GenerateWPRestController'
        - 'Codeception\Command\GenerateWPRestPostTypeController'
        - 'Codeception\Command\GenerateWPAjax'
        - 'Codeception\Command\GenerateWPCanonical'
        - 'Codeception\Command\GenerateWPXMLRPC'

```

I believed I had set the config file to use parameters from the env file, and yet when I did a printenv they had not been loaded, so I loaded them myself to see if that was the issue. 

Yes, the bootstrap file from the unit tests directory is missing. 

And regarding running the suites all at once... normally I wouldn't do that, but the tutorial I was following ( [](https://www.theaveragedev.com/setting-wpbrowser-bedrock/ )) told me to attempt to do so at first when there were no tests just to make sure everything was working. After that didn't work I attempted to run just the unit tests, and that's where I found the error about the bootstrap file.

**Comment by lucatume** [comment]
Ok, let's try to make this work:

1. "best practice" would dictate to have the modules configurations in the suites files (e.g. `acceptance.suite.yml`) and not in the main `codeception.yml` configuration file. It's not what's causing the issue here but it's worth pointing it out.
2. the `codeception.yml` configuration file you provided is missing the `params:` setting; as you can see [on Codeception documentation](https://codeception.com/docs/06-ModulesAndHelpers#Dynamic-Configuration-With-Parameters). You should add these lines to the `codeception.yml` file:

**Comment by iworkinpixels** [comment]
Ok, getting closer! Adding that in lets the database connect, so we get back to the error message about the bootstrap file being missing.

I think once I fix the bootstrap file problem I might be in business!

**Comment by lucatume** [comment]
Did you add the missing `_bootstrap.php` file(s)? It can be empty but, in your `codeception.yml` configuration file, your telling Codeception to look and expect for one:

```yaml
actor: Tester
paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    helpers: tests/_support
settings:
    bootstrap: _bootstrap.php
    colors: true
    memory_limit: 1024M
    ...
```

wp-browser is set of modules for [Codeception](http://codeception.com/ "Codeception - BDD-style PHP testing."), you can find more about this issue, and others, on [Codeception documentation](https://codeception.com/docs/02-GettingStarted).
