### ISSUE TITLE
[BUG] Doesn't work with phpunit >8.2

### ISSUE THREAD

**Issue by mickaelperrin** [lucatume/wp-browser#256]
**Environment**
OS: Mac
PHP version: 7.3.2
Installed Codeception version: 3.0.1
Installed wp-browser version: 2.2.1
WordPress version:  5.2.1
Local development environment: Docker
WordPress structure and management: custom

**Can you perform the test manually?**
No

**Codeception configuration file**  

```yaml
paths:
    tests: tests/codeception
    output: tests/codeception/_output
    data: tests/codeception/_data
    support: tests/codeception/_support
    envs: tests/codeception/_envs
actor_suffix: Tester
extensions:
    enabled:
        - Codeception\Extension\RunFailed
    commands:
        - Codeception\Command\GenerateWPUnit
        - Codeception\Command\GenerateWPRestApi
        - Codeception\Command\GenerateWPRestController
        - Codeception\Command\GenerateWPRestPostTypeController
        - Codeception\Command\GenerateWPAjax
        - Codeception\Command\GenerateWPCanonical
        - Codeception\Command\GenerateWPXMLRPC
params:
    - .env.testing
```

**Suite configuration file**
```yaml
# Codeception Test Suite Configuration
#
# Suite for unit or integration tests that require WordPress functions and classes.

actor: WpunitTester
modules:
    enabled:
        - WPLoader
        - \Helper\Wpunit
    config:
        WPLoader:
            wpRootFolder: "%WP_ROOT_FOLDER%"
            dbName: "%TEST_DB_NAME%"
            dbHost: "%TEST_DB_HOST%"
            dbUser: "%TEST_DB_USER%"
            dbPassword: "%TEST_DB_PASSWORD%"
            tablePrefix: "%TEST_TABLE_PREFIX%"
            domain: "%TEST_SITE_WP_DOMAIN%"
            adminEmail: "%TEST_SITE_ADMIN_EMAIL%"
            title: "Sebastien Martinez"
            pluginsFolder: "../app"
            plugins:
                - dkod-framework/dkod-framework.php
            activatePlugins:
                - woocommerce/woocommerce.php
                - advanced-custom-fields-pro/acf.php
```

**Describe the bug**
Unable to run any `wpunit` tests

**Output**
```
Fatal error: Uncaught Error: Call to undefined method PHPUnit\Framework\TestSuite::isTestMethod() in /src/vendor/codeception/codeception/src/Codeception/Test/Loader/Unit.php:46
Stack trace:
#0 /src/vendor/codeception/codeception/src/Codeception/Test/Loader/Unit.php(30): Codeception\Test\Loader\Unit->createTestFromPhpUnitMethod(Object(ReflectionClass), Object(ReflectionMethod))
#1 /src/vendor/codeception/codeception/src/Codeception/Test/Loader.php(139): Codeception\Test\Loader\Unit->loadTests('/WordPress/plug...')
#2 /src/vendor/codeception/codeception/src/Codeception/SuiteManager.php(95): Codeception\Test\Loader->loadTests(NULL)
#3 /src/vendor/codeception/codeception/src/Codeception/Codecept.php(190): Codeception\SuiteManager->loadTests(NULL)
#4 /src/vendor/codeception/codeception/src/Codeception/Codecept.php(159): Codeception\Codecept->runSuite(Array, 'wpunit', NULL)
#5 /src/vendor/codeception/codeception/src/Codeception/Command/Run.php(494): Codeception\Codecept->run('wpunit')
#6 /src/vendor/codeception/codeception/src/ in /src/vendor/codeception/codeception/src/Codeception/Test/Loader/Unit.php on line 46

```

**To Reproduce**
Steps to reproduce the behavior, simply install with composer
```
composer require lucatume/wp-browser --dev
```

**Expected behavior**
The test run ;)

**Additional context**
Adding constraint to `phpunit < 8.2` resolve the issue.`
Currently the constraint is only in  the `dev` dependencies of composer.
