### ISSUE TITLE
[FEATURE REQUEST] SQLite support

### ISSUE THREAD

**Issue by lucatume** [lucatume/wp-browser#267]
**Is your feature request related to a problem? Please describe.**
Faster integration tests.

**Describe the solution you'd like**
I'd like to be able to configure the `WPLoader` module like this to use a SQLite in-memory database:

```yaml
actor: WpunitTester
modules:
    enabled:
        - \Helper\WpunitTester
        - WPLoader
    config:
        WPLoader:
            wpRootFolder: "%WP_ROOT_FOLDER%"
            useSqlite: memory
            plugins: [ 'acme-plugin/plugin.php' ]
            activatePlugins: [ 'acme-plugin/plugin.php' ]
```

On the same note I'd like to be able to use a file-based SQLite database like this and have the database created for me:

```yaml
actor: WpunitTester
modules:
    enabled:
        - \Helper\WpunitTester
        - WPLoader
    config:
        WPLoader:
            wpRootFolder: "%WP_ROOT_FOLDER%"
            useSqlite: true
            plugins: [ 'acme-plugin/plugin.php' ]
            activatePlugins: [ 'acme-plugin/plugin.php' ]
```

Finally I should be able to specify the SQLite database file location:

```yaml
actor: WpunitTester
modules:
    enabled:
        - \Helper\WpunitTester
        - WPLoader
    config:
        WPLoader:
            wpRootFolder: "%WP_ROOT_FOLDER%"
            useSqlite: tests/_data/test.sqlite
            plugins: [ 'acme-plugin/plugin.php' ]
            activatePlugins: [ 'acme-plugin/plugin.php' ]
```

This should be all the required configuration.
