### ISSUE TITLE
[BUG] Group support needs specific configuration ?

### ISSUE THREAD

**Issue by mickaelperrin** [lucatume/wp-browser#269]
**Environment**
OS: Mac
PHP version: 7.3.6
Installed Codeception version: 3.0.2
Installed wp-browser version: 2.2.15
WordPress version: 5.2.2
Local development environment:  docker
WordPress structure and management: custom inspired by themosis  

**Can you perform the test manually?**

**Codeception configuration file**  

Base
```yaml
paths:
  tests: tests/codeception
  data: tests/codeception/_data
  output: tests/codeception/_output
  support: tests/codeception/_support
  envs: tests/codeception/_env
actor_suffix: Tester
extensions:
  enabled:
    - Codeception\Extension\RunFailed
  commands:
    - Codeception\Command\GenerateWPUnit
    - Codeception\Command\GenerateWPRestApi
    - Codeception\Command\GenerateWPRestController
    - Codeception\Command\GenerateWPRestPostTypeController
    - Codeception\Command\GenerateWPAjax
    - Codeception\Command\GenerateWPCanonical
    - Codeception\Command\GenerateWPXMLRPC
coverage:
  enabled: true
  remote_context_options:
    ssl:
      verify_peer_name: false
      verify_peer: false
settings:
  bootstrap: _bootstrap.php
modules:
  config:
    WPDb:
      dsn: 'mysql:host=%TEST_SITE_DB_HOST%;dbname=%TEST_SITE_DB_NAME%'
      user: '%TEST_SITE_DB_USER%'
      password: '%TEST_SITE_DB_PASSWORD%'
      populate: true
      cleanup: false
      waitlock: 10
      url: '%TEST_SITE_WP_URL%'
      urlReplacement: false
      tablePrefix: '%TEST_SITE_TABLE_PREFIX%'
      #populator: 'mysql -u $user -h $host $dbname < $dump'
    WPBrowser:
      url: '%TEST_SITE_WP_URL%'
      adminUsername: '%TEST_SITE_ADMIN_USERNAME%'
      adminPassword: '%TEST_SITE_ADMIN_PASSWORD%'
      adminPath: '%TEST_SITE_WP_ADMIN_PATH%'
    WPFilesystem:
      wpRootFolder: '%WP_ROOT_FOLDER%'
      plugins: '../app/plugins'
      mu-plugins: '../app/mu-plugins'
      themes: '../app/themes'
      uploads: '../app/uploads'
    WPWebDriver:
      url: '%TEST_SITE_WP_URL%'
      browser: chrome
      host: hub
      port: 4444
      restart: true
      wait: 2
      adminUsername: '%TEST_SITE_ADMIN_USERNAME%'
      adminPassword: '%TEST_SITE_ADMIN_PASSWORD%'
      adminUrl: '%TEST_SITE_WP_ADMIN_PATH%'
      window_size: 1920x1080
      capabilities:
        # --disable-infobars: hide "Chrome is being controlled by automated test software"
        # Used in more recent releases of Selenium.
        "goog:chromeOptions":
          args: ["--no-sandbox", "--user-agent=wp-browser", "--disable-infobars"]
        # Support the old format for back-compatibility purposes.
        "chromeOptions":
          args: ["--no-sandbox", "--user-agent=wp-browser", "--disable-infobars"]
    WPLoader:
      wpRootFolder: '%WP_ROOT_FOLDER%'
      dbName: "%TEST_DB_NAME%"
      dbHost: "%TEST_DB_HOST%"
      dbUser: "%TEST_DB_USER%"
      dbPassword: "%TEST_DB_PASSWORD%"
      tablePrefix: "%TEST_SITE_TABLE_PREFIX%"
      domain: "%TEST_SITE_WP_DOMAIN%"
      adminEmail: "%TEST_SITE_ADMIN_EMAIL%"
      title: "Test site"
      #pluginsFolder: "/src/www/wp-content/plugins"
      theme: "storefront"
      configFile: "wp-config.codeception.php"
      language: "fr"
     plugins:
        - advanced-custom-fields-pro/acf.php
      activatePlugins:
        - advanced-custom-fields-pro/acf.php
      loadOnly: true
```
Plugin
```yaml
extends: /src/codeception.base.yml
modules:
  config:
    WPDb:
      dump: 'tests/codeception/_data/db.tests.sql'
coverage:
  enabled: true
  c3_url: "http://URL/c3.php?"
  include:
    - src/*
  exlude:
    - src/Zoho_ORM/*
params:
  - .env.testing
settings:
  bootstrap: _bootstrap.php
```

**Suite configuration file**

```yaml
# Codeception Test Suite Configuration
#
# Suite for functional tests
# Emulate web requests and make WordPress process them

actor: FunctionalTester
modules:
  enabled:
    - WPDb
    - WPLoader
    #- WPBrowser
    #- WPFilesystem
    - WPWebDriver
    - Asserts
    #- \Helper\Functional
    - \dkod\framework\Tests\Codeception\WooCommerce\ProductAdminHelper
    - \dkod\framework\Tests\Codeception\WordPress\AdminHelper
    - \dkod\framework\Tests\Codeception\WordPress\FormHelper
    - \dkod\framework\Tests\Codeception\Misc\CustomHelper
    - \dkod\framework\Tests\Codeception\WooCommerce\FrontEndHelper
  config:
    loadOnly: true
    \dkod\framework\Tests\Codeception\WooCommerce\ProductAdminHelper:
      depends:
        WPWebDriver
    \dkod\framework\Tests\Codeception\WooCommerce\FrontEndHelper:
      depends:
        WPWebDriver
    \dkod\framework\Tests\Codeception\WordPress\FormHelper:
      depends:
        WPWebDriver
```

**Describe the bug**
I try to use the `group` feature of codeception.
I added some `group` in phpdoc blocs, but got the following error

**Output**
```
codecept run --coverage-xml --coverage-html -vvv --steps  -g lead
Codeception PHP Testing Framework v3.0.2
Powered by PHPUnit 8.2.4 by Sebastian Bergmann and contributors.
Running with seed:

[Groups] lead

  [Connecting To Db] {"config":{"tablePrefix":"wp7dc89def_","populate":true,"cleanup":false,"reconnect":false,"dump":"tests/codeception/_data/db.tests.sql","populator":null,"urlReplacement":false,"waitlock":10,"dsn":"mysql:host=mysql;dbname=database","user":"user","password":"password","url":"https://woocommerce-zoho.local.dkod.fr"},"options":[]}
  [Db] Connected to default database
  WPLoader module will load WordPress when all other modules initialized.

Acceptance Tests (0) ------------------------------------------------------------------------------------------------------------------
Modules: WPDb, WPWebDriver, WPLoader, Asserts
---------------------------------------------------------------------------------------------------------------------------------------
  Running as single site
  WordPress status: {
      "constants": {
          "ABSPATH": "/src/www/",
          "WP_DEFAULT_THEME": "woocommercezoho",
          "WP_CONTENT_DIR": "/src/app",
          "WP_PLUGIN_DIR": "/src/app/plugins",
          "WP_HOME": "https://woocommerce-zoho.local.dkod.fr",
          "WP_SITEURL": "http://woocommerce-zoho.local.dkod.fr/",
          "WPMU_PLUGIN_DIR": "/src/app/mu-plugins",
          "DB_HOST": "mysql",
          "DB_NAME": "database",
          "DB_PASSWORD": "password",
          "DB_USER": "user",
          "CUSTOM_USER_TABLE": "not set",
          "CUSTOM_USER_META_TABLE": "not set",
          "DISABLE_WP_CRON": "not set"
      },
      "globals": {
          "table_prefix": "wp7dc89def_"
      },
      "checks": {
          "Site is multisite": "no",
          "ABSPATH points to valid WordPress directory": "Yes, wp-load.php file found in WordPress root directory.",
          "Database connection works": "Yes, connection successful.",
          "Database structure as expected": "Yes, as expected.",
          "Blog installed": "Yes, blog is installed.",
          "Theme :": {
              "template": "storefront",
              "stylesheet": "storefront",
              "storefront directory": "../app/themes/storefront"
          },
          "Must-use plugins health-check:": [
              "load.php"
          ],
          "Plugins health-check:": {
              "Active plugin [dkod-framework/dkod-framework.php]": "file [../app/plugins/dkod-framework/dkod-framework.php] does not exist.",
              "Active plugin [advanced-custom-fields-pro/acf.php]": "file [../app/plugins/advanced-custom-fields-pro/acf.php] found.",
              "Active plugin [debug-bar/debug-bar.php]": "file [../app/plugins/debug-bar/debug-bar.php] found.",
              "Active plugin [gravityforms/gravityforms.php]": "file [../app/plugins/gravityforms/gravityforms.php] found.",
              "Active plugin [woo-order-test/wc-ot.php]": "file [../app/plugins/woo-order-test/wc-ot.php] found.",
              "Active plugin [woocommerce/woocommerce.php]": "file [../app/plugins/woocommerce/woocommerce.php] found.",
              "Active plugin [wp-cfm/wp-cfm.php]": "file [../app/plugins/wp-cfm/wp-cfm.php] found.",
              "Active plugin [wp-crontrol/wp-crontrol.php]": "file [../app/plugins/wp-crontrol/wp-crontrol.php] found.",
              "Inactive plugin [disable-gutenberg]": "../app/plugins/disable-gutenberg"
          }
      }
  }
---------------------------------------------------------------------------------------------------------------------------------------
  [Connecting To Db] {"config":{"tablePrefix":"wp7dc89def_","populate":true,"cleanup":false,"reconnect":false,"dump":"tests/codeception/_data/db.tests.sql","populator":null,"urlReplacement":false,"waitlock":10,"dsn":"mysql:host=mysql;dbname=database","user":"user","password":"password","url":"https://woocommerce-zoho.local.dkod.fr"},"options":[]}
  [Db] Connected to default database
  WPLoader module will load WordPress when all other modules initialized.

In EventListener.php line 64:

  [Codeception\Exception\ModuleException]
  WPLoader: Global `app` object is either empty or not an instance of the \Codeception\Application class.


Exception trace:
 () at /src/vendor/lucatume/wp-browser/src/tad/WPBrowser/Module/Traits/EventListener.php:64
 Codeception\Module\WPLoader->getEventDispatcher() at /src/vendor/lucatume/wp-browser/src/tad/WPBrowser/Module/Traits/EventListener.php:42
 Codeception\Module\WPLoader->addAction() at /src/vendor/lucatume/wp-browser/src/Codeception/Module/WPLoader.php:220
 Codeception\Module\WPLoader->initialize() at /src/vendor/lucatume/wp-browser/src/Codeception/Module/WPLoader.php:205
 Codeception\Module\WPLoader->_initialize() at /src/vendor/codeception/codeception/src/Codeception/SuiteManager.php:80
 Codeception\SuiteManager->initialize() at /src/vendor/codeception/codeception/src/Codeception/Codecept.php:189
 Codeception\Codecept->runSuite() at /src/vendor/codeception/codeception/src/Codeception/Codecept.php:160
 Codeception\Codecept->run() at /src/vendor/codeception/codeception/src/Codeception/Command/Run.php:496
 Codeception\Command\Run->runSuites() at /src/vendor/codeception/codeception/src/Codeception/Command/Run.php:391
 Codeception\Command\Run->execute() at /src/vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at /src/vendor/symfony/console/Application.php:969
 Symfony\Component\Console\Application->doRunCommand() at /src/vendor/symfony/console/Application.php:255
 Symfony\Component\Console\Application->doRun() at /src/vendor/symfony/console/Application.php:148
 Symfony\Component\Console\Application->run() at /src/vendor/codeception/codeception/src/Codeception/Application.php:107
 Codeception\Application->run() at /src/vendor/codeception/codeception/codecept:43

run [-o|--override OVERRIDE] [-e|--ext EXT] [--report] [--html [HTML]] [--xml [XML]] [--phpunit-xml [PHPUNIT-XML]] [--tap [TAP]] [--json [JSON]] [--colors] [--no-colors] [--silent] [--steps] [-d|--debug] [--no-redirect] [--coverage [COVERAGE]] [--coverage-html [COVERAGE-HTML]] [--coverage-xml [COVERAGE-XML]] [--coverage-text [COVERAGE-TEXT]] [--coverage-crap4j [COVERAGE-CRAP4J]] [--coverage-phpunit [COVERAGE-PHPUNIT]] [--no-exit] [-g|--group GROUP] [-s|--skip SKIP] [-x|--skip-group SKIP-GROUP] [--env ENV] [-f|--fail-fast] [--no-rebuild] [--seed SEED] [--] [<suite>] [<test>]

  [Db] Disconnected from default
  [Db] Disconnected from default
```
