### ISSUE TITLE
[SETUP ISSUE] Can't make WPQueries work with WPUnitTester

### ISSUE THREAD

**Issue by essekia** [lucatume/wp-browser#272]
**Environment**
OS: Mac
PHP version:7.2
Installed Codeception version: 3.0.0
Installed wp-browser version: 2.2.14
WordPress version: 5.2.2
Local development environment: Docker
WordPress structure and management: [e.g. default, Bedrock, other]

**Did you use the `codecept init wpbrowser` command?**
Yes

**Did you take a look at Codeception and wp-browser documentation?**
Yes

**Codeception configuration file**

**Suite configuration file**
If you're encountering an issue with a specific suite, please provide its configuration file.

```yaml
actor: WpunitTester
modules:
    enabled:
        - WPLoader
        - WPQueries
          # - \Helper\Wpunit
    config:
        WPLoader:
            wpRootFolder: "%WP_ROOT_FOLDER%"
            dbName: "%DB_NAME%"
            dbHost: "%DB_HOST%"
            dbUser: "%DB_USER%"
            dbPassword: "%DB_PASSWORD%"
            tablePrefix: "%TABLE_PREFIX%"
            dump: "dump.sql"
            populate: true #import the dump before the tests
            cleanup: true #import the dump between tests
            domain: "%WP_DOMAIN%"
            adminEmail: "%ADMIN_EMAIL%"
            title: "Test"
            plugins: ["...php"]
            activatePlugins: ["...php"]
```

**Describe the issue you're encountering**
This is the right way to use WPQueries methods, right? 

`  $this->assertQueries();`

This is not working in WPUnitTester, I did add WPQueries to the config modules.

**Output**
 [Error] Call to undefined method AccessControlFiltersTest::assertQueries()  

**To Reproduce**
1. Setup WPQueries in suite config with WPLoader
2. run codecept build
3. Call a method from WPQueries using $this
