### ISSUE TITLE
[FEATURE REQUEST] Robust code

### ISSUE THREAD

**Issue by szepeviktor** [lucatume/wp-browser#291]
Please consider adding static analysis.

This is @phpstan with WordPress extensions.

`phpstan.neon.dist`

```yaml
# Add this to composer.json
#  "scripts": {
#      "post-install-cmd": "PHPStan\\WordPress\\Composer\\FixWpStubs::php73Polyfill",
#      "post-update-cmd": "PHPStan\\WordPress\\Composer\\FixWpStubs::php73Polyfill"
#  }
#$ composer require --dev phpstan/phpstan-shim szepeviktor/phpstan-wordpress
# Comment out wp_set_auth_cookie and wp_clear_auth_cookie in src/includes/functions.php:168
#$ vendor/bin/phpstan analyze -l 0
# Then raise level up to 7

includes:
    - phar://phpstan.phar/conf/bleedingEdge.neon
    - vendor/szepeviktor/phpstan-wordpress/extension.neon
parameters:
    level: max
    inferPrivatePropertyTypeFromConstructor: true
    paths:
        - %currentWorkingDirectory%/src/Codeception/
    excludes_analyse:
        - %currentWorkingDirectory%/src/Codeception/TestCase/WPXMLRPCTestCase.php
    autoload_files:
        - %currentWorkingDirectory%/vendor/codeception/codeception/autoload.php
        - %currentWorkingDirectory%/src/includes/functions.php
        - %currentWorkingDirectory%/src/includes/utils.php
        - %currentWorkingDirectory%/src/includes/spy-rest-server.php
        - %currentWorkingDirectory%/src/includes/exceptions.php
        - %currentWorkingDirectory%/src/includes/factory.php
        - %currentWorkingDirectory%/src/includes/trac.php
    ignoreErrors:
        # Uses func_get_args()
        - '#^Function add_query_arg invoked with [123] parameters?, 0 required\.$#'
```
