### ISSUE TITLE
[BUG] Database is not preserved?

### ISSUE THREAD

**Issue by eltoma-alexkuc** [lucatume/wp-browser#302]
**Environment**
OS: OSX 10.13.6
PHP version: 7.3.8
Installed Codeception version: 3.1.0
Installed wp-browser version: 2.2.20
WordPress version: 5.2.3
Local development environment: Docker via docker-compose
WordPress structure and management: default

**Can you perform the test manually?**
Not applicable as the test is purely WPBrowser code (test code follows).

**Codeception configuration file**  
```yaml
paths:
    tests: tests
    output: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
actor_suffix: Tester
extensions:
    enabled:
        - Codeception\Extension\RunFailed
    commands:
        - Codeception\Command\GenerateWPUnit
        - Codeception\Command\GenerateWPRestApi
        - Codeception\Command\GenerateWPRestController
        - Codeception\Command\GenerateWPRestPostTypeController
        - Codeception\Command\GenerateWPAjax
        - Codeception\Command\GenerateWPCanonical
        - Codeception\Command\GenerateWPXMLRPC
params:
    - .env.testing
```

**Suite configuration file**
```yaml
actor: AcceptanceTester
modules:
    enabled:
        - WPDb
        - WPBrowser
        - WPFilesystem
        - \Helper\Acceptance
        - WPCLI
        - Asserts
    config:
        WPDb:
            dsn: 'mysql:host=%TEST_SITE_DB_HOST%;dbname=%TEST_SITE_DB_NAME%'
            user: '%TEST_SITE_DB_USER%'
            password: '%TEST_SITE_DB_PASSWORD%'
            dump: 'tests/_data/dump.sql'
            #import the dump before the tests; this means the test site database will be repopulated before the tests.
            populate: true
            # re-import the dump between tests; this means the test site database will be repopulated between the tests.
            cleanup: false
            waitlock: 10
            url: '%TEST_SITE_WP_URL%'
            urlReplacement: true #replace the hardcoded dump URL with the one above
            tablePrefix: '%TEST_SITE_TABLE_PREFIX%'
        WPBrowser:
            url: '%TEST_SITE_WP_URL%'
            adminUsername: '%TEST_SITE_ADMIN_USERNAME%'
            adminPassword: '%TEST_SITE_ADMIN_PASSWORD%'
            adminPath: '%TEST_SITE_WP_ADMIN_PATH%'
        WPFilesystem:
            wpRootFolder: '%WP_ROOT_FOLDER%'
        WPCLI:
            path: '%WP_ROOT_FOLDER%'
            throw: true
            timeout: 60
```

**Describe the bug**
I am creating a post and testing its existence via `seePostInDatabase` with `cleanup` in `WPDB` set to `false`. However, the test fails as it appears that data is not preserved. Though I could be wrong.

**Output**
If applicable paste here the output of the command that's causing the issue:

```bash
Codeception PHP Testing Framework v3.1.0
Powered by PHPUnit 8.3.4 by Sebastian Bergmann and contributors.
Running with seed: 


  [Connecting To Db] {"config":{"tablePrefix":"wp_","populate":true,"cleanup":false,"reconnect":false,"dump":"tests/_data/dump.sql","populator":null,"urlReplacement":true,"waitlock":10,"dsn":"mysql:host=mysql;dbname=eltoma_global","user":"user3525","password":"P@ssw0rd321!,.","url":"http://eltoma-global.com"},"options":[]}
  [Db] Connected to default eltoma_global

Acceptance Tests (2) ---------------------------------------
Modules: WPDb, WPBrowser, WPFilesystem, \Helper\Acceptance, WPCLI, Asserts
------------------------------------------------------------
CleanupBugCest: Try to see post once
Signature: CleanupBugCest:tryToSeePostOnce
Test: tests/acceptance/CleanupBugCest.php:tryToSeePostOnce
Scenario --
 I have post in database {"post_type":"book","post_title...}
  [Query] SELECT ID FROM wp_posts ORDER BY ID DESC LIMIT 1
  [Query] INSERT INTO `wp_posts` (`post_author`, `post_date`, `post_date_gmt`, `post_content`, `post_title`, `post_excerpt`, `post_status`, `comment_status`, `ping_status`, `post_password`, `post_name`, `to_ping`, `pinged`, `post_modified`, `post_modified_gmt`, `post_content_filtered`, `post_parent`, `guid`, `menu_order`, `post_type`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
  [Parameters] [1,"2019-09-06 03:46:56","2019-09-06 03:46:56","Post 1 content","Alice in Wonderland","Post 1 excerpt","publish","open","open","","post-1-title","","","2019-09-06 03:46:56","2019-09-06 03:46:56","",0,"http://eltoma-global.com/?p=1",0,"book"]
  [Query] INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (?, ?, ?)
  [Parameters] [1,"readers_count",23]
  [Query] SELECT term_id FROM `wp_terms` WHERE `name` = ? 
  [Parameters] ["fiction"]
  [Query] SELECT term_id FROM `wp_terms` WHERE `slug` = ? 
  [Parameters] ["fiction"]
  [Query] SELECT term_id FROM `wp_terms` WHERE `term_id` = ? 
  [Parameters] ["fiction"]
  [Query] INSERT INTO `wp_terms` (`slug`, `term_group`, `name`) VALUES (?, ?, ?)
  [Parameters] ["fiction",0,"fiction"]
  [Query] INSERT INTO `wp_term_taxonomy` (`description`, `parent`, `count`, `taxonomy`, `term_id`) VALUES (?, ?, ?, ?, ?)
  [Parameters] ["",0,0,0,1]
  [Query] SELECT term_taxonomy_id FROM `wp_term_taxonomy` WHERE `term_id` = ? AND `taxonomy` = ? 
  [Parameters] [1,0]
  [Query] INSERT INTO `wp_term_relationships` (`object_id`, `term_taxonomy_id`, `term_order`) VALUES (?, ?, ?)
  [Parameters] [1,"1",0]
 I see post in database {"post_title":"Alice in Wonderland"}
  [Query] SELECT count(*) FROM `wp_posts` WHERE `post_title` = ? 
  [Parameters] ["Alice in Wonderland"]
 PASSED 

CleanupBugCest: Try to see post twice
Signature: CleanupBugCest:tryToSeePostTwice
Test: tests/acceptance/CleanupBugCest.php:tryToSeePostTwice
Scenario --
 I see post in database {"post_title":"Alice in Wonderland"}
  [Query] SELECT count(*) FROM `wp_posts` WHERE `post_title` = ? 
  [Parameters] ["Alice in Wonderland"]
 FAIL 

------------------------------------------------------------
DEPRECATION: Calling the "Codeception\Lib\Connector\Guzzle::getInternalResponse()" method before the "request()" one is deprecated since Symfony 4.1 and will throw an exception in 5.0. /var/www/html/wp_plugin/vendor/symfony/browser-kit/Client.php:219


Time: 8.63 seconds, Memory: 14.00 MB

There was 1 failure:

---------
1) CleanupBugCest: Try to see post twice
 Test  tests/acceptance/CleanupBugCest.php:tryToSeePostTwice
 Step  See post in database {"post_title":"Alice in Wonderland"}
 Fail  No matching records found for criteria {"post_title":"Alice in Wonderland"} in table wp_posts
Failed asserting that 0 is greater than 0.

Scenario Steps:

 1. $I->seePostInDatabase({"post_title":"Alice in Wonde...}) at tests/acceptance/CleanupBugCest.php:24


FAILURES!
Tests: 2, Assertions: 2, Failures: 1.
  [Db] Disconnected from default
```

**To Reproduce**
```php
<?php

class CleanupBugCest {
    public function _before(AcceptanceTester $I) {

    }

    public function tryToSeePostOnce(AcceptanceTester $I) {
        $I->havePostInDatabase([
            'post_type' => 'book',
            'post_title' => 'Alice in Wonderland',
            'meta_input' => [
                'readers_count' => 23,
            ],
            'tax_input' => [
                ['genre' => 'fiction'],
            ],
        ]);

        $I->seePostInDatabase(['post_title' => 'Alice in Wonderland']);
    }

    public function tryToSeePostTwice(AcceptanceTester $I) {
        $I->seePostInDatabase(['post_title' => 'Alice in Wonderland']);
    }
}
```

**Expected behavior**
DB data should be preserved and test should succeed.
