### ISSUE TITLE
remove_action error in WPAjaxTestCase.php on line 133

### ISSUE THREAD

**Issue by sky4git** [lucatume/wp-browser#325]
**Environment**
OS: Windows
PHP version: 7.3.10  
Installed Codeception version: 3.1.0  
Installed wp-browser version: 2.2.30  
WordPress version: 5.4.2
Local development environment: PHP, Apache, Mysql  
WordPress structure and management: default  

**Can you perform the test manually?**
No.

**Codeception configuration file**  
```yaml
paths:
    tests: tests
    output: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
actor_suffix: Tester
extensions:
    enabled:
        - Codeception\Extension\RunFailed
    commands:
        - Codeception\Command\GenerateWPUnit
        - Codeception\Command\GenerateWPRestApi
        - Codeception\Command\GenerateWPRestController
        - Codeception\Command\GenerateWPRestPostTypeController
        - Codeception\Command\GenerateWPAjax
        - Codeception\Command\GenerateWPCanonical
        - Codeception\Command\GenerateWPXMLRPC
params:
    - .env.testing
settings:
    lint: false
    shuffle: true
    colors: true
    strict_xml: false
    memory_limit: 1024M
    backup_globals: true
    report_useless_tests: false
    disallow_test_output: false
    be_strict_about_changes_to_global_state: false
    log_incomplete_skipped: true
```

**Suite configuration file**
```yaml
actor: EsbtestTester
modules:
    enabled:
        - \Helper\Esbtest
    config:
        WPLoader:
            multisite: false
            wpRootFolder: "M:/wp-dev"
            dbName: "wp_test_integration"
            dbHost: "localhost"
            dbUser: "db_manager"
            dbPassword: "strongPassWd"
            title: "WP Test"
            wpDebug: false
            phpBinary: "php"
            theme: localtheme
            configFile: "wp-config-tests.php"
            tablePrefix: 'wp_'
```
**Simple Ajax test class in the suite**
```php
class testAjaxTest extends \Codeception\TestCase\WPAjaxTestCase
{
    /**
     * @var \EsbtestTester
     */
    protected $tester;
    
    public function setUp(): void
    {
        // Before...
        parent::setUp();
        
        // Your set up methods here.
    }

    public function tearDown(): void
    {
        // Your tear down methods here.

        // Then...
        parent::tearDown();
    }

    // Tests
    public function test_it_works(): void
    {

        $post = static::factory()->post->create_and_get();
        $this->assertInstanceOf(\WP_Post::class, $post);
        
    }
}
```
# Codeception Test Suite Configuration

**Describe the bug**
I've generated the Ajax test class through the following
```bash
vendor/bin/codecept generate:wpajax esbtest testAjax
``` 
Class generated successfully.
I've ran the test using the following command:
```bash
vendor/bin/codecept --debug --fail-fast --colors run esbtest testAjaxTest
```

**Output**
```bash
Codeception PHP Testing Framework v3.1.2
Powered by PHPUnit 8.4.1 by Sebastian Bergmann and contributors.
Running with seed:

[Seed] 326354121

  Rebuilding EsbtestTester...
PHP Fatal error:  Uncaught Error: Call to undefined function Codeception\TestCase\remove_action() in M:\wp-dev\wp-content\themes\localtheme\vendor\lucatume\wp-browser\src\Codeception\TestCase\WPAjaxTestCase.php:133
Stack trace:
#0 M:\wp-dev\wp-content\themes\localtheme\vendor\codeception\phpunit-wrapper\src\TestCase.php(26): Codeception\TestCase\WPAjaxTestCase::_setUpBeforeClass()
#1 [internal function]: Codeception\PHPUnit\TestCase::setUpBeforeClass()
#2 M:\wp-dev\wp-content\themes\localtheme\vendor\codeception\codeception\src\Codeception\Subscriber\BeforeAfterTest.php(47): call_user_func(Array)
#3 M:\wp-dev\wp-content\themes\localtheme\vendor\codeception\codeception\src\Codeception\Subscriber\BeforeAfterTest.php(33): Codeception\Subscriber\BeforeAfterTest->runHooks('beforeClass')
#4 M:\wp-dev\wp-content\themes\localtheme\vendor\symfony\event-dispatcher\EventDispatcher.php(260): Codeception\Subscriber\BeforeAfterTest->beforeClass(Object(Codeception\Event\SuiteEvent), 'suite.before', Object(Symfony\Componen in M:\wp-dev\wp-content\themes\localtheme\vendor\lucatume\wp-browser\src\Codeception\TestCase\WPAjaxTestCase.php on line 133

```

**To Reproduce**
Please see the commands I've mentiond before.

**Expected behavior**
This simple test should run normally. 

**Screenshots**
No available due to sensitivity of data.

**Additional context**
I've a Namespace in my theme. However, prior to update composer packages and PHP to version 7.3.10 test ran fine.  I am not sure why it stuck on **remove_action** method.

**Comment by sky4git** [comment]
Partially fixed:
I forgot to enable the *WPLoader* module the in **suite configuration file**: 
This is the new version of the file:
```yaml
actor: EsbtestTester
modules:
    enabled:
        - WPLoader
        - \Helper\Esbtest
    config:
        WPLoader:
            multisite: false
            wpRootFolder: "M:/wp-dev"
            dbName: "wp_test_integration"
            dbHost: "localhost"
            dbUser: "db_manager"
            dbPassword: "strongPassWd"
            title: "WP Test"
            wpDebug: false
            phpBinary: "php"
            theme: localtheme
            configFile: "wp-config-tests.php"
            tablePrefix: 'wp_'
```

However, when I run the test it always run out of memory:
**Output**
```bash
PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 262144 bytes) in M:\eforms-dev\wp-includes\class-wp-hook.php on line 172

Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 262144 bytes) in M:\eforms-dev\wp-includes\class-wp-hook.php on line 172
PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 262144 bytes) in M:\eforms-dev\wp-includes\class-wp-fatal-error-handler.php on line 73

Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 262144 bytes) in M:\eforms-dev\wp-includes\class-wp-fatal-error-handler.php on line 73
```
Any thoughts on that.
