### ISSUE TITLE
[BUG] WPHealthCheck shows wrong theme for wpunit suite

### ISSUE THREAD

**Issue by philschoefer** [lucatume/wp-browser#328]
**Environment**
OS: Mac
PHP version: 7.3
Installed Codeception version: 3.0.2 
Installed wp-browser version: 2.2.15  
WordPress version: 5.2.2
Local development environment: Docker 
WordPress structure and management: Bedrock  

**Codeception configuration file**  
Paste, in a fenced YAML block, the content of your Codeception configuration file; remove any sensitive data!  

```yaml
actor: Tester
params:
    - .env
paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    helpers: tests/_support
settings:
    colors: true
    memory_limit: 1024M
modules:
    config:
        WPLoader:
            wpRootFolder: ./web
            dbName: wordpress_test
            dbHost: 127.0.0.1
            dbUser: wordpress
            dbPassword: password
            wpDebug: true
            dbCharset: utf8
            dbCollate: ''
            tablePrefix: ueb_
            domain: local.uebersetzer.jetzt
            adminEmail: admin@uebersetzer.jetzt
            title: 'Übersetzer.jetzt (Test)'
            phpBinary: php
            language: ''
            plugins: []
            activatePlugins: []
```

**Suite configuration file**
Paste, in a fenced YAML block, the content of the suite configuration file; remove any sensitive data!

```yaml
# Codeception Test Suite Configuration

# suite for wpunit tests.
# Codeception Test Suite Configuration
#
# Suite for unit or integration tests that require WordPress functions and classes.

actor: WpunitTester
modules:
  enabled:
    - WPLoader
    - \Helper\Wpunit
  config:
    WPLoader:
      wpRootFolder: '%WP_ROOT_FOLDER%'
      dbName: '%TEST_DB_NAME%'
      dbHost: '%TEST_DB_HOST%'
      dbUser: '%TEST_DB_USER%'
      dbPassword: '%TEST_DB_PASSWORD%'
      tablePrefix: '%TEST_TABLE_PREFIX%'
      domain: '%TEST_SITE_WP_DOMAIN%'
      adminEmail: '%TEST_SITE_ADMIN_EMAIL%'
      title: 'Übersetzer.jetzt'
      theme: uejetzt
      configFile: '%TEST_CONFIG_FILE%'
      plugins: []
      activatePlugins: []

```

**Describe the bug**
For some reason the `WPHealthCheck` outputs that the active theme in the test wordpress environment is `twentynineteen` even though it successfully includes and switches to the theme defined in the config file (`uejetzt`).

**Output**
```
Running as single site
  Set template to [uejetzt] and stylesheet to [uejetzt]
  Installing WordPress in isolated process...
  Isolated installation script output: 
  
  Disabling cron
  
  Configuration:
  
  {
      "root": "/Users/philipp/Sites/1231-ubersetzer.jetzt/",
      "autoload": "/Users/philipp/Sites/1231-ubersetzer.jetzt/vendor/autoload.php",
      "installationFilters": [],
      "constants": {
          "ABSPATH": "/Users/philipp/Sites/1231-ubersetzer.jetzt/web/",
          "WP_DEBUG": true,
          "WP_TESTS_TABLE_PREFIX": "ueb_",
          "DB_NAME": "wordpress_test",
          "DB_USER": "root",
          "DB_PASSWORD": "password",
          "DB_HOST": "local.uebersetzer.jetzt",
          "DB_CHARSET": "utf8",
          "DB_COLLATE": "",
          "WP_TESTS_DOMAIN": "local.uebersetzer.jetzt",
          "WP_TESTS_EMAIL": "admin@local.uebersetzer.jetzt",
          "WP_TESTS_TITLE": "\u00dcbersetzer.jetzt",
          "WP_PHP_BINARY": "php",
          "WPLANG": "",
          "WP_LANG_DIR": "/Users/philipp/Sites/1231-ubersetzer.jetzt/vendor/lucatume/wp-browser/src/includes/../data/languages",
          "DISABLE_WP_CRON": true
      }
  }
  
  
  The following tables will be dropped: 
        - posts
        - comments
        - links
        - options
        - postmeta
        - terms
        - term_taxonomy
        - term_relationships
        - termmeta
        - commentmeta
  
  Installing WordPress...
  
  
  WordPress status: {
      "constants": {
          "ABSPATH": "/Users/philipp/Sites/1231-ubersetzer.jetzt/web/",
          "WP_DEFAULT_THEME": "uejetzt",
          "WP_CONTENT_DIR": "/Users/philipp/Sites/1231-ubersetzer.jetzt/web/wp-content",
          "WP_PLUGIN_DIR": "/Users/philipp/Sites/1231-ubersetzer.jetzt/web/wp-content/plugins",
          "WP_HOME": "not set",
          "WP_SITEURL": "not set",
          "WPMU_PLUGIN_DIR": "/Users/philipp/Sites/1231-ubersetzer.jetzt/web/wp-content/mu-plugins",
          "DB_HOST": "local.uebersetzer.jetzt",
          "DB_NAME": "wordpress_test",
          "DB_PASSWORD": "password",
          "DB_USER": "root",
          "CUSTOM_USER_TABLE": "not set",
          "CUSTOM_USER_META_TABLE": "not set",
          "DISABLE_WP_CRON": true
      },
      "globals": {
          "table_prefix": "ueb_"
      },
      "checks": {
          "Site is multisite": "no",
          "ABSPATH points to valid WordPress directory": "Yes, wp-load.php file found in WordPress root directory.",
          "Database connection works": "Yes, connection successful.",
          "Database structure as expected": "Yes, as expected.",
          "Blog installed": "Yes, blog is installed.",
          "Theme :": {
              "template": "twentynineteen",
              "stylesheet": "twentynineteen",
              "twentynineteen directory": "wp-content/themes/twentynineteen"
          },
          "Must-use plugins health-check:": [
              "error_reporting.php",
              "bedrock-autoloader.php",
              "write_log.php"
          ],
          "Plugins health-check:": {
              "Inactive plugin [user-switching]": "wp-content/plugins/user-switching",
              "Inactive plugin [custom-user-profile-photo]": "wp-content/plugins/custom-user-profile-photo",
              "Inactive plugin [akismet]": "wp-content/plugins/akismet",
              "Inactive plugin [uk-cookie-consent]": "wp-content/plugins/uk-cookie-consent",
              "Inactive plugin [better-search-replace]": "wp-content/plugins/better-search-replace",
              "Inactive plugin [cryptx]": "wp-content/plugins/cryptx",
              "Inactive plugin [autoptimize]": "wp-content/plugins/autoptimize",
              "Inactive plugin [enable-media-replace]": "wp-content/plugins/enable-media-replace",
              "Inactive plugin [simple-csv-xls-exporter]": "wp-content/plugins/simple-csv-xls-exporter",
              "Inactive plugin [post-thumbnail-editor]": "wp-content/plugins/post-thumbnail-editor",
              "Inactive plugin [shortpixel-image-optimiser]": "wp-content/plugins/shortpixel-image-optimiser",
              "Inactive plugin [elastic-email-sender]": "wp-content/plugins/elastic-email-sender"
          }
      }
  }
```

**To Reproduce**
Install WordPress, install custom theme, switch wpunit config to use that theme and run `codecept run wpunit -vv`.

**Expected behavior**
I think this is just a bug since I can successfully test the methods in my themes `functions.php`. However, if I look into the `wordpress_test` database for the `template` option it does say `twentynineteen`. Am I correct assuming that at some point after the DB gets cleared the theme is set again? Because what struck me also is that the theme switch happens as one of the first things but then the installation happens after the initial switch.
