### ISSUE TITLE
[SETUP ISSUE] Document and explore Bedrock compatibility

### ISSUE THREAD

**Issue by dorni1234** [lucatume/wp-browser#340]
**Environment**
OS: Linux 5.4.10
PHP version: 7.4.1
Installed Codeception version: 3.1.2
Installed wp-browser version: 2.2.32
WordPress version: 5.3
Local development environment: Valet-Linux
WordPress structure and management: Bedrock

**Did you use the `codecept init wpbrowser` command?**
Yes.

**Did you take a look at Codeception and wp-browser documentation?**
Yes.

**Codeception configuration file**

```yaml
paths:
    tests: tests
    output: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
actor_suffix: Tester
extensions:
    enabled:
        - Codeception\Extension\RunFailed
    commands:
        - Codeception\Command\GenerateWPUnit
        - Codeception\Command\GenerateWPRestApi
        - Codeception\Command\GenerateWPRestController
        - Codeception\Command\GenerateWPRestPostTypeController
        - Codeception\Command\GenerateWPAjax
        - Codeception\Command\GenerateWPCanonical
        - Codeception\Command\GenerateWPXMLRPC
params:
    - .env.testing
```

**Suite configuration file**

```yaml
# Codeception Test Suite Configuration
#
# Suite for unit or integration tests that require WordPress functions and classes.

actor: WpunitTester
modules:
    enabled:
        - WPDb
        - WPLoader
        - \Helper\Wpunit
    config:
        WPDb:
            dsn: 'mysql:host=%TEST_DB_HOST%;dbname=%TEST_DB_NAME%'
            user: '%TEST_DB_USER%'
            password: '%TEST_DB_PASSWORD%'
            dump: 'tests/_data/dump.sql'
            populate: true
            cleanup: false
            url: '%TEST_SITE_WP_DOMAIN%'
            tablePrefix: '%TEST_TABLE_PREFIX%'
        WPLoader:
            wpRootFolder: "%WP_ROOT_FOLDER%"
            dbName: "%TEST_DB_NAME%"
            dbHost: "%TEST_DB_HOST%"
            dbUser: "%TEST_DB_USER%"
            dbPassword: "%TEST_DB_PASSWORD%"
            tablePrefix: "%TEST_TABLE_PREFIX%"
            domain: "%TEST_SITE_WP_DOMAIN%"
            adminEmail: "%TEST_SITE_ADMIN_EMAIL%"
            title: "Site Title"
            theme: <themename>
            configFile: web/test-config.php
            pluginsFolder: '../app/plugins'
            plugins: ['woocommerce/woocommerce.php', 'advanced-custom-fields-pro/acf.php']
            activatePlugins: ['woocommerce/woocommerce.php', 'advanced-custom-fields-pro/acf.php']
            loadOnly: true
```

**Describe the issue you're encountering**
I have a Bedrock setup in which I want to integrate tests. I set up WPUnit tests, but when I run them, the database given in `DB_NAME` in the Bedrock `.env` file is wiped clear (wp_post, wp_postmeta, wp_termmeta, wp_term_taxonomy empty etc.), even though I defined a different database in the variable `TEST_DB_NAME` in the `.env.testing` file.

I assume this to be a configuration error, but I cannot figure how to properly set up wpbrowser to have mercy on my database.
