### ISSUE TITLE
[Question] Running the composer update command stuck 

### ISSUE THREAD

**Issue by kjnanda** [lucatume/wp-browser#369]
**Environment**
OS: Mac
PHP version: 7.3.0
Installed Codeception version: 2.5.4
Installed wp-browser version: 2.2.1
WordPress version: 5.4
Local development environment:  MAMP
WordPress structure and management: default

**Codeception configuration file**  
Paste, in a fenced YAML block, the content of your Codeception configuration file; remove any sensitive data!  

```yaml
actor: Tester
paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    helpers: tests/_support
bootstrap: _bootstrap.php
settings:
    colors: true
    memory_limit: 1024M
params:
    - env
```

**Suite configuration file**
Paste, in a fenced YAML block, the content of the suite configuration file; remove any sensitive data!

```yaml
# Codeception Test Suite Configuration

# suite for acceptance tests.
# perform tests in browser using the WebDriver or PhpBrowser.
# If you need both WebDriver and PHPBrowser tests - create a separate suite.

class_name: AcceptanceTester
modules:
    enabled:
        - \Helper\Acceptance
        - WPWebDriver
        - Asserts
    config:
        WPWebDriver:
            host: 'hub-cloud.browserstack.com'
            port: 80
            browser: 'chrome'
            url: 'http://automation.me/'
            adminUsername: ''
            adminPassword: ''
            adminPath: '/wp-admin'
            capabilities:
                'browserstack.user': '%BROWSERSTACK_USER_NAME%'
                'browserstack.key': '%BROWSERSTACK_ACCESS_KEY%'
                'os': 'OS X'
                'os_version': 'mojave'
                'browser_version': '78'
                'browserstack.debug': 'true'
                'browserstack.networkLogs': 'true'
                'build': '%TRAVIS_BUILD_NUMBER%'
                'project': 'Automation '
                'browserstack.local': 'true'
                'browserstack.use_w3c': 'true'
```

**Describe the bug**
I want to update codeception to its latest version but using `composer update` command it sucks the process after these 2 lines. 

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
```

And then nothing happens.

**Expected behavior**
Running this command should update codeception to its latest version. But it seems there must be some dependency with `lucatume/wp-browser` package.

**Screenshots**
![composer_update](https://user-images.githubusercontent.com/15173772/79424260-825f3900-7fdd-11ea-8cbb-6e6bcaad00bd.png)

**Additional context**

Can you please guide me in the right direction?
