### ISSUE TITLE
[Facebook\WebDriver\Exception\WebDriverException]  JSON decoding of remote response failed. 

### ISSUE THREAD

**Issue by unfulvio** [lucatume/wp-browser#38]
this is fantastic and I've just started using codeception+wp-browser

everything runs perfectly but I ran into an issue while trying out the webdriver though

I can't get it to work... I'm quite sure this is not a bug but a configuration error - apologies but I've been running in circles for a couple of hours and couldn't find anything useful on google

in the moment I enable WPWebDriver I get this error when running ` wpcept run`

```
[Facebook\WebDriver\Exception\WebDriverException]                                                                                                                         
  JSON decoding of remote response failed.          
```

and immediately below follows the whole HTML page from the test site printed in my console...

I've made a script with wp-cli to quickly start a server but everything else, both the server, unit tests and codeception acceptance tests they all run fine - I'm on Ubuntu 15.10, phantomjs is correctly installed

this is my codeception.yml

```
actor: Tester
paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    helpers: tests/_support
settings:
    bootstrap: _bootstrap.php
    colors: true
    memory_limit: 1024M
modules:
    enabled:
      - WPLoader
      - WPBrowser
      - WPWebDriver
    config:
        Db:
            dsn: 'mysql:host=localhost;dbname=wp_codeception_tests'
            user: wpcept
            password:
            dump: tests/_data/dump.sql
        WPBrowser:
            url: 'http://0.0.0.0:8080'
            adminUsername: admin
            adminPassword: password
            adminUrl: /wp-admin
        WPDb:
            dsn: 'mysql:host=localhost;dbname=wp_codeception_tests'
            user: wpcept
            password:
            dump: tests/_data/dump.sql
            populate: true
            cleanup: true
            url: 'http://0.0.0.0:8080'
            tablePrefix: wp_
        WPLoader:
            wpRootFolder: temp/wordpress
            dbName: wp_codeception_tests
            dbHost: localhost
            dbUser: root
            dbPassword:
            wpDebug: true
            dbCharset: utf8
            dbCollate: ''
            tablePrefix: wp_
            domain: localhost
            adminEmail: admin@example.com
            title: 'SkyVerge Tests'
            phpBinary: php
        WPWebDriver:
            url: 'http://0.0.0.0'
            browser: phantomjs
            port: 8080
            restart: true
            wait: 2
            adminUsername: admin
            adminPassword: password
            adminUrl: '/wp-admin'
```

many thanks!

**Comment by lucatume** [comment]
Well, first of all: thanks.

First try: in your `WPWebDriver` configuration you are specifying a `port:8080` but that `port` parameter is to specify the port `phantomjs` is listening on.  
Try modifying the configuration to this:

```yaml
WPWebDriver:
            url: 'http://0.0.0.0:8080'
            browser: phantomjs
            port: 4444
            restart: true
            wait: 2
            adminUsername: admin
            adminPassword: password
            adminUrl: '/wp-admin'
```

Where the `4444` port is the port phantomjs *usually* listens on; your configuration might differ though.
For future reference keep in mind that `WPBrowser` extends `PHPBrowser` and `WPWebDriver` extends `WebDriver`: when it comes to configuration and reference the base is the same.

Keep me posted.
