### ISSUE TITLE
[BUG] Env vars not set

### ISSUE THREAD

**Issue by arall** [lucatume/wp-browser#398]
**Environment**
OS: Mac / Linux
PHP version: 7.2 / 7.4
Installed Codeception version: 4.1.4
Installed wp-browser version: 2.5.2
WordPress version: [e.g. 5.4]  
Local development environment: Vagrant
WordPress structure and management: default 

**Describe the bug**
Some environment variables are not set properly in `acceptance.suite.yml` (and probably others).

For example, if I set this values in the `.env.testing` (redacted):
```
TEST_SITE_ADMIN_PASSWORD=FxWDcC9aPnlMchA6xuG8F4o31gNSEs
```
And set the env name in the `acceptance.suite.yml` (redacted):
```
actor: AcceptanceTester
modules:
    enabled:
        - WPBrowser
    config:
        WPBrowser:
            adminPassword: '%TEST_SITE_ADMIN_PASSWORD%'
```
I will not be able to login.

However, if I hardcore the password in the `acceptance.suite.yml`, it works:
```
actor: AcceptanceTester
modules:
    enabled:
        - WPBrowser
    config:
        WPBrowser:
            adminPassword: 'FxWDcC9aPnlMchA6xuG8F4o31gNSEs'
```
But, if I use `admin` as value of `TEST_SITE_ADMIN_PASSWORD` in the `.env.testing`, it works.

The same applies for `TEST_SITE_DB_DSN` env. 

I see that you recently worked in the Dotenv here: https://github.com/lucatume/wp-browser/releases/tag/2.5.2, so might be related.

Perhaps has something to do with the length or the characters? Is strange that some vars work and some others doesn't.
