### ISSUE TITLE
[DOC REQUEST] Running wp-browser in Docker environment

### ISSUE THREAD

**Issue by dingo-d** [lucatume/wp-browser#399]
**Did you search the documentation first?**

Yes

**What do you think is missing from the documentation?**

There is no described way to use dockerized WordPress with wp-browser.

**Do you have any examples of what you'd like to see added to the documentation?**

I'm currently trying to setup GH action workflow that will run integration and acceptance tests for my plugin, but I'm having a really hard time figuring out how to run them using docker.

It would be cool if there was a tutorial on how to set such setup up (ideal for CI/CD pipeline).

**Comment by lucatume** [comment]
That piece of documentation is one that I keep putting off as I find out new things.

For a maybe-helpful example, did you take a look at [wp-browser own Docker based setup](https://github.com/lucatume/wp-browser/blob/master/docker-compose.yml)?

I use it [in GitHub Actions as well](https://github.com/lucatume/wp-browser/blob/master/.github/workflows/ci.yaml) with great satisfaction.

**Comment by dingo-d** [comment]
I looked at it and I found it to be super complicated for what I need it 😂 

I got the part of setting WordPress and MySQL up (as a service), but I need to find a way to provide a path inside my `.env.testing` (the `WP_ROOT_FOLDER`). 

Since my WP is inside a container, I'm not sure what to put as `WP_ROOT_FOLDER`.

If I put `vendor/wordpress/wordpress` will that work?

**Comment by lucatume** [comment]
I'm not sure I'm getting all of it and, w/o having access to the configuration, it's difficult to provide a non misleading answer.

What kind of project are you working on? A plugin, a theme, a whole site?

If you're working on a plugin or a theme, where are those in respect to the WordPress root folder on your host machine?

> Since my WP is inside a container [...]
Does this mean you're binding the root WordPress directory on your host machine into the container? Would you be able to share the `docker-compose` configuration file?

**Comment by dingo-d** [comment]
It's a wp plugin: https://github.com/dingo-d/woo-solo-api/blob/feature/2.0.0-update/.github/workflows/ci.yml

Locally, the plugin is located in the plugins folder of the installation where I'm running tests on. I was running integration tests on a different wp instance in a totally different location (wanted to do that for my acceptance tests, but that didn't work).

In the GH actions, I've set up so that I have 

```yml
container:
            image: wordpress:5.4.1-php7.2
            env:
                WORDPRESS_DB_HOST: mysql
                WORDPRESS_DB_USER: admin
                WORDPRESS_DB_PASSWORD: ""
                WORDPRESS_DB_NAME: wordpresstest
            ports:
                - 8080:80
            volumes:
                - /__w/woo-solo-api/woo-solo-api:/var/www/html/wp-content/plugins/:rw
            options: --cpus 2

        services:
            mysql:
                image: mysql:5.7
                env:
                    MYSQL_ALLOW_EMPTY_PASSWORD: yes
                    MYSQL_DATABASE: wordpresstest
                ports:
                    - 3306
                options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
```

So from what I understood, this will execute all my steps inside that WordPress container. But the problem is that I cannot see any installation path when I do `ls` inside steps.

I have created my own custom action, so I'll probably see how to use that to run tests inside that container (https://github.com/dingo-d/plugin-test-action)
