### ISSUE TITLE
[SETUP ISSUE] Module Asserts is not installed.

### ISSUE THREAD

**Issue by fclaussen** [lucatume/wp-browser#412]
**Environment**
OS: Mac
PHP version: 7.3.5
Installed Codeception version: Unsure(isn't wp-browser installing it as a dep?)
Installed wp-browser version: 2.5
WordPress version: 5.4.1
Local development environment: Local by Flywheel (the new one, with no virtualbox)
WordPress structure and management: default

**Did you use the `codecept init wpbrowser` command?**
Yes. That is the command that is not working for me.

**Did you take a look at Codeception and wp-browser documentation?**
Yes.
More specifically: [https://wpbrowser.wptestkit.dev/getting-started/configuration](https://wpbrowser.wptestkit.dev/getting-started/configuration)

**Codeception configuration file**
Is this the codeception.dist.yml?
```yaml
paths:
    tests: tests
    output: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
actor_suffix: Tester
extensions:
    enabled:
        - Codeception\Extension\RunFailed
    commands:
        - Codeception\Command\GenerateWPUnit
        - Codeception\Command\GenerateWPRestApi
        - Codeception\Command\GenerateWPRestController
        - Codeception\Command\GenerateWPRestPostTypeController
        - Codeception\Command\GenerateWPAjax
        - Codeception\Command\GenerateWPCanonical
        - Codeception\Command\GenerateWPXMLRPC
params:
    - .env.testing

```

**Suite configuration file**
I have none.

**Describe the issue you're encountering**
I run `./vendor/bin/codecept init wpbrowser` to start the process. I select yes to setup interactively. Comparing to [the screenshots here](https://wpbrowser.wptestkit.dev/getting-started/configuration) I don't get the first few questions about what I want to name my suites.
Moving on through the setup, after it asks if any additional plugins are required, I answer no and then it breaks with this error.
```
[Codeception\Exception\ConfigurationException]
  Module Asserts is not installed.
  Use Composer to install corresponding package:

  composer require codeception/module-asserts --dev
```

I've tried starting over but running this command before `init wpbrowser` but then I get to the same point with a different error: 
```
[Codeception\Exception\ConfigurationException]
  The WPDb module requires the Db Codeception module or component.
  Use Composer to install the corresponding package:
  "composer require codeception/module-db --dev"
```

After I got the second error I thought it was time to come here as none of these extra commands are documented anywhere.

**To Reproduce**
Install the latest Local By Flywheel (v5.4.1) - This may not be required as I tried this elsewhere and I got the same error
Run the setup.

**Screenshots**
<img width="1237" alt="Screen Shot 2020-05-27 at 12 25 38 PM" src="https://user-images.githubusercontent.com/1021860/83046667-55a73400-a015-11ea-96a8-21adfc1ee1ad.png">
<img width="737" alt="Screen Shot 2020-05-27 at 12 26 26 PM" src="https://user-images.githubusercontent.com/1021860/83046676-58a22480-a015-11ea-97ac-ac7168b74671.png">
