### ISSUE TITLE
[BUG] Database connection issues in Flywheel

### ISSUE THREAD

**Issue by fclaussen** [lucatume/wp-browser#414]
**Environment**
OS: Mac
PHP version: 7.3.5
Installed Codeception version: 4.1.5
Installed wp-browser version: 2.5.5
WordPress version: 5.4.1
Local development environment: Local by Flywheel (v5.4.1)
WordPress structure and management: default

**Can you perform the test manually?**
no

**Codeception configuration file**  
Paste, in a fenced YAML block, the content of your Codeception configuration file; remove any sensitive data!  

```yaml
paths:
    tests: tests
    output: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
actor_suffix: Tester
extensions:
    enabled:
        - Codeception\Extension\RunFailed
    commands:
        - Codeception\Command\GenerateWPUnit
        - Codeception\Command\GenerateWPRestApi
        - Codeception\Command\GenerateWPRestController
        - Codeception\Command\GenerateWPRestPostTypeController
        - Codeception\Command\GenerateWPAjax
        - Codeception\Command\GenerateWPCanonical
        - Codeception\Command\GenerateWPXMLRPC
params:
    - .env.testing
```

**Suite configuration file**
Paste, in a fenced YAML block, the content of the suite configuration file; remove any sensitive data!

```yaml
# Codeception Test Suite Configuration
#
# Suite for acceptance tests.
# Perform tests in browser using the WPWebDriver or WPBrowser.
# Use WPDb to set up your initial database fixture.
# If you need both WPWebDriver and WPBrowser tests - create a separate suite.

actor: AcceptanceTester
modules:
    enabled:
        - WPDb
        - WPBrowser
        - \Helper\Acceptance
    config:
        WPDb:
            dsn: '%TEST_SITE_DB_DSN%'
            user: '%TEST_SITE_DB_USER%'
            password: '%TEST_SITE_DB_PASSWORD%'
            dump: 'tests/_data/dump.sql'
            #import the dump before the tests; this means the test site database will be repopulated before the tests.
            populate: true
            # re-import the dump between tests; this means the test site database will be repopulated between the tests.
            cleanup: true
            waitlock: 10
            url: '%TEST_SITE_WP_URL%'
            urlReplacement: true #replace the hardcoded dump URL with the one above
            tablePrefix: '%TEST_SITE_TABLE_PREFIX%'
        WPBrowser:
            url: '%TEST_SITE_WP_URL%'
            adminUsername: '%TEST_SITE_ADMIN_USERNAME%'
            adminPassword: '%TEST_SITE_ADMIN_PASSWORD%'
            adminPath: '%TEST_SITE_WP_ADMIN_PATH%'
            headers:
                X_TEST_REQUEST: 1
                X_WPBROWSER_REQUEST: 1
```

**Describe the bug**
It appears the test can't connect to the database.
After the `init wpbrowser` function I called each suite as a sanity check.

| unit | wpunit | functional | run acceptance |
|-----|--------|-----------|-----------------|
| ✅ | 🚫 | 🚫 | 🚫 |

**Output**
For wpunit I got the following error
```
Warning: mysqli_real_connect(): (HY000/2002): No such file or directory in /Users/trewknowledge002/Local Sites/gdpr/app/public/wp-includes/wp-db.php on line 1626

wp_die called
Message : <p><code>No such file or directory</code></p>
<h1>Error establishing a database connection</h1>
<p>This either means that the username and password information in your <code>wp-config.php</code> file is incorrect or we can&#8217;t contact the database server at <code>localhost:~/Library/Application Support/Local/run/lUUlsB1jb/mysql/mysqld.sock</code>. This could mean your host&#8217;s database server is down.</p>
<ul>
<li>Are you sure you have the correct username and password?</li>
<li>Are you sure you have typed the correct hostname?</li>
<li>Are you sure the database server is running?</li>
</ul>
<p>If you&#8217;re unsure what these terms mean you should probably contact your host. If you still need help you can always visit the <a href="https://wordpress.org/support/forums/">WordPress Support Forums</a>.</p>

Title :

Warning: Cannot modify header information - headers already sent by (output started at /Users/trewknowledge002/Local Sites/gdpr/app/public/wp-includes/wp-db.php:1626) in /Users/trewknowledge002/Local Sites/gdpr/app/public/wp-includes/pluggable.php on line 1281

Warning: Cannot modify header information - headers already sent by (output started at /Users/trewknowledge002/Local Sites/gdpr/app/public/wp-includes/wp-db.php:1626) in /Users/trewknowledge002/Local Sites/gdpr/app/public/wp-includes/pluggable.php on line 1284
```

For functional or acceptance I got this:

```
Codeception PHP Testing Framework v4.1.5
Powered by PHPUnit 7.5.20 by Sebastian Bergmann and contributors.
Running with seed:



  [Codeception\Exception\ModuleException]
  Db: SQLSTATE[HY000] [2002] No such file or directory while creating PDO connection
```

**To Reproduce**
Follow these steps: https://wpbrowser.wptestkit.dev/tutorials/local-flywheel-setup

- Create a new site on local
- add the extra stuff on composer.json to account for that Codeception 4 issue
- Run init wpbrowser
- When asked for your database host, look in flywheel. In my case it is `/Users/trewknowledge002/Library/Application Support/Local/run/lUUlsB1jb/mysql/mysqld.sock`
- Try running all suites

**Expected behavior**
All suites would run

**Screenshots**
<img width="794" alt="Screen Shot 2020-05-29 at 7 35 57 PM" src="https://user-images.githubusercontent.com/1021860/83313341-c439ec80-a1e3-11ea-92fe-480af0f03399.png">
<img width="998" alt="Screen Shot 2020-05-29 at 7 37 29 PM" src="https://user-images.githubusercontent.com/1021860/83313362-db78da00-a1e3-11ea-8582-2d4908143a91.png">
<img width="706" alt="Screen Shot 2020-05-29 at 7 38 31 PM" src="https://user-images.githubusercontent.com/1021860/83313403-0cf1a580-a1e4-11ea-809c-d91f84a0f0e2.png">
<img width="1680" alt="Screen Shot 2020-05-29 at 7 38 42 PM" src="https://user-images.githubusercontent.com/1021860/83313414-1713a400-a1e4-11ea-8abb-bebcd1cd6cf4.png">
<img width="681" alt="Screen Shot 2020-05-29 at 7 38 52 PM" src="https://user-images.githubusercontent.com/1021860/83313419-1b3fc180-a1e4-11ea-8969-5f5af20ac5c6.png">
