### ISSUE TITLE
[BUG] $I->activatePlugin Exception: A ChoiceFormField can only be created from an input tag with a type of checkbox or radio

### ISSUE THREAD

**Issue by BrianHenryIE** [lucatume/wp-browser#415]
**Environment**
OS: Mac
PHP version: 7.4
Installed Codeception version: 4.1.5
Installed wp-browser version: 2.5.5
WordPress version: 5.4.1
Local development environment: MacOS Apache
WordPress structure and management: default

**Can you perform the test manually?**
Yes, opening plugins.php in Firefox and activating the plugin works fine.

**Codeception configuration file**  

```yaml
paths:
    tests: tests
    output: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
actor_suffix: Tester
extensions:
    enabled:
        - Codeception\Extension\RunFailed
    commands:
        - Codeception\Command\GenerateWPUnit
        - Codeception\Command\GenerateWPRestApi
        - Codeception\Command\GenerateWPRestController
        - Codeception\Command\GenerateWPRestPostTypeController
        - Codeception\Command\GenerateWPAjax
        - Codeception\Command\GenerateWPCanonical
        - Codeception\Command\GenerateWPXMLRPC
params:
    - .env.testing
coverage:
    enabled: true
    include:
        - src/*
    exclude:
        - src/dependencies/*
        - src/vendor/*
bootstrap: bootstrap.php
```

`bootstrap.php` defines some $GLOBALS. Replacing it with an empty `<?php` file doesn't change behaviour.

**Suite configuration file**

```yaml
actor: AcceptanceTester
modules:
    enabled:
        - WPDb
        - WPBrowser
        - \Helper\Acceptance
    config:
        WPDb:
            dsn: 'mysql:host=%TEST_SITE_DB_HOST%;dbname=%TEST_SITE_DB_NAME%'
            user: '%TEST_SITE_DB_USER%'
            password: '%TEST_SITE_DB_PASSWORD%'
            dump: 'tests/_data/dump.sql'
            #import the dump before the tests; this means the test site database will be repopulated before the tests.
            populate: true
            # re-import the dump between tests; this means the test site database will be repopulated between the tests.
            cleanup: true
            waitlock: 10
            originalUrl: http://localhost
            url: '%TEST_SITE_WP_URL%'
            urlReplacement: true #replace the hardcoded dump URL with the one above
            tablePrefix: '%TEST_SITE_TABLE_PREFIX%'
        WPBrowser:
            url: '%TEST_SITE_WP_URL%'
            adminUsername: '%TEST_SITE_ADMIN_USERNAME%'
            adminPassword: '%TEST_SITE_ADMIN_PASSWORD%'
            adminPath: '%TEST_SITE_WP_ADMIN_PATH%'
            headers:
                X_TEST_REQUEST: 1
                X_WPBROWSER_REQUEST: 1
```

**Describe the bug**
I'm trying to activate a plugin with `$I->activatePlugin("bh-wc-set-gateway-by-url")` and I'm getting the error: `A ChoiceFormField can only be created from an input tag with a type of checkbox or radio (given type is "hidden")`

I have logged in as admin (and searched the issues here for the problem).

**Output**

```shell script
There was 1 error:

---------
1) SettingsPageCest: Test settings page for name
 Test  tests/acceptance/SettingsPageCest.php:testSettingsPageForName
                                                                                                                                       
  [LogicException] A ChoiceFormField can only be created from an input tag with a type of checkbox or radio (given type is "hidden").  
                                                                                                                                       

Scenario Steps:

 3. $I->activatePlugin("bh-wc-set-gateway-by-url") at tests/acceptance/SettingsPageCest.php:22
 2. $I->amOnPluginsPage() at tests/acceptance/SettingsPageCest.php:20
 1. $I->loginAsAdmin() at tests/acceptance/SettingsPageCest.php:7

#1  /Users/BrianHenryIE/Sites/triplea-payment-gateway-for-woocommerce/vendor/symfony/dom-crawler/Field/ChoiceFormField.php:208
#2  /Users/BrianHenryIE/Sites/triplea-payment-gateway-for-woocommerce/vendor/symfony/dom-crawler/Field/FormField.php:55
#3  /Users/BrianHenryIE/Sites/triplea-payment-gateway-for-woocommerce/vendor/lucatume/wp-browser/src/Codeception/Module/WPBrowser.php:86
#4  Codeception\Module\WPBrowser->activatePlugin
#5  /Users/BrianHenryIE/Sites/triplea-payment-gateway-for-woocommerce/tests/_support/_generated/AcceptanceTesterActions.php:4062
#6  /Users/BrianHenryIE/Sites/triplea-payment-gateway-for-woocommerce/tests/acceptance/SettingsPageCest.php:22
#7  SettingsPageCest->testSettingsPageForName
```

**To Reproduce**

It can be reproduced from the commit at:
https://github.com/BrianHenryIE/triplea-woocommerce-plugin/tree/c6a4f563d148b46d923403cbd71b366efb3e9f46

**Expected behavior**

The plugin gets activated and we carry on!

**Additional context**

In the HTML saved by Codeception in _output, the only mentions of bh-wc-set-gateway-by-url in the page don't have any attribute "hidden" near them.

```html
<tr class="inactive" data-slug="bh-wc-set-gateway-by-url" data-plugin="bh-wc-set-gateway-by-url/bh-wc-set-gateway-by-url.php">
<th scope='row' class='check-column'>
<label class="screen-reader-text" for="checkbox_8fec7cc87629620a6fffed265f960f00">Select Set Gateway By URL</label>
<input type="checkbox" name="checked[]" value="bh-wc-set-gateway-by-url/bh-wc-set-gateway-by-url.php" id="checkbox_8fec7cc87629620a6fffed265f960f00" />
</th>
<td class='plugin-title column-primary'>
<strong>Set Gateway By URL</strong>
<div class="row-actions visible">
<span class='activate'><a href="plugins.php?action=activate&amp;plugin=bh-wc-set-gateway-by-url%2Fbh-wc-set-gateway-by-url.php&amp;plugin_status=all&amp;paged=1&amp;s&amp;_wpnonce=078353fac1" class="edit" aria-label="Activate Set Gateway By URL">Activate</a> | </span>
<span class='delete'><a href="plugins.php?action=delete-selected&amp;checked%5B0%5D=bh-wc-set-gateway-by-url%2Fbh-wc-set-gateway-by-url.php&amp;plugin_status=all&amp;paged=1&amp;s&amp;_wpnonce=129c5982f5" class="delete" aria-label="Delete Set Gateway By URL">Delete</a></span>
</div>
<button type="button" class="toggle-row"><span class="screen-reader-text">Show more details</span></button>
</td>
<td class='column-description desc'>
<div class='plugin-description'><p>Use <em>?payment_gateway=gateway_id</em> in URLs sent to customers to set the WooCommerce checkout payment gateway for them.</p></div>
<div class='inactive second plugin-version-author-uri'>Version 1.0.5 | By <a href="https://BrianHenry.ie">Brian Henry</a> | <a href="http://localhost/triplea-payment-gateway-for-woocommerce/wp-admin/plugin-install.php?tab=plugin-information&#038;plugin=bh-wc-set-gateway-by-url&#038;TB_iframe=true&#038;width=600&#038;height=550" class="thickbox open-plugin-details-modal" aria-label="More information about Set Gateway By URL" data-title="Set Gateway By URL">View details</a></div>
</td>
</tr>
```

```html
var _wpUpdatesItemCounts = {"plugins":{"all":["triplea-payment-gateway-for-woocommerce\/triplea-payment-gateway-for-woocommerce.php","bh-wc-set-gateway-by-url\/bh-wc-set-gateway-by-url.php","woocommerce\/woocommerce.php"],"search":[],"active":["triplea-payment-gateway-for-woocommerce\/triplea-payment-gateway-for-woocommerce.php","woocommerce\/woocommerce.php"],"inactive":["bh-wc-set-gateway-by-url\/bh-wc-set-gateway-by-url.php"],"recently_activated":[],"upgrade":[],"mustuse":[],"dropins":[],"paused":[]},"totals":{"counts":{"plugins":0,"themes":0,"wordpress":0,"translations":0,"total":0},"title":""}};
```

I also used `$I->see('Search installed plugins');` to verify `amOnPluginsPage` has completed.
