### ISSUE TITLE
[BUG] Session not created error when running acceptance and functional tests

### ISSUE THREAD

**Issue by dingo-d** [lucatume/wp-browser#416]
**Environment**
OS: MacOS 10.15.5
PHP version: 7.3.18
Installed Codeception version: 4.1.5
Installed wp-browser version: `dev-feat/wptestcase-isolation 8d5fd0f`
WordPress version: 5.4.1
Local development environment: VVV
WordPress structure and management: Default

**Can you perform the test manually?**
Yes I can go to the site, it works fine

**Codeception configuration file**  
Paste, in a fenced YAML block, the content of your Codeception configuration file; remove any sensitive data!  

```yaml
paths:
    tests: tests
    output: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
actor_suffix: Tester
extensions:
    enabled:
        - Codeception\Extension\RunFailed
    commands:
        - Codeception\Command\GenerateWPUnit
        - Codeception\Command\GenerateWPRestApi
        - Codeception\Command\GenerateWPRestController
        - Codeception\Command\GenerateWPRestPostTypeController
        - Codeception\Command\GenerateWPAjax
        - Codeception\Command\GenerateWPCanonical
        - Codeception\Command\GenerateWPXMLRPC
params:
    - .env.testing
coverage:
    enabled: true
    include:
        - src/*
    exclude:
        - src/Core/CompiledContainer.php
        - src/Old/*
    low_limit: 30
    high_limit: 75
settings:
    colors: true
    memory_limit: 2048M
```

**Suite configuration file**
Paste, in a fenced YAML block, the content of the suite configuration file; remove any sensitive data!

Functional.suite.yaml
```yaml
# Codeception Test Suite Configuration
#
# Suite for functional tests
# Emulate web requests and make WordPress process them

actor: FunctionalTester
modules:
    enabled:
        - WPDb
        - WPWebDriver
        - WPFilesystem
        - Asserts
        - \Helper\Functional
    config:
        WPDb:
            dsn: 'mysql:host=%TEST_SITE_DB_HOST%;dbname=%TEST_SITE_DB_NAME%'
            user: '%TEST_SITE_DB_USER%'
            password: '%TEST_SITE_DB_PASSWORD%'
            dump: 'tests/_data/dump.sql'
            populate: true
            cleanup: true
            waitlock: 10
            url: '%TEST_SITE_WP_URL%'
            originalUrl: '%TEST_SITE_WP_URL%'
            urlReplacement: true
            tablePrefix: '%TEST_SITE_TABLE_PREFIX%'
        WPWebDriver:
            url: '%TEST_SITE_WP_URL%'
            adminUsername: '%TEST_SITE_ADMIN_USERNAME%'
            adminPassword: '%TEST_SITE_ADMIN_PASSWORD%'
            adminPath: '%TEST_SITE_WP_ADMIN_PATH%'
            browser: chrome
            host: localhost
            port: 9515
            window_size: false #disabled for Chrome driver
            capabilities:
                # Used in more recent releases of Selenium.
                "goog:chromeOptions":
                    args: ["--no-sandbox", "--headless", "--disable-gpu", "--user-agent=wp-browser"]
                # Support the old format for back-compatibility purposes.
                "chromeOptions":
                    args: ["--no-sandbox", "--headless", "--disable-gpu", "--user-agent=wp-browser"]
        WPFilesystem:
            wpRootFolder: '%WP_ROOT_FOLDER%'
            plugins: '/wp-content/plugins'
            mu-plugins: '/wp-content/mu-plugins'
            themes: '/wp-content/themes'
            uploads: '/wp-content/uploads'
```

Acceptance.suite.yml

```yml
# Codeception Test Suite Configuration
#
# Suite for acceptance tests.
# Perform tests in browser using the WPWebDriver or WPBrowser.
# Use WPDb to set up your initial database fixture.
# If you need both WPWebDriver and WPBrowser tests - create a separate suite.

actor: AcceptanceTester
modules:
    enabled:
        - WPDb
        - WPWebDriver
        - \Helper\Acceptance
    config:
        WPDb:
            dsn: 'mysql:host=%TEST_SITE_DB_HOST%;dbname=%TEST_SITE_DB_NAME%'
            user: '%TEST_SITE_DB_USER%'
            password: '%TEST_SITE_DB_PASSWORD%'
            dump: 'tests/_data/dump.sql'
            #import the dump before the tests; this means the test site database will be repopulated before the tests.
            populate: true
            # re-import the dump between tests; this means the test site database will be repopulated between the tests.
            cleanup: true
            waitlock: 10
            url: '%TEST_SITE_WP_URL%'
            originalUrl: '%TEST_SITE_WP_URL%'
            urlReplacement: true #replace the hardcoded dump URL with the one above
            tablePrefix: '%TEST_SITE_TABLE_PREFIX%'
        WPWebDriver:
            originalUrl: '%TEST_SITE_WP_URL%'
            url: '%TEST_SITE_WP_URL%'
            adminUsername: '%TEST_SITE_ADMIN_USERNAME%'
            adminPassword: '%TEST_SITE_ADMIN_PASSWORD%'
            adminPath: '%TEST_SITE_WP_ADMIN_PATH%'
            browser: chrome
            host: localhost
            port: 9515
            window_size: false #disabled for Chrome driver
            capabilities:
                # Used in more recent releases of Selenium.
                "goog:chromeOptions":
                    args: ["--no-sandbox", "--headless", "--disable-gpu", "--user-agent=wp-browser"]
                # Support the old format for back-compatibility purposes.
                "chromeOptions":
                    args: ["--no-sandbox", "--headless", "--disable-gpu", "--user-agent=wp-browser"]
```

**Describe the bug**
I have ChromeDriver v 84.0.4147.30 and Selenium server v 3.141.59

And when I try to run either acceptance or functional tests I get

```bash
  [Facebook\WebDriver\Exception\SessionNotCreatedException] session not created: This version of ChromeDriver only supports Chrome version 84
```

error.

When running tests on another project, everything works fine (same setup). Not sure what could be the issue

**Output**

```bash
vendor/bin/codecept run Acceptance -vvv

Codeception PHP Testing Framework v4.1.5
Powered by PHPUnit 8.5.5 by Sebastian Bergmann and contributors.
Running with seed:


  [Connecting To Db] {"config":{"tablePrefix":"wp_","populate":true,"cleanup":true,"reconnect":false,"dump":"tests/_data/dump.sql","populator":null,"urlReplacement":true,"originalUrl":"https://myproject.test/","waitlock":10,"dsn":"mysql:host=vvv.test;dbname=tests","user":"external","password":"external","url":"https://myproject.test/"},"options":[]}
  [Db] Connected to default tests
  [Query] INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES (?, ?, ?)
  [Parameters] ["admin_email_lifespan",2533080438,"yes"]
  [Query] INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES (?, ?, ?)
  [Parameters] ["_transient_doing_cron",1591191570,"yes"]

Acceptance Tests (2) -----------------------------------------------------------------------------------------------------------------------------------------------------------------------
Modules: WPDb, WPWebDriver, \Helper\Acceptance
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
PluginActivationCest: Activate plugin successfully
Signature: Tests\Acceptance\Activation\PluginActivationCest:activatePluginSuccessfully
Test: tests/Acceptance/Activation/PluginActivationCest.php:activatePluginSuccessfully
Scenario --
  [Query] INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES (?, ?, ?)
  [Parameters] ["admin_email_lifespan",2533080438,"yes"]
  [Query] INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES (?, ?, ?)
  [Parameters] ["_transient_doing_cron",1591191573,"yes"]
  WebDriver::debugWebDriverLogs method has been called when webDriver is not set
  WebDriver::_saveScreenshot method has been called when webDriver is not set
  WebDriver::_savePageSource method has been called when webDriver is not set
  Screenshot and page source were saved into '.../public_html/wp-content/plugins/my-plugin/tests/_output/' dir
 ERROR

PluginActivationCest: See error being thrown on plugin activation if acf is not activated
Signature: Tests\Acceptance\Activation\PluginActivationCest:seeErrorBeingThrownOnPluginActivationIfAcfIsNotActivated
Test: tests/Acceptance/Activation/PluginActivationCest.php:seeErrorBeingThrownOnPluginActivationIfAcfIsNotActivated
Scenario --
  [Query] INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES (?, ?, ?)
  [Parameters] ["admin_email_lifespan",2533080438,"yes"]
  [Query] INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES (?, ?, ?)
  [Parameters] ["_transient_doing_cron",1591191575,"yes"]
  WebDriver::debugWebDriverLogs method has been called when webDriver is not set
  WebDriver::_saveScreenshot method has been called when webDriver is not set
  WebDriver::_savePageSource method has been called when webDriver is not set
  Screenshot and page source were saved into '.../public_html/wp-content/plugins/my-plugin/tests/_output/' dir
 ERROR

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


Time: 7.04 seconds, Memory: 29.35 MB

There were 2 errors:

---------
1) PluginActivationCest: Activate plugin successfully
 Test  tests/Acceptance/Activation/PluginActivationCest.php:activatePluginSuccessfully

  [Facebook\WebDriver\Exception\SessionNotCreatedException] session not created: This version of ChromeDriver only supports Chrome version 84

.../public_html/wp-content/plugins/my-plugin/vendor/php-webdriver/webdriver/lib/Exception/WebDriverException.php:125
.../public_html/wp-content/plugins/my-plugin/vendor/php-webdriver/webdriver/lib/Remote/HttpCommandExecutor.php:370
.../public_html/wp-content/plugins/my-plugin/vendor/php-webdriver/webdriver/lib/Remote/RemoteWebDriver.php:136
.../public_html/wp-content/plugins/my-plugin/vendor/codeception/module-webdriver/src/Codeception/Module/WebDriver.php:1473
.../public_html/wp-content/plugins/my-plugin/vendor/codeception/module-webdriver/src/Codeception/Module/WebDriver.php:424
.../public_html/wp-content/plugins/my-plugin/vendor/codeception/codeception/src/Codeception/Subscriber/Module.php:56
.../public_html/wp-content/plugins/my-plugin/vendor/symfony/event-dispatcher/EventDispatcher.php:230
.../public_html/wp-content/plugins/my-plugin/vendor/symfony/event-dispatcher/EventDispatcher.php:59
.../public_html/wp-content/plugins/my-plugin/vendor/codeception/phpunit-wrapper/src/DispatcherWrapper.php:22
.../public_html/wp-content/plugins/my-plugin/vendor/codeception/phpunit-wrapper/src/Listener.php:134
.../public_html/wp-content/plugins/my-plugin/vendor/codeception/phpunit-wrapper/src/Listener.php:103
.../public_html/wp-content/plugins/my-plugin/vendor/phpunit/phpunit/src/Framework/TestResult.php:411
.../public_html/wp-content/plugins/my-plugin/vendor/codeception/codeception/src/Codeception/Test/Test.php:75
.../public_html/wp-content/plugins/my-plugin/vendor/phpunit/phpunit/src/Framework/TestSuite.php:597
.../public_html/wp-content/plugins/my-plugin/vendor/codeception/phpunit-wrapper/src/Runner.php:117
.../public_html/wp-content/plugins/my-plugin/vendor/codeception/codeception/src/Codeception/SuiteManager.php:161
.../public_html/wp-content/plugins/my-plugin/vendor/codeception/codeception/src/Codeception/Codecept.php:196
.../public_html/wp-content/plugins/my-plugin/vendor/codeception/codeception/src/Codeception/Codecept.php:163
.../public_html/wp-content/plugins/my-plugin/vendor/codeception/codeception/src/Codeception/Command/Run.php:503
.../public_html/wp-content/plugins/my-plugin/vendor/codeception/codeception/src/Codeception/Command/Run.php:397
.../public_html/wp-content/plugins/my-plugin/vendor/symfony/console/Command/Command.php:258
.../public_html/wp-content/plugins/my-plugin/vendor/symfony/console/Application.php:911
.../public_html/wp-content/plugins/my-plugin/vendor/symfony/console/Application.php:264
.../public_html/wp-content/plugins/my-plugin/vendor/symfony/console/Application.php:140
.../public_html/wp-content/plugins/my-plugin/vendor/codeception/codeception/src/Codeception/Application.php:117
.../public_html/wp-content/plugins/my-plugin/vendor/codeception/codeception/app.php:46
.../public_html/wp-content/plugins/my-plugin/vendor/codeception/codeception/app.php:47
.../public_html/wp-content/plugins/my-plugin/vendor/codeception/codeception/codecept:7

Artifacts:

Png: .../public_html/wp-content/plugins/my-plugin/tests/_output/Tests.Acceptance.Activation.PluginActivationCest.activatePluginSuccessfully.fail.png
Html: .../public_html/wp-content/plugins/my-plugin/tests/_output/Tests.Acceptance.Activation.PluginActivationCest.activatePluginSuccessfully.fail.html

---------
2) PluginActivationCest: See error being thrown on plugin activation if acf is not activated
 Test  tests/Acceptance/Activation/PluginActivationCest.php:seeErrorBeingThrownOnPluginActivationIfAcfIsNotActivated

  [Facebook\WebDriver\Exception\SessionNotCreatedException] session not created: This version of ChromeDriver only supports Chrome version 84

.../public_html/wp-content/plugins/my-plugin/vendor/php-webdriver/webdriver/lib/Exception/WebDriverException.php:125
.../public_html/wp-content/plugins/my-plugin/vendor/php-webdriver/webdriver/lib/Remote/HttpCommandExecutor.php:370
.../public_html/wp-content/plugins/my-plugin/vendor/php-webdriver/webdriver/lib/Remote/RemoteWebDriver.php:136
.../public_html/wp-content/plugins/my-plugin/vendor/codeception/module-webdriver/src/Codeception/Module/WebDriver.php:1473
.../public_html/wp-content/plugins/my-plugin/vendor/codeception/module-webdriver/src/Codeception/Module/WebDriver.php:424
.../public_html/wp-content/plugins/my-plugin/vendor/codeception/codeception/src/Codeception/Subscriber/Module.php:56
.../public_html/wp-content/plugins/my-plugin/vendor/symfony/event-dispatcher/EventDispatcher.php:230
.../public_html/wp-content/plugins/my-plugin/vendor/symfony/event-dispatcher/EventDispatcher.php:59
.../public_html/wp-content/plugins/my-plugin/vendor/codeception/phpunit-wrapper/src/DispatcherWrapper.php:22
.../public_html/wp-content/plugins/my-plugin/vendor/codeception/phpunit-wrapper/src/Listener.php:134
.../public_html/wp-content/plugins/my-plugin/vendor/codeception/phpunit-wrapper/src/Listener.php:103
.../public_html/wp-content/plugins/my-plugin/vendor/phpunit/phpunit/src/Framework/TestResult.php:411
.../public_html/wp-content/plugins/my-plugin/vendor/codeception/codeception/src/Codeception/Test/Test.php:75
.../public_html/wp-content/plugins/my-plugin/vendor/phpunit/phpunit/src/Framework/TestSuite.php:597
.../public_html/wp-content/plugins/my-plugin/vendor/codeception/phpunit-wrapper/src/Runner.php:117
.../public_html/wp-content/plugins/my-plugin/vendor/codeception/codeception/src/Codeception/SuiteManager.php:161
.../public_html/wp-content/plugins/my-plugin/vendor/codeception/codeception/src/Codeception/Codecept.php:196
.../public_html/wp-content/plugins/my-plugin/vendor/codeception/codeception/src/Codeception/Codecept.php:163
.../public_html/wp-content/plugins/my-plugin/vendor/codeception/codeception/src/Codeception/Command/Run.php:503
.../public_html/wp-content/plugins/my-plugin/vendor/codeception/codeception/src/Codeception/Command/Run.php:397
.../public_html/wp-content/plugins/my-plugin/vendor/symfony/console/Command/Command.php:258
.../public_html/wp-content/plugins/my-plugin/vendor/symfony/console/Application.php:911
.../public_html/wp-content/plugins/my-plugin/vendor/symfony/console/Application.php:264
.../public_html/wp-content/plugins/my-plugin/vendor/symfony/console/Application.php:140
.../public_html/wp-content/plugins/my-plugin/vendor/codeception/codeception/src/Codeception/Application.php:117
.../public_html/wp-content/plugins/my-plugin/vendor/codeception/codeception/app.php:46
.../public_html/wp-content/plugins/my-plugin/vendor/codeception/codeception/app.php:47
.../public_html/wp-content/plugins/my-plugin/vendor/codeception/codeception/codecept:7

Artifacts:

Png: .../public_html/wp-content/plugins/my-plugin/tests/_output/Tests.Acceptance.Activation.PluginActivationCest.seeErrorBeingThrownOnPluginActivationIfAcfIsNotActivated.fail.png
Html: .../public_html/wp-content/plugins/my-plugin/tests/_output/Tests.Acceptance.Activation.PluginActivationCest.seeErrorBeingThrownOnPluginActivationIfAcfIsNotActivated.fail.html

ERRORS!
Tests: 2, Assertions: 0, Errors: 2.
  [Db] Disconnected from default
```

```bash
vendor/bin/codecept run Functional -vvv

Codeception PHP Testing Framework v4.1.5
Powered by PHPUnit 8.5.5 by Sebastian Bergmann and contributors.
Running with seed:


  [Connecting To Db] {"config":{"tablePrefix":"wp_","populate":true,"cleanup":true,"reconnect":false,"dump":"tests/_data/dump.sql","populator":null,"urlReplacement":true,"originalUrl":"https://myproject.test/","waitlock":10,"dsn":"mysql:host=vvv.test;dbname=tests","user":"external","password":"external","url":"https://myproject.test/"},"options":[]}
  [Db] Connected to default tests
  [Query] INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES (?, ?, ?)
  [Parameters] ["admin_email_lifespan",2533080438,"yes"]
  [Query] INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES (?, ?, ?)
  [Parameters] ["_transient_doing_cron",1591191612,"yes"]

Functional Tests (1) -----------------------------------------------------------------------------------------------------------------------------------------------------------------------
Modules: WPDb, WPWebDriver, WPFilesystem, Asserts, \Helper\Functional
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
LoginCest: Test login endpoint works
Signature: Tests\Functional\Endpoints\LoginCest:testLoginEndpointWorks
Test: tests/Functional/Endpoints/LoginCest.php:testLoginEndpointWorks
Scenario --
  [Query] INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES (?, ?, ?)
  [Parameters] ["admin_email_lifespan",2533080438,"yes"]
  [Query] INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES (?, ?, ?)
  [Parameters] ["_transient_doing_cron",1591191614,"yes"]
  WebDriver::debugWebDriverLogs method has been called when webDriver is not set
  WebDriver::_saveScreenshot method has been called when webDriver is not set
  WebDriver::_savePageSource method has been called when webDriver is not set
  Screenshot and page source were saved into '/public_html/wp-content/plugins/my-plugin/tests/_output/' dir
 ERROR

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


Time: 3.85 seconds, Memory: 26.90 MB

There was 1 error:

---------
1) LoginCest: Test login endpoint works
 Test  tests/Functional/Endpoints/LoginCest.php:testLoginEndpointWorks

  [Facebook\WebDriver\Exception\SessionNotCreatedException] session not created: This version of ChromeDriver only supports Chrome version 84

/public_html/wp-content/plugins/my-plugin/vendor/php-webdriver/webdriver/lib/Exception/WebDriverException.php:125
/public_html/wp-content/plugins/my-plugin/vendor/php-webdriver/webdriver/lib/Remote/HttpCommandExecutor.php:370
/public_html/wp-content/plugins/my-plugin/vendor/php-webdriver/webdriver/lib/Remote/RemoteWebDriver.php:136
/public_html/wp-content/plugins/my-plugin/vendor/codeception/module-webdriver/src/Codeception/Module/WebDriver.php:1473
/public_html/wp-content/plugins/my-plugin/vendor/codeception/module-webdriver/src/Codeception/Module/WebDriver.php:424
/public_html/wp-content/plugins/my-plugin/vendor/codeception/codeception/src/Codeception/Subscriber/Module.php:56
/public_html/wp-content/plugins/my-plugin/vendor/symfony/event-dispatcher/EventDispatcher.php:230
/public_html/wp-content/plugins/my-plugin/vendor/symfony/event-dispatcher/EventDispatcher.php:59
/public_html/wp-content/plugins/my-plugin/vendor/codeception/phpunit-wrapper/src/DispatcherWrapper.php:22
/public_html/wp-content/plugins/my-plugin/vendor/codeception/phpunit-wrapper/src/Listener.php:134
/public_html/wp-content/plugins/my-plugin/vendor/codeception/phpunit-wrapper/src/Listener.php:103
/public_html/wp-content/plugins/my-plugin/vendor/phpunit/phpunit/src/Framework/TestResult.php:411
/public_html/wp-content/plugins/my-plugin/vendor/codeception/codeception/src/Codeception/Test/Test.php:75
/public_html/wp-content/plugins/my-plugin/vendor/phpunit/phpunit/src/Framework/TestSuite.php:597
/public_html/wp-content/plugins/my-plugin/vendor/codeception/phpunit-wrapper/src/Runner.php:117
/public_html/wp-content/plugins/my-plugin/vendor/codeception/codeception/src/Codeception/SuiteManager.php:161
/public_html/wp-content/plugins/my-plugin/vendor/codeception/codeception/src/Codeception/Codecept.php:196
/public_html/wp-content/plugins/my-plugin/vendor/codeception/codeception/src/Codeception/Codecept.php:163
/public_html/wp-content/plugins/my-plugin/vendor/codeception/codeception/src/Codeception/Command/Run.php:503
/public_html/wp-content/plugins/my-plugin/vendor/codeception/codeception/src/Codeception/Command/Run.php:397
/public_html/wp-content/plugins/my-plugin/vendor/symfony/console/Command/Command.php:258
/public_html/wp-content/plugins/my-plugin/vendor/symfony/console/Application.php:911
/public_html/wp-content/plugins/my-plugin/vendor/symfony/console/Application.php:264
/public_html/wp-content/plugins/my-plugin/vendor/symfony/console/Application.php:140
/public_html/wp-content/plugins/my-plugin/vendor/codeception/codeception/src/Codeception/Application.php:117
/public_html/wp-content/plugins/my-plugin/vendor/codeception/codeception/app.php:46
/public_html/wp-content/plugins/my-plugin/vendor/codeception/codeception/app.php:47
/public_html/wp-content/plugins/my-plugin/vendor/codeception/codeception/codecept:7

Artifacts:

Png: /public_html/wp-content/plugins/my-plugin/tests/_output/Tests.Functional.Endpoints.LoginCest.testLoginEndpointWorks.fail.png
Html: /public_html/wp-content/plugins/my-plugin/tests/_output/Tests.Functional.Endpoints.LoginCest.testLoginEndpointWorks.fail.html

ERRORS!
Tests: 1, Assertions: 0, Errors: 1.
  [Db] Disconnected from default
```
