### ISSUE TITLE
[BUG] Correctly set admin bar visibility setting for new users.

### ISSUE THREAD

**Issue by ryanshoover** [lucatume/wp-browser#422]
**Environment**
OS: Ubuntu
PHP version: 7.4.7
Installed Codeception version: 4.1.6
Installed wp-browser version: 2.6.1
WordPress version: 5.4.2
Local development environment: Docker
WordPress structure and management: default

**Can you perform the test manually?**
Not sure what this means

**Codeception configuration file**  
Paste, in a fenced YAML block, the content of your Codeception configuration file; remove any sensitive data!  

```yaml
actor: Tester
paths:
    tests: tests
    log: tests/_output
    data: codecept/_data
    support: codecept/_support
    envs: codecept/_envs
params:
    - env
    - .env
settings:
    shuffle: true
bootstrap: _bootstrap.php
extensions:
    commands:
        - Codeception\Command\GenerateWPUnit
        - Codeception\Command\GenerateWPRestApi
        - Codeception\Command\GenerateWPRestController
        - Codeception\Command\GenerateWPRestPostTypeController
        - Codeception\Command\GenerateWPAjax
        - Codeception\Command\GenerateWPCanonical
        - Codeception\Command\GenerateWPXMLRPC
modules:
    config:
        WPLoader:
            loadOnly: false
            dbName: '%WORDPRESS_DB_NAME%'
            dbHost: '%WORDPRESS_DB_HOST%'
            dbUser: '%WORDPRESS_DB_USER%'
            dbPassword: '%WORDPRESS_DB_PASSWORD%'
            tablePrefix: '%WORDPRESS_TABLE_PREFIX%'
            wpRootFolder: '%WORDPRESS_ROOT_FOLDER%'
            domain: '%WORDPRESS_URL%'
            adminEmail: '%WORDPRESS_ADMIN_EMAIL%'
        WPDb:
            dsn: 'mysql:host=%WORDPRESS_DB_HOST%;dbname=%WORDPRESS_DB_NAME%'
            user: '%WORDPRESS_DB_USER%'
            password: '%WORDPRESS_DB_PASSWORD%'
            url: '%WORDPRESS_URL%'
            populator: 'mysql -u $user -p$password -h $host $dbname < $dump'
            dump: wp-content/mysql.sql
            populate: true
            cleanup: true
            urlReplacement: true
            tablePrefix: '%WORDPRESS_TABLE_PREFIX%'
        WPBrowser:
            url: '%WORDPRESS_URL%'
            adminPath: /wp-admin
            adminUsername: '%WORDPRESS_ADMIN_USERNAME%'
            adminPassword: '%WORDPRESS_ADMIN_PASSWORD%'
        WPCLI:
            path: '%WORDPRESS_ROOT_FOLDER%'
        WPFilesystem:
            wpRootFolder: '%WORDPRESS_ROOT_FOLDER%'
        WPWebDriver:
            url: '%WORDPRESS_URL%'
            adminPath: /wp-admin
            adminUsername: '%WORDPRESS_ADMIN_USERNAME%'
            adminPassword: '%WORDPRESS_ADMIN_PASSWORD%'
            window_size: false
            host: webdriver
            port: 4444
            browser: chrome
            start: true
extensions:
    enabled:
        - tad\WPBrowser\Extension\Symlinker
    config:
        tad\WPBrowser\Extension\Symlinker:
            mode: "theme"
            destination: "/var/www/html/wp-content/themes"
            rootFolder: "/usr/local/src/config/themes/%SYMLINK_FOLDER%"
```

**Suite configuration file**
Paste, in a fenced YAML block, the content of the suite configuration file; remove any sensitive data!

```yaml
# Codeception Test Suite Configuration
#
# Suite for functional tests
# Emulate web requests and make WordPress process them

actor: FunctionalTester
modules:
    enabled:
        - WPDb
        - WPBrowser
        - \Helper\Functional
```

**Describe the bug**
Writing tests around showing and hiding the admin bar, we found a bug with new user creation and that setting. The generator sets the value of `show_admin_bar_front` to the raw value of `true`. However, WP Core checks for the string value of `"true"`. Since wp-browser sets the value to true, the value gets stored in the database as `"1"`. And as a result, any user created by `WPBrowser\Generators\User` doesn't get an admin bar showing on the frontend.

https://github.com/lucatume/wp-browser/blob/master/src/tad/WPBrowser/Generators/User.php#L129
https://github.com/WordPress/WordPress/blob/master/wp-includes/admin-bar.php#L1254

**To Reproduce**
Run this functional test

```php
    public function testAuthorSeesAdminBar( FunctionalTester $I ) {
        $user_id = $I->haveUserInDatabase(
            'author',
            'author',
            [
                'user_pass'  => 'password',
            ]
        );

        // Given that I am logged in as a user with the Subscriber Role.
        $I->loginAs( 'author', 'password' );

        // I view the homepage
        $I->amOnPage( '/' );

        // I don't see the admin bar
        $I->seeElement( '#wpadminbar' );
    }
```

**Expected behavior**
We expect an author to see an admin bar when viewing the frontend, since it's default WP behavior.
