### ISSUE TITLE
[BUG] Original URL port number erroneously appended to replacement URL in functional/acceptance suites

### ISSUE THREAD

**Issue by EvanShaw** [lucatume/wp-browser#430]
**Environment**
OS: Linux  
PHP version: 7.4  
Installed Codeception version: 4.1.6
Installed wp-browser version: 2.6.5
WordPress version: 5.4
Local development environment: Docker
WordPress structure and management: default

**Can you perform the test manually?**
No, because my test environment is a Docker container without any exposed ports

**Codeception configuration file**  
```yaml
paths:
    tests: tests
    output: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
actor_suffix: Tester
extensions:
    enabled:
        - Codeception\Extension\RunFailed
    commands:
        - Codeception\Command\GenerateWPUnit
        - Codeception\Command\GenerateWPRestApi
        - Codeception\Command\GenerateWPRestController
        - Codeception\Command\GenerateWPRestPostTypeController
        - Codeception\Command\GenerateWPAjax
        - Codeception\Command\GenerateWPCanonical
        - Codeception\Command\GenerateWPXMLRPC
params:
    - .env.testing
```

**Suite configuration file**
```yaml
# Codeception Test Suite Configuration
#
# Suite for functional tests
# Emulate web requests and make WordPress process them

actor: FunctionalTester
modules:
    enabled:
        - WPDb
        - WPBrowser
        # - WPFilesystem
        - Asserts
        - \Helper\Functional
        - \Helper\NinshoValidatorProducts
        - REST:
            depends: WPBrowser
    config:
        WPDb:
            dsn: 'mysql:host=%TEST_SITE_DB_HOST%;dbname=%TEST_SITE_DB_NAME%'
            user: '%TEST_SITE_DB_USER%'
            password: '%TEST_SITE_DB_PASSWORD%'
            dump: 'tests/_data/aivec-apps-test.sql'
            populate: true
            cleanup: true
            waitlock: 10
            url: '%TEST_SITE_WP_URL%'
            urlReplacement: true
            tablePrefix: '%TEST_SITE_TABLE_PREFIX%'
        WPBrowser:
            url: '%TEST_SITE_WP_URL%'
            adminUsername: '%TEST_SITE_ADMIN_USERNAME%'
            adminPassword: '%TEST_SITE_ADMIN_PASSWORD%'
            adminPath: '%TEST_SITE_WP_ADMIN_PATH%'
            headers:
                X_TEST_REQUEST: 1
                X_WPBROWSER_REQUEST: 1

        WPFilesystem:
            wpRootFolder: '%WP_ROOT_FOLDER%'
            plugins: '/wp-content/plugins'
            mu-plugins: '/wp-content/mu-plugins'
            themes: '/wp-content/themes'
            uploads: '/wp-content/uploads'
```

**Describe the bug**
When `urlReplace` is `true` and the URL in the dump file has a port number, that port number will be appended to the replacement URL, which causes functional/acceptance test methods to fail. I'm running my environments in Docker where the container URL is `http://ninsho-validator-acceptance-tests-wordpress`. The URL in the dump file is `http://localhost:5100`. After URL replacement the resulting URL is `http://ninsho-validator-acceptance-tests-wordpress:5100`.

Also important to note: **I am running the tests from within the Docker container.**

**Output**
Running `$I->amOnPluginsPage()` results in the following error:
```
[GuzzleHttp\Exception\ConnectException] cURL error 7: Failed to connect to ninsho-validator-acceptance-tests-wordpress port 5100: Connection refused
```

**To Reproduce**
Create a WordPress site on localhost with a random port. Dump the database. Use the dumpfile for a functional/acceptance test where `urlReplace` is `true` and `url` is set to some other local environment without a port number.

**Expected behavior**
The port number is not appended to the replacement URL
