### ISSUE TITLE
[BUG] wp_remote_request throws cURL error 60

### ISSUE THREAD

**Issue by dingo-d** [lucatume/wp-browser#433]
**Environment**
OS: Mac OS 10.15.6
PHP version: 7.4.8
Installed Codeception version: 4.1.6
Installed wp-browser version: 2.6.5
WordPress version: 5.4  
Local development environment: local LEMP stack
WordPress structure and management: default

**Can you perform the test manually?**
Locally, calling curl, or doing any kind of API call works fine.

**Codeception configuration file**  
Paste, in a fenced YAML block, the content of your Codeception configuration file; remove any sensitive data!  

```yaml
paths:
    tests: tests
    output: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
actor_suffix: Tester
extensions:
    enabled:
        - Codeception\Extension\RunFailed
    commands:
        - Codeception\Command\GenerateWPUnit
        - Codeception\Command\GenerateWPRestApi
        - Codeception\Command\GenerateWPRestController
        - Codeception\Command\GenerateWPRestPostTypeController
        - Codeception\Command\GenerateWPAjax
        - Codeception\Command\GenerateWPCanonical
        - Codeception\Command\GenerateWPXMLRPC
params:
    - .env.testing
coverage:
    enabled: true
    include:
        - src/*
    exclude:
        - src/Core/CompiledContainer.php
        - src/Old/*
    low_limit: 30
    high_limit: 75
settings:
    colors: true
    memory_limit: 2048M
```

**Suite configuration file**
Paste, in a fenced YAML block, the content of the suite configuration file; remove any sensitive data!

```yaml
# Codeception Test Suite Configuration
#
# Suite for unit or integration tests that require WordPress functions and classes.

actor: IntegrationTester
modules:
    enabled:
        - WPLoader
        - \Helper\Integration
    config:
        WPLoader:
            wpRootFolder: "%WP_ROOT_FOLDER%"
            dbName: "%TEST_DB_NAME%"
            dbHost: "%TEST_DB_HOST%"
            dbUser: "%TEST_DB_USER%"
            dbPassword: "%TEST_DB_PASSWORD%"
            tablePrefix: "%TEST_TABLE_PREFIX%"
            domain: "%TEST_SITE_WP_DOMAIN%"
            adminEmail: "%TEST_SITE_ADMIN_EMAIL%"
            title: "Test"
            plugins: ['advanced-custom-fields-pro/acf.php', 'classic-editor/classic-editor.php', 'members/members.php', 'my-plugin/my-plugin.php']
            activatePlugins: ['advanced-custom-fields-pro/acf.php', 'classic-editor/classic-editor.php', 'members/members.php', 'my-plugin/my-plugin.php']
```

**Describe the bug**
When running an integration test that calls a code that does a simple `wp_remote_request()` towards locally installed WP rest endpoint (`wp/v2`) I get

```bash
 cURL error 60: SSL certificate problem: self signed certificate
```

Also, I've noticed that if I use `wp_rest_url()` the returned value (when running tests) will give me `http`, even though everywhere I have `https` specified.

Any idea what could be the issue?
