### ISSUE TITLE
[SETUP ISSUE] Undefined index: default

### ISSUE THREAD

**Issue by alexmigf** [lucatume/wp-browser#445]
**Environment**
OS: [Linux]
PHP version: [7.4.3]
Installed Codeception version: [4.1.7]
Installed wp-browser version: [2.6.10]
WordPress version: [5.6-alpha-48969]
Local development environment: [Valet]
WordPress structure and management: [default]

**Did you use the `codecept init wpbrowser` command?**
Yes

**Did you take a look at Codeception and wp-browser documentation?**
Yes

**Codeception configuration file**

```yaml
paths:
    tests: tests
    output: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
actor_suffix: Tester
extensions:
    enabled:
        - Codeception\Extension\RunFailed
    commands:
        - Codeception\Command\GenerateWPUnit
        - Codeception\Command\GenerateWPRestApi
        - Codeception\Command\GenerateWPRestController
        - Codeception\Command\GenerateWPRestPostTypeController
        - Codeception\Command\GenerateWPAjax
        - Codeception\Command\GenerateWPCanonical
        - Codeception\Command\GenerateWPXMLRPC
params:
    - .env.testing
```

**Suite configuration file**

```yaml
actor: AcceptanceTester
modules:
    enabled:
        - WPDb
        - WPBrowser
        - \Helper\Acceptance
    config:
        WPDb:
            dsn: '%TEST_SITE_DB_DSN%'
            user: '%TEST_SITE_DB_USER%'
            password: '%TEST_SITE_DB_PASSWORD%'
            dump: 'tests/_data/dump.sql'
            #import the dump before the tests; this means the test site database will be repopulated before the tests.
            populate: true
            # re-import the dump between tests; this means the test site database will be repopulated between the tests.
            cleanup: true
            waitlock: 10
            url: '%TEST_SITE_WP_URL%'
            urlReplacement: true #replace the hardcoded dump URL with the one above
            tablePrefix: '%TEST_SITE_TABLE_PREFIX%'
        WPBrowser:
            url: '%TEST_SITE_WP_URL%'
            adminUsername: '%TEST_SITE_ADMIN_USERNAME%'
            adminPassword: '%TEST_SITE_ADMIN_PASSWORD%'
            adminPath: '%TEST_SITE_WP_ADMIN_PATH%'
            headers:
                X_TEST_REQUEST: 1
                X_WPBROWSER_REQUEST: 1
```

**Describe the issue you're encountering**
When i run `./vendor/bin/codecept run` it shows this error: `In ErrorHandler.php line 83: Undefined index: default `

**Screenshots**
<img src="https://i.ibb.co/HX1vKKz/Captura-de-ecr-de-2020-09-11-12-35-16.png" alt="Captura-de-ecr-de-2020-09-11-12-35-16" border="0">

**Comment by lucatume** [comment]
Hi @alexmigf, thanks for taking the time to report the issue and fill in the questions.

That error tells me something is off with the database configuration.
I will reproduce your testing environment locally and try to see what comes out of it.

In the meanwhile: is the `tests/_data/dump.sql` file present? Is it a valid SQL file?

**Comment by alexmigf** [comment]
Hi @lucatume , yes, is present and it's a valid SQL file.

**Comment by lucatume** [comment]
@alexmigf what's the output of the same command with the `--debug` flag? That shoul provide the trace, would you be able to paste it here?

**Comment by alexmigf** [comment]
@lucatume here it is https://pastebin.com/raw/xCyav5dB

**Comment by lucatume** [comment]
@alexmigf thanks for providing the trace, I'm doing a bit of maintenance work on wp-browser and have not been able to reply immediately.

I will look into this and let you know what comes of it.

**Comment by lucatume** [comment]
@alexmigf the pastebin link has expired, could you re-test w/ the latest version of wp-browser (released yesterday) and let me know if something changed.

If not, could you paste the trace here?

**Comment by dingo-d** [comment]
Hi! I seem to be having the same issue as the above. My error is

>   Undefined index: default at vendor/lucatume/wp-browser/src/Codeception/Module/WPDb.php:4175

```bash
 @php ./vendor/bin/codecept run Acceptance '--debug'
Codeception PHP Testing Framework v4.1.21
Powered by PHPUnit 9.5.5 by Sebastian Bergmann and contributors.

  [Connecting To Db] {"config":{"tablePrefix":"inf_","populate":true,"cleanup":true,"reconnect":false,"dump":"tests/_data/dump.sql","populator":null,"urlReplacement":true,"originalUrl":null,"waitlock":30,"dsn":"mysql:host=localhost;dbname=tests","user":"root","password":"","url":"http://infinum.test"},"options":[]}
  [Db] Connected to default tests
  Rebuilding AcceptanceTester...

In ErrorHandler.php line 84:

  [PHPUnit\Framework\Exception (8)]
  Undefined index: default at vendor/lucatume/wp-browser/src/Codeception/Module/WPDb.php:4175


Exception trace:
  at /home/dzoljom/Sites/Infinum/infinum/wp-content/themes/redesign/vendor/codeception/codeception/src/Codeception/Subscriber/ErrorHandler.php:84
 Codeception\Subscriber\ErrorHandler->errorHandler() at /home/dzoljom/Sites/Infinum/infinum/wp-content/themes/redesign/vendor/lucatume/wp-browser/src/Codeception/Module/WPDb.php:4175
 Codeception\Module\WPDb->loadDumpUsingDriver() at /home/dzoljom/Sites/Infinum/infinum/wp-content/themes/redesign/vendor/codeception/module-db/src/Codeception/Module/Db.php:703
 Codeception\Module\Db->_loadDump() at /home/dzoljom/Sites/Infinum/infinum/wp-content/themes/redesign/vendor/lucatume/wp-browser/src/Codeception/Module/WPDb.php:4191
 Codeception\Module\WPDb->_loadDump() at /home/dzoljom/Sites/Infinum/infinum/wp-content/themes/redesign/vendor/codeception/module-db/src/Codeception/Module/Db.php:318
 Codeception\Module\Db->populateDatabases() at /home/dzoljom/Sites/Infinum/infinum/wp-content/themes/redesign/vendor/codeception/module-db/src/Codeception/Module/Db.php:470
 Codeception\Module\Db->_beforeSuite() at /home/dzoljom/Sites/Infinum/infinum/wp-content/themes/redesign/vendor/lucatume/wp-browser/src/Codeception/Module/WPDb.php:4262
 Codeception\Module\WPDb->_beforeSuite() at /home/dzoljom/Sites/Infinum/infinum/wp-content/themes/redesign/vendor/codeception/codeception/src/Codeception/Subscriber/Module.php:38
 Codeception\Subscriber\Module->beforeSuite() at /home/dzoljom/Sites/Infinum/infinum/wp-content/themes/redesign/vendor/symfony/event-dispatcher/EventDispatcher.php:230
 Symfony\Component\EventDispatcher\EventDispatcher->callListeners() at /home/dzoljom/Sites/Infinum/infinum/wp-content/themes/redesign/vendor/symfony/event-dispatcher/EventDispatcher.php:59
 Symfony\Component\EventDispatcher\EventDispatcher->dispatch() at /home/dzoljom/Sites/Infinum/infinum/wp-content/themes/redesign/vendor/codeception/codeception/src/Codeception/Event/DispatcherWrapper.php:22
 Codeception\SuiteManager->dispatch() at /home/dzoljom/Sites/Infinum/infinum/wp-content/themes/redesign/vendor/codeception/codeception/src/Codeception/SuiteManager.php:159
 Codeception\SuiteManager->run() at /home/dzoljom/Sites/Infinum/infinum/wp-content/themes/redesign/vendor/codeception/codeception/src/Codeception/Codecept.php:208
 Codeception\Codecept->runSuite() at /home/dzoljom/Sites/Infinum/infinum/wp-content/themes/redesign/vendor/codeception/codeception/src/Codeception/Codecept.php:162
 Codeception\Codecept->run() at /home/dzoljom/Sites/Infinum/infinum/wp-content/themes/redesign/vendor/codeception/codeception/src/Codeception/Command/Run.php:532
 Codeception\Command\Run->runSuites() at /home/dzoljom/Sites/Infinum/infinum/wp-content/themes/redesign/vendor/codeception/codeception/src/Codeception/Command/Run.php:407
 Codeception\Command\Run->execute() at /home/dzoljom/Sites/Infinum/infinum/wp-content/themes/redesign/vendor/symfony/console/Command/Command.php:288
 Symfony\Component\Console\Command\Command->run() at /home/dzoljom/Sites/Infinum/infinum/wp-content/themes/redesign/vendor/symfony/console/Application.php:974
 Symfony\Component\Console\Application->doRunCommand() at /home/dzoljom/Sites/Infinum/infinum/wp-content/themes/redesign/vendor/symfony/console/Application.php:291
 Symfony\Component\Console\Application->doRun() at /home/dzoljom/Sites/Infinum/infinum/wp-content/themes/redesign/vendor/symfony/console/Application.php:167
 Symfony\Component\Console\Application->run() at /home/dzoljom/Sites/Infinum/infinum/wp-content/themes/redesign/vendor/codeception/codeception/src/Codeception/Application.php:117
 Codeception\Application->run() at /home/dzoljom/Sites/Infinum/infinum/wp-content/themes/redesign/vendor/codeception/codeception/app.php:46
 {closure}() at /home/dzoljom/Sites/Infinum/infinum/wp-content/themes/redesign/vendor/codeception/codeception/app.php:47
 require() at /home/dzoljom/Sites/Infinum/infinum/wp-content/themes/redesign/vendor/codeception/codeception/codecept:7

run [-o|--override OVERRIDE] [-e|--ext EXT] [--report] [--html [HTML]] [--xml [XML]] [--phpunit-xml [PHPUNIT-XML]] [--tap [TAP]] [--json [JSON]] [--colors] [--no-colors] [--silent] [--steps] [-d|--debug] [--bootstrap [BOOTSTRAP]] [--no-redirect] [--coverage [COVERAGE]] [--coverage-html [COVERAGE-HTML]] [--coverage-xml [COVERAGE-XML]] [--coverage-text [COVERAGE-TEXT]] [--coverage-crap4j [COVERAGE-CRAP4J]] [--coverage-cobertura [COVERAGE-COBERTURA]] [--coverage-phpunit [COVERAGE-PHPUNIT]] [--no-exit] [-g|--group GROUP] [-s|--skip SKIP] [-x|--skip-group SKIP-GROUP] [--env ENV] [-f|--fail-fast] [--no-rebuild] [--seed SEED] [--no-artifacts] [--] [<suite> [<test>]]


COMMAND DID NOT FINISH PROPERLY.
  [Db] Disconnected from default
  [Db] Disconnected from default
Script @php ./vendor/bin/codecept run Acceptance handling the test:acceptance event returned with error code 8
```

My `Acceptance.suite.yml` file looks like this:

```yaml
# Codeception Test Suite Configuration
#
# Suite for acceptance tests.
# Perform tests in browser using the WPWebDriver or WPBrowser.
# Use WPDb to set up your initial database fixture.
# If you need both WPWebDriver and WPBrowser tests - create a separate suite.

actor: AcceptanceTester
modules:
    enabled:
        - \Helper\Acceptance
        - WPDb
        - WPWebDriver
    config:
        WPDb:
            dsn: '%TEST_SITE_DB_DSN%'
            user: '%TEST_SITE_DB_USER%'
            password: '%TEST_SITE_DB_PASSWORD%'
            dump: 'tests/_data/dump.sql'
            #import the dump before the tests; this means the test site database will be repopulated before the tests.
            populate: true
            # re-import the dump between tests; this means the test site database will be repopulated between the tests.
            cleanup: true
            waitlock: 30
            url: '%TEST_SITE_WP_URL%'
            urlReplacement: true #replace the hardcoded dump URL with the one above
            tablePrefix: '%TEST_SITE_TABLE_PREFIX%'
        WPWebDriver:
            originalUrl: '%TEST_SITE_WP_URL%'
            url: '%TEST_SITE_WP_URL%'
            adminUsername: '%TEST_SITE_ADMIN_USERNAME%'
            adminPassword: '%TEST_SITE_ADMIN_PASSWORD%'
            adminPath: '%TEST_SITE_WP_ADMIN_PATH%'
            browser: chrome
            host: localhost
            port: 4000
            window_size: false #disabled for Chrome driver
            wait: 5
            headers:
                X_TEST_REQUEST: 1
                X_WPBROWSER_REQUEST: 1
            capabilities:
                # Used in more recent releases of Selenium.
                "goog:chromeOptions":
                    args: ["--no-sandbox", "--disable-gpu", "--headless", "--user-agent=wp-browser", "allow-insecure-localhost", "--ignore-certificate-errors", "--window-size=960,540"]
                # Support the old format for back-compatibility purposes.
                "chromeOptions":
                    args: ["--no-sandbox", "--disable-gpu", "--headless", "--user-agent=wp-browser", "allow-insecure-localhost", "--ignore-certificate-errors", "--window-size=960,540"]
```

The .env.testing looks like

```
# Where the WordPress is located
WP_ROOT_FOLDER=/home/dzoljom/Sites/Infinum/infinum

# Acceptance and functional tests
TEST_SITE_DB_DSN=mysql:host=localhost;dbname=tests
TEST_SITE_DB_HOST=localhost
TEST_SITE_DB_NAME=tests
TEST_SITE_DB_USER=root
TEST_SITE_DB_PASSWORD=
TEST_SITE_TABLE_PREFIX=inf_
TEST_SITE_ADMIN_USERNAME=admin
TEST_SITE_ADMIN_PASSWORD=password
TEST_SITE_WP_ADMIN_PATH=/wp-admin
TEST_SITE_WP_URL=http://infinum.test
TEST_SITE_WP_DOMAIN=infinum.test
TEST_SITE_ADMIN_EMAIL=admin@infinum.test

# Integration tests
TEST_DB_NAME=tests
TEST_DB_HOST=localhost
TEST_DB_USER=root
TEST_DB_PASSWORD=

TEST_TABLE_PREFIX=wp_

TEST=true
```

I'm testing this inside WSL2 on Windows 10 so it's running on Ubuntu 20.04 with PHP 7.4.3 (with valet for wsl)

Any idea what am I doing wrong?
