### ISSUE TITLE
[SETUP ISSUE] Setting up acceptance tests using travis, selenium stand alone server and chrome

### ISSUE THREAD

**Issue by cristeacosmin** [lucatume/wp-browser#458]
**Environment**
OS: Linux
PHP version: 7.3
Installed Codeception version: 4.1.7
Installed wp-browser version: 2.6
WordPress version: 5.5.1
Local development environment: Travis
WordPress structure and management: default

**Did you use the `codecept init wpbrowser` command?**
Yes

**Did you take a look at Codeception and wp-browser documentation?**
Yes

**Codeception configuration file**
If you were able to complete the setup then paste, in a fenced YAML block, the content of your Codeception configuration file; remove any sensitive data!

```yaml
paths:
  tests: tests
  output: tests/_output
  data: tests/_data
  support: tests/_support
  envs: tests/_envs
actor_suffix: Tester
extensions:
  enabled:
    - Codeception\Extension\RunFailed
    # - Codeception\Extension\Recorder
  config:
    # Codeception\Extension\Recorder:
    #   delete_successful: false
    #   module: WPWebDriver
  commands:
    - Codeception\Command\GenerateWPUnit
    - Codeception\Command\GenerateWPRestApi
    - Codeception\Command\GenerateWPRestController
    - Codeception\Command\GenerateWPRestPostTypeController
    - Codeception\Command\GenerateWPAjax
    - Codeception\Command\GenerateWPCanonical
    - Codeception\Command\GenerateWPXMLRPC
params:
  - .env.testing
```

**Suite configuration file**
If you're encountering an issue with a specific suite, please provide its configuration file.

```yaml
# Codeception Test Suite Configuration
#
# Suite for acceptance tests.
# Perform tests in browser using the WPWebDriver or WPBrowser.
# Use WPDb to set up your initial database fixture.
# If you need both WPWebDriver and WPBrowser tests - create a separate suite.

actor: AcceptanceTester
modules:
  enabled:
    - WPDb
    - WPWebDriver
    - \Helper\Acceptance
  config:
    WPDb:
      dsn: "mysql:host=%DB_HOST%;dbname=%DB_NAME%"
      user: "%DB_USER%"
      password: "%DB_PASSWORD%"
      dump: "tests/_data/dump.sql"
      populate: true
      cleanup: false
      waitlock: 10
      url: "%WP_URL%"
      urlReplacement: true 
      tablePrefix: "wp_"
    WPWebDriver:
      url: "%WP_URL%"
      adminUsername: "%WP_ADMIN%"
      adminPassword: "%WP_PASSWORD%"
      adminPath: "/wp-admin"
      browser: chrome
      host: localhost
      port: 4444
      window_size: "1920x1080"
      capabilities:
        chromeOptions:
          args:
            [
              "--headless",
              "--disable-gpu",
              "--no-sandbox"
            ]
```

**Describe the issue you're encountering**
I wrote a basic acceptance test for a plugin (locally) using selenium stand alone server & chrome driver, but I cant make it work on travis

**Output**
This is the error that I get:
[Facebook\WebDriver\Exception\UnknownErrorException] unknown error: net::ERR_CONNECTION_REFUSED

**Screenshots**
![image](https://user-images.githubusercontent.com/10389279/94021391-a14bcd80-fdbc-11ea-8e96-bb5f0b856f88.png)

**Additional context**
This is the travis file:
```yaml
language: php

dist: xenial

os: linux

notifications:
  email: false

php:
  - "7.3"

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
    - env: WP_VERSION=nightly

services:
  - mysql
  - xvfb

cache:
  apt: true
  directories:
    - vendor
    - $HOME/.composer/cache/files

addons:
  chrome: stable
  apt:
    update: true
    sources:
      - google-chrome
    packages:
      - dpkg
      - google-chrome-stable
  hosts:
    - wp.dev
env:
  global:
    - WP_FOLDER="/tmp/wordpress"
    - WP_URL="http://wp.dev"
    - WP_DOMAIN="wp.dev"
    - DB_NAME="test"
    - WP_TABLE_PREFIX="wp_"
    - WP_ADMIN_USERNAME="admin"
    - WP_ADMIN_PASSWORD="admin"
  matrix:
    - WP_VERSION=latest

before_install:
  - sudo add-apt-repository -y ppa:ondrej/php
  - sudo apt-get update
  - sudo apt-get -y install php7.3-fpm php7.3-mysql libjpeg-dev libpng12-dev nginx chromium-chromedriver
  - mysql -e "create database IF NOT EXISTS $DB_NAME;" -uroot
  - mkdir -p $WP_FOLDER
  - mkdir tools
  - wget https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar -P $(pwd)/tools/
  - chmod +x tools/wp-cli.phar && mv tools/wp-cli.phar tools/wp
  - export PATH=$PATH:$(pwd)/tools
  - export PATH=vendor/bin:$PATH

install:
  - composer install --prefer-dist
  - cd $WP_FOLDER
  - wp core download --version=$WP_VERSION
  - wp config create --dbname="$DB_NAME" --dbuser="root" --dbpass="" --dbhost="127.0.0.1" --dbprefix="$WP_TABLE_PREFIX"
  - wp core install --url="$WP_URL" --title="WP DEV" --admin_user="$WP_ADMIN_USERNAME" --admin_password="$WP_ADMIN_PASSWORD" --admin_email="admin@$WP_DOMAIN" --skip-email
  - wp rewrite structure '/%postname%/' --hard
  - wp core update-db
  - wp db export $TRAVIS_BUILD_DIR/tests/_data/dump.sql
  - cd $TRAVIS_BUILD_DIR
  - sudo cp build/travis-nginx-conf /etc/nginx/sites-available/$WP_DOMAIN
  - sudo sed -e "s?%WP_FOLDER%?$WP_FOLDER?g" --in-place /etc/nginx/sites-available/$WP_DOMAIN
  - sudo sed -e "s?%WP_DOMAIN%?$WP_DOMAIN?g" --in-place /etc/nginx/sites-available/$WP_DOMAIN
  - sudo ln -s /etc/nginx/sites-available/$WP_DOMAIN /etc/nginx/sites-enabled/

before_script:
  - sudo service php7.3-fpm restart
  - sudo service nginx restart
  - ln -s $TRAVIS_BUILD_DIR $WP_FOLDER/wp-content/plugins
  - codecept build
  - sleep 2
  - export DISPLAY=99:0
  - sleep 2
  - java -jar bin/selenium-server-standalone-3.141.59.jar >/dev/null 2>&1 &
  - sleep 2

script:
  - codecept run acceptance -vvv

```
PS: wpunit tests are working without any problems - but I cant get these ones to work out.. any insight would be helpful :)
