### ISSUE TITLE
[SETUP ISSUE] vlucas/phpdotenv interfering with .env.testing variables

### ISSUE THREAD

**Issue by twelch555** [lucatume/wp-browser#466]
**Environment**
OS: Mac Catalina
PHP version: 7.4
Installed Codeception version: 4.1.8
Installed wp-browser version: 2.6.14
WordPress version: 5.51
Local development environment: self-installed AMP stack
WordPress structure and management: default

**Did you use the `codecept init wpbrowser` command?** Yes
The bootstrap command is the recommended way to scaffold tests.

**Did you take a look at Codeception and wp-browser documentation?** Yes
Codeception documentation can be found [here](https://codeception.com/docs/01-Introduction), wp-browser documentation can be found [here](https://wpbrowser.wptestkit.dev/).

**Codeception configuration file**
If you were able to complete the setup then paste, in a fenced YAML block, the content of your Codeception configuration file; remove any sensitive data!

```yaml
paths:
    tests: tests
    output: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
actor_suffix: Tester
extensions:
    enabled:
        - Codeception\Extension\RunFailed
    commands:
        - Codeception\Command\GenerateWPUnit
        - Codeception\Command\GenerateWPRestApi
        - Codeception\Command\GenerateWPRestController
        - Codeception\Command\GenerateWPRestPostTypeController
        - Codeception\Command\GenerateWPAjax
        - Codeception\Command\GenerateWPCanonical
        - Codeception\Command\GenerateWPXMLRPC
params:
    - .env.testing
```

**Suite configuration file**

**Describe the issue you're encountering**
With a vanilla install following the set of questions and the suggested package vlucas/phpdotenv installed [but admittedly not configured in anyway] environment variables were not being passed from the .env.testing file to the 4 suite config files. Errors resulted as the %*% were attempted to be process literally.

Removal of the vlucas/phpdotenv restored proper and expected functionality.

**Additional context**
I am new to Codeception/WP Browser and was aiming for a vanilla out-of-the-box experience. As a recommendation, it would be useful for new users to provide some indication of when the list of suggested packages (in the composer install output) might be useful and what extra work might be needed in integrating them.

Unless of course, things should have worked out of the box with the vlucas/phpdotenv package installed. Then there's an issue.

And a huge thanks, WP Browser is highly valuable and useful set of tools.
