### ISSUE TITLE
[BUG] [Error] Call to undefined function Codeception\TestCase\_cleanup_query_vars()  

### ISSUE THREAD

**Issue by jchristopher** [lucatume/wp-browser#470]
**Environment**
OS: Mac  
PHP version: 7.4  
Installed Codeception version: 4.1.11
Installed wp-browser version: 2.6.16
WordPress version: 5.5.3
Local development environment: Lando
WordPress structure and management: Default

**Can you perform the test manually?**
N/A

**Codeception configuration file**  

```yaml
# Codeception Test Suite Configuration
#
# Suite for unit or integration tests that require WordPress functions and classes.

actor: WpunitTester
modules:
    enabled:
        - WPDb
        - WPLoader
        - \Helper\Wpunit
    config:
        WPDb:
            dsn: "mysql:host=%TEST_DB_HOST%;dbname=%TEST_DB_NAME%"
            user: "%TEST_DB_USER%"
            password: "%TEST_DB_PASSWORD%"
            dump: 'tests/_data/dump.sql'
            populate: true
            cleanup: true
            waitlock: 1
            url: "%TEST_SITE_WP_URL%"
            urlReplacement: true
            tablePrefix: "%TEST_TABLE_PREFIX%"
        WPLoader:
            loadOnly: true
            wpRootFolder: "%WP_ROOT_FOLDER%"
            dbName: "%TEST_DB_NAME%"
            dbHost: "%TEST_DB_HOST%"
            dbUser: "%TEST_DB_USER%"
            dbPassword: "%TEST_DB_PASSWORD%"
            wpDebug: true
            tablePrefix: "%TEST_TABLE_PREFIX%"
            domain: "%TEST_SITE_WP_DOMAIN%"
            adminEmail: "%TEST_SITE_ADMIN_EMAIL%"
            title: "SearchWP Test"
            plugins: ['classic-editor/classic-editor.php', 'myplugin/myplugin.php']
            activatePlugins: ['classic-editor/classic-editor.php', 'myplugin/myplugin.php']
```

**Describe the bug**
I'm quite new to wp-browser and _really_ enjoy it so far. I'm in the process of migrating some WordPress unit tests (as per the WordPress developer handbook) and everything has worked great so far, aside from this one test:

```php
namespace MyProject;

class UrlTest extends \Codeception\TestCase\WPTestCase {

	public function test_load_url() {
		$this->go_to( site_url( '?s=test' ) );
		$results = $GLOBALS['wp_query']->posts;

		$this->assertArrayHasKey( 'mykey', $GLOBALS['wp_query']->query_vars );
	}
}
```

**Output**
```
www-data:/app$ codecept run wpunit
Codeception PHP Testing Framework v4.1.11
Powered by PHPUnit 9.4.3 by Sebastian Bergmann and contributors.
Running with seed: 


Wpunit Tests (1) ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
E UrlTest: Test_load_url (0.05s)
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


Time: 00:01.785, Memory: 38.50 MB

There was 1 error:

---------
1) UrlTest: Test_load_url
 Test  tests/wpunit/MyProject/UrlTest.php:test_load_url
                                                                                 
  [Error] Call to undefined function Codeception\TestCase\_cleanup_query_vars()  
                                                                                 

ERRORS!
Tests: 1, Assertions: 0, Errors: 1.
```

**Expected behavior**
The test to run.

**Additional context**
For the time being I have commented out the call to the method here:

https://github.com/lucatume/wp-browser/blob/2.6.16/src/Codeception/TestCase/WPTestCase.php#L701

`$this->go_to( site_url( '?s=test' ) );` in my test is what's triggering the Error.

Chances are _very_ good I'm doing something wrong somewhere, but I'm curious why `utils.php` (which defines `_cleanup_query_vars()`) isn't being loaded. Perhaps something I need to change about my setup?

I'm wondering if it's because I'm using both `WPDb` and `WPLoader` (with `loadOnly: true`) that's preventing `utils.php` from being loaded, but I was having database issues running other tests (my plugin uses custom database tables that didn't exist unless I used both `WPDb` and `WPLoader` as outlined above) but maybe that's where I went wrong?

Thank you again for wp-browser, this is awesome! If I've messed up this Issue and need to change/refine/provide details please let me know.
