### ISSUE TITLE
[BUG] Call to undefined method testClass::getAnnotations()

### ISSUE THREAD

**Issue by dingo-d** [lucatume/wp-browser#484]
**Environment**
OS: MacOS 11.1
PHP version: 7.4.13
Installed Codeception version: 4.1.15
Installed wp-browser version: 2.6.17
WordPress version: 5.6  
Local development environment: Laravel Valet
WordPress structure and management: default

**Can you perform the test manually?**
The feature I'm testing works when running from browser.

**Codeception configuration file**  

```yaml
paths:
    tests: tests
    output: tests/_output
    data: tests/_data
    support: tests/Support
    envs: tests/Envs
actor_suffix: Tester
extensions:
    enabled:
        - Codeception\Extension\RunFailed
    commands:
        - Codeception\Command\GenerateWPUnit
        - Codeception\Command\GenerateWPRestApi
        - Codeception\Command\GenerateWPRestController
        - Codeception\Command\GenerateWPRestPostTypeController
        - Codeception\Command\GenerateWPAjax
        - Codeception\Command\GenerateWPCanonical
        - Codeception\Command\GenerateWPXMLRPC
params:
    - .env.testing
namespace: Tests
coverage:
    enabled: true
    include:
        - src/*
    exclude:
        - src/Core/CompiledContainer.php
    low_limit: 30
    high_limit: 75
settings:
    colors: true
    memory_limit: 1024M
```

**Suite configuration file**
Paste, in a fenced YAML block, the content of the suite configuration file; remove any sensitive data!

```yaml
# Codeception Test Suite Configuration
#
# Suite for unit or integration tests that require WordPress functions and classes.

actor: IntegrationTester
modules:
    enabled:
        - WPLoader
        - \Helper\Wpunit
    config:
        WPLoader:
            wpRootFolder: "%WP_ROOT_FOLDER%"
            dbName: "%TEST_DB_NAME%"
            dbHost: "%TEST_DB_HOST%"
            dbUser: "%TEST_DB_USER%"
            dbPassword: "%TEST_DB_PASSWORD%"
            tablePrefix: "%TEST_TABLE_PREFIX%"
            domain: "%TEST_SITE_WP_DOMAIN%"
            adminEmail: "%TEST_SITE_ADMIN_EMAIL%"
            title: "Test"
            theme: a1-careers-page
            plugins: ['advanced-custom-fields-pro/acf.php']
            activatePlugins: ['advanced-custom-fields-pro/acf.php']
```

**Describe the bug**
When running integration tests i get the 

>   [Error] Call to undefined method testClass::getAnnotations()

Pointing to the `parent::setUp()` method.

Test looks like this:

```php
<?php

namespace Tests\Integration\Rest;

use Codeception\TestCase\WPTestCase;

class CandidatesTest extends WPTestCase
{
	private $routeName;
	private $request;
	private $server;

	public function setUp(): void
	{
		parent::setUp();

		global $wp_rest_server;

		$this->server = $wp_rest_server = new \WP_REST_Server;
		do_action('rest_api_init');

		$this->routeName = '/wp-json/a1c/v1/candidate';

		$_SERVER['REQUEST_URI'] = $this->routeName;

		$this->request = new \WP_REST_Request('GET', $this->routeName);
	}

	public function tearDown(): void
	{
		global $wp_rest_server;
		$wp_rest_server = null;

		$_SERVER['REQUEST_URI'] = '';

		parent::tearDown();
	}

	/**
	 * Tests if the route was registered with WordPress
	 */
	public function testRouteRegistered()
	{
		$routes = $this->server->get_routes();
		$this->assertArrayHasKey($this->routeName, $routes);
	}
}
```

**Expected behavior**
Test should pass. Same test, on a different project worked. Maybe something broke in the latest versions of PHPUnit/Codeception?
