### ISSUE TITLE
[SETUP ISSUE] WpUnit tests cant connect to database. Every other suite can. 

### ISSUE THREAD

**Issue by calvinalkan** [lucatume/wp-browser#492]
**Environment**
OS: [Mac]
PHP version: [7.4]
Installed Codeception version: [4.1.18]
Installed wp-browser version: [latest]
WordPress version: [5.6]
Local development environment: [Valet]
WordPress structure and management: [default]

**Did you use the `codecept init wpbrowser` command?**
Yes

**Did you take a look at Codeception and wp-browser documentation?**
Yes

**Codeception configuration file**

```yaml
paths:
    tests: tests
    output: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
actor_suffix: Tester
extensions:
    enabled:
        - Codeception\Extension\RunFailed
    commands:
        - Codeception\Command\GenerateWPUnit
        - Codeception\Command\GenerateWPRestApi
        - Codeception\Command\GenerateWPRestController
        - Codeception\Command\GenerateWPRestPostTypeController
        - Codeception\Command\GenerateWPAjax
        - Codeception\Command\GenerateWPCanonical
        - Codeception\Command\GenerateWPXMLRPC
params:
    - .env.testing

```

**Suite configuration file**
If you're encountering an issue with a specific suite, please provide its configuration file.

```yaml
# Codeception Test Suite Configuration
#
# Suite for unit or integration tests that require WordPress functions and classes.

actor: WpunitTester
modules:
    enabled:
        - WPLoader
        - \Helper\Wpunit
    config:
        WPLoader:
            wpRootFolder: "%WP_ROOT_FOLDER%"
            dbName: "%TEST_DB_NAME%"
            dbHost: "%TEST_DB_HOST%"
            dbUser: "%TEST_DB_USER%"
            dbPassword: "%TEST_DB_PASSWORD%"
            tablePrefix: "%TEST_TABLE_PREFIX%"
            domain: "%TEST_SITE_WP_DOMAIN%"
            adminEmail: "%TEST_SITE_ADMIN_EMAIL%"
            title: "booking"
            plugins: ['snicco-bookings-internal/snicco-bookings.php']
            activatePlugins: ['snicco-bookings-internal/snicco-bookings.php']
```

**Describe the issue you're encountering**

I'm trying to get wpunit tests to work since the last 5 hours but gave up now. Every test suite works besides the wpunit suite. 

```
wp_die called
Message : <h1>Error establishing a database connection</h1>
Title : Database Error

```

**Output**
Running vendor/bin/codecept run integration -vvv returns the following ( integration is the name for wpunit suite )
```

  Running as single site
  Active plugins:
        - snicco-bookings-internal/snicco-bookings.php
  Installing WordPress in isolated process...
  Isolated installation script output: 
  
  Disabling cron
  
  Configuration:
  
  {
      "root": "/Users/calvinalkan/valet/booking/wp-content/plugins/snicco-bookings-internal/",
      "autoload": "/Users/calvinalkan/valet/booking/wp-content/plugins/snicco-bookings-internal/vendor/autoload.php",
      "installationFilters": [],
      "constants": {
          "ABSPATH": "/Users/calvinalkan/valet/booking/",
          "WP_DEBUG": true,
          "WP_TESTS_TABLE_PREFIX": "wp_",
          "DB_NAME": "wp_booking_test",
          "DB_USER": "root",
          "DB_PASSWORD": "",
          "DB_HOST": "localhost",
          "DB_CHARSET": "utf8",
          "DB_COLLATE": "",
          "WP_TESTS_DOMAIN": "booking.test",
          "WP_TESTS_EMAIL": "calvin@snicco.de",
          "WP_TESTS_TITLE": "booking",
          "WP_PHP_BINARY": "php",
          "WPLANG": "",
          "WP_LANG_DIR": "/Users/calvinalkan/valet/booking/wp-content/plugins/snicco-bookings-internal/vendor/lucatume/wp-browser/src/includes/../data/languages",
          "DISABLE_WP_CRON": true
      },
      "tablesHandling": "empty",
      "activePlugins": [
          "snicco-bookings-internal/snicco-bookings.php"
      ]
  }
  
  <!DOCTYPE html>
  <html dir='ltr'>
  <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta name="viewport" content="width=device-width">
                        <title>WordPress &rsaquo; Error</title>
        <style type="text/css">
                html {
                        background: #f1f1f1;
                }
                body {
                        background: #fff;
                        color: #444;
                        font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif;
                        margin: 2em auto;
                        padding: 1em 2em;
                        max-width: 700px;
                        -webkit-box-shadow: 0 1px 3px rgba(0, 0, 0, 0.13);
                        box-shadow: 0 1px 3px rgba(0, 0, 0, 0.13);
                }
                h1 {
                        border-bottom: 1px solid #dadada;
                        clear: both;
                        color: #666;
                        font-size: 24px;
                        margin: 30px 0 0 0;
                        padding: 0;
                        padding-bottom: 7px;
                }
                #error-page {
                        margin-top: 50px;
                }
                #error-page p,
                #error-page .wp-die-message {
                        font-size: 14px;
                        line-height: 1.5;
                        margin: 25px 0 20px;
                }
                #error-page code {
                        font-family: Consolas, Monaco, monospace;
                }
                ul li {
                        margin-bottom: 10px;
                        font-size: 14px ;
                }
                a {
                        color: #0073aa;
                }
                a:hover,
                a:active {
                        color: #006799;
                }
                a:focus {
                        color: #124964;
                        -webkit-box-shadow:
                                0 0 0 1px #5b9dd9,
                                0 0 2px 1px rgba(30, 140, 190, 0.8);
                        box-shadow:
                                0 0 0 1px #5b9dd9,
                                0 0 2px 1px rgba(30, 140, 190, 0.8);
                        outline: none;
                }
                .button {
                        background: #f7f7f7;
                        border: 1px solid #ccc;
                        color: #555;
                        display: inline-block;
                        text-decoration: none;
                        font-size: 13px;
                        line-height: 2;
                        height: 28px;
                        margin: 0;
                        padding: 0 10px 1px;
                        cursor: pointer;
                        -webkit-border-radius: 3px;
                        -webkit-appearance: none;
                        border-radius: 3px;
                        white-space: nowrap;
                        -webkit-box-sizing: border-box;
                        -moz-box-sizing:    border-box;
                        box-sizing:         border-box;
  
                        -webkit-box-shadow: 0 1px 0 #ccc;
                        box-shadow: 0 1px 0 #ccc;
                        vertical-align: top;
                }
  
                .button.button-large {
                        height: 30px;
                        line-height: 2.15384615;
                        padding: 0 12px 2px;
                }
  
                .button:hover,
                .button:focus {
                        background: #fafafa;
                        border-color: #999;
                        color: #23282d;
                }
  
                .button:focus {
                        border-color: #5b9dd9;
                        -webkit-box-shadow: 0 0 3px rgba(0, 115, 170, 0.8);
                        box-shadow: 0 0 3px rgba(0, 115, 170, 0.8);
                        outline: none;
                }
  
                .button:active {
                        background: #eee;
                        border-color: #999;
                        -webkit-box-shadow: inset 0 2px 5px -3px rgba(0, 0, 0, 0.5);
                        box-shadow: inset 0 2px 5px -3px rgba(0, 0, 0, 0.5);
                }
  
                        </style>
  </head>
  <body id="error-page">
        <div class="wp-die-message">One or more database tables are unavailable. The database may need to be <a href="maint/repair.php?referrer=is_blog_installed">repaired</a>.</div></body>
  </html>
        

wp_die called
Message : <h1>Error establishing a database connection</h1>
Title : Database Error

wp_die called
Message : <h1>Error establishing a database connection</h1>
Title : Database Error

wp_die called
Message : <h1>Error establishing a database connection</h1>
Title : Database Error

wp_die called
Message : <h1>Error establishing a database connection</h1>
Title : Database Error

wp_die called
Message : <h1>Error establishing a database connection</h1>
Title : Database Error

wp_die called
Message : <h1>Error establishing a database connection</h1>
Title : Database Error

wp_die called
Message : <h1>Error establishing a database connection</h1>
Title : Database Error

wp_die called
Message : <h1>Error establishing a database connection</h1>
Title : Database Error

wp_die called
Message : <h1>Error establishing a database connection</h1>
Title : Database Error

wp_die called
Message : <h1>Error establishing a database connection</h1>
Title : Database Error

wp_die called
Message : <h1>Error establishing a database connection</h1>
Title : Database Error

wp_die called
Message : <h1>Error establishing a database connection</h1>
Title : Database Error

Warning: Cannot modify header information - headers already sent by (output started at /Users/calvinalkan/valet/booking/wp-content/plugins/snicco-bookings-internal/vendor/lucatume/wp-browser/src/includes/functions.php:130) in /Users/calvinalkan/valet/booking/wp-includes/pluggable.php on line 1296

Warning: Cannot modify header information - headers already sent by (output started at /Users/calvinalkan/valet/booking/wp-content/plugins/snicco-bookings-internal/vendor/lucatume/wp-browser/src/includes/functions.php:130) in /Users/calvinalkan/valet/booking/wp-includes/pluggable.php on line 1299
```

**Additional context**
This is the wperror message. Not sure what to do here. Also I noticed that the scafollding did not generate any bootstrap files in the test suites. Is that expected?
One or more database tables are unavailable. The database may need to be
