### ISSUE TITLE
[SETUP ISSUE] Configuration in CircleCi

### ISSUE THREAD

**Issue by skydev2020** [lucatume/wp-browser#498]
**Environment**
OS: CircleCi
PHP version: 7.2
Installed Codeception version: 4.0
Installed wp-browser version: 3.0
WordPress version: 5.4

**Did you use the `codecept init wpbrowser` command?**
No: Instead I pushed the generated tests/_suite, _support, acceptance ,acceptance.suite.yml and codeception.dist.yml file.

**Did you take a look at Codeception and wp-browser documentation?**
Yes I did

**Codeception configuration file**
If you were able to complete the setup then paste, in a fenced YAML block, the content of your Codeception configuration file; remove any sensitive data!

```yaml
paths:
    tests: tests
    output: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
actor_suffix: Tester
extensions:
    enabled:
        - Codeception\Extension\RunFailed
    commands:
        - Codeception\Command\GenerateWPUnit
        - Codeception\Command\GenerateWPRestApi
        - Codeception\Command\GenerateWPRestController
        - Codeception\Command\GenerateWPRestPostTypeController
        - Codeception\Command\GenerateWPAjax
        - Codeception\Command\GenerateWPCanonical
        - Codeception\Command\GenerateWPXMLRPC
params:
    - .env.testing
```

**Suite configuration file**
If you're encountering an issue with a specific suite, please provide its configuration file.

```yaml
# suite for acceptance tests.
# perform tests in browser using the WebDriver or PhpBrowser.
# If you need both WebDriver and PHPBrowser tests - create a separate suite.

# Codeception Test Suite Configuration
#
# Suite for acceptance tests.
# Perform tests in browser using the WPWebDriver or WPBrowser.
# Use WPDb to set up your initial database fixture.
# If you need both WPWebDriver and WPBrowser tests - create a separate suite.

actor: AcceptanceTester
modules:
    enabled:
        - WPDb
        - WPWebDriver
        - \Helper\Acceptance
    config:
        WPDb:
            dsn: '%TEST_SITE_DB_DSN%'
            user: '%TEST_SITE_DB_USER%'
            password: '%TEST_SITE_DB_PASSWORD%'
            dump: 'tests/_data/test.sql'
            #import the dump before the tests; this means the test site database will be repopulated before the tests.
            populate: false
            # re-import the dump between tests; this means the test site database will be repopulated between the tests.
            cleanup: true
            waitlock: 10
            url: '%TEST_SITE_WP_URL%'            
            urlReplacement: false #replace the hardcoded dump URL with the one above
            tablePrefix: '%TEST_SITE_TABLE_PREFIX%'
        WPBrowser:
            url: '%TEST_SITE_WP_URL%'
            adminUsername: '%TEST_SITE_ADMIN_USERNAME%'
            adminPassword: '%TEST_SITE_ADMIN_PASSWORD%'
            adminPath: '%TEST_SITE_WP_ADMIN_PATH%'            
            headers:
                X_TEST_REQUEST: 1
                X_WPBROWSER_REQUEST: 1
        WPWebDriver:
            url: '%TEST_SITE_WP_URL%'
            adminUsername: '%TEST_SITE_ADMIN_USERNAME%'
            adminPassword: '%TEST_SITE_ADMIN_PASSWORD%'
            adminPath: '%TEST_SITE_WP_ADMIN_PATH%' 
            browser: chrome
            headers:
                X_TEST_REQUEST: 1
                X_WPBROWSER_REQUEST: 1
            host: localhost
            port: 4444 #9515
            window_size: false #disabled for Chrome driver
            capabilities:
                # Used in more recent releases of Selenium.
                "goog:chromeOptions":
                    args: ["--headless", "--no-sandbox", "--disable-gpu", "--user-agent=wp-browser", "allow-insecure-localhost", "--ignore-certificate-errors"]
                # Support the old format for back-compatibility purposes.
                "chromeOptions":
                    args: ["--headless", "--no-sandbox", "--disable-gpu", "--user-agent=wp-browser", "allow-insecure-localhost", "--ignore-certificate-errors"]
```

**Describe the issue you're encountering**
As you see I used '.env.testing' in codeception.dist.yml but .env.testing is in gitignore and can't be put in Git. and this file can't be accessible in circleci.
What I can do I can put environment variable in CircleCI like this.
![image](https://user-images.githubusercontent.com/57546027/116886903-3c165f80-ac5c-11eb-938e-c77bf74ba70c.png)

How can I use these env variables in codeception.dist.yml and acceptance.suite.yml

**Output**
And after I run vendor/bin/codecept run acceptance, I get following message and I think it is because this configuration.
```
In Configuration.php line 164:
                                              
  Configuration file could not be found.      
  Run `bootstrap` to initialize Codeception.  
                                              
```

**To Reproduce**
Steps to reproduce the behavior.

**Screenshots**

**Additional context**

**Comment by lucatume** [comment]
Hi @skydev2020, thanks for taking the time to report the issue and provide details.

I would check these:
1. If your `codeception.dist.yml` configuration file says the tests should look for a `.env.testing` configuration file and that is not committed, then that is probably the issue. You know this better than I do, so take this with a grain of salt: I usually only put non-sensitive data in the `.env.testing` file; nothing that would be in production and setting up all the env vars required by tests in secrets seems a bit cumbersome. I would take a hybrid approach and put what is required to set up tests in the `.env.testing` env file and commit that. What really needs to stay secret, put in the CI secrets.
2. Read [this section](https://codeception.com/docs/06-ModulesAndHelpers#Dynamic-Configuration-With-Parameters) of Codeception documentation; you can specify more than one file and a file and env.

The latter could help you as you could configure parameters like this:

```yaml
params:
  - .env.dist.testing # safe vars only, common to local and CI env
  - env # If something is set in the current env, pick it up to override the configuration
```
  
This way **if** there are secrets, they will override the base configuration

Let me know if this helps you.

**Comment by skydev2020** [comment]
I use normal for acceptance.suite.yml.
Some of the contents are like this.
    user: '%TEST_SITE_DB_USER%'
  But when this is executed in circleci, it gives the error like %TEST_SITE_DB_USER% is not defined.
I tested using both of way, using CircleCI environmental variables in CircleCI website and circleci config.yml environments variable.
 ```
docker:      
      - image: circleci/php:7.2.30
      - image: circleci/mariadb:10.3
    environment:
      - WP_TESTS_DIR: "/tmp/wordpress-tests-lib"
      - WP_CORE_DIR: "/tmp/wordpress/"
      - TEST_SITE_DB_HOST: "127.0.0.1"
```
Do you have any idea why these values are not pulled from config variable?
