### ISSUE TITLE
All pages created with havePageInDatabase lead to 404 errors

### ISSUE THREAD

**Issue by aberkow** [lucatume/wp-browser#499]
This is _probably_ not a bug? It's more likely that I've done something wrong setting up wp-browser, but I can't figure out quite what. I'm using a docker-compose set up with the official WP docker image for the server. Then, I have two mysql db containers. One for testing and the other for development. I added mysql dump file to my project at `/tests/_data/dump.sql`. I also was able to initialize the project for codeception and wp-browser correctly (I believe). Any help you can offer would be great!

**Environment**
OS: Mac
PHP version: 7.4.16
Installed Codeception version: 4.1.20
Installed wp-browser version: 3.0.6
WordPress version: 5.7.1
Local development environment: docker
WordPress structure and management: default except wordpress directory is at `/var/www/html/wordpress`

**Did you use the `codecept init wpbrowser` command?**
Yes

**Did you take a look at Codeception and wp-browser documentation?**
Yes

**Codeception configuration file**
If you were able to complete the setup then paste, in a fenced YAML block, the content of your Codeception configuration file; remove any sensitive data!

```yaml
paths:
    tests: tests
    output: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
actor_suffix: Tester
extensions:
    enabled:
        - Codeception\Extension\RunFailed
    commands:
        - Codeception\Command\GenerateWPUnit
        - Codeception\Command\GenerateWPRestApi
        - Codeception\Command\GenerateWPRestController
        - Codeception\Command\GenerateWPRestPostTypeController
        - Codeception\Command\GenerateWPAjax
        - Codeception\Command\GenerateWPCanonical
        - Codeception\Command\GenerateWPXMLRPC
params:
    - .env.testing
```

**Suite configuration file**
If you're encountering an issue with a specific suite, please provide its configuration file.

```yaml
actor: AcceptanceTester
modules:
    enabled:
        - WPCLI
        - WPDb
        - WPBrowser
        - \Helper\Acceptance
    config:
        WPCLI:
            # the path needs to be from the root of this project
            # _not_ relative to this file
            path: ./www/wordpress
            throw: true
            timeout: 60
            allow-root: true
        WPDb:
            dsn: '%TEST_SITE_DB_DSN%'
            user: '%TEST_SITE_DB_USER%'
            password: '%TEST_SITE_DB_PASSWORD%'
            dump: 'tests/_data/dump.sql'
            #import the dump before the tests; this means the test site database will be repopulated before the tests.
            populate: true
            # re-import the dump between tests; this means the test site database will be repopulated between the tests.
            cleanup: true
            waitlock: 10
            url: '%TEST_SITE_WP_URL%'
            originalUrl: '%TEST_SITE_WP_URL%'
            # urlReplacement: true #replace the hardcoded dump URL with the one above
            tablePrefix: '%TEST_SITE_TABLE_PREFIX%'
        WPBrowser:
            url: '%TEST_SITE_WP_URL%'
            adminUsername: '%TEST_SITE_ADMIN_USERNAME%'
            adminPassword: '%TEST_SITE_ADMIN_PASSWORD%'
            adminPath: '%TEST_SITE_WP_ADMIN_PATH%'
            headers:
                X_TEST_REQUEST: 1
                X_WPBROWSER_REQUEST: 1
```

**Describe the issue you're encountering**
I can create a page to test with `$I->havePageInDatabase` and then assert that's true with `$I->seePageInDatabase`. However, when I try to go to that page with `$I->amOnPage` I always get a 404. I know that I'm using the right db configuration because when I pause the test to inspect and debug, I can see the page both by looking at it in Sequel Pro and with the interactive console.

**Output**
```php
<?php

class WPFirstCest
{
    public function _before(AcceptanceTester $I)
    {
    }

    public function testShortcodeWithNoPictures(AcceptanceTester $I) {
        $noPics = [
            'post_title' => 'No Pictures',
            'post_name' => 'no-pictures',
            'post_content' => '[UC-Today category="arts" pictures="false"]',
            'post_type' => 'page',
            'post_status' => 'publish'
        ];

        $I->amGoingTo('Create pages for the shortcodes');
        $I->havePageInDatabase($noPics);
        $I->seePageInDatabase($noPics);

        $I->amGoingTo('Go to the page with no pictures');
        // this 404s but doesn't throw an error.
        $I->amOnPage('/' . $noPics['post_name']);
        // taking a snapshot just because
        $I->makeHtmlSnapshot('no-pictures');
        $I->pause();
        // here I can see in my local server logs that the page is 404. testing in the interactive console confirms that even though the page is in the db
    }
}

```
