### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by maxchirkov** [lucatume/wp-browser#5]
Codeception is totally new to me, so may be some of these issues are just my settings, but I do need some help to figure them out.

**1. Installation Issue:**

Ran into this weird issue when tried running `composer install` or/and `composer update`:
```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for lucatume/wp-browser master@dev -> satisfiable by lucatume/wp-browser[dev-master].
    - lucatume/wp-browser dev-master requires badcow/lorem-ipsum dev-master -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```

Included the package in question into the composer like so, and the installation went through:
```json
{
  "require": {
    "badcow/lorem-ipsum": "dev-master"
  },
  "require-dev": {
    "lucatume/wp-browser": "master@dev"
  }
}
```

**3. WPDb Config Issue:**

To begin with, I was under impression that I could provide WPDb credentials for existing WP Install and run tests against it. Oh man, was I wrong - it simply wiped out my existing DB without any warnings. Even though it was my dev site where I test plugins, I still had quite a bit of test pages with shortcodes and what not that I need to recreate manually now. Only later I noticed it's mentioned in the instructions for WPLoader that `dbNAme` will drop existing DB.

After the unfortunate experience, I figured that I probably need a blank DB with dedicated user name and a ~/wordpress/ folder with WP package in it. I spent over 2 hours trying to get WPDb config to work and still couldn't do it. 

Here is the config:
```
class_name: AcceptanceTester
modules:
    enabled:
        - WPBrowser
        - AcceptanceHelper
        - WPDb
    config:
        WPBrowser:
            url: 'http://wptests.dev'
            adminUsername: 'admin'
            adminPassword: 'password'
            adminUrl: '/wp-core/wp-admin'
        WPDb:
            dsn: 'mysql:host=localhost;dbname=wptests'
            user: "wptester"
            password: "test"
            dump: 'tests/_data/dump.sql'
            populate: true
            cleanup: true
            url: 'http://wptests.dev'
            tablePrefix: wp_
            checkExistence: true
            update: true   
```
and this is the error that I get:
```
 [Codeception\Exception\Module]                                                                                                           
  (Exception in WPDb) SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) while creating PDO connection 
```
I don't understand why the error references `root`, since I don't use that user name anywhere in the config. I tried changing user to something that doesn't exist, then it references the name in the error correctly, but then there is simply no such user name. If I add that custom user to mysql db - it goes back to referencing root in the error.

**3. WPLoader**
It is spelled `dbNAme` in the instructions, which I copied and pasted into my yml file. This was throwing the following error:
```
[Codeception\Exception\ModuleConfig]                                              
  WPLoader module is not configured!                                                
  Options: wpRootFolder, dbName, dbHost, dbUser, dbPassword are required            
                  Please, update the configuration and set all the required fields 
```
Renaming the property to `dbName` fixed the error, but there is no any activity/reporting when running `codecept run`. All I get is:
```
Codeception PHP Testing Framework v2.0.9
Powered by PHPUnit 4.4.1 by Sebastian Bergmann.
``` 
and nothing else. The DB stays empty.

Here is my WP Loader:
```
WPLoader:
            wpRootFolder: '/Users/username/Sites/wptests.dev'
            dbName: 'wptests'
            dbHost: 'localhost'
            dbUser: 'wptester'
            dbPassword: 'test'
            wpDebug: true
            dbCharset: 'utf8'
            dbCollate: ''
            tablePrefix: 'wp_'
            domain: 'wptests.dev'
            adminEmail: 'admin@example.com'
            title: 'Test Blog'
            phpBinary: 'php'
            language: ''
```

I ran configs one by one and all together. Always same results.

It would be nice to be able to take a look at a working example, otherwise I'm not sure if this package is stable or I'm simply misconfiguring it.

I would appreciate any pointers you could give me as far as getting this baby going.

Thanks!
