### ISSUE TITLE
Acceptance tests wont run - timeout

### ISSUE THREAD

**Issue by robruiz** [lucatume/wp-browser#501]
**Environment**
OS: Windows 10
PHP version: 7.4
Installed Codeception version: 4.1.20
Installed wp-browser version: latest
WordPress version: 5.7.1
Local development environment: Local (by Flywheel) version 5.10.3
WordPress structure and management: default

**Can you perform the test manually?**
Yes

**Codeception configuration file**  
`
actor: AcceptanceTester

extensions:
  enabled:
    - Codeception\Extension\RunProcess:
        0: chromedriver --url-base=/wd/hub --whitelisted-ips=
        1: npm run end2end
        sleep: 3

modules:
  enabled:
    - WPBrowser
    - WPDb
    - WPFilesystem
  config:
    WPBrowser:
      url: http://localhost:10022
      adminUsername: admin
      adminPassword: password
      adminPath: '/wp-admin'
      headers:
        X_WPBROWSER_REQUEST: 1
        X_TEST_REQUEST: 1
        X_APM_REQUEST: 1
    WPDb:
      dsn: mysql:host=localhost:10024;dbname=local
      user: root
      password: root
      dump: 'tests/_data/dump.sql'
      populate: true
      cleanup: true
      waitlock: 10
      url: http://localhost:10022/
      urlReplacement: true #replace the hardcoded dump URL with the one above
      tablePrefix: wp_
    WPFilesystem:
      wpRootFolder: [ the root folder path ]
      themes: '/wp-content/themes'
      plugins: '/wp-content/plugins'
      mu-plugins: '/wp-content/mu-plugins'
      uploads: '/wp-content/uploads'

```yaml
actor: Tester
paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    helpers: tests/_support
settings:
    bootstrap: _bootstrap.php
    colors: true
    memory_limit: 1024M
params:
    - .env.testing
`


**Suite configuration file**
Paste, in a fenced YAML block, the content of the suite configuration file; remove any sensitive data!

```yaml
# Codeception Test Suite Configuration

# suite for acceptance tests.
# perform tests in browser using the WebDriver or PhpBrowser.
# If you need both WebDriver and PHPBrowser tests - create a separate suite.

class_name: AcceptanceTester
modules:
    enabled:
        - WPBrowser
        - WPDb
        - AcceptanceHelper
        - WPFilesystem
    config:
        WPBrowser:
            url: '%WP_URL%'
            adminUsername: 'admin'
            adminPassword: 'admin'
            adminPath: '/wp-admin'
        WPDb:
            dsn: 'mysql:host=%DB_HOST%;dbname=%DB_NAME%'
            user: %DB_USER%
            password: %DB_PASSWORD%
            dump: 'tests/_data/dump.sql'
            populate: true
            cleanup: true
            reconnect: false
            url: '%WP_URL%'
            tablePrefix: 'wp_'
        WPFilesystem:
            wpRootFolder: '%WP_ROOT_FOLDER%'
            themes: '/wp-content/themes'
            plugins: '/wp-content/plugins'
            mu-plugins: '/wp-content/mu-plugins'
            uploads: '/wp-content/uploads'
```

**Describe the bug**
It just never completes the process. After 300 seconds it times out

**Output**
[Symfony\Component\Process\Exception\ProcessTimedOutException]                                                                           The process ""vendor/bin/codecept" "run" "acceptance"" exceeded the timeout of 300 seconds.

**To Reproduce**
Install/Configure, then run acceptance of functional tests.

**Expected behavior**
Expecting test to run
