### ISSUE TITLE
Populate: true option doesn't clear/drop the database before test

### ISSUE THREAD

**Issue by skydev2020** [lucatume/wp-browser#502]
**Environment**
OS: Ubuntu
PHP version: 7.2
Installed Codeception version: [e.g. 2.5.0]
Installed wp-browser version: 4.1.20

**Did you use the `codecept init wpbrowser` command?**
Yes

**Did you take a look at Codeception and wp-browser documentation?**
Yes a lot

**Codeception configuration file**

```
paths:
    tests: tests
    output: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
actor_suffix: Tester
extensions:
    enabled:
        - Codeception\Extension\RunFailed
commands:
        - Codeception\Command\GenerateWPUnit
        - Codeception\Command\GenerateWPRestApi
        - Codeception\Command\GenerateWPRestController
        - Codeception\Command\GenerateWPRestPostTypeController
        - Codeception\Command\GenerateWPAjax
        - Codeception\Command\GenerateWPCanonical
        - Codeception\Command\GenerateWPXMLRPC
params:
    - env
```
    
**Suite configuration file**
If you're encountering an issue with a specific suite, please provide its configuration file.

```yaml

class_name: AcceptanceTester
modules:
    enabled:
        - WPBrowser
        - WPDb
        - AcceptanceHelper
        - WPFilesystem
    config:
        WPBrowser:
            url: '%WP_URL%'
            adminUsername: 'admin'
            adminPassword: 'admin'
            adminPath: '/wp-admin'
        WPDb:
            dsn: 'mysql:host=%DB_HOST%;dbname=%DB_NAME%'
            user: %DB_USER%
            password: %DB_PASSWORD%
            dump: 'tests/_data/dump.sql'
            populate: true
            cleanup: true
            reconnect: false
            url: '%WP_URL%'
            tablePrefix: 'wp_'
        WPFilesystem:
            wpRootFolder: '%WP_ROOT_FOLDER%'
            themes: '/wp-content/themes'
            plugins: '/wp-content/plugins'
            mu-plugins: '/wp-content/mu-plugins'
            uploads: '/wp-content/uploads'
```

**Describe the issue you're encountering**
I have db file along with acceptance.suite.yml

`# Codeception Test Suite Configuration

actor: AcceptanceTester
modules:
    enabled:
        - WPDb
        - WPWebDriver
        - \Helper\Acceptance
    config:
        WPDb:
            dsn: '%TEST_SITE_DB_DSN%'
            user: '%TEST_SITE_DB_USER%'
            password: '%TEST_SITE_DB_PASSWORD%'
            dump: '%TEST_SITE_DB_DUMP%'
            # import the dump before the tests; this means the test site database will be repopulated before the tests.
            populate: true
            # re-import the dump between tests; this means the test site database will be repopulated between the tests.
            cleanup: false
            waitlock: 10
            url: '%TEST_SITE_WP_URL%'
            urlReplacement: false # replace the hardcoded dump URL with the one above
            tablePrefix: '%TEST_SITE_TABLE_PREFIX%'
        WPBrowser:
            url: '%TEST_SITE_WP_URL%'
            adminUsername: '%TEST_SITE_ADMIN_USERNAME%'
            adminPassword: '%TEST_SITE_ADMIN_PASSWORD%'
            adminPath: '%TEST_SITE_WP_ADMIN_PATH%'
            headers:
                X_TEST_REQUEST: 1
                X_WPBROWSER_REQUEST: 1
        WPWebDriver:
            url: '%TEST_SITE_WP_URL%'
            adminUsername: '%TEST_SITE_ADMIN_USERNAME%'
            adminPassword: '%TEST_SITE_ADMIN_PASSWORD%'
            adminPath: '%TEST_SITE_WP_ADMIN_PATH%'
            browser: chrome
            headers:
                X_TEST_REQUEST: 1
                X_WPBROWSER_REQUEST: 1
            host: 127.0.0.1
            port: 4444 # 9515
            window_size: false # disabled for Chrome driver
            connection_timeout: 60
            request_timeout: 60
            pageload_timeout: 60
            capabilities:
                # Used in more recent releases of Selenium.
                "goog:chromeOptions":
                    args: ["--no-sandbox", "--disable-gpu", "--user-agent=wp-browser", "allow-insecure-localhost", "--ignore-certificate-errors"]
                # Support the old format for back-compatibility purposes.
                "chromeOptions":
                    args: ["--no-sandbox", "--disable-gpu", "--user-agent=wp-browser", "allow-insecure-localhost", "--ignore-certificate-errors"]`

As you see here I set the populate:true option is enabled which means db would be dropped or cleared before tests

**Output**
It doesn't clear the tables with following message.
And I have to manually drop the database and recreate database to run the test.

```
Codeception PHP Testing Framework v4.1.20
Powered by PHPUnit 9.5.4 by Sebastian Bergmann and contributors.

  [Connecting To Db] {"config":{"tablePrefix":"wp_","populate":true,"cleanup":false,"reconnect":false,"dump":"tests/_data/lasso_test.sql","populator":null,"urlReplacement":false,"originalUrl":null,"waitlock":10,"dsn":"mysql:host=localhost;dbname=wordpress_test;","user":"root","password":"password","url":"http://affiliate.local:8080"},"options":[]}
  [Db] Connected to default wordpress_test

In Db.php line 283:
                                                                               
  [Codeception\Exception\ModuleException]                                      
  Db: SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'wp_comm  
  entmeta' already exists                                                      
  SQL query being executed:                                                    
  CREATE TABLE `wp_commentmeta` (                                              
    `meta_id` bigint(20) UNSIGNED NOT NULL,                                    
    `comment_id` bigint(20) UNSIGNED NOT NULL DEFAULT 0,                       
    `meta_key` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,           
    `meta_value` longtext COLLATE utf8mb4_unicode_ci DEFAULT NULL              
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci           
                                                                               

Exception trace:
  at /media/user/Data/Projects/wordpress/wp-content/plugins/lasso/vendor/codeception/module-db/src/Codeception/Lib/Driver/Db.php:283
 Codeception\Lib\Driver\Db->sqlQuery() at /media/user/Data/Projects/wordpress/wp-content/plugins/lasso/vendor/codeception/module-db/src/Codeception/Lib/Driver/MySql.php:19
 Codeception\Lib\Driver\MySql->sqlQuery() at /media/user/Data/Projects/wordpress/wp-content/plugins/lasso/vendor/codeception/module-db/src/Codeception/Lib/Driver/Db.php:162
 Codeception\Lib\Driver\Db->load() at /media/user/Data/Projects/wordpress/wp-content/plugins/lasso/vendor/codeception/module-db/src/Codeception/Module/Db.php:721
 Codeception\Module\Db->loadDumpUsingDriver() at /media/user/Data/Projects/wordpress/wp-content/plugins/lasso/vendor/lucatume/wp-browser/src/Codeception/Module/WPDb.php:4178
 Codeception\Module\WPDb->loadDumpUsingDriver() at /media/user/Data/Projects/wordpress/wp-content/plugins/lasso/vendor/codeception/module-db/src/Codeception/Module/Db.php:703
 Codeception\Module\Db->_loadDump() at /media/user/Data/Projects/wordpress/wp-content/plugins/lasso/vendor/lucatume/wp-browser/src/Codeception/Module/WPDb.php:4191
 Codeception\Module\WPDb->_loadDump() at /media/user/Data/Projects/wordpress/wp-content/plugins/lasso/vendor/codeception/module-db/src/Codeception/Module/Db.php:318
 Codeception\Module\Db->populateDatabases() at /media/user/Data/Projects/wordpress/wp-content/plugins/lasso/vendor/codeception/module-db/src/Codeception/Module/Db.php:470
 Codeception\Module\Db->_beforeSuite() at /media/user/Data/Projects/wordpress/wp-content/plugins/lasso/vendor/lucatume/wp-browser/src/Codeception/Module/WPDb.php:4262
 Codeception\Module\WPDb->_beforeSuite() at /media/user/Data/Projects/wordpress/wp-content/plugins/lasso/vendor/codeception/codeception/src/Codeception/Subscriber/Module.php:38
 Codeception\Subscriber\Module->beforeSuite() at /media/user/Data/Projects/wordpress/wp-content/plugins/lasso/vendor/symfony/event-dispatcher/EventDispatcher.php:230
 Symfony\Component\EventDispatcher\EventDispatcher->callListeners() at /media/user/Data/Projects/wordpress/wp-content/plugins/lasso/vendor/symfony/event-dispatcher/EventDispatcher.php:59
 Symfony\Component\EventDispatcher\EventDispatcher->dispatch() at /media/user/Data/Projects/wordpress/wp-content/plugins/lasso/vendor/codeception/codeception/src/Codeception/Event/DispatcherWrapper.php:22
 Codeception\SuiteManager->dispatch() at /media/user/Data/Projects/wordpress/wp-content/plugins/lasso/vendor/codeception/codeception/src/Codeception/SuiteManager.php:159
 Codeception\SuiteManager->run() at /media/user/Data/Projects/wordpress/wp-content/plugins/lasso/vendor/codeception/codeception/src/Codeception/Codecept.php:208
 Codeception\Codecept->runSuite() at /media/user/Data/Projects/wordpress/wp-content/plugins/lasso/vendor/codeception/codeception/src/Codeception/Codecept.php:162
 Codeception\Codecept->run() at /media/user/Data/Projects/wordpress/wp-content/plugins/lasso/vendor/codeception/codeception/src/Codeception/Command/Run.php:401
 Codeception\Command\Run->execute() at /media/user/Data/Projects/wordpress/wp-content/plugins/lasso/vendor/symfony/console/Command/Command.php:256
 Symfony\Component\Console\Command\Command->run() at /media/user/Data/Projects/wordpress/wp-content/plugins/lasso/vendor/symfony/console/Application.php:971
 Symfony\Component\Console\Application->doRunCommand() at /media/user/Data/Projects/wordpress/wp-content/plugins/lasso/vendor/symfony/console/Application.php:290
 Symfony\Component\Console\Application->doRun() at /media/user/Data/Projects/wordpress/wp-content/plugins/lasso/vendor/symfony/console/Application.php:166
 Symfony\Component\Console\Application->run() at /media/user/Data/Projects/wordpress/wp-content/plugins/lasso/vendor/codeception/codeception/src/Codeception/Application.php:117
 Codeception\Application->run() at /media/user/Data/Projects/wordpress/wp-content/plugins/lasso/vendor/codeception/codeception/app.php:46
 {closure}() at /media/user/Data/Projects/wordpress/wp-content/plugins/lasso/vendor/codeception/codeception/app.php:47
 require() at /media/user/Data/Projects/wordpress/wp-content/plugins/lasso/vendor/codeception/codeception/codecept:7

run [-o|--override OVERRIDE] [-e|--ext EXT] [--report] [--html [HTML]] [--xml [XML]] [--phpunit-xml [PHPUNIT-XML]] [--tap [TAP]] [--json [JSON]] [--colors] [--no-colors] [--silent] [--steps] [-d|--debug] [--bootstrap [BOOTSTRAP]] [--no-redirect] [--coverage [COVERAGE]] [--coverage-html [COVERAGE-HTML]] [--coverage-xml [COVERAGE-XML]] [--coverage-text [COVERAGE-TEXT]] [--coverage-crap4j [COVERAGE-CRAP4J]] [--coverage-cobertura [COVERAGE-COBERTURA]] [--coverage-phpunit [COVERAGE-PHPUNIT]] [--no-exit] [-g|--group GROUP] [-s|--skip SKIP] [-x|--skip-group SKIP-GROUP] [--env ENV] [-f|--fail-fast] [--no-rebuild] [--seed SEED] [--no-artifacts] [--] [<suite> [<test>]]

```

**To Reproduce**
vendor/bin/codecept -vvv run acceptance _InitializeCest

**Screenshots**
![image](https://user-images.githubusercontent.com/57546027/118813419-af1d0880-b8e1-11eb-9df6-d04043ca5971.png)
![image](https://user-images.githubusercontent.com/57546027/118813518-ccea6d80-b8e1-11eb-8ddf-33fe71772f1a.png)
![image](https://user-images.githubusercontent.com/57546027/118813657-f3100d80-b8e1-11eb-8866-13f33c8ada9c.png)

**Additional context**
