### ISSUE TITLE
Failure at loadSessionSnapShot: [Facebook\WebDriver\Exception\UnknownCommandException] unknown command: unknown command: session/043b61bb0f3edad9ee3af04a305fd21b/cookie/_lr_hb_-mbf2js

### ISSUE THREAD

**Issue by skydev2020** [lucatume/wp-browser#503]
**Environment**
OS: Ubuntu
PHP version: 7.2
Installed Codeception version: 4.1.20
Installed wp-browser version: 3.0

**Can you perform the test manually?**
Yes I am doing a manual testing using this command.
vendor/bin/codecept -vvv run acceptance _InitializeCest

**Codeception configuration file**  
Paste, in a fenced YAML block, the content of your Codeception configuration file; remove any sensitive data!  

```yaml
actor: Tester
paths:
    tests: tests
    output: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
actor_suffix: Tester
extensions:
    enabled:
        - Codeception\Extension\RunFailed
commands:
        - Codeception\Command\GenerateWPUnit
        - Codeception\Command\GenerateWPRestApi
        - Codeception\Command\GenerateWPRestController
        - Codeception\Command\GenerateWPRestPostTypeController
        - Codeception\Command\GenerateWPAjax
        - Codeception\Command\GenerateWPCanonical
        - Codeception\Command\GenerateWPXMLRPC
params:
    - env```


**Suite configuration file**
Paste, in a fenced YAML block, the content of the suite configuration file; remove any sensitive data!

```yaml
# Codeception Test Suite Configuration

# suite for acceptance tests.
# perform tests in browser using the WebDriver or PhpBrowser.
# If you need both WebDriver and PHPBrowser tests - create a separate suite.

actor: AcceptanceTester
modules:
    enabled:
        - WPDb
        - WPWebDriver
        - \Helper\Acceptance
    config:
        WPDb:
            dsn: '%TEST_SITE_DB_DSN%'
            user: '%TEST_SITE_DB_USER%'
            password: '%TEST_SITE_DB_PASSWORD%'
            dump: '%TEST_SITE_DB_DUMP%'
            # import the dump before the tests; this means the test site database will be repopulated before the tests.
            populate: true
            # re-import the dump between tests; this means the test site database will be repopulated between the tests.
            reconnect: true
            cleanup: false
            waitlock: 10
            url: '%TEST_SITE_WP_URL%'
            urlReplacement: false # replace the hardcoded dump URL with the one above
            tablePrefix: '%TEST_SITE_TABLE_PREFIX%'
        WPBrowser:
            url: '%TEST_SITE_WP_URL%'
            adminUsername: '%TEST_SITE_ADMIN_USERNAME%'
            adminPassword: '%TEST_SITE_ADMIN_PASSWORD%'
            adminPath: '%TEST_SITE_WP_ADMIN_PATH%'
            headers:
                X_TEST_REQUEST: 1
                X_WPBROWSER_REQUEST: 1
        WPWebDriver:
            url: '%TEST_SITE_WP_URL%'
            adminUsername: '%TEST_SITE_ADMIN_USERNAME%'
            adminPassword: '%TEST_SITE_ADMIN_PASSWORD%'
            adminPath: '%TEST_SITE_WP_ADMIN_PATH%'
            browser: chrome
            headers:
                X_TEST_REQUEST: 1
                X_WPBROWSER_REQUEST: 1
            host: 127.0.0.1
            port: 4444 # 9515
            window_size: false # disabled for Chrome driver
            connection_timeout: 60
            request_timeout: 60
            pageload_timeout: 60
            capabilities:
                # Used in more recent releases of Selenium.
                "goog:chromeOptions":
                    args: ["--no-sandbox", "--disable-gpu", "--user-agent=wp-browser", "allow-insecure-localhost", "--ignore-certificate-errors"]
                # Support the old format for back-compatibility purposes.
                "chromeOptions":
                    args: ["--no-sandbox", "--disable-gpu", "--user-agent=wp-browser", "allow-insecure-localhost", "--ignore-certificate-errors"]```

**Describe the bug**
I have 2 tests in one file and whenever it rutns 2nd test it fails.
Here is the test code.

```
class _InitializeCest
{
    public function _before(AcceptanceTester $I)
    {
        
    }

    // tests
    public function activatePluginTest(AcceptanceTester $I)
    {
        $I->loginAsAdmin();
        $I->amOnPluginsPage();
        $I->seePluginInstalled('lasso');
        $I->activatePlugin('lasso');        
        $I->seePluginActivated('lasso'); // Check whether activated in wordpress level
        
        $I->amOnPage('/wp-admin/edit.php?post_type=lasso-urls&page=install');
        $I->fillField(['name' => 'license_serial'], getenv('LOCAL_LICENSE_TEST'));
        $I->click('Activate Lasso');
        $I->wait(15);
        $I->see('Choose a Default Display Box Theme');
        $I->click('.choose_display_onboard.cactus');        
        $I->see('Customize Your Displays');
        $I->click('button.btn.step-4');
        $I->see("You're Ready");
        $I->click('Go to Dashboard');
        $I->see("Dashboard");
    }

    public function addNewLink(AcceptanceTester $I)
    {
        $I->amOnPage('/wp-admin/edit.php?post_type=lasso-urls');
        $I->click("header button.btn"); //Add New Link Button
        $I->see('Add A New Link'); // Modal Dialog
        $I->fillField(['id' => 'add-new-url-box'], 'https://codeception.com/');
        $I->wait(10);
        $I->see("Primary Destination URL"); // check open to detail page        
    }
}
```

**Output**
```
Codeception PHP Testing Framework v4.1.20
Powered by PHPUnit 9.5.4 by Sebastian Bergmann and contributors.

  [Connecting To Db] {"config":{"tablePrefix":"wp_","populate":true,"cleanup":false,"reconnect":false,"dump":"tests/_data/lasso_test.sql","populator":null,"urlReplacement":false,"originalUrl":null,"waitlock":10,"dsn":"mysql:host=localhost;dbname=wordpress_test;","user":"root","password":"password","url":"http://affiliate.local:8080"},"options":[]}
  [Db] Connected to default wordpress_test
  Rebuilding AcceptanceTester...
  [Query] INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES (?, ?, ?)
  [Parameters] ["admin_email_lifespan",2533080438,"yes"]
  [Query] INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES (?, ?, ?)
  [Parameters] ["_transient_doing_cron",1621429766,"yes"]

Acceptance Tests (2) ----------------------------------------------------------
Modules: WPDb, WPWebDriver, \Helper\Acceptance
-------------------------------------------------------------------------------
_InitializeCest: Activate plugin test
Signature: _InitializeCest:activatePluginTest
Test: tests/acceptance/_InitializeCest.php:activatePluginTest
Scenario --
 I login as admin 
  Trying to login, attempt 0/5...
  [GET] http://affiliate.local:8080/wp-login.php
  Cookies matching pattern /^wordpress_[a-z0-9]{32}$/ : {"wordpress_35baec3e4bb6c450c6f25653b5238026": "admin%7C1621602027%7C0vmQi3kEOYZlmotBrwcM4wP1UezBhWHRnaX81UqmZxd%7C5aa11e08a83a29b22c66a8029dd23791988a7588a7b06d4ff10da7866b758ee6"}
  Cookies matching pattern /^wordpress_logged_in_[a-z0-9]{32}$/ : {"wordpress_logged_in_35baec3e4bb6c450c6f25653b5238026": "admin%7C1621602027%7C0vmQi3kEOYZlmotBrwcM4wP1UezBhWHRnaX81UqmZxd%7C4083c6c6c19336a9707105befcb1b44f8b18a82d223af817f828dc76db2b6a2d"}
 I am on plugins page 
  [GET] http://affiliate.local:8080/wp-admin/plugins.php
 I see plugin installed "lasso"
 I activate plugin "lasso"
 I see plugin activated "lasso"
 I am on page "/wp-admin/edit.php?post_type=lasso-urls&page=install"
  [GET] http://affiliate.local:8080/wp-admin/edit.php?post_type=lasso-urls&page=install
 I fill field {"name":"license_serial"},"8da720d00b72c37c3822f3ccfcc2d11a"
 I click "Activate Lasso"
 I wait 15
 I see "Choose a Default Display Box Theme"
 I click ".choose_display_onboard.cactus"
 I see "Customize Your Displays"
 I click "button.btn.step-4"
 I see "You're Ready"
 I click "Go to Dashboard"
 I see "Dashboard"
 PASSED 

_InitializeCest: Add new link
Signature: _InitializeCest:addNewLink
Test: tests/acceptance/_InitializeCest.php:addNewLink
Scenario --
 I am on page "/wp-admin/edit.php?post_type=lasso-urls"
  [GET] http://affiliate.local:8080/wp-admin/edit.php?post_type=lasso-urls
  Screenshot and page source were saved into '/media/user/Data/Projects/wordpress/wp-content/plugins/lasso/tests/_output/' dir
 ERROR 

-------------------------------------------------------------------------------


Time: 02:03.466, Memory: 14.00 MB

There was 1 error:

---------
1) _InitializeCest: Add new link
 Test  tests/acceptance/_InitializeCest.php:addNewLink
                                                                                                                                                                                                                                                                                                      
  [Facebook\WebDriver\Exception\WebDriverCurlException] Curl error thrown for http POST to /session/178ffb6cc7d4d34ba608b48328e7dad8/url with params: {"url":"http://affiliate.local:8080/wp-admin/edit.php?post_type=lasso-urls"}

Operation timed out after 60002 milliseconds with 0 bytes received  
                                                                                                                                                                                                                                                                                                      

Scenario Steps:

 1. $I->amOnPage("/wp-admin/edit.php?post_type=lasso-urls") at tests/acceptance/_InitializeCest.php:34

/media/user/Data/Projects/wordpress/wp-content/plugins/lasso/vendor/php-webdriver/webdriver/lib/Remote/HttpCommandExecutor.php:332
/media/user/Data/Projects/wordpress/wp-content/plugins/lasso/vendor/php-webdriver/webdriver/lib/Remote/RemoteWebDriver.php:591
/media/user/Data/Projects/wordpress/wp-content/plugins/lasso/vendor/php-webdriver/webdriver/lib/Remote/RemoteWebDriver.php:250
/media/user/Data/Projects/wordpress/wp-content/plugins/lasso/vendor/codeception/module-webdriver/src/Codeception/Module/WebDriver.php:1010
/media/user/Data/Projects/wordpress/wp-content/plugins/lasso/vendor/codeception/codeception/src/Codeception/Step.php:268
/media/user/Data/Projects/wordpress/wp-content/plugins/lasso/vendor/codeception/codeception/src/Codeception/Scenario.php:76
/media/user/Data/Projects/wordpress/wp-content/plugins/lasso/tests/_support/_generated/AcceptanceTesterActions.php:4852
/media/user/Data/Projects/wordpress/wp-content/plugins/lasso/tests/acceptance/_InitializeCest.php:34
/media/user/Data/Projects/wordpress/wp-content/plugins/lasso/vendor/codeception/codeception/src/Codeception/Lib/Di.php:128
/media/user/Data/Projects/wordpress/wp-content/plugins/lasso/vendor/codeception/codeception/src/Codeception/Test/Cest.php:138
/media/user/Data/Projects/wordpress/wp-content/plugins/lasso/vendor/codeception/codeception/src/Codeception/Test/Cest.php:150
/media/user/Data/Projects/wordpress/wp-content/plugins/lasso/vendor/codeception/codeception/src/Codeception/Test/Cest.php:82
/media/user/Data/Projects/wordpress/wp-content/plugins/lasso/vendor/codeception/codeception/src/Codeception/Test/Test.php:98
/media/user/Data/Projects/wordpress/wp-content/plugins/lasso/vendor/phpunit/phpunit/src/Framework/TestSuite.php:677
/media/user/Data/Projects/wordpress/wp-content/plugins/lasso/vendor/codeception/phpunit-wrapper/src/Runner.php:117
/media/user/Data/Projects/wordpress/wp-content/plugins/lasso/vendor/codeception/codeception/src/Codeception/SuiteManager.php:161
/media/user/Data/Projects/wordpress/wp-content/plugins/lasso/vendor/codeception/codeception/src/Codeception/Codecept.php:208
/media/user/Data/Projects/wordpress/wp-content/plugins/lasso/vendor/codeception/codeception/src/Codeception/Codecept.php:162
/media/user/Data/Projects/wordpress/wp-content/plugins/lasso/vendor/codeception/codeception/src/Codeception/Command/Run.php:401
/media/user/Data/Projects/wordpress/wp-content/plugins/lasso/vendor/symfony/console/Command/Command.php:256
/media/user/Data/Projects/wordpress/wp-content/plugins/lasso/vendor/symfony/console/Application.php:971
/media/user/Data/Projects/wordpress/wp-content/plugins/lasso/vendor/symfony/console/Application.php:290
/media/user/Data/Projects/wordpress/wp-content/plugins/lasso/vendor/symfony/console/Application.php:166
/media/user/Data/Projects/wordpress/wp-content/plugins/lasso/vendor/codeception/codeception/src/Codeception/Application.php:117
/media/user/Data/Projects/wordpress/wp-content/plugins/lasso/vendor/codeception/codeception/app.php:46
/media/user/Data/Projects/wordpress/wp-content/plugins/lasso/vendor/codeception/codeception/app.php:47
/media/user/Data/Projects/wordpress/wp-content/plugins/lasso/vendor/codeception/codeception/codecept:7

Artifacts:

Png: /media/user/Data/Projects/wordpress/wp-content/plugins/lasso/tests/_output/.InitializeCest.addNewLink.fail.png
Html: /media/user/Data/Projects/wordpress/wp-content/plugins/lasso/tests/_output/.InitializeCest.addNewLink.fail.html

ERRORS!
Tests: 2, Assertions: 7, Errors: 1.
  [Db] Disconnected from default
  [Db] Disconnected from default

```

**Expected behavior**
I think it should visit `'/wp-admin/edit.php?post_type=lasso-urls'` page but itshows CURL issue.

**Screenshots**
If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/57546027/118822134-76cdf800-b8ea-11eb-8856-0b207ac432e6.png)

**Additional context**
If I change `cleanup: true` in acceptance.suite.yml it does not have this error but I don't want to go through the plugin activation process again to speed up
