### ISSUE TITLE
[BUG] WP CLI throws error when there's a space in PHP path

### ISSUE THREAD

**Issue by joppuyo** [lucatume/wp-browser#516]
**Environment**
OS: Mac
PHP 7.4.1
Installed Codeception version: 4.1.21
Installed wp-browser version: 3.0.8
WordPress version: 5.8 
Local development environment: Local by Flywheel
WordPress structure and management: default

**Codeception configuration file**  

```yaml
paths:
    tests: tests
    output: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
actor_suffix: Tester
extensions:
    enabled:
        - Codeception\Extension\RunFailed
    commands:
        - Codeception\Command\GenerateWPUnit
        - Codeception\Command\GenerateWPRestApi
        - Codeception\Command\GenerateWPRestController
        - Codeception\Command\GenerateWPRestPostTypeController
        - Codeception\Command\GenerateWPAjax
        - Codeception\Command\GenerateWPCanonical
        - Codeception\Command\GenerateWPXMLRPC
params:
    - .env.testing
```


**Suite configuration file**

```yaml
# Codeception Test Suite Configuration
#
# Suite for acceptance tests.
# Perform tests in browser using the WPWebDriver or WPBrowser.
# Use WPDb to set up your initial database fixture.
# If you need both WPWebDriver and WPBrowser tests - create a separate suite.

actor: AcceptanceTester
modules:
    enabled:
        - WPDb
        - WPBrowser
        - \Helper\Acceptance
        - WPCLI
    config:
        WPDb:
            dsn: '%TEST_SITE_DB_DSN%'
            user: '%TEST_SITE_DB_USER%'
            password: '%TEST_SITE_DB_PASSWORD%'
            dump: 'tests/_data/dump.sql'
            #import the dump before the tests; this means the test site database will be repopulated before the tests.
            populate: true
            # re-import the dump between tests; this means the test site database will be repopulated between the tests.
            cleanup: true
            waitlock: 10
            url: '%TEST_SITE_WP_URL%'
            urlReplacement: true #replace the hardcoded dump URL with the one above
            tablePrefix: '%TEST_SITE_TABLE_PREFIX%'
        WPBrowser:
            url: '%TEST_SITE_WP_URL%'
            adminUsername: '%TEST_SITE_ADMIN_USERNAME%'
            adminPassword: '%TEST_SITE_ADMIN_PASSWORD%'
            adminPath: '%TEST_SITE_WP_ADMIN_PATH%'
            headers:
                X_TEST_REQUEST: 1
                X_WPBROWSER_REQUEST: 1
        WPCLI:
            path: '%WP_ROOT_FOLDER%'
            allow-root: true
```

**Describe the bug**
When using `$I->cli()` helper, it throws an error if there's a space in the PHP path. I'm running the tests in Local by Flywheel shell and the PHP path is `/Users/johannessiipola/Library/Application Support/Local/lightning-services/php-7.4.1+14/bin/darwin/bin/php`.

**Output**
```
vendor/bin/codecept run acceptance --fail-fast --debug
Codeception PHP Testing Framework v4.1.21
Powered by PHPUnit 9.5.7 by Sebastian Bergmann and contributors.

  [Connecting To Db] {"config":{"tablePrefix":"wp_","populate":true,"cleanup":true,"reconnect":false,"dump":"tests/_data/dump.sql","populator":null,"urlReplacement":true,"originalUrl":null,"waitlock":10,"dsn":"mysql:host=localhost;dbname=local","user":"root","password":"root","url":"http://disable-drop-cap.test"},"options":[]}
  [Db] Connected to default local
  Rebuilding AcceptanceTester...
  [Query] INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES (?, ?, ?)
  [Parameters] ["admin_email_lifespan",2533080438,"yes"]
  [Query] INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES (?, ?, ?)
  [Parameters] ["_transient_doing_cron",1627140269,"yes"]

Acceptance Tests (1) --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Modules: WPDb, WPBrowser, \Helper\Acceptance, WPCLI
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
AcceptanceCest: I see drop cap
Signature: AcceptanceCest:iSeeDropCap
Test: tests/acceptance/AcceptanceCest.php:iSeeDropCap
Scenario --
  [Query] INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES (?, ?, ?)
  [Parameters] ["admin_email_lifespan",2533080438,"yes"]
  [Query] INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES (?, ?, ?)
  [Parameters] ["_transient_doing_cron",1627140270,"yes"]
 I cli ["core","update-db"]
  [WPCLI command] ["core","update-db"]
  [WPCLI command with configuration options] ["--allow-root","core","update-db"]
  [WPCLI command with environment] []
  WPCLI Process failed: Command "/Users/johannessiipola/Library/Application Support/Local/lightning-services/php-7.4.1+14/bin/darwin/bin/php /Users/johannessiipola/Documents/Projects/disable-drop-cap/app/public/wp-content/plugins/remove-drop-cap/vendor/wp-cli/wp-cli/php/boot-fs.php --path=/Users/johannessiipola/Documents/Projects/disable-drop-cap/app/public --allow-root core update-db" failed (127) with error: sh: /Users/johannessiipola/Library/Application: No such file or directory
  [WPCLI output] sh: /Users/johannessiipola/Library/Application: No such file or directory
  [WPCLI  status] 127
 ERROR 

-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


Time: 00:00.825, Memory: 10.00 MB

There was 1 error:

---------
1) AcceptanceCest: I see drop cap
 Test  tests/acceptance/AcceptanceCest.php:iSeeDropCap
                                                                                                                                                                                                                                                                                                        
  [ModuleException] WPCLI: wp-cli terminated with status [127] and output [sh: /Users/johannessiipola/Library/Application: No such file or directory]

WPCLI module is configured to throw an exception when wp-cli terminates with an error status; set the `throw` parameter to `false` to avoid this.  
                                                                                                                                                                                                                                                                                                        

Scenario Steps:

 1. $I->cli(["core","update-db"]) at tests/acceptance/AcceptanceCest.php:7

#1  /Users/johannessiipola/Documents/Projects/disable-drop-cap/app/public/wp-content/plugins/remove-drop-cap/vendor/lucatume/wp-browser/src/Codeception/Module/WPCLI.php:313
#2  /Users/johannessiipola/Documents/Projects/disable-drop-cap/app/public/wp-content/plugins/remove-drop-cap/vendor/lucatume/wp-browser/src/Codeception/Module/WPCLI.php:209
#3  /Users/johannessiipola/Documents/Projects/disable-drop-cap/app/public/wp-content/plugins/remove-drop-cap/vendor/lucatume/wp-browser/src/Codeception/Module/WPCLI.php:144
#4  Codeception\Module\WPCLI->cli
#5  /Users/johannessiipola/Documents/Projects/disable-drop-cap/app/public/wp-content/plugins/remove-drop-cap/tests/_support/_generated/AcceptanceTesterActions.php:7521
#6  /Users/johannessiipola/Documents/Projects/disable-drop-cap/app/public/wp-content/plugins/remove-drop-cap/tests/acceptance/AcceptanceCest.php:7
#7  AcceptanceCest->_before

ERRORS!
Tests: 1, Assertions: 0, Errors: 1.
  [Db] Disconnected from default
  [Db] Disconnected from default
```
**To Reproduce**
Create integration test with the following content:

```
<?php

class AcceptanceCest
{
    public function _before(AcceptanceTester $I)
    {
        $I->cli(['core', 'update-db']);
    }

    public function iSeeDropCap(AcceptanceTester $I)
    {
        $I->loginAsAdmin();
    }

}
```

**Expected behavior**
WP CLI command should work

**Additional context**
The code used to work in an earlier version of WP Browser. I tried to manually set a PHP path with quotes but I couldn't get it to work.
