### ISSUE TITLE
WPWebDriver can't see "Classic Editor" Visual/Text buttons[BUG]

### ISSUE THREAD

**Issue by jerclarke** [lucatume/wp-browser#518]
**Environment**
OS: macOS 10.15
PHP version: v3.3.25
Installed Codeception version:  4.1.21
Installed wp-browser version: 3.0.8
WordPress version: 5.4 (also tested 5.4)  
Local development environment: MAMP
WordPress structure and management: default

Also:
ChromeDriver version: 92.0.4515.43

**Can you perform the test manually?**

Yes. I have the "Classic Editor" plugin on both 5.4 and 5.8 and in Chrome I can switch tabs normally in "classic" editing mode.

But when I use WPWebDriver with ChromeDriver, they just don't show (though the js for the Text editor does seem to work which is strange.).

**Codeception configuration file**  
Paste, in a fenced YAML block, the content of your Codeception configuration file; remove any sensitive data!  

```yaml
paths:
    tests: tests
    output: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
actor_suffix: Tester
extensions:
    enabled:
        - Codeception\Extension\RunFailed
    commands:
        - Codeception\Command\GenerateWPUnit
        - Codeception\Command\GenerateWPRestApi
        - Codeception\Command\GenerateWPRestController
        - Codeception\Command\GenerateWPRestPostTypeController
        - Codeception\Command\GenerateWPAjax
        - Codeception\Command\GenerateWPCanonical
        - Codeception\Command\GenerateWPXMLRPC
params:
    - .env.testing
```

**Suite configuration file**
Paste, in a fenced YAML block, the content of the suite configuration file; remove any sensitive data!

```yaml
actor: AcceptanceTester
modules:
    enabled:
        - WPDb
        - WPWebDriver
        - \Helper\Acceptance
    config:
        WPDb:
            dsn: '%TEST_SITE_DB_DSN%'
            user: '%TEST_SITE_DB_USER%'
            password: '%TEST_SITE_DB_PASSWORD%'
            dump: 'tests/_data/dump.sql'
            #import the dump before the tests; this means the test site database will be repopulated before the tests.
            populate: true
            # re-import the dump between tests; this means the test site database will be repopulated between the tests.
            cleanup: true
            waitlock: 10
            url: '%TEST_SITE_WP_URL%'
            urlReplacement: true #replace the hardcoded dump URL with the one above
            tablePrefix: '%TEST_SITE_TABLE_PREFIX%'
        WPWebDriver:
            url: '%TEST_SITE_WP_URL%'
            adminUsername: '%TEST_SITE_ADMIN_USERNAME%'
            adminPassword: '%TEST_SITE_ADMIN_PASSWORD%'
            adminPath: '%TEST_SITE_WP_ADMIN_PATH%'
            browser: chrome
            host: 127.0.0.1
            port: 9515
            window_size: false
            headers:
                X_TEST_REQUEST: 1
                X_WPBROWSER_REQUEST: 1
            capabilities:
                chromeOptions:
                    args: ["--headless", "--disable-gpu", "--proxy-server='direct://'", "--proxy-bypass-list=*", "--user-agent=GVCodeceptionAcceptanceWebDriver"]
```

**Describe the bug**

![GVPostEditorCest testUpdatingDraft fail](https://user-images.githubusercontent.com/139995/127915532-17094164-1ac6-46f0-b18e-856e60c943c2.png)

When I do an acceptance test of the post editor with Classic Editor plugin enabled, ChromeDriver doesn't see the tab buttons to switch between Visual and Text. 

I was working on a 5.4 site when I noticed it, but it also seems to apply to 5.8 (tested on a fresh site with only Gutenberg Starter Theme and Classic Editor plugin). 

Maybe this is a known issue? Just wanted to make sure. 

I'm currently working on a bug who's symptom is the inability to switch the tabs, so I got really stuck trying to write a regression test 😅

Here's the test that generates the screenshot:

```php
public function testClassicEditorVisualAndTextTabs(BrowserTester $I) {
	$I->loginAsAdmin();
	$I->amOnAdminPage('/post-new.php');
	$I->see('Add New Post');

	$I->wait(2);

	$I->see("Visual", "#content-tmce");
	$I->click("#content-tmce");
	$I->see("Text", "#content-html");

}	
```

**Output**

In addition to the screenshot, I also of course get the HTML output. Here's a screenshot of what I get when I open the local HTML file:

<img width="1126" alt="Screen Shot 2021-08-02 at 3 12 48 PM" src="https://user-images.githubusercontent.com/139995/127918104-89051abe-dbc6-47a1-9ad1-cd66e0b26b8d.png">

I was expecting the JS to be just completely broken, as that's usually why the Visual/Text buttons break, but it worked fine as you can see, just not Visual/Text tabs!

**To Reproduce**

* Install Classic Editor plugin so the editor loads the classic TinyMCE
* Run a WPWebDriver test that loads the post editor
* Try to `$I->see()` or `$I->click()` the **Visual** or **Text** tabs.
* They are strangely totally missing, but the "Text" editor's JS tools are present, which is so weird.

**Expected behavior**

They should be present like when I visit normally.

**Additional context**

This might not be a "bug in WP-Browser", but I was looking to know if others have encountered this, and if it can be fixed in WPB then that seems like it might help others as well. 

Happy to hear any potential solutions! Maybe it's something about my setup that it more particular than it seemed.
