### ISSUE TITLE
Setting up wpRootFolder for WPFilesystem

### ISSUE THREAD

**Issue by jcvignoli** [lucatume/wp-browser#519]
Before filling up a proper bug report, I would like to know if that's an expected feature that wp browser adds a local development path to my defined wpRootFolder for WPFilesystem.

I defined in my suite.yml file the config value 

wpRootFolder: '%TEST_REMOTE_ROOT_FOLDER%'

to which wp browser adds a local path that I haven't defined anywhere in my .env.test setup. I'm not getting it; could you please let me know if that is expected?

**Comment by lucatume** [comment]
I'm missing the information required to answer, I fear.

What is the value corresponding to the `%TEST_REMOTE_ROOT_FOLDER%` on your machine or the CI machine?
What "local path" is added to it? What does the resulting path look like? 
If you could provide the main and the suite configuration files, that would help me understand.

**Comment by jcvignoli** [comment]
Thanks for your quick reply. Due to your questions, I guess this behaviour is not expected.

Test_remote_root_folder is the root path of my remote testing machine. Let's say /var/wp

My local dev env is located at /var/local

The resulting path throwing a wp browser error ("path doesn't exist", I don't have the exact msg right now) is
/var/local/var/wp

Let me know if you need further info. I don't understand wp browser behaviour since /var/local is nowhere defined.

**Comment by jcvignoli** [comment]
I can provide you with further info, given the fact that I edited the real paths.

The error thrown by wp browser:

```
In WPFilesystem.php line 173:
                                                                               
  [Codeception\Exception\ModuleConfigException]                                
  WPFilesystem module is not configured!                                       
                                                                               
  [/var/local/var/wp] is not a valid WordPress root fo  
  lder.                                                                        
                                                                               
  The WordPress root folder is the one that contains the 'wp-load.php' file.
```

Relevant codeception section:

```
paths:
    tests: tests
    output: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
params:
    - .env.testing
actor_suffix: Tester
extensions:
    enabled:
        - Codeception\Extension\RunFailed
env:
        extensions:
            enabled:
              - Codeception\Extension\RunProcess:
                  0: ./tests/geckodriver
                  sleep: 7 # seconds before processing boot, otherwise it fails sometimes
    wpfirefox:
        modules:
             enabled:
                - WPWebDriver
        extensions:
            enabled:
              - Codeception\Extension\RunProcess:
                  0: ./tests/geckodriver
                  sleep: 7 # seconds to process boot, otherwise it fails sometimes
            commands:
                - Codeception\Command\GenerateWPUnit
                - Codeception\Command\GenerateWPRestApi
                - Codeception\Command\GenerateWPRestController
                - Codeception\Command\GenerateWPRestPostTypeController
                - Codeception\Command\GenerateWPAjax
                - Codeception\Command\GenerateWPCanonical
                - Codeception\Command\GenerateWPXMLRPC

```

relevant .env.testing

```
TEST_REMOTE_ROOT_FOLDER='/var/wp'`

relevant acceptanceRemote.suite.yml
`# Codeception Test Suite Configuration -> For a remote server
#
actor: AcceptanceRemoteTester
modules:
    enabled:
        - \Helper\AcceptanceRemote
        - WPFilesystem
    config:
        WPFilesystem:
            wpRootFolder: '%TEST_REMOTE_ROOT_FOLDER%'
        WPDb:
            dsn: '%TEST_REMOTE_DB_DSN%'
            user: '%TEST_REMOTE_DB_USER%'
            password: '%TEST_REMOTE_DB_PASSWORD%'
            dump: test.sql'
            #import the dump before the tests; this means the test site database will be repopulated before the tests.
            populate: false
            # re-import the dump between tests; this means the test site database will be repopulated between the tests.
            cleanup: false
            waitlock: 10
            url: '%TEST_REMOTE_WP_URL%'
            urlReplacement: true #replace the hardcoded dump URL with the one above
            tablePrefix: '%TEST_TABLE_PREFIX%'
        WPBrowser:
            url: '%TEST_REMOTE_WP_URL%'
            adminUsername: '%TEST_WP_ADMIN_USERNAME%'
            adminPassword: '%TEST_WP_ADMIN_PASSWORD%'
            adminPath: '%TEST_WP_ADMIN_PATH%'
            headers:
                X_TEST_REQUEST: 1
                X_WPBROWSER_REQUEST: 1
env:
   wpfirefox:
       modules:
          config:
             WPWebDriver:
                 url: '%TEST_REMOTE_WP_URL%'
                 adminUsername: '%TEST_WP_ADMIN_USERNAME%'
                 adminPassword: '%TEST_WP_ADMIN_PASSWORD%'
                 adminPath: '%TEST_WP_ADMIN_PATH%'
                 browser: firefox
                 path: ''
                 capabilities:
                     # Used in more recent releases of Selenium.
                     moz:firefoxOptions:
                         args: ["-headless"] # Run Firefox in headless mode
```
