### ISSUE TITLE
[BUG] activatePlugin() doesn't work

### ISSUE THREAD

**Issue by jcvignoli** [lucatume/wp-browser#520]
**Environment**
OS: Linux
PHP version:7.4.20
Installed Codeception version: v4.1.21
Installed wp-browser version: v3.0
WordPress version: v5.8

**Can you perform the test manually?**
Yes

**Codeception configuration file**  
```yaml
paths:
    tests: tests
    output: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
params:
    - .env.testing
actor_suffix: Tester
extensions:
    enabled:
        - Codeception\Extension\RunFailed
env:
    wpfirefox:
        extensions:
            enabled:
              - Codeception\Extension\RunProcess:
                  0: ./tests/geckodriver
                  sleep: 7 # seconds to process boot, otherwise it fails sometimes
            commands:
                - Codeception\Command\GenerateWPUnit
                - Codeception\Command\GenerateWPRestApi
                - Codeception\Command\GenerateWPRestController
                - Codeception\Command\GenerateWPRestPostTypeController
                - Codeception\Command\GenerateWPAjax
                - Codeception\Command\GenerateWPCanonical
                - Codeception\Command\GenerateWPXMLRPC
```

**Suite configuration file**
```yaml
actor: AcceptanceRemoteTester
modules:
    enabled:
        - \Helper\AcceptanceRemote
        - Filesystem
        - WPWebDriver
    config:
        WPFilesystem:
            wpRootFolder: '%WP_ROOT_REMOTE_FOLDER%'
        WPBrowser:
            url: '%TEST_REMOTE_WP_URL%'
            adminUsername: '%TEST_WP_ADMIN_USERNAME%'
            adminPassword: '%TEST_WP_ADMIN_PASSWORD%'
            adminPath: '%TEST_WP_ADMIN_PATH%'
            headers:
                X_TEST_REQUEST: 1
                X_WPBROWSER_REQUEST: 1
env:
   wpfirefox:
       modules:
          config:
             WPWebDriver:
                 url: '%TEST_REMOTE_WP_URL%'
                 adminUsername: '%TEST_WP_ADMIN_USERNAME%'
                 adminPassword: '%TEST_WP_ADMIN_PASSWORD%'
                 adminPath: '%TEST_WP_ADMIN_PATH%'
                 browser: firefox
                 path: ''
                 capabilities:
                     # Used in more recent releases of Selenium.
                     moz:firefoxOptions:
                         args: ["-headless"] # Run Firefox in headless mode
```

**Describe the bug**
activatePlugin() fails to activate a plugin. It fails without a warning, the plugin remains just unactivated in WordPress.

deactivatePlugin() does properly its job.

I use exactly the same plugin slug in both function, using first the desactivatePlugin(). 

**Output**
Test: tests/acceptanceRemote/006-InstallCest.php:checkCanInstallLumiere
Scenario --
 #Code _before#
 AcceptanceTrait: login_universal "AcceptanceRemoteTester"
   I load session snapshot "login"
   I login as admin 
  Trying to login, attempt 0/5...
  [GET] [...]/wp-login.php
  Cookies matching pattern /^wordpress_[a-z0-9]{32}$/ : 
  Cookies matching pattern /^wordpress_logged_in_[a-z0-9]{32}$/ : {"[...]": "[...]"}
   I save session snapshot "login"
  [Snapshot] Saved "login" session snapshot
 I am on plugins page 
  [GET] [...]/wp-admin/plugins.php
 I activate plugin "lumiere-movies"
 I am on page "/wp-admin/tools.php?page=crontrol_admin_manage_page"
  [GET] [...]/wp-admin/tools.php?page=crontrol_admin_manage_page
 I see "lumiere_cron_hook"
 #Code _after#
  Screenshot and page source were saved into 'tests/_output/' dir
 FAIL 

**To Reproduce**
Use deactivatePlugin() then activatePlugin().

**Expected behavior**
To activate the plugin.
