### ISSUE TITLE
[SETUP ISSUE]

### ISSUE THREAD

**Issue by JAW-Dev** [lucatume/wp-browser#521]
**Environment**
OS: Mac
PHP version: 7.4
Installed Codeception version: 4.1.22
Installed wp-browser version: 3.0
WordPress version: 5.8
Local development environment: Valet

**Did you use the `codecept init wpbrowser` command?**
yes

**Did you take a look at Codeception and wp-browser documentation?**
yes

**Codeception configuration file**

```yaml
paths:
  tests: tests
  output: tests/_output
  data: tests/_data
  support: tests/_support
  envs: tests/_envs
actor_suffix: Tester
settings:
  colors: true
  memory_limit: 1024M
extensions:
  enabled:
    - Codeception\Extension\RunFailed
  commands:
    - Codeception\Command\GenerateWPUnit
    - Codeception\Command\GenerateWPRestApi
    - Codeception\Command\GenerateWPRestController
    - Codeception\Command\GenerateWPRestPostTypeController
    - Codeception\Command\GenerateWPAjax
    - Codeception\Command\GenerateWPCanonical
    - Codeception\Command\GenerateWPXMLRPC
params:
  - .env.testing
```

**Describe the issue you're encountering**
Some modules aren't installed like codeception/module-db. When I try to install that I get an error `codeception/module-webdriver 1.0.1 requires php-webdriver/webdriver ^1.6.0`. When I try to install php-webdriver I get the error `php-webdriver/webdriver 1.7.0 requires ext-zip * -> the requested PHP extension zip is missing from your system.`

It seems like an issue with my system but I can't find any solutions for this. I installed Codeception, delete the config file, installed WP-Browser, and ran `vendor/bin/codecept init wpbrowser`. That got me to this point.
