### ISSUE TITLE
[SETUP ISSUE]

### ISSUE THREAD

**Issue by ajayver** [lucatume/wp-browser#522]
**Environment**
OS: Windows 10/Docker
PHP version: 7.4
Installed Codeception version: 4.1.22
Installed wp-browser version: 3.0.8
WordPress version: 5.8
Local development environment: Docker
WordPress structure and management: default

**Did you use the `codecept init wpbrowser` command?**
Yes

**Did you take a look at Codeception and wp-browser documentation?**
Yes

**Codeception configuration file**

```yaml
paths:
    tests: tests
    output: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
actor_suffix: Tester
extensions:
    enabled:
        - Codeception\Extension\RunFailed
    commands:
        - Codeception\Command\GenerateWPUnit
        - Codeception\Command\GenerateWPRestApi
        - Codeception\Command\GenerateWPRestController
        - Codeception\Command\GenerateWPRestPostTypeController
        - Codeception\Command\GenerateWPAjax
        - Codeception\Command\GenerateWPCanonical
        - Codeception\Command\GenerateWPXMLRPC
params:
    - .env.testing

```

**Suite configuration file**
```yaml
# Codeception Test Suite Configuration
#
# Suite for unit or integration tests that require WordPress functions and classes.
actor: WpunitTester
modules:
    enabled:
        - WPLoader
        - \Helper\Wpunit
    config:
        WPLoader:
            wpRootFolder: "%WP_ROOT_FOLDER%"
            dbName: "%TEST_DB_NAME%"
            dbHost: "%TEST_DB_HOST%"
            dbUser: "%TEST_DB_USER%"
            dbPassword: "%TEST_DB_PASSWORD%"
            tablePrefix: "%TEST_TABLE_PREFIX%"
            domain: "%TEST_SITE_WP_DOMAIN%"
            adminEmail: "%TEST_SITE_ADMIN_EMAIL%"
            title: "Test"
            plugins: ['uncanny-automator/uncanny-automator.php']
            activatePlugins: ['uncanny-automator/uncanny-automator.php']
```

**Describe the issue you're encountering**
The tests run fine, but two warnings appear when I try to run wpunit suite due to previous output in isolated-install.php. As far as I know, phpunit doesn't like any output before it runs.

**Output**
```
> docker-compose exec -T -w /var/www/html/wp-content/plugins/uncanny-automator wordpress codecept run wpunit


==== Redirecting to Composer-installed version in vendor/codeception. You can skip this using --no-redirect ====
Codeception PHP Testing Framework v4.1.22
Powered by PHPUnit 9.5.8 by Sebastian Bergmann and contributors.
[29-Aug-2021 14:09:47 UTC] PHP Warning:  Cannot modify header information - headers already sent by (output started at /var/www/html/wp-content/plugins/uncanny-automator/vendor/lucatume/wp-browser/src/includes/isolated-install.php:41) in /var/www/html/wp-includes/pluggable.php on line 1340
[29-Aug-2021 14:09:47 UTC] PHP Warning:  Cannot modify header information - headers already sent by (output started at /var/www/html/wp-content/plugins/uncanny-automator/vendor/lucatume/wp-browser/src/includes/isolated-install.php:41) in /var/www/html/wp-includes/pluggable.php on line 1343

Wpunit Tests (1) -------------------------------------------
✔ SomeClassTest: Test_it_works (0.16s)
------------------------------------------------------------


Time: 00:10.232, Memory: 42.50 MB

OK (1 test, 1 assertion)
```

**To Reproduce**
* Install wp-browser following all the steps from the guide, 
* Create a wpunit test using the build-in helper function
* Run wpunit suite
