### ISSUE TITLE
Indirect modification of overloaded element

### ISSUE THREAD

**Issue by JAW-Dev** [lucatume/wp-browser#527]
**Environment**
OS: Mac
PHP 7.4
Installed Codeception version: 1.0
Installed wp-browser version: 3.0
WordPress version: 5.8.1
Local development environment: Valet

**Did you use the `codecept init wpbrowser` command?**
yes

**Did you take a look at Codeception and wp-browser documentation?**
yes

**Codeception configuration file**
```
paths:
    tests: tests
    output: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
actor_suffix: Tester
extensions:
    enabled:
        - Codeception\Extension\RunFailed
    commands:
        - Codeception\Command\GenerateWPUnit
        - Codeception\Command\GenerateWPRestApi
        - Codeception\Command\GenerateWPRestController
        - Codeception\Command\GenerateWPRestPostTypeController
        - Codeception\Command\GenerateWPAjax
        - Codeception\Command\GenerateWPCanonical
        - Codeception\Command\GenerateWPXMLRPC
params:
    - .env.testing
```

**Describe the issue you're encountering**
When I run the `run` command I'm getting this error.

`Indirect modification of overloaded element of tad\WPBrowser\Utils\Configuration has no effect at vendor/lucatume/wp-browser/src/Codeception/Module/WPLoader.php:746`

**Output**
```
Codeception PHP Testing Framework v4.1.22
Powered by PHPUnit 9.5.9 by Sebastian Bergmann and contributors.

Acceptance Tests (0) -----------------------------------------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Functional Tests (0) -----------------------------------------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Unit Tests (0) -----------------------------------------------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------

In ErrorHandler.php line 84:
                                                                                                                                                                        
  Indirect modification of overloaded element of tad\WPBrowser\Utils\Configuration has no effect at vendor/lucatume/wp-browser/src/Codeception/Module/WPLoader.php:746  
                                                                                                                                                                        

run [-o|--override OVERRIDE] [-e|--ext EXT] [--report] [--html [HTML]] [--xml [XML]] [--phpunit-xml [PHPUNIT-XML]] [--tap [TAP]] [--json [JSON]] [--colors] [--no-colors] [--silent] [--steps] [-d|--debug] [--bootstrap [BOOTSTRAP]] [--no-redirect] [--coverage [COVERAGE]] [--coverage-html [COVERAGE-HTML]] [--coverage-xml [COVERAGE-XML]] [--coverage-text [COVERAGE-TEXT]] [--coverage-crap4j [COVERAGE-CRAP4J]] [--coverage-cobertura [COVERAGE-COBERTURA]] [--coverage-phpunit [COVERAGE-PHPUNIT]] [--no-exit] [-g|--group GROUP] [-s|--skip SKIP] [-x|--skip-group SKIP-GROUP] [--env ENV] [-f|--fail-fast] [--no-rebuild] [--seed SEED] [--no-artifacts] [--] [<suite> [<test>]]
```
