### ISSUE TITLE
[BUG] Setting loadOnly to true causes error "Constant DB_NAME already defined" but only on PHP 8

### ISSUE THREAD

**Issue by joppuyo** [lucatume/wp-browser#533]
**Environment**
OS: Linux
PHP version: 8.0
Installed Codeception version: 4.1.22
Installed wp-browser version: 3.0.11
WordPress version: 5.0 - 5.8
Local development environment: Docker
WordPress structure and management: default

**Can you perform the test manually?**
Yes

**Codeception configuration file**  
Paste, in a fenced YAML block, the content of your Codeception configuration file; remove any sensitive data!  

```yaml
paths:
    tests: tests
    output: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
actor_suffix: Tester
extensions:
    enabled:
        - Codeception\Extension\RunFailed
    commands:
        - Codeception\Command\GenerateWPUnit
        - Codeception\Command\GenerateWPRestApi
        - Codeception\Command\GenerateWPRestController
        - Codeception\Command\GenerateWPRestPostTypeController
        - Codeception\Command\GenerateWPAjax
        - Codeception\Command\GenerateWPCanonical
        - Codeception\Command\GenerateWPXMLRPC
params:
    - .env.testing
```

**Suite configuration file**
Paste, in a fenced YAML block, the content of the suite configuration file; remove any sensitive data!

```yaml
# Codeception Test Suite Configuration
#
# Suite for acceptance tests.
# Perform tests in browser using the WPWebDriver or WPBrowser.
# Use WPDb to set up your initial database fixture.
# If you need both WPWebDriver and WPBrowser tests - create a separate suite.

actor: AcceptanceTester
modules:
    enabled:
        - WPDb
        - WPBrowser
        - WPCLI
        - \Helper\Acceptance
        - WPLoader
    config:
        WPDb:
            dsn: '%TEST_SITE_DB_DSN%'
            user: '%TEST_SITE_DB_USER%'
            password: '%TEST_SITE_DB_PASSWORD%'
            dump: 'tests/_data/dump.sql'
            #import the dump before the tests; this means the test site database will be repopulated before the tests.
            populate: true
            # re-import the dump between tests; this means the test site database will be repopulated between the tests.
            cleanup: false
            waitlock: 10
            url: '%TEST_SITE_WP_URL%'
            urlReplacement: true #replace the hardcoded dump URL with the one above
            tablePrefix: '%TEST_SITE_TABLE_PREFIX%'
        WPBrowser:
            url: '%TEST_SITE_WP_URL%'
            adminUsername: '%TEST_SITE_ADMIN_USERNAME%'
            adminPassword: '%TEST_SITE_ADMIN_PASSWORD%'
            adminPath: '%TEST_SITE_WP_ADMIN_PATH%'
            headers:
                X_TEST_REQUEST: 1
                X_WPBROWSER_REQUEST: 1
        WPCLI:
            path: '%WP_ROOT_FOLDER%'
            allow-root: true
        WPLoader:
            loadOnly: true
            wpRootFolder: '%WP_ROOT_FOLDER%'
            dbName: '%TEST_SITE_DB_NAME%'
            dbHost: '%TEST_SITE_DB_HOST%'
            dbUser: '%TEST_SITE_DB_USER%'
            dbPassword: '%TEST_SITE_DB_PASSWORD%'
            tablePrefix: '%TEST_SITE_TABLE_PREFIX%'
            domain: '%TEST_SITE_WP_DOMAIN%'
            adminEmail: '%TEST_SITE_ADMIN_EMAIL%'
            title: 'Test site'
```

**Describe the bug**
If I set loadOnly to false under WPLoader In my Acceptance suite configuration everything works as it should when running on PHP 7.0 - 7.4 and 8.0. But if I set loadOnly to true, it works in 7.0 - 7.4 but in PHP 8.0 the test suite crashes with error `Constant DB_NAME already defined at ../../../wp-config.php:23`. It's almost like WordPress is being loaded twice or something. I'm not sure if there's something wrong with my suite configuration but I'm fairly certain it should work since I'm using very vanilla config.

**Output**
```
In ErrorHandler.php line 84:
                                                                 
  [PHPUnit\Framework\Exception (2)]                              
  Constant DB_NAME already defined at ../../../wp-config.php:23  
                                                                 

Exception trace:
  at /var/www/html/wp-content/plugins/wp-browser-bug-report/vendor/codeception/codeception/src/Codeception/Subscriber/ErrorHandler.php:84
 Codeception\Subscriber\ErrorHandler->errorHandler() at n/a:n/a
 define() at /var/www/html/wp-config.php:23
 require_once() at /var/www/html/wp-load.php:37
 include_once() at /var/www/html/wp-content/plugins/wp-browser-bug-report/vendor/lucatume/wp-browser/src/Codeception/Module/WPLoader.php:618
 Codeception\Module\WPLoader->bootstrapWP() at /var/www/html/wp-content/plugins/wp-browser-bug-report/vendor/lucatume/wp-browser/src/Codeception/Module/WPLoader.php:470
 Codeception\Module\WPLoader->_loadWordpress() at /var/www/html/wp-content/plugins/wp-browser-bug-report/vendor/symfony/event-dispatcher/EventDispatcher.php:230
 Symfony\Component\EventDispatcher\EventDispatcher->callListeners() at /var/www/html/wp-content/plugins/wp-browser-bug-report/vendor/symfony/event-dispatcher/EventDispatcher.php:59
 Symfony\Component\EventDispatcher\EventDispatcher->dispatch() at /var/www/html/wp-content/plugins/wp-browser-bug-report/vendor/lucatume/wp-browser/src/tad/WPBrowser/Events/EventDispatcherAdapter.php:348
````

**To Reproduce**
I have a full minimal repro here: https://github.com/joppuyo/wp-browser-bug-report with Docker and GitHub actions. Here's the successful run in GH actions: https://github.com/joppuyo/wp-browser-bug-report/actions/runs/1301315469 and here's the failed run: https://github.com/joppuyo/wp-browser-bug-report/actions/runs/1301316895

**Expected behavior**
It should work and not crash.
