### ISSUE TITLE
[DOC REQUEST] WPUnit test changes admin password to "password"

### ISSUE THREAD

**Issue by Borlabs-Ben** [lucatume/wp-browser#534]
**Did you search the documentation first?**
Yes.

**What do you think is missing from the documentation?**
Description why *WPLoader* or the WPUnit test changes the password of the admin to **password**.

**Do you have any examples of what you'd like to see added to the documentation?**

**wpunit.suite.yml**
```actor: WpunitTester
modules:
    enabled:
        - WPLoader
        - WPFilesystem
        - \Helper\Wpunit
```

**codeception.dist.yml** (excerpt)
```
WPLoader:
    wpRootFolder: '/var/www/html/single-test/'
    dbName: 'wp_single_test'
    dbHost: 'db'
    dbUser: 'wordpress'
    dbPassword: 'wordpress'
    tablePrefix: 'wp_'
    domain: 'localhost/single-test'
    title: 'Test - Codeception'
    loadOnly: false
```

As soon as I run a simple WPUnit test, the password of the WordPress instance is changed to **password**. I cannot find any information, why this happens nor how to change the password from **password** to something else. I could only find the string **password** within Wpbrowser.php, but this module is not being used in my configuration.
