### ISSUE TITLE
Configuring headers with wpwebdriver

### ISSUE THREAD

**Issue by charlesdeb** [lucatume/wp-browser#535]
**Environment**
OS: Linux
PHP version: 7.2
Installed Codeception version: 4.1.22
Installed wp-browser version: 3.0.11
WordPress version: 5.8
Local development environment: PHP built-in server
WordPress structure and management: SpinupWP

**Did you use the `codecept init wpbrowser` command?**
Yep
**Did you take a look at Codeception and wp-browser documentation?**
Yep, been over it many times!

**Codeception configuration file**

```
paths:
    tests: tests
    output: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
actor_suffix: Tester
extensions:
    enabled:
        - Codeception\Extension\RunFailed
    commands:
        - Codeception\Command\GenerateWPUnit
        - Codeception\Command\GenerateWPRestApi
        - Codeception\Command\GenerateWPRestController
        - Codeception\Command\GenerateWPRestPostTypeController
        - Codeception\Command\GenerateWPAjax
        - Codeception\Command\GenerateWPCanonical
        - Codeception\Command\GenerateWPXMLRPC
params:
    - .env.testing
```

**Suite configuration file**

The suite file that works and sets the headers properly is this one `acceptance_wpbrowser.suite.yml` :

```
actor: AcceptanceTester
modules:
  enabled:
    - WPDb
    - \Helper\Acceptance
    - WPBrowser
    - CustomTestHelper # Irrelevant to this problem
    - WPLoader # required in order to use WP functions in Codeception to set up test data
  config:
    WPDb:
      dsn: '%TEST_SITE_DB_DSN%'
      user: '%TEST_SITE_DB_USER%'
      password: '%TEST_SITE_DB_PASSWORD%'
      dump: 'tests/_data/dump.sql'
      populate: true
      cleanup: false # required for WPLoader
      waitlock: 10
      url: '%TEST_SITE_WP_URL%'
      originalUrl: '%TEST_SITE_WP_URL%'
      urlReplacement: true #replace the hardcoded dump URL with the one above
      tablePrefix: '%TEST_SITE_TABLE_PREFIX%'
    WPBrowser:
      url: '%TEST_SITE_WP_URL%'
      adminUsername: '%TEST_SITE_ADMIN_USERNAME%'
      adminPassword: '%TEST_SITE_ADMIN_PASSWORD%'
      adminPath: '%TEST_SITE_WP_ADMIN_PATH%'
      headers:
        X_TEST_REQUEST: 1
        X_WPBROWSER_REQUEST: 1
    WPLoader:
      wpRootFolder: '%WP_ROOT_FOLDER%'
      dbName: '%TEST_SITE_DB_NAME%'
      dbHost: '%TEST_SITE_DB_HOST%'
      dbUser: '%TEST_SITE_DB_USER%'
      dbPassword: '%TEST_SITE_DB_PASSWORD%'
      tablePrefix: '%TEST_SITE_TABLE_PREFIX%'
      domain: '%TEST_SITE_WP_DOMAIN%'
      adminEmail: '%TEST_SITE_ADMIN_EMAIL%'
      title: 'Site (Local)'
      theme: some_theme
      pluginsFolder: '../content/plugins'
      plugins: ... redacted
      activatePlugins: ... redacted
```

My `acceptance_wpwebdriver.suite.yml file` which I am having problems with is:

```
actor: AcceptanceTester
modules:
  enabled:
    - WPDb
    - \Helper\Acceptance
    - WPWebDriver
    - CustomTestHelper # Irrelevant to this problem
    - WPLoader # required in order to use WP functions in Codeception to set up test data
  config:
    WPDb:
      dsn: '%TEST_SITE_DB_DSN%'
      user: '%TEST_SITE_DB_USER%'
      password: '%TEST_SITE_DB_PASSWORD%'
      dump: 'tests/_data/dump.sql'
      populate: true
      cleanup: false # required for WPLoader
      waitlock: 10
      url: '%TEST_SITE_WP_URL%'
      originalUrl: '%TEST_SITE_WP_URL%'
      urlReplacement: true #replace the hardcoded dump URL with the one above
      tablePrefix: '%TEST_SITE_TABLE_PREFIX%'
    WPWebDriver:
      url: '%TEST_SITE_WP_URL%'
      adminUsername: '%TEST_SITE_ADMIN_USERNAME%'
      adminPassword: '%TEST_SITE_ADMIN_PASSWORD%'
      adminPath: '%TEST_SITE_WP_ADMIN_PATH%'
      port: 9515
      browser: chrome
      headers:
        X_TEST_REQUEST: 1
        X_WPBROWSER_REQUEST: 1
    WPLoader:
      wpRootFolder: '%WP_ROOT_FOLDER%'
      dbName: '%TEST_SITE_DB_NAME%'
      dbHost: '%TEST_SITE_DB_HOST%'
      dbUser: '%TEST_SITE_DB_USER%'
      dbPassword: '%TEST_SITE_DB_PASSWORD%'
      tablePrefix: '%TEST_SITE_TABLE_PREFIX%'
      domain: '%TEST_SITE_WP_DOMAIN%'
      adminEmail: '%TEST_SITE_ADMIN_EMAIL%'
      title: 'TBN UK (Local)'
      theme: tbnuk
      pluginsFolder: '../content/plugins'
      plugins: ...redacted
      activatePlugins: ... redacted
```

**Describe the issue you're encountering**

I have managed to configure my `acceptance_wpbrowser.suite.yml` file (above) to set the headers, and pick them up in my application in my `wp-config.php` file in order to get it to run against a test database. (Actually, it's not actually `wp-config.php` as my app is structured a bit differently, but it does the same thing), but when I apply the same changes to my `acceptance_wpwebdriver.suite.yml` file, then the `wp-config.php` file does not see the headers, and consequently does not use the test database.

According to this page in your docs, <https://wpbrowser.wptestkit.dev/tutorials/automatically-change-db-in-tests>, the headers parameter in the `*.suite.yml` files can be used for both `WPWebDriver` and `WPBrowser`. (As a small aside, I think there are some simple typos in this page - you refer to the `WPWebDriver` config in your example, but the example actually seems to refer to `WPBrowser` if I understand it correctly). However, on this page <https://wpbrowser.wptestkit.dev/modules/wpwebdriver> which describes how to configure `WPWebDriver`, no mention is made of the headers parameter. Is this a typo? Or does WPWebdriver not actually allow header config?

This is my code in `wp-config.php` (with my own debugging added)

```
var_dump($_SERVER);

if (
    // Custom header.
    isset($_SERVER['HTTP_X_TEST_REQUEST'])
    // Custom user agent.
    || (isset($_SERVER['HTTP_USER_AGENT']) && $_SERVER['HTTP_USER_AGENT'] === 'wp-browser')
    // The env var set by the WPClIr or WordPress modules.
    || getenv('WPBROWSER_HOST_REQUEST')
) {
    echo 'using test database';
    // Use the test database if the request comes from a test.
		App::define('DB_NAME', env('TEST_SITE_DB_NAME'));
		App::define('DB_USER', env('TEST_SITE_DB_USER'));
		App::define('DB_PASSWORD', env('TEST_SITE_DB_PASSWORD'));
		App::define('DB_HOST', env('TEST_SITE_DB_HOST') ?: 'localhost');
		$table_prefix = env('TEST_SITE_TABLE_PREFIX') ?: 'wp_';
}
else
{

    echo 'using real database';
    // Else use the default one.
    App::define('DB_NAME', env('DB_NAME'));
    App::define('DB_USER', env('DB_USER'));
    App::define('DB_PASSWORD', env('DB_PASSWORD'));
    App::define('DB_HOST', env('DB_HOST') ?: 'localhost');
    $table_prefix = env('DB_PREFIX') ?: 'wp_';
}
```
I am wondering if the `WPLoader` module is causing problems somewhere - but it shouldn't be the problem.

**Output**

With my basic debugging above enabled, when I inspect the `$_SERVER` variable (via the `var_dump`) I cannot see the `HTTP_X_TEST_REQUEST` value when running WPWebDriver tests. I also see "using real database" on my automated chrome browser when running WPWebDriver tests, but when running `WPBrowser` tests, I see "using test database". As you can imagine, I want to be using the test database for all my testing.

**To Reproduce**
As above - but it's pretty fiddly.

**Comment by n7studios** [comment]
If you configure WPWebDriver to use the headless ChromeDriver:
```
        WPWebDriver:
            url: '%TEST_SITE_WP_URL%'
            adminUsername: '%TEST_SITE_ADMIN_USERNAME%'
            adminPassword: '%TEST_SITE_ADMIN_PASSWORD%'
            adminPath: '%TEST_SITE_WP_ADMIN_PATH%'
            browser: chrome
            host: localhost
            port: 9515
            window_size: false #disabled for Chrome driver
            capabilities:
                chromeOptions:
                    args: ["--headless", "--disable-gpu"]
```

The above results in the value of `$_SERVER['HTTP_USER_AGENT']` containing `HeadlessChrome`:
```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/95.0.4638.69 Safari/537.36
```

This is different when you just view your WordPress site through your web browser:
```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36
```

You could then inspect the HTTP User Agent to determine the database you want to use in your `wp-config.php` file:
```php
if( isset( $_SERVER['HTTP_X_TEST_REQUEST'] ) && $_SERVER['HTTP_X_TEST_REQUEST'] ) {
	// WPBrowser request. Connect to test DB.
    define( 'DB_NAME', 'test' );
} elseif( isset( $_SERVER['HTTP_USER_AGENT'] ) && strpos( $_SERVER['HTTP_USER_AGENT'], 'HeadlessChrome' ) !== false ) {
	// WPWebDriver request. Connect to test DB.
    define( 'DB_NAME', 'test' );
} else {
	// Connect to local DB.
    define( 'DB_NAME', 'local' );
}
```

Not the most elegant solution, and it's unlikely to work if you're *not* using the ChromeDriver in headless mode.
