### ISSUE TITLE
[SETUP ISSUE] Headless Selenium in Docker Setup

### ISSUE THREAD

**Issue by kyletozer** [lucatume/wp-browser#537]
**Environment**
OS: Ubuntu 20.04.3 LTS
PHP version: 7.4
Installed Codeception version: 4.1.22
Installed wp-browser version: 3.0
WordPress version: 5.8.1
Local development environment: Docker
WordPress structure and management: Timber

**Did you use the `codecept init wpbrowser` command?**
Yes

**Did you take a look at Codeception and wp-browser documentation?**
Yes

**Codeception configuration file**

```yaml
paths:
    tests: tests
    output: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
actor_suffix: Tester
extensions:
    enabled:
        - Codeception\Extension\RunFailed
    commands:
        - Codeception\Command\GenerateWPUnit
        - Codeception\Command\GenerateWPRestApi
        - Codeception\Command\GenerateWPRestController
        - Codeception\Command\GenerateWPRestPostTypeController
        - Codeception\Command\GenerateWPAjax
        - Codeception\Command\GenerateWPCanonical
        - Codeception\Command\GenerateWPXMLRPC
params:
    - .env.testing
```

**Suite configuration file**
acceptance.suite.yml:
```yaml
# Codeception Test Suite Configuration
#
# Suite for acceptance tests.
# Perform tests in browser using the WPWebDriver or WPBrowser.
# Use WPDb to set up your initial database fixture.
# If you need both WPWebDriver and WPBrowser tests - create a separate suite.

actor: AcceptanceTester
modules:
    enabled:
        - WPDb
        # - WPBrowser
        - WPWebDriver
        - \Helper\Acceptance
        
    config:
        WPDb:
            dsn: '%TEST_SITE_DB_DSN%'
            user: '%TEST_SITE_DB_USER%'
            password: '%TEST_SITE_DB_PASSWORD%'
            dump: 'tests/_data/dump.sql'
            #import the dump before the tests; this means the test site database will be repopulated before the tests.
            populate: true
            # re-import the dump between tests; this means the test site database will be repopulated between the tests.
            cleanup: true
            waitlock: 10
            url: '%TEST_SITE_WP_URL%'
            urlReplacement: true #replace the hardcoded dump URL with the one above
            tablePrefix: '%TEST_SITE_TABLE_PREFIX%'
        WPWebDriver:
            url: '%TEST_SITE_WP_URL%'
            adminUsername: '%TEST_SITE_ADMIN_USERNAME%'
            adminPassword: '%TEST_SITE_ADMIN_PASSWORD%'
            adminPath: '%TEST_SITE_WP_ADMIN_PATH%'
            browser: chrome
            host: localhost
            port: 4444
            path: ''
            window_size: false #disabled for Chrome driver
            capabilities:
                chromeOptions:
                    args: ["--headless", "--disable-gpu", "--proxy-server='direct://'", "--proxy-bypass-list=*"]
        WPBrowser:
            url: '%TEST_SITE_WP_URL%'
            adminUsername: '%TEST_SITE_ADMIN_USERNAME%'
            adminPassword: '%TEST_SITE_ADMIN_PASSWORD%'
            adminPath: '%TEST_SITE_WP_ADMIN_PATH%'
            headers:
                X_TEST_REQUEST: 1
                X_WPBROWSER_REQUEST: 1
```

**Describe the issue you're encountering**
Trying to set up the WPWebDriver via Docker as described [here](https://wpbrowser.wptestkit.dev/modules/wpwebdriver) and [here](https://codeception.com/docs/modules/WebDriver#headless-selenium-in-docker)

docker-compose.yml:
```yaml
version: '3'

services:
  wp:
    build:
      context: .
      dockerfile: wp.Dockerfile
      args:
        WP_DB_NAME: &WP_DB_NAME wpdb
        WP_DB_USER: &WP_DB_USER wpuser
        WP_DB_PASS: &WP_DB_PASS secret
    environment:
      WP_DB_HOST: db
      WP_DB_NAME: *WP_DB_NAME
      WP_DB_USER: *WP_DB_USER
      WP_DB_PASS: *WP_DB_PASS
      WP_DEV_SITEURL: http://localhost
      WP_DEBUG: 1
    ports:
      - 80:80
      - 9001:9001
      - 3000:3000
      - 3001:3001
    volumes:
      - ./src/:/var/www/html:delegated

  db:
    build:
      context: .
      dockerfile: db.Dockerfile
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: *WP_DB_NAME
      MYSQL_USER: *WP_DB_USER
      MYSQL_PASSWORD: *WP_DB_PASS
    ports:
      - 33060:3306
    volumes:
      - db_data:/var/lib/mysql

  webdriver:
    image: selenium/standalone-chrome:95.0
    restart: always
    network_mode: host

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8889:80

volumes:
  db_data:
```

**Output**
When running "codecept run acceptance":

```
Codeception PHP Testing Framework v4.1.22
Powered by PHPUnit 9.5.10 by Sebastian Bergmann and contributors.

Acceptance Tests (1) ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
E SigninCest: First enable 
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


Time: 00:01.160, Memory: 20.00 MB

There was 1 error:

---------
1) SigninCest: First enable
 Test  tests/acceptance/SigninCest.php:firstEnable
                                                                                                                                                      
  [ConnectionException] Can't connect to WebDriver at http://localhost:4444. Make sure that ChromeDriver, GeckoDriver or Selenium Server is running. 
```

**To Reproduce**
Complete wp-browser installation and setup then connect to remote container housing wordpress installation and run command for acceptance test suite

**Additional context**
Feel free to ask questions and I'll do my best to answer

**Comment by kyletozer** [comment]
Thanks for the suggestions @lucatume. Here is an update.

Changing the `host` value in my `acceptance.suite.yml` file from `localhost` to `127.0.0.1` gives me the same output.

However, setting the `host` value to `webdriver` gives me different output:

```
Codeception PHP Testing Framework v4.1.22
Powered by PHPUnit 9.5.10 by Sebastian Bergmann and contributors.

Acceptance Tests (1) ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
E SigninCest: First enable (0.04s)
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


Time: 00:04.737, Memory: 20.00 MB

There was 1 error:

---------
1) SigninCest: First enable
 Test  tests/acceptance/SigninCest.php:firstEnable
                                                                                                                                                 
  [Facebook\WebDriver\Exception\UnknownErrorException] unknown error: net::ERR_CONNECTION_REFUSED
  (Session info: headless chrome=95.0.4638.54)  
                                                                                                                                                 

Scenario Steps:

 1. $I->loginAsAdmin() at tests/acceptance/SigninCest.php:13

#1  /var/www/html/vendor/php-webdriver/webdriver/lib/Exception/WebDriverException.php:139
#2  /var/www/html/vendor/php-webdriver/webdriver/lib/Remote/HttpCommandExecutor.php:372
#3  /var/www/html/vendor/php-webdriver/webdriver/lib/Remote/RemoteWebDriver.php:585
#4  /var/www/html/vendor/php-webdriver/webdriver/lib/Remote/RemoteWebDriver.php:246
#5  /var/www/html/vendor/lucatume/wp-browser/src/Codeception/Module/WPWebDriver.php:101
#6  /var/www/html/vendor/lucatume/wp-browser/src/Codeception/Module/WPWebDriver.php:63
#7  Codeception\Module\WPWebDriver->loginAsAdmin
#8  /var/www/html/tests/_support/_generated/AcceptanceTesterActions.php:4383
#9  /var/www/html/tests/acceptance/SigninCest.php:13
#10 SigninCest->firstEnable
Artifacts:

Png: /var/www/html/tests/_output/SigninCest.firstEnable.fail.png
Html: /var/www/html/tests/_output/SigninCest.firstEnable.fail.html

ERRORS!
Tests: 1, Assertions: 0, Errors: 1.
```

I had also changed the webdriver service in my `docker-compose.yml` to the following:
```
...
  webdriver:
    image: selenium/standalone-chrome:95.0
    restart: always
    # network_mode: host
    expose:
      - "4444"
...
``` 

I also tried using `netcat` inside of the `wp` container to test connection issues, here is the output from that:
```
nc -vz webdriver 4444
Connection to webdriver (172.18.0.5) 4444 port [tcp/*] succeeded!
```

**Comment by kyletozer** [comment]
@lucatume I was actually able to resolve this issue by making some changes to my `docker-compose.yml` file:
```
version: '3'

services:
  wp:
    build:
      context: .
      dockerfile: wp.Dockerfile
      args:
        WP_DB_HOST: &WP_DB_HOST 127.0.0.1
        WP_DB_NAME: &WP_DB_NAME wpdb
        WP_DB_USER: &WP_DB_USER wpuser
        WP_DB_PASS: &WP_DB_PASS secret
    environment:
      WP_DB_HOST: *WP_DB_HOST
      WP_DB_NAME: *WP_DB_NAME
      WP_DB_USER: *WP_DB_USER
      WP_DB_PASS: *WP_DB_PASS
      WP_DEV_SITEURL: http://localhost
      WP_DEBUG: 1
    network_mode: host
    # ports:
    #   - 80:80
    #   - 9001:9001
    #   - 3000:3000
    #   - 3001:3001
    volumes:
      - ./src/:/var/www/html:delegated

  db:
    build:
      context: .
      dockerfile: db.Dockerfile
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: *WP_DB_NAME
      MYSQL_USER: *WP_DB_USER
      MYSQL_PASSWORD: *WP_DB_PASS
    network_mode: host
    # ports:
    #   - 33060:3306
    volumes:
      - db_data:/var/lib/mysql

  webdriver:
    image: selenium/standalone-chrome:95.0
    restart: always
    network_mode: host
    # expose:
    #   - "4444"

volumes:
  db_data:
```

I blame Docker for this one, I'm no Docker networking expert. But the container seems to have a hard time connecting to the webdriver service through container name resolution. Changing all of my containers to network through the host seems to solve this.
