### ISSUE TITLE
[BUG] WPDb url replacement leads to corrupt database when the original url is found in serialized data

### ISSUE THREAD

**Issue by LucasDemea** [lucatume/wp-browser#540]
**Environment**
OS: Linux
PHP version: 7.4 
Installed Codeception version: 4.1.22
Installed wp-browser version: 3.0.12  
WordPress version: 5.8
Local development environment: Vagrant VM
WordPress structure and management: Bedrock

**Suite configuration file**
```yaml
# functional.suite.yml
 WPDb:
      dsn: "%DB_DSN%"
      user: "%DB_USER%"
      password: "%DB_PASSWORD%"
      dump: "tests/_data/dump.sql"
      populate: true
      cleanup: true
      waitlock: 10
      url: "%WP_URL%"
      urlReplacement: true
      originalUrl: "%ORIGINAL_URL%"
      tablePrefix: "%DB_PREFIX%"
```

**Describe the bug**
When the original url is found in the imported dump in a serialized form, the url gets replaced, but the serialized string length is not updated, leading to a corrupt database.
