### ISSUE TITLE
[BUG]: Bootstrap plugin throws errors in v3.0.20

### ISSUE THREAD

**Issue by jasonbahl** [lucatume/wp-browser#559]
**Environment**
OS: Linux
PHP version: 7.4, 7.3, 8.0
Installed Codeception version: 4.1.22
Installed wp-browser version: regression started in 3.0.20 (was working for 3.0.19 and prior) 
WordPress version: [e.g. 5.4]  
Local development environment: Docker (provided in the WPGraphQL repo)
WordPress structure and management: defualt

**Can you perform the test manually?**
> If applicable, try to walk through the test and execute it manually: can you do it using the browser?

In this case, the regression happens before tests are even run. The regression is preventing a bootstrap.php plugin file from being activated before tests run. 

But yes, I can perform what's supposed to be tested in a browser.

**Codeception configuration file**  
Paste, in a fenced YAML block, the content of your Codeception configuration file; remove any sensitive data!  

```yaml
// codeception.dist.yml

paths:
  tests: '%TESTS_DIR%'
  output: '%TESTS_OUTPUT%'
  data: '%TESTS_DATA%'
  support: '%TESTS_SUPPORT%'
  envs: '%TESTS_ENVS%'
params:
  - env
  - .env
actor_suffix: Tester
settings:
  colors: true
  memory_limit: 1024M
coverage:
  enabled: true
  remote: false
  c3_url: '%WP_URL%/wp-content/plugins/wp-graphql/wp-graphql.php'
  include:
    - src/*.php
  exclude:
    - wp-graphql.php
    - vendor/*
    - src/Admin/GraphiQL/app/*
    - src/Admin/GraphiQL/js/*
  show_only_summary: false
extensions:
  enabled:
    - Codeception\Extension\RunFailed
  commands:
    - Codeception\Command\GenerateWPUnit
    - Codeception\Command\GenerateWPRestApi
    - Codeception\Command\GenerateWPRestController
    - Codeception\Command\GenerateWPRestPostTypeController
    - Codeception\Command\GenerateWPAjax
    - Codeception\Command\GenerateWPCanonical
    - Codeception\Command\GenerateWPXMLRPC
modules:
  config:
    WPDb:
      dsn: 'mysql:host=%DB_HOST%;dbname=%DB_NAME%'
      user: '%DB_USER%'
      password: '%DB_PASSWORD%'
      populator: 'mysql -u $user -p$password -h $host $dbname < $dump'
      dump: 'tests/_data/dump.sql'
      populate: false
      cleanup: true
      waitlock: 0
      url: '%WP_URL%'
      urlReplacement: true
      tablePrefix: '%WP_TABLE_PREFIX%'
    WPBrowser:
      url: '%WP_URL%'
      wpRootFolder: '%WP_ROOT_FOLDER%'
      adminUsername: '%ADMIN_USERNAME%'
      adminPassword: '%ADMIN_PASSWORD%'
      adminPath: '/wp-admin'
      cookies: false
    REST:
      depends: WPBrowser
      url: '%WP_URL%'
    WPFilesystem:
      wpRootFolder: '%WP_ROOT_FOLDER%'
      plugins: '/wp-content/plugins'
      mu-plugins: '/wp-content/mu-plugins'
      themes: '/wp-content/themes'
      uploads: '/wp-content/uploads'
    WPLoader:
      wpRootFolder: '%WP_ROOT_FOLDER%'
      dbName: '%DB_NAME%'
      dbHost: '%DB_HOST%'
      dbUser: '%DB_USER%'
      dbPassword: '%DB_PASSWORD%'
      tablePrefix: '%WP_TABLE_PREFIX%'
      domain: '%WP_DOMAIN%'
      adminEmail: '%ADMIN_EMAIL%'
      title: 'Test'
      plugins:
        - wp-graphql/tests/_bootstrap/bootstrap.php # this is where the regression is happening
        - wp-graphql/wp-graphql.php
      activatePlugins:
        - wp-graphql/tests/_bootstrap/bootstrap.php # this is where the regression is happening
        - wp-graphql/wp-graphql.php
      configFile: 'tests/_data/config.php'

```

**Suite configuration file**
Paste, in a fenced YAML block, the content of the suite configuration file; remove any sensitive data!

```yaml
// tests/wpunit.suite.dist.yml

actor: WpunitTester
modules:
  enabled:
    - WPLoader
  disabled:
    - WPDb
    - WPBrowser
  config:
    WPDb:
      cleanup: false
    WPLoader:
      plugins:
        - wp-graphql/tests/_bootstrap/bootstrap.php # this is where the regression is happening
        - wp-graphql/wp-graphql.php
      activatePlugins:
        - wp-graphql/tests/_bootstrap/bootstrap.php # this is where the regression is happening
        - wp-graphql/wp-graphql.php
      configFile:
        - 'tests/_data/config.php'
```

**Describe the bug**
I have a "bootstrap.php" file which includes some functionality I want across the board. For example, it registers a custom post type and custom taxonomy and configures some other WordPress environment settings for testing. 

The contents of the file are: 

```php
<?php

// Disable updates to prevent WP from going into maintenance mode while tests run
add_filter( 'enable_maintenance_mode', '__return_false' );
add_filter( 'wp_auto_update_core', '__return_false' );
add_filter( 'auto_update_plugin', '__return_false' );
add_filter( 'auto_update_theme', '__return_false' );

/**
 * This registers custom Post Type and Taxomomy for use in query tests to make sure
 * APIs for Custom Taxonomies and Custom Post Types work as expected.
 */
add_action( 'init', function() {
	register_post_type(
		'bootstrap_cpt',
		[
			'show_in_graphql'     => true,
			'graphql_single_name' => 'bootstrapPost',
			'graphql_plural_name' => 'bootstrapPosts',
			'hierarchical'        => true,
			'taxonomies' => [ 'bootstrap_tax' ]
		]
	);
	register_taxonomy(
		'bootstrap_tax',
		[ 'bootstrap_cpt' ],
		[
			'show_in_graphql'     => true,
			'graphql_single_name' => 'bootstrapTerm',
			'graphql_plural_name' => 'bootstrapTerms',
			'hierarchical'        => true,
		]
	);
});
```

I have this file included as a plugin so that it's functionality is present for all test suites. You can see this in the yaml configs above.

In wp-browser 3.0.19 and earlier, there was no issues including this file. 

**Output**
In v3.0.20+ I now get the following output: 

```bash
Powered by PHPUnit 8.5.22 by Sebastian Bergmann and contributors.
[13-Jan-2022 18:27:02 UTC] Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(

In bootstrap.php line 148:
                                                                               
  Activating plugin [wp-graphql/tests/_bootstrap/bootstrap.php]...The plugin   
  does not have a valid header.                
```

Based on the error message, I thought I could simply add a valid plugin header to the bootstrap.php file. 

I added: 

```php
<?php
/**
 * Plugin Name: WPGraphQL Tests Bootstrap
 */
```

to the top of the bootstrap.php file, but the error was still output.

I decided to refactor my tests and move this functionality to the specific test suites that need it, instead of including it globally, so I'm currently unblocked by this, but other users might be affected. (see: https://github.com/wp-graphql/wp-graphql/pull/2215)

**To Reproduce**
- Include the above `bootstrap.php` as a plugin / activePlugin in a wpunit test suite
- try to tun tests
- see the output

**Expected behavior**
I expect tests to run just fine, like they were in v3.0.19 and prior. I would also expect adding a valid plugin header to the bootstrap.php file to fix the issue. Instead, I had to remove that file altogether.

**Screenshots**

![Screen Shot 2022-01-14 at 8 25 32 AM](https://user-images.githubusercontent.com/1260765/149540375-769999aa-b0a7-4f44-aa7a-3a592ed80819.png)

You can see this live in a failed Github Action test run, here: https://github.com/wp-graphql/wp-graphql/runs/4807579298?check_suite_focus=true#step:8:420

**Additional context**
This is also discussed a bit here: https://github.com/lucatume/wp-browser/pull/556#issuecomment-1012444359
