### ISSUE TITLE
[SETUP ISSUE] Can't access WP_Query class and other WordPress stuff in wpunit tests

### ISSUE THREAD

**Issue by charlesdeb** [lucatume/wp-browser#566]
**Environment**
OS: Ubuntu
PHP version: 7.3
Installed Codeception version: 4.1.22
Installed wp-browser version: 3.0.13
WordPress version: 5.9
Local development environment: PHP built-in server
WordPress structure and management: Spinup

**Did you use the `codecept init wpbrowser` command?**
Yep

**Did you take a look at Codeception and wp-browser documentation?**
Oh yes!

**Codeception configuration file**
If you were able to complete the setup then paste, in a fenced YAML block, the content of your Codeception configuration file; remove any sensitive data!

```yaml
paths:
    tests: tests
    output: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
actor_suffix: Tester
extensions:
    enabled:
        - Codeception\Extension\RunFailed
    commands:
        - Codeception\Command\GenerateWPUnit
        - Codeception\Command\GenerateWPRestApi
        - Codeception\Command\GenerateWPRestController
        - Codeception\Command\GenerateWPRestPostTypeController
        - Codeception\Command\GenerateWPAjax
        - Codeception\Command\GenerateWPCanonical
        - Codeception\Command\GenerateWPXMLRPC
params:
    - .env.testing
```

**Suite configuration file**
If you're encountering an issue with a specific suite, please provide its configuration file.

```yaml
actor: WpunitTester
modules:
  enabled:
    - WPDb
    - WPLoader
    - \Helper\Wpunit
    - MyTestHelper
  config:
    WPDb:
      dsn: '%TEST_DB_DSN%'
      user: '%TEST_DB_USER%'
      password: '%TEST_DB_PASSWORD%'
      dump: 'tests/_data/dump.sql'
      populate: true
      cleanup: false # required for WPLoader
      waitlock: 10
      url: '%TEST_SITE_WP_URL%'
      originalUrl: '%TEST_SITE_WP_URL%'
      urlReplacement: true #replace the hardcoded dump URL with the one above
      tablePrefix: '%TEST_SITE_TABLE_PREFIX%'
    WPLoader:
      wpRootFolder: '%WP_ROOT_FOLDER%'
      dbName: '%TEST_DB_NAME%'
      dbHost: '%TEST_DB_HOST%'
      dbUser: '%TEST_DB_USER%'
      dbPassword: '%TEST_DB_PASSWORD%'
      tablePrefix: '%TEST_TABLE_PREFIX%'
      domain: '%TEST_SITE_WP_DOMAIN%'
      adminEmail: '%TEST_SITE_ADMIN_EMAIL%'
      title: 'xxx some title'
      theme: sometheme
      pluginsFolder: '../content/plugins'
      plugins:
        [
          'client/some_plugin.php',
          'advanced-custom-fields-pro/acf.php',
          'auth0/WP_Auth0.php',
        ]
      activatePlugins:
        [
          'client/some_plugin.php',
          'advanced-custom-fields-pro/acf.php',
          'auth0/WP_Auth0.php',
        ]
```

**Describe the issue you're encountering**
According to the docs <https://wpbrowser.wptestkit.dev/levels-of-testing#wordpress-unit-tests> I would expect to be able to reference WordPress functions, classes and constants in my tests. But they don't seem to be registering in my setup

**Output**
Tail end of my test output looks like

```text
.
.
.
Wpunit Tests (4) ---------------------------------------------------------------------------------------
Modules: WPDb, WPLoader, \Helper\Wpunit, MyTestHelper
-------------------------------------------------------------------------------------------------------------
✔ GenrePickerTest: Constructor requires days (0.01s)
✔ GenrePickerTest: Constructor rejects bogus days (0.00s)
✔ GenrePickerTest: Constructor works (0.00s)
E GenrePickerTest: Gets all genres (0.00s)
-------------------------------------------------------------------------------------------------------------
Time: 00:02.958, Memory: 54.50 MB

There was 1 error:

---------
1) GenrePickerTest: Gets all genres
 Test  tests/wpunit/Myplugin/GenrePickerTest.php:testGetsAllGenres
                                                 
 [Error] Undefined constant 'WP_Query' 
                                                 
#1  /path/to/files/ClientX/code/site/tests/wpunit/Myplugin/GenrePickerTest.php:71

ERRORS!
Tests: 4, Assertions: 4, Errors: 1.
  [Db] Disconnected from default
```

The test in question looks like this:

```php
namespace MyPlugin\TvGuide;

require_once './public/content/plugins/xxx/public/class-xxx-scheduler-tv-guide-genre-picker.php';

use MyPlugin\TvGuide\GenrePicker;
use WP_Query;

class GenrePickerTest extends \Codeception\TestCase\WPTestCase {
.
.
.

	public function testGetsAllGenres() {
		$this->factory()->term->create_many(3, array('taxonomy' => 'genre'));

		$screening_dates = array('2020-10-10');
		$genre_picker    = new GenrePicker($screening_dates);

		$genres_query = $genre_picker->genres_query();

		$this->assertInstanceOf(\WP_Query, $genres_query());
	}
```

**To Reproduce**
As above really. If I use `WP_Query` instead of `\WP_Query` I get (the expected) warnings about unknown constants etc. I thought the whole point of Wpunit tests was that I _didn't_ have to do a bunch of includes for core WP functionality in my tests. Presumably my config is wrong somewhere...
