### ISSUE TITLE
[QUESTION] Activating/deactivating plugin via environments

### ISSUE THREAD

**Issue by grazianodev** [lucatume/wp-browser#572]
Hi, 

I have read [this post](https://theaveragedev.com/activating-plugins-in-wordpress-tests/) of yours on using environments to activate a plugin in a test, and I hope you can help with two questions that I have.

### QUESTION 1

After reading your post I have ended up with the following configuration, where I basically have a PLUGIN A activated by default, and a PLUGIN B only activated in the PLUGIN_B_ON environment: 

```
actor: IntegrationTester
modules:
   enabled:
      - WPLoader 

   config:        
      
      WPLoader:
        loadOnly: false
        multisite: false
        wpRootFolder: '%WP_ROOT_FOLDER%'
        dbName: '%INTEGRATION_TEST_DB_NAME%'
        dbHost: '%TEST_SITE_DB_HOST%'
        dbUser: '%TEST_SITE_DB_USER%'
        dbPassword: '%TEST_SITE_DB_PASSWORD%'
        isolatedInstall: true
        installationTableHandling: empty
        tablePrefix: '%TEST_SITE_TABLE_PREFIX%'
        domain: '%TEST_SITE_WP_DOMAIN%'
        adminEmail: '%TEST_SITE_ADMIN_EMAIL%'
        title: "Integration Tests"
        plugins: [
          "PLUGIN-A/PLUGIN-A.php"
        ]
        activatePlugins: [
          "PLUGIN-A/PLUGIN-A.php"
        ]

env: 
  PLUGIN_B_ON: 
    modules:    
      config: 
        WPLoader:
          plugins: 
            - "PLUGIN-B/PLUGIN-B.php"
          activatePlugins: 
            - "PLUGIN-B/PLUGIN-B.php"
```

Please consider the following tests with the above configuration in mind:
         
```
class CreateMemberTest {  

   public function testCantCreateMemberWhenPluginBIsNotActive() {

      $this->expectException( PluginNotActiveException::class );

      $Member = ( new CreateMember()->create();      

      // Assertions here

   }

   /**
    * @env PLUGIN_B_ON
    */

   public function testCreatesMemberSuccessfully() {
      // Test
   }

}

```
In the first test, I expect the CreateMember class to throw an exception when PLUGIN B is not active.

When I run `codecept run integration` (default), the first test is run and is successful (because plugin B is not active), while the second test doesn't run at all; when I run `codecept run integration --env PLUGIN_B_ON`, the second test runs and is successful, but the first test fails because PLUGIN B is active when PLUGIN_B_ON, so the CreateMember class does not throw an exception.

This all works as expected I believe, but then how do you suggest handling the first test so that it succeeds even when running the tests with `--env PLUGIN_B_ON`?

### QUESTION 2

Can you have a plugin activated by default, and deactivate it in a certain environment? 

I tried the following:

```
actor: IntegrationTester
modules:
   enabled:
      - WPLoader 

   config:        
      
      WPLoader:
        loadOnly: false
        multisite: false
        wpRootFolder: '%WP_ROOT_FOLDER%'
        dbName: '%INTEGRATION_TEST_DB_NAME%'
        dbHost: '%TEST_SITE_DB_HOST%'
        dbUser: '%TEST_SITE_DB_USER%'
        dbPassword: '%TEST_SITE_DB_PASSWORD%'
        isolatedInstall: true
        installationTableHandling: empty
        tablePrefix: '%TEST_SITE_TABLE_PREFIX%'
        domain: '%TEST_SITE_WP_DOMAIN%'
        adminEmail: '%TEST_SITE_ADMIN_EMAIL%'
        title: "Integration Tests"
        plugins: [
          "PLUGIN-A/PLUGIN-A.php",
          "PLUGIN-B/PLUGIN-B.php"
        ]
        activatePlugins: [
          "PLUGIN-A/PLUGIN-A.php",
          "PLUGIN-B/PLUGIN-B.php"
        ]

env: 
  PLUGIN_B_ON: 
    modules:    
      config: 
        WPLoader:
          plugins: [
            "PLUGIN-A/PLUGIN-A.php"
          ]
          activatePlugins: [
            "PLUGIN-A/PLUGIN-A.php"
          ]
```

This does not work, probably because Codeception does not override the values when merging...

Thank you for any help!
