### ISSUE TITLE
[SETUP ISSUE] Getting step 1 of WP setup process when running basic acceptance test.

### ISSUE THREAD

**Issue by w33zy** [lucatume/wp-browser#579]
**Environment**
OS: Windows
PHP version: 7.4.28
Installed Codeception version: 4.1.31
Installed wp-browser version: ^3.1
WordPress version: 6.0
Local development environment: Laragon
WordPress structure and management: default WP install

**Did you use the `codecept init wpbrowser` command?**
Yes

**Did you take a look at Codeception and wp-browser documentation?**
Yes

**Codeception configuration file**
If you were able to complete the setup then paste, in a fenced YAML block, the content of your Codeception configuration file; remove any sensitive data!

```yaml
paths:
    tests: tests
    output: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
actor_suffix: Tester
extensions:
    enabled:
        - Codeception\Extension\RunFailed
    commands:
        - Codeception\Command\GenerateWPUnit
        - Codeception\Command\GenerateWPRestApi
        - Codeception\Command\GenerateWPRestController
        - Codeception\Command\GenerateWPRestPostTypeController
        - Codeception\Command\GenerateWPAjax
        - Codeception\Command\GenerateWPCanonical
        - Codeception\Command\GenerateWPXMLRPC
params:
    - .env.testing
```

**Suite configuration file**
If you're encountering an issue with a specific suite, please provide its configuration file.

```yaml
actor: AcceptanceTester
modules:
    enabled:
        - WPDb
        - WPBrowser
        - \Helper\Acceptance
    config:
        WPDb:
            dsn: '%TEST_SITE_DB_DSN%'
            user: '%TEST_SITE_DB_USER%'
            password: '%TEST_SITE_DB_PASSWORD%'
            dump: 'tests/_data/dump.sql'
            #import the dump before the tests; this means the test site database will be repopulated before the tests.
            populate: true
            # re-import the dump between tests; this means the test site database will be repopulated between the tests.
            cleanup: true
            waitlock: 10
            url: '%TEST_SITE_WP_URL%'
            urlReplacement: true #replace the hardcoded dump URL with the one above
            tablePrefix: '%TEST_SITE_TABLE_PREFIX%'
        WPBrowser:
            url: '%TEST_SITE_WP_URL%'
            adminUsername: '%TEST_SITE_ADMIN_USERNAME%'
            adminPassword: '%TEST_SITE_ADMIN_PASSWORD%'
            adminPath: '%TEST_SITE_WP_ADMIN_PATH%'
            headers:
                X_TEST_REQUEST: 1
                X_WPBROWSER_REQUEST: 1
```

**Describe the issue you're encountering**
On running a basic 2 step acceptance test of "I am on page `/hello-world`, I see an H1 with 'Hello World!'..." the test fails. When I open the HTML file generated by the test, instead of seeing the default 1st post, I see the language selection step of the WordPress setup process.
