### ISSUE TITLE
[BUG] WpDb module causes request timeout when letCron is not set to true

### ISSUE THREAD

**Issue by egamipeaks** [lucatume/wp-browser#584]
**Environment**
MacOs 10.15.7
PHP version: 8.0.20
Installed Codeception version: 4.1.31
Installed wp-browser version: 3.1.6
WordPress version: 5.8.4
Local development environment: Vagrant (Trellis)
WordPress structure and management: Bedrock

**Can you perform the test manually?**
Yes

**Codeception configuration file**  

```yaml
paths:
    tests: tests
    output: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
actor_suffix: Tester
extensions:
    enabled:
        - Codeception\Extension\RunFailed
    commands:
        - Codeception\Command\GenerateWPUnit
        - Codeception\Command\GenerateWPRestApi
        - Codeception\Command\GenerateWPRestController
        - Codeception\Command\GenerateWPRestPostTypeController
        - Codeception\Command\GenerateWPAjax
        - Codeception\Command\GenerateWPCanonical
        - Codeception\Command\GenerateWPXMLRPC
params:
    - .env.php/testing.env.php
```

**Suite configuration file**

```yaml
actor: AcceptanceTester
modules:
    enabled:
        - WpDb
        - WpBrowser
        - \Helper\Acceptance
    config:
        WpDb:
            dsn: '%TEST_SITE_DB_DSN%'
            user: '%TEST_SITE_DB_USER%'
            password: '%TEST_SITE_DB_PASSWORD%'
            dump: 'tests/_data/dump.sql'
            #import the dump before the tests; this means the test site database will be repopulated before the tests.
            populate: true
            # re-import the dump between tests; this means the test site database will be repopulated between the tests.
            cleanup: true
            waitlock: 0
            url: '%TEST_SITE_WP_URL%'
            # urlReplacement: true #replace the hardcoded dump URL with the one above
            tablePrefix: '%TEST_SITE_TABLE_PREFIX%'
        WpBrowser:
            url: '%TEST_SITE_WP_URL%'
            adminUsername: '%TEST_SITE_ADMIN_USERNAME%'
            adminPassword: '%TEST_SITE_ADMIN_PASSWORD%'
            adminPath: '%TEST_SITE_WP_ADMIN_PATH%'
            capabilities:
                acceptInsecureCerts: true
            headers:
                # X_TEST_REQUEST: 1
                X_WPBROWSER_REQUEST: 1
```

**Describe the bug**
When `letCron` is not set to `true` in the WpDb module, acceptance tests time out. I have tried commenting out the line in the method `prepareDb`: `$this->haveTransientInDatabase('doing_cron', strtotime('+9 minutes'));`

When this line is not present, the test runs fine. I have even moved that line to my test itself, and the test still runs fine. When that line is present, however, the database seems to be locked, as I can see wp_options inserts taking 20+ seconds.

I have also tested by switching to the `Db` module instead of `WpDb`, and the tests run fine that way as well.

**Output**
`[GuzzleHttp\Exception\ConnectException] cURL error 28: Operation timed out after 30000 milliseconds with 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)`

**To Reproduce**
Run acceptance test

**Expected behavior**
The test passes without the request timing out.
