### ISSUE TITLE
[BUG] waitForText() not working

### ISSUE THREAD

**Issue by brianhogg** [lucatume/wp-browser#601]
**Environment**
OS: Mac
PHP version: 8.0.14
Installed Codeception version: 4.2.2
Installed wp-browser version: 3.1.6
WordPress version: 6.1.1
Local development environment: Valet 
WordPress structure and management: default

**Can you perform the test manually?**
If applicable, try to walk through the test and execute it manually: can you do it using the browser? Yes

**Codeception configuration file**  
Paste, in a fenced YAML block, the content of your Codeception configuration file; remove any sensitive data!  

```yaml
coverage:
    enabled: true
paths:
    tests: tests
    output: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
actor_suffix: Tester
extensions:
    enabled:
        - Codeception\Extension\RunFailed
    commands:
        - Codeception\Command\GenerateWPUnit
        - Codeception\Command\GenerateWPRestApi
        - Codeception\Command\GenerateWPRestController
        - Codeception\Command\GenerateWPRestPostTypeController
        - Codeception\Command\GenerateWPAjax
        - Codeception\Command\GenerateWPCanonical
        - Codeception\Command\GenerateWPXMLRPC
params:
    - .env.testing
```

**Suite configuration file**
Paste, in a fenced YAML block, the content of the suite configuration file; remove any sensitive data!

```yaml
# Codeception Test Suite Configuration
#
# Suite for acceptance tests.
# Perform tests in browser using the WPWebDriver or WPBrowser.
# Use WPDb to set up your initial database fixture.
# If you need both WPWebDriver and WPBrowser tests - create a separate suite.

actor: AcceptanceTester
extensions:
    enabled:
        - Codeception\Extension\RunProcess:
            - chromedriver --url-base=/wd/hub
        - Codeception\Extension\RunFailed
modules:
    enabled:
        - WPDb
        - WPLoader
        - \Helper\ShortcodeWebDriver
        - \Helper\Acceptance
        - \Helper\TribeDb
        - \Helper\RecurringEvents
    config:
        # Doing this just to bootstrap WordPress, so we can use tribe_events ORM to create events
        WPLoader:
            loadOnly: true
            wpRootFolder: "%WP_ROOT_FOLDER%"
            dbName: "%TEST_DB_NAME%"
            dbHost: "%TEST_DB_HOST%"
            dbUser: "%TEST_DB_USER%"
            dbPassword: "%TEST_DB_PASSWORD%"
            tablePrefix: "%TEST_TABLE_PREFIX%"
            domain: "%TEST_SITE_WP_DOMAIN%"
            adminEmail: "%TEST_SITE_ADMIN_EMAIL%"
            title: "shortcode test"
            plugins: ['the-events-calendar/the-events-calendar.php', 'the-events-calendar-shortcode-pro/the-events-calendar-shortcode-pro.php', 'events-calendar-pro/events-calendar-pro.php']
            activatePlugins: ['the-events-calendar/the-events-calendar.php', 'the-events-calendar-shortcode-pro/the-events-calendar-shortcode-pro.php', 'events-calendar-pro/events-calendar-pro.php']
        WPDb:
            dsn: 'mysql:host=%TEST_SITE_DB_HOST%;dbname=%TEST_SITE_DB_NAME%;port=%DB_PORT%'
            user: '%TEST_SITE_DB_USER%'
            password: '%TEST_SITE_DB_PASSWORD%'
            dump: 'tests/_data/dump.sql'
            #import the dump before the tests; this means the test site database will be repopulated before the tests.
            populate: true
            # re-import the dump between tests; this means the test site database will be repopulated between the tests.
            cleanup: true
            waitlock: 10
            url: '%TEST_SITE_WP_URL%'
            urlReplacement: true #replace the hardcoded dump URL with the one above
            tablePrefix: '%TEST_SITE_TABLE_PREFIX%'
        \Helper\ShortcodeWebDriver:
            url: '%TEST_SITE_WP_URL%'
            adminUsername: '%TEST_SITE_ADMIN_USERNAME%'
            adminPassword: '%TEST_SITE_ADMIN_PASSWORD%'
            adminPath: '%TEST_SITE_WP_ADMIN_PATH%'
            browser: chrome
            host: localhost
            port: 9515
            window_size: maximize #disabled for Chrome driver
            capabilities:
                chromeOptions:
                    args: [ "--user-agent=wp-browser",  "--ignore-certificate-errors" ]
```

**Describe the bug**
Attempting to use `$I->waitForText()` either with or without a selector specified generates the error "Unrecognized selector"

**Output**
Unrecognized selector

**To Reproduce**
Create a test that generates a page, navigates to it, then try `$I->waitForText()`

**Expected behavior**
Test waits for the given text to be seen

**Additional context**
`waitForElement` `waitForElementVisible` etc works no problem, which is odd :)
