### ISSUE TITLE
[BUG] Integration tests seems to have different contexts to WP db changes and test DB changes

### ISSUE THREAD

**Issue by andergmartins** [lucatume/wp-browser#611]
**Environment**
OS: Mac
PHP version: 8.0
Installed Codeception version: 4.2.2
Installed wp-browser version: 3.1.8
WordPress version: 6.2
Local development environment: Docker
WordPress structure and management: default

**Codeception configuration file**  

```yaml
paths:
    tests: tests/codeception
    output: tests/codeception/_output
    data: tests/codeception/_data
    support: tests/codeception/_support
    envs: tests/codeception/_envs
actor_suffix: Tester
extensions:
    enabled:
        - Codeception\Extension\RunFailed
    commands:
        - Codeception\Command\GenerateWPUnit
        - Codeception\Command\GenerateWPRestApi
        - Codeception\Command\GenerateWPRestController
        - Codeception\Command\GenerateWPRestPostTypeController
        - Codeception\Command\GenerateWPAjax
        - Codeception\Command\GenerateWPCanonical
        - Codeception\Command\GenerateWPXMLRPC
settings:
    lint: true
    report_useless_tests: true
    colors: true
```

**Suite configuration file**

```yaml
actor: WpunitTester
modules:
    enabled:
        - \Helper\Wpunit
        - WPDb
        - WPLoader
        - Sequence
    config:
        WPDb:
            dump: "tests/codeception/_data/sql/dump.sql"
            populate: true
            cleanup: false
            urlReplacement: true
            letAdminEmailVerification: false
            letCron: false
        WPLoader:
            loadOnly: false
            isolatedInstall: false
            tablePrefix: "wp_"
            installationTableHandling: drop
            plugins:
                - post-expirator/post-expirator.php
                - pre-tests/pre-tests.php
                - ray-future/ray-future.php
            activatePlugins:
                - post-expirator/post-expirator.php
                - pre-tests/pre-tests.php
                - ray-future/ray-future.php
bootstrap: bootstrap.php
```

**Codeception env file**

```yaml
modules:
    config:
        WPDb:
            dsn: "mysql:host=host.docker.internal;port=59351;dbname=wordpress;charset=UTF8"
            user: "root"
            password: "wordpress"
            url: "http:\/\/host.docker.internal:59354"
            originalUrl: "https://tests.local"
        WPLoader:
            wpRootFolder: "/project/tests/docker/volumes/php8.0-wordpress"
            dbName: "wordpress"
            dbHost: "host.docker.internal:59351"
            dbUser: "root"
            dbPassword: "wordpress"
            domain: "host.docker.internal:59354"
            title: "Tests on php8.0"
        WPWebDriver:
            url: "http:\/\/host.docker.internal:59354"
            adminUsername: "admin"
            adminPassword: "admin"
```

**Describe the bug**

I have the following test:

```php
<?php
namespace Modules\Expirator\Migrations;

class V30000ActionArgsSchemaTest extends \Codeception\TestCase\WPTestCase
{
    /**
     * @var \WpunitTester
     */
    protected $tester;

    public function setUp(): void
    {
        parent::setUp();
        $this->prepareSiteFormigrationTest();
    }

    public function tearDown(): void
    {
        parent::tearDown();
    }

    protected function prepareSiteFormigrationTest()
    {
        $this->tester->haveOptionInDatabase('postexpiratorVersion', '2.9.2');
    }

    // Tests
    public function testVersion()
    {
        update_option('postexpiratorVersion', '3.0.0');
        $version = get_option('postexpiratorVersion');

        $this->assertEquals('3.0.0', $version);
        $this->tester->dontSeeOptionInDatabase('postexpiratorVersion', '2.9.2');
    }
}
```

I see inconsistency between the context of `update_option` and the `dontSeeOptionInDatabase`. That is just a simple test, but I see the same when testing a WordPress plugin code.

The database is changed when `update_option` runs, or when I'm running MySQL queries by hand in the test. But Since `loadOnly` is false, it is running in a transaction. Ok, but `dontSeeOptionInDatabase` and other helper functions don't run on the same transaction. 

I tried `loadOnly` as true, but then the WP is not bootstrapped correctly, for example the global `$wpdb` var is null.

**Output**

The output says:

```bash
1) V30000ActionArgsSchemaTest: Version
 Test  tests/codeception/wpunit/Modules/Expirator/Migrations/V30000ActionArgsSchemaTest.php:testVersion
Unexpectedly found matching records for criteria {"option_name":"postexpiratorVersion","option_value":"2.9.2"} in table wp_options
Failed asserting that 1 is less than 1.
#1  /project/vendor/lucatume/wp-browser/src/Codeception/Module/WPDb.php:327
#2  Codeception\Module\WPDb->dontSeeOptionInDatabase
#3  /project/tests/codeception/_support/_generated/WpunitTesterActions.php:64
#4  /project/tests/codeception/wpunit/Modules/Expirator/Migrations/V30000ActionArgsSchemaTest.php:32
#5  /project/vendor/bin/codecept:120
```
That means the `update_option` changes are not visible by tester methods like `seeOptionInDatabase` or `dontSeeOptionInDatabase`.

**Expected behavior**

I understand the test runs on a transaction, but I think both WP and the tester should run on the same transaction.
