### ISSUE TITLE
[BUG] _switchTheme only passes one param, must pass two

### ISSUE THREAD

**Issue by fschroiff** [lucatume/wp-browser#620]
**Environment**
OS: Mac 
PHP version: 7.4.30 
Installed Codeception version: v4.1.22
Installed wp-browser version:  2.6.17 / 3.1.9
WordPress version: 6.2.2 
Local development environment: Local by Flywheel
WordPress structure and management: default  

**Can you perform the test manually?**
Test hangs on `Activating plugin [woocommerce/woocommerce.php]`. Can activate in browser.

**Codeception configuration file**  
```yaml
paths:
    tests: tests
    output: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
actor_suffix: Tester
extensions:
    enabled:
        - Codeception\Extension\RunFailed
    commands:
        - Codeception\Command\GenerateWPUnit
        - Codeception\Command\GenerateWPRestApi
        - Codeception\Command\GenerateWPRestController
        - Codeception\Command\GenerateWPRestPostTypeController
        - Codeception\Command\GenerateWPAjax
        - Codeception\Command\GenerateWPCanonical
        - Codeception\Command\GenerateWPXMLRPC
params:
    - .env.testing.local
coverage:
    enabled: true
    include:
        - app/*
```


**Suite configuration file**
```yaml
# Codeception Test Suite Configuration
#
# Suite for unit or integration tests that require WordPress functions and classes.

actor: WpunitTester
error_level: E_ALL & ~E_STRICT & ~E_DEPRECATED & ~E_NOTICE
bootstrap: bootstrap.php
modules:
    enabled:
        - WPLoader
        - \Helper\Wpunit
    config:
        WPLoader:
            wpDebug: false
            multisite: false
            configFile: "wp-content/themes/abc/test-setup.php"
            wpRootFolder: "%WP_ROOT_FOLDER%"
            dbName: "%TEST_DB_NAME%"
            dbHost: "%TEST_DB_HOST%"
            dbUser: "%TEST_DB_USER%"
            dbPassword: "%TEST_DB_PASSWORD%"
            tablePrefix: "%TEST_TABLE_PREFIX%"
            domain: "%TEST_SITE_WP_DOMAIN%"
            adminEmail: "%TEST_SITE_ADMIN_EMAIL%"
            title: "abc"
            theme: abc
            plugins:
              - 'woocommerce/woocommerce.php'
            activatePlugins:
              - 'woocommerce/woocommerce.php'
```

**Describe the bug**
Test hangs on `Activating plugin [woocommerce/woocommerce.php]`. 

```
  [ArgumentCountError]                                                                                                                                        
  Too few arguments to function Automattic\WooCommerce\Blocks\BlockTemplatesController::check_should_use_blockified_product_grid_templates(), 1 passed in /V  
  olumes/Work/flywheel/navingo/app/public/wp-includes/class-wp-hook.php on line 308 and exactly 2 expected   
```

From stack trace I can pinpoint the issue to this call https://github.com/lucatume/wp-browser/blob/38e15758d2960d31ce6347bff843574f147d2630/src/Codeception/Module/WPLoader.php#L805

`$this->wp->do_action('after_switch_theme', $stylesheet);`

https://developer.wordpress.org/reference/hooks/after_switch_theme/

The action takes two args: `do_action( 'after_switch_theme', string $old_name, WP_Theme $old_theme )`.

**Output**
```
In BlockTemplatesController.php line 166:
                                                                                                                                                              
  [ArgumentCountError]                                                                                                                                        
  Too few arguments to function Automattic\WooCommerce\Blocks\BlockTemplatesController::check_should_use_blockified_product_grid_templates(), 1 passed in /V  
  olumes/Work/flywheel/navingo/app/public/wp-includes/class-wp-hook.php on line 308 and exactly 2 expected                                                    
                                                                                                                                                              

Exception trace:
  at /app/public/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/BlockTemplatesController.php:166
 Automattic\WooCommerce\Blocks\BlockTemplatesController->check_should_use_blockified_product_grid_templates() at /app/public/wp-includes/class-wp-hook.php:308
 WP_Hook->apply_filters() at /app/public/wp-includes/class-wp-hook.php:332
 WP_Hook->do_action() at /app/public/wp-includes/plugin.php:517
 do_action() at /app/public/wp-content/vendor/lucatume/wp-browser/src/tad/WPBrowser/Adapters/WP.php:152
 tad\WPBrowser\Adapters\WP->do_action() at /app/public/wp-content/vendor/lucatume/wp-browser/src/Codeception/Module/WPLoader.php:805
 Codeception\Module\WPLoader->_switchTheme() at /app/public/wp-content/vendor/lucatume/wp-browser/src/Codeception/Module/WPLoader.php:712
 Codeception\Module\WPLoader->installAndBootstrapInstallation() at /app/public/wp-content/vendor/lucatume/wp-browser/src/Codeception/Module/WPLoader.php:479
 Codeception\Module\WPLoader->_loadWordpress() at /app/public/wp-content/vendor/lucatume/wp-browser/src/Codeception/Module/WPLoader.php:368
 Codeception\Module\WPLoader->initialize() at /app/public/wp-content/vendor/lucatume/wp-browser/src/Codeception/Module/WPLoader.php:329
 Codeception\Module\WPLoader->_initialize() at /app/public/wp-content/vendor/codeception/codeception/src/Codeception/SuiteManager.php:83
 Codeception\SuiteManager->initialize() at /app/public/wp-content/vendor/codeception/codeception/src/Codeception/Codecept.php:204
 Codeception\Codecept->runSuite() at /app/public/wp-content/vendor/codeception/codeception/src/Codeception/Codecept.php:162
 Codeception\Codecept->run() at /app/public/wp-content/vendor/codeception/codeception/src/Codeception/Command/Run.php:532
 Codeception\Command\Run->runSuites() at /app/public/wp-content/vendor/codeception/codeception/src/Codeception/Command/Run.php:407
 Codeception\Command\Run->execute() at /app/public/wp-content/vendor/symfony/console/Command/Command.php:298
 Symfony\Component\Console\Command\Command->run() at /app/public/wp-content/vendor/symfony/console/Application.php:1040
 Symfony\Component\Console\Application->doRunCommand() at /app/public/wp-content/vendor/symfony/console/Application.php:301
 Symfony\Component\Console\Application->doRun() at /app/public/wp-content/vendor/symfony/console/Application.php:171
 Symfony\Component\Console\Application->run() at /app/public/wp-content/vendor/codeception/codeception/src/Codeception/Application.php:117
 Codeception\Application->run() at /app/public/wp-content/vendor/codeception/codeception/app.php:46
 {closure}() at /app/public/wp-content/vendor/codeception/codeception/app.php:47
 require() at /app/public/wp-content/vendor/codeception/codeception/codecept:7
```

**To Reproduce**
Run the test with WooCommerce 7.8.0: works! 
Run the test with WooCommerce 7.9.0: fails!

**Expected behavior**
Test should run correctly with WooCommerce 7.9.0
