### ISSUE TITLE
amOnAdminAjaxPage isn't working as expected !

### ISSUE THREAD

**Issue by Ok9xNirab** [lucatume/wp-browser#625]
```php
<?php

class CartCest
{
    public function ajaxTest(AcceptanceTester $I)
    {
        $I->amOnAdminAjaxPage(['action' => 'pathao_get_zones123', 'data' => ['city' => 23, 'type' => 'billing'], 'nonce' => '8475']);
    }
}
```

Here `pathao_get_zones123` is a invalid action. But i see **success** on terminal.

**Comment by lucatume** [comment]
@Ok9xNirab I need more information about your setup, Codeception and wp-browser versions as required in the issue templates.
What HTTP code do you get when visiting the page manually, from the browser?

**Comment by Ok9xNirab** [comment]
### Environment
OS: **Mac**
PHP version: **8.2**
Installed Codeception version: **4.2.2**
Installed wp-browser version: **dev-master**
WordPress version: **6.2**
Local development environment: **Valet**
WordPress structure and management: **default**

### Can you perform the test manually?
> Yes.

![Screenshot 2023-07-25 at 1 38 06 AM](https://github.com/lucatume/wp-browser/assets/40653908/0b13b487-6866-41e1-b06d-b85e92b3be3a)


### Codeception configuration file

```yaml
paths:
    tests: tests
    output: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
actor_suffix: Tester
extensions:
    enabled:
        - Codeception\Extension\RunFailed
    commands:
        - Codeception\Command\GenerateWPUnit
        - Codeception\Command\GenerateWPRestApi
        - Codeception\Command\GenerateWPRestController
        - Codeception\Command\GenerateWPRestPostTypeController
        - Codeception\Command\GenerateWPAjax
        - Codeception\Command\GenerateWPCanonical
        - Codeception\Command\GenerateWPXMLRPC
params:
    - .env.testing

```

### Suite configuration file

```yaml
# Codeception Test Suite Configuration
#
# Suite for acceptance tests.
# Perform tests in browser using the WPWebDriver or WPBrowser.
# Use WPDb to set up your initial database fixture.
# If you need both WPWebDriver and WPBrowser tests - create a separate suite.

actor: AcceptanceTester
modules:
    enabled:
        - WPDb
        - WPBrowser
        - \Helper\Acceptance
    config:
        WPDb:
            dsn: '%TEST_SITE_DB_DSN%'
            user: '%TEST_SITE_DB_USER%'
            password: '%TEST_SITE_DB_PASSWORD%'
            dump: 'tests/_data/dump.sql'
            #import the dump before the tests; this means the test site database will be repopulated before the tests.
            populate: true
            # re-import the dump between tests; this means the test site database will be repopulated between the tests.
            cleanup: true
            waitlock: 10
            url: '%TEST_SITE_WP_URL%'
            urlReplacement: true #replace the hardcoded dump URL with the one above
            tablePrefix: '%TEST_SITE_TABLE_PREFIX%'
        WPBrowser:
            url: '%TEST_SITE_WP_URL%'
            adminUsername: '%TEST_SITE_ADMIN_USERNAME%'
            adminPassword: '%TEST_SITE_ADMIN_PASSWORD%'
            adminPath: '%TEST_SITE_WP_ADMIN_PATH%'
            headers:
                X_TEST_REQUEST: 1
                X_WPBROWSER_REQUEST: 1
```
