### ISSUE TITLE
[SETUP ISSUE] Suite cannot be identified from the debug backtrace.

### ISSUE THREAD

**Issue by AlexShaposhnykov** [lucatume/wp-browser#626]
**Environment**
OS: Mac, m1
PHP version: 8.0
Installed Codeception version: 4.2
Installed wp-browser version: 3.1
WordPress version: 6.2
Local development environment: wp-env (docker)
WordPress structure and management: default

**Did you use the `codecept init wpbrowser` command?**
Yes

**Did you take a look at Codeception and wp-browser documentation?**
Yes

**Codeception configuration file**
```yaml
paths:
  tests: tests
  output: tests/_output
  data: tests/_data
  support: tests/_support
  envs: tests/_envs
actor_suffix: Tester
extensions:
  enabled:
    - Codeception\Extension\RunFailed
  commands:
    - Codeception\Command\GenerateWPUnit
    - Codeception\Command\GenerateWPRestApi
    - Codeception\Command\GenerateWPRestController
    - Codeception\Command\GenerateWPRestPostTypeController
    - Codeception\Command\GenerateWPAjax
    - Codeception\Command\GenerateWPCanonical
    - Codeception\Command\GenerateWPXMLRPC
params:
  - .env.testing
```

**Suite configuration file**
```yaml
actor: FunctionalTester
modules:
  enabled:
    - WPDb
    - WPBrowser
    # - WPFilesystem
    - Asserts
    - \Helper\Functional
  config:
    WPDb:
      dsn: '%TEST_SITE_DB_DSN%'
      user: '%TEST_SITE_DB_USER%'
      password: '%TEST_SITE_DB_PASSWORD%'
      dump: 'tests/_data/dump.sql'
      populate: true
      cleanup: true
      waitlock: 10
      url: '%TEST_SITE_WP_URL%'
      urlReplacement: true
      tablePrefix: '%TEST_SITE_TABLE_PREFIX%'
    WPBrowser:
      url: '%TEST_SITE_WP_URL%'
      adminUsername: '%TEST_SITE_ADMIN_USERNAME%'
      adminPassword: '%TEST_SITE_ADMIN_PASSWORD%'
      adminPath: '%TEST_SITE_WP_ADMIN_PATH%'
      headers:
        X_TEST_REQUEST: 1
        X_WPBROWSER_REQUEST: 1

    WPFilesystem:
      wpRootFolder: '%WP_ROOT_FOLDER%'
      plugins: '/wp-content/plugins'
      mu-plugins: '/wp-content/mu-plugins'
      themes: '/wp-content/themes'
      uploads: '/wp-content/uploads'
```

**Describe the issue you're encountering**
I'm trying to execute a basic test just to see if my setup is correct. When I'm running the "vendor/bin/codecept run functional --debug" command, I'm getting this issue "Suite cannot be identified from the debug backtrace." 

**To Reproduce**
Create a new test file using one of the examples from the documentation. For example, "vendor/bin/codecept generate:wpunit suite SomeClass". Try to execute tests in that file using the "vendor/bin/codecept run unit" command

**Screenshots**
<img width="627" alt="image" src="https://github.com/lucatume/wp-browser/assets/38754314/bcefb685-43ac-4aaf-86cb-e4a074238e71">
<img width="349" alt="image" src="https://github.com/lucatume/wp-browser/assets/38754314/e768b3e4-8653-4a93-8b70-bef796030468">
<img width="1098" alt="image" src="https://github.com/lucatume/wp-browser/assets/38754314/b598fdcd-f19d-483d-87aa-c91e524107ef">
<img width="1103" alt="image" src="https://github.com/lucatume/wp-browser/assets/38754314/b59e0198-b83b-4a66-8db3-69cd3a71dd18">

**Additional context**
My yaml configurations are located here <rootDir>/tests/[acceptance|unit|functional|wpunit].suite.yaml, however it seems like when the identifySuiteFromTrace() runs, it only looks through my "vendor" folder, not the actual root folder of my plugin where the "tests" folder with yaml configurations is located.

If I have no tests inside a suite, and I try to run the "vendor/bin/codecept run functional" then everything is working fine.
<img width="1101" alt="image" src="https://github.com/lucatume/wp-browser/assets/38754314/198c09ad-7059-4651-8a00-d83c1a3b56b3">
