### ISSUE TITLE
[SETUP ISSUE] wp-browser v4 wp-config file parsing issue

### ISSUE THREAD

**Issue by snandos** [lucatume/wp-browser#627]
**Environment**
OS: Docker php:8.1-apache
PHP version: 8.1
Installed Codeception version: 5.0.11
Installed wp-browser version: v4.x-dev 3b12879
WordPress version: 6.3
Local development environment: Docker
WordPress structure and management: Custom Docker-Image for Development

**Did you use the `codecept init wpbrowser` command?**
yes

**Did you take a look at Codeception and wp-browser documentation?**
yes

**Codeception configuration file**
```yaml
actor: Tester
paths:
  tests: tests
  log: tests/output
  data: tests/data
  support: tests/support
  envs: tests/envs
  output: tests/output
  
params:
  - tests/.test.env    
  - CODECEPTION_ENV: 'true'
```

**Suite configuration file**

```yaml
actor: UnitTester
bootstrap: _bootstrap.php
modules:
    enabled:
        - lucatume\WPBrowser\Module\WPLoader
    config:
        lucatume\WPBrowser\Module\WPLoader:
           loadOnly: true
           wpRootFolder: "%WORDPRESS_ROOT_DIR%" 
           dbUrl: "%WORDPRESS_DB_URL%"
           wpDebug: true
           tablePrefix: "%TEST_TABLE_PREFIX%"
           domain: "%WORDPRESS_DOMAIN%"
           adminEmail: "admin@%WORDPRESS_DOMAIN%"
           title: "Integration Tests"
           plugins: [""]
           theme: "my-theme" 
```

**Describe the issue you're encountering**
I want to unit test my WordPress setup with codeception. I'm already doing acceptance tests successfully (without wp-browser), so I would love to use codeception for unittests as well.
All my code resides in my custom theme. For development I use a custom written Dockerfile derived from the official WordPress-Dockerfile. Codeception is being run inside this docker container.
Because of the docker setup, I need to use a wp-config file which is not default. For example I use a `getenv_docker` function to retrieve environment variables either from a .env file or from environment variables itself. Like `define( 'DB_NAME', getenv_docker('WORDPRESS_DB_NAME', 'wordpress') );`.

Because of this, wp-browser won't do anything since it is not able to parse my wp-config:
```
In WPConfigFile.php line 132:                                           
  Could not parse the wp-config.php file:                                             

In WPConfigFile.php line 118:                                                       
  [lucatume\WPBrowser\Process\ProcessException (255)]  
                                                       
In SerializableClosure.php line 155:                                                                 
  Uncaught Exception: Serialization of 'Closure' is not allowed 
```

When uncommenting all these "dynamic" defines, at least it can parse the file. But of course won't be able to read the needed configs:
```
In WPConfigFile.php line 164:                                 
  Constant DB_NAME not defined.  
```

My question is: why does it need to parse and read an existing `wp-config.php` file in the first place, when I define those options in the codeception scenario? Am I missing something in the config? The `loadOnly` option is still confusing for me.

If the parsing of a wp-config is inevitable, do you have an idea how I can get around this issue while still keeping my wp-config in place? Like specifying a different wp-config file.

Thank you for your awesome work!
