### ISSUE TITLE
[BUG] Invalid Chrome binary: not executable or not existing on init command

### ISSUE THREAD

**Issue by dingo-d** [lucatume/wp-browser#638]
**Environment**
OS: MacOS Ventura 13.5.2 (22G91)
PHP version: 8.1.23
Installed Codeception version: 5.0.11
Installed wp-browser version:  4.0.3
WordPress version: 6.3.1
Local development environment: Docker
WordPress structure and management: default

**Can you perform the test manually?**
No

**Codeception configuration file**  
N/A

**Describe the bug**
When initializing wbrowser inside the docker container I get the following output:

```bash
Initializing wp-browser for a plugin project.
You can quit this process at any time with CTRL+C.
 Created tests directory and sub-directories.
You can use a portable configuration based on PHP built-in server, Chromedriver and SQLite.
? Do you want to use this configuration? (y/n) y
 Installing WordPress in tests/_wordpress ...
 Plugin activated.
 Created database dump in tests/Support/Data/dump.sql.
 Installing Chromedriver ...
 Invalid Chrome binary: not executable or not existing.
 Setup failed, check the error message above and try again.
```

**To Reproduce**
Using docker with the following compose file:

```yaml
version: "3.9"

services:
  wordpress:
    platform: linux/amd64
    image: wordpress:6.3-php8.1-apache
    container_name: docker-wp
    working_dir: /var/www/html
    tty: true
    restart: always
    depends_on:
      - database
    volumes:
      - ./:/var/www/html
    environment:
      DB_PORT: 33068
      DB_HOST: wordpress-db
      DB_NAME: docker-wp
      DB_USER: wp
      DB_PASSWORD: wp
      DB_PREFIX: wp
      AUTH_KEY: ";zA]fZH-mQNL~?)3KBm4]>P-U+f@Cs*Pq#xdt7QC!CSPT`*`+>Q1iYl-`-kp2PfV"
      SECURE_AUTH_KEY: "@ON3 [Jl+{PY|~bUrCoudir=uj-C=]ZnDd-hk.#cAevd2<B]f[=Lq,-a<Q-%p+=3"
      LOGGED_IN_KEY: "([<=!eb*STU!2#qUcy!D5adyr;(t28Ea}y)81*-+,-V{C;[D5Pc|eQ}-m>Z]IR8"
      NONCE_KEY: "(smPecdFUF1Q[&~B=90|7c&Z7>)4c.UCG*-+EDX!u%eu?+|I,zf#.q&+,2/hG[f"
      AUTH_SALT: "~&7I2:*jQ)1^PLra)5r+`9/uLYm.]Jt@ON)n<?@Z4e9oXuW8y.64VQ-Q*=i <4;^"
      SECURE_AUTH_SALT: "=&+5]|;>:oaCg]xTU5lk4yTZ?}=./lzm7?.bv||qXCU.!Hk4([5Yqh`}ovp++r9+"
      LOGGED_IN_SALT: "=1.jNYVmYPoQ-K3}IX3(7!B4F5U@f1:T85<GWYI-Chc,:hUm^4Oa^|0m,a`KgoI"
      NONCE_SALT: ">z`m(crm{`%T|.J]:Z))wCxGrb,&F9bsG)J_V4dk=ckL<tRAE_)uK@]+v.!~xb{"
    ports:
      - "8000:80"
    networks:
      - wpsite

  database:
    platform: linux/amd64
    image: mysql:8.0
    volumes:
      - data_db:/var/lib/mysql
    restart: always
    container_name: wordpress-db
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: docker-wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: wp
    ports:
      - 33068:3306
    networks:
      - wpsite

networks:
  wpsite:
volumes:
  data_db:
```

Exec to container, install the composer package inside the test plugin and run the init script.

**Expected behavior**
Everything should be installed.

**Additional context**
Tried running the init script from the outside of the container, and I got this error

> Parse error: syntax error, unexpected '|', expecting '{' in /Users/deniszoljom/Projects/Personal/wp-docker-testing/wp-content/plugins/test-plugin/vendor/lucatume/wp-browser/src/Deprecated/deprecated-functions.php on line 162

I will try to install the package outside of the docker container and run the init script, will see if that will work, although I'm not sure if that should make any difference on the tests 🤷🏼‍♂️ 

### EDIT

Installing from the system and running the init script will work, need to see if this will have any effects on the tests (because of Docker, hadn't played with it in a long time).

### EDIT 2:

The E2E tests fail with:

```bash
vendor/bin/codecept run
Codeception PHP Testing Framework v5.0.11 https://helpukrainewin.org
Starting ChromeDriver on port 65071 ... ok
Starting PHP built-in server on port 65068 to serve tests/_wordpress ... ok

Tests.EndToEnd Tests (1) -------------------------------------------------------
E ActivationCest: Test_it_deactivates_activates_correctly
--------------------------------------------------------------------------------
Time: 00:00.469, Memory: 14.00 MB

There was 1 error:
1) ActivationCest: Test_it_deactivates_activates_correctly
 Test  tests/EndToEnd/ActivationCest.php:test_it_deactivates_activates_correctly

  [Facebook\WebDriver\Exception\UnknownCommandException] unknown command: unknown command: wd/hub/session

#1  /Users/deniszoljom/Projects/Personal/wp-docker-testing/wp-content/plugins/test-plugin/vendor/php-webdriver/webdriver/lib/Exception/WebDriverException.php:144
#2  /Users/deniszoljom/Projects/Personal/wp-docker-testing/wp-content/plugins/test-plugin/vendor/php-webdriver/webdriver/lib/Remote/HttpCommandExecutor.php:359
#3  /Users/deniszoljom/Projects/Personal/wp-docker-testing/wp-content/plugins/test-plugin/vendor/php-webdriver/webdriver/lib/Remote/RemoteWebDriver.php:129
#4  /Users/deniszoljom/Projects/Personal/wp-docker-testing/wp-content/plugins/test-plugin/vendor/symfony/event-dispatcher/EventDispatcher.php:220
#5  /Users/deniszoljom/Projects/Personal/wp-docker-testing/wp-content/plugins/test-plugin/vendor/symfony/event-dispatcher/EventDispatcher.php:56
#6  /Users/deniszoljom/Projects/Personal/wp-docker-testing/wp-content/plugins/test-plugin/vendor/bin/codecept:120
Artifacts:

Png: /Users/deniszoljom/Projects/Personal/wp-docker-testing/wp-content/plugins/test-plugin/tests/_output/Tests.EndToEnd.ActivationCest.test.it.deactivates.activates.correctly.fail.png
Html: /Users/deniszoljom/Projects/Personal/wp-docker-testing/wp-content/plugins/test-plugin/tests/_output/Tests.EndToEnd.ActivationCest.test.it.deactivates.activates.correctly.fail.html

ERRORS!
Tests: 1, Assertions: 0, Errors: 1.
```
