### ISSUE TITLE
[BUG] Unknown operation: MODIFY on woocommerce activation

### ISSUE THREAD

**Issue by dingo-d** [lucatume/wp-browser#642]
**Environment**
OS: MacOS 13.6 (22G120) Ventura
PHP version: 8.1
Installed Codeception version: 5.0.11
Installed wp-browser version: 4.0.3
WordPress version: 6.3.1
Local development environment: Valet
WordPress structure and management: default

**Can you perform the test manually?**
Yes, going to http://localhost:62011/wp-admin/edit.php?post_type=post works. Also activating themes and plugins manually work as well.

I created a test using the generate command, and tried running it using `vendor/bin/codecept run Integration` command. The test is the default one, create and get posts and asset that the instance is correct.

**Codeception configuration file**  
Paste, in a fenced YAML block, the content of your Codeception configuration file; remove any sensitive data!  

```yaml
namespace: Tests
support_namespace: Support
paths:
    tests: tests
    output: tests/_output
    data: tests/Support/Data
    support: tests/Support
    envs: tests/_envs
actor_suffix: Tester
params:
    - tests/.env
extensions:
    enabled:
        - Codeception\Extension\RunFailed
        - lucatume\WPBrowser\Extension\ChromeDriverController
        - lucatume\WPBrowser\Extension\BuiltInServerController
    config:
        lucatume\WPBrowser\Extension\ChromeDriverController:
            port: '%CHROMEDRIVER_PORT%'
        lucatume\WPBrowser\Extension\BuiltInServerController:
            workers: 5
            port: '%BUILTIN_SERVER_PORT%'
            docroot: '%WORDPRESS_ROOT_DIR%'
            env:
                DATABASE_TYPE: sqlite
                DB_ENGINE: sqlite
                DB_DIR: '%codecept_root_dir%/tests/Support/Data'
                DB_FILE: db.sqlite
    commands:
        - lucatume\WPBrowser\Command\RunOriginal
        - lucatume\WPBrowser\Command\RunAll
        - lucatume\WPBrowser\Command\GenerateWPUnit
        - lucatume\WPBrowser\Command\DbExport
        - lucatume\WPBrowser\Command\DbImport
        - lucatume\WPBrowser\Command\DevStart
        - lucatume\WPBrowser\Command\DevStop
        - lucatume\WPBrowser\Command\DevInfo
        - lucatume\WPBrowser\Command\DevRestart
        - lucatume\WPBrowser\Command\ChromedriverUpdate
```

**Suite configuration file**
Paste, in a fenced YAML block, the content of the suite configuration file; remove any sensitive data!

```yaml
# Codeception Test Suite Configuration

# suite for E2E tests.

# Integration suite configuration
#
# Run integration and "WordPress unit" tests.

actor: EndToEndTester
bootstrap: _bootstrap.php
modules:
    enabled:
        - lucatume\WPBrowser\Module\WPWebDriver
        - lucatume\WPBrowser\Module\WPDb
        - lucatume\WPBrowser\Module\WPFilesystem
        - lucatume\WPBrowser\Module\WPLoader
    config:
        lucatume\WPBrowser\Module\WPWebDriver:
            url: '%WORDPRESS_URL%'
            adminUsername: '%WORDPRESS_ADMIN_USER%'
            adminPassword: '%WORDPRESS_ADMIN_PASSWORD%'
            adminPath: '/wp-admin'
            browser: chrome
            host: '%CHROMEDRIVER_HOST%'
            port: '%CHROMEDRIVER_PORT%'
            window_size: 1200x1000
            capabilities:
              "goog:chromeOptions":
                args:
                  - "--headless"
                  - "--disable-gpu"
                  - "--disable-dev-shm-usage"
                  - "--proxy-server='direct://'"
                  - "--proxy-bypass-list=*"
                  - "--no-sandbox"
        lucatume\WPBrowser\Module\WPDb:
            dbUrl: '%WORDPRESS_DB_URL%'
            dump: 'tests/Support/Data/dump.sql'
            populate: true
            cleanup: true
            reconnect: false
            url: '%WORDPRESS_URL%'
            urlReplacement: false
            tablePrefix: '%WORDPRESS_TABLE_PREFIX%'
        lucatume\WPBrowser\Module\WPFilesystem:
            wpRootFolder: '%WORDPRESS_ROOT_DIR%'
        lucatume\WPBrowser\Module\WPLoader:
            loadOnly: true
            wpRootFolder: "%WORDPRESS_ROOT_DIR%" 
            dbUrl: '%WORDPRESS_DB_URL%'
            domain: '%WORDPRESS_DOMAIN%'
            
# Integration suite configuration
#
# Run integration and "WordPress unit" tests.

actor: IntegrationTester
bootstrap: _bootstrap.php
modules:
    enabled:
        - lucatume\WPBrowser\Module\WPLoader
    config:
        lucatume\WPBrowser\Module\WPLoader:
           wpRootFolder: "%WORDPRESS_ROOT_DIR%"
           dbUrl: '%WORDPRESS_DB_URL%'
           wpDebug: true
           tablePrefix: '%TEST_TABLE_PREFIX%'
           domain: '%WORDPRESS_DOMAIN%'
           adminEmail: 'admin@%WORDPRESS_DOMAIN%'
           title: 'Integration Tests'
           plugins: ['woocommerce/woocommerce.php', 'wp-orderprotection/wp-orderprotection.php']
           theme: 'storefront'
```

**Describe the bug**
I copied the woocommerce plugin and storefront theme to the `tests/_wordpress` folder, and when I ran the test command `vendor/bin/codecept run Integration` I got the error about database.

**Output**

```bash
lucatume\WPBrowser\Module\WPLoader: Failed to activate plugin woocommerce/woocommerce.php. The plugin generated unexpected output.: <div id="error"><p class="wpdberror">WordPress
   database error: [<div style="clear:both"> </div>
  <div class="queries" style="clear:both;margin-bottom:2px;border:red dotted thin;">
  <p>MySQL query:</p>
  <p>
  				ALTER TABLE test_actionscheduler_actions                                                                                                               
  				MODIFY COLUMN scheduled_date_gmt datetime NULL default &#039;0000-00-00 00:00:00&#039;,                                                                
  				MODIFY COLUMN scheduled_date_local datetime NULL default &#039;0000-00-00 00:00:00&#039;,                                                              
  				MODIFY COLUMN last_attempt_gmt datetime NULL default &#039;0000-00-00 00:00:00&#039;,                                                                  
  				MODIFY COLUMN last_attempt_local datetime NULL default &#039;0000-00-00 00:00:00&#039;                                                                 
  		</p>                                                                                                                                                             
  <p>Queries made or created this session were:</p>
  <ol>
  <li>Executing: BEGIN | (no parameters)</li>
  <li>Executing: ROLLBACK | (no parameters)</li>
  </ol>
  </div>
  <div style="clear:both;margin-bottom:2px;border:red dotted thin;" class="error_message" style="border-bottom:dotted blue thin;">
  Error occurred at line 3378 in Function <code>handle_error</code>. Error message was: Unknown operation: MODIFY.
  </div>
  <p>Backtrace:</p>
  <pre>#0 my-plugin/tests/_wordpress/wp-content/mu-plugins/sqlite-database-integration/wp-includes/sqlite
  /class-wp-sqlite-db.php(289): WP_SQLite_Translator->get_error_message()
  #1 my-plugin/tests/_wordpress/wp-content/plugins/woocommerce/packages/action-scheduler/classes/schema/ActionS
  cheduler_StoreSchema.php(126): WP_SQLite_DB->query(&#039;\n\t\t\t\tALTER TABL...&#039;)
  #2 my-plugin/tests/_wordpress/wp-includes/class-wp-hook.php(310): ActionScheduler_StoreSchema->update_sche
  ma_5_0(&#039;actionscheduler...&#039;, 0)
  #3 my-plugin/tests/_wordpress/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters(&#039;&#039;, Arr
  ay)
  #4 my-plugin/tests/_wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
  #5 my-plugin/tests/_wordpress/wp-content/plugins/woocommerce/packages/action-scheduler/classes/abstracts/Acti
  onScheduler_Abstract_Schema.php(62): do_action(&#039;action_schedule...&#039;, &#039;actionscheduler...&#039;, 0)
  #6 my-plugin/tests/_wordpress/wp-content/plugins/woocommerce/packages/action-scheduler/classes/data-stores/Ac
  tionScheduler_DBStore.php(43): ActionScheduler_Abstract_Schema->register_tables()
  #7 my-plugin/tests/_wordpress/wp-content/plugins/woocommerce/packages/action-scheduler/classes/data-stores/Ac
  tionScheduler_HybridStore.php(57): ActionScheduler_DBStore->init()
  #8 my-plugin/tests/_wordpress/wp-content/plugins/woocommerce/packages/action-scheduler/classes/abstracts/Acti
  onScheduler.php(180): ActionScheduler_HybridStore->init()
  #9 my-plugin/tests/_wordpress/wp-content/plugins/woocommerce/packages/action-scheduler/action-scheduler.php(5
  8): ActionScheduler::init(&#039;/Users/deniszol...&#039;)
  #10 my-plugin/tests/_wordpress/wp-content/plugins/woocommerce/packages/action-scheduler/action-scheduler.php(
  64): action_scheduler_initialize_3_dot_6_dot_2()
  #11 my-plugin/tests/_wordpress/wp-content/plugins/woocommerce/includes/class-woocommerce.php(572): include_on
  ce(&#039;/Users/deniszol...&#039;)
  #12 my-plugin/tests/_wordpress/wp-content/plugins/woocommerce/includes/class-woocommerce.php(185): WooCommerc
  e->includes()
  #13 my-plugin/tests/_wordpress/wp-content/plugins/woocommerce/includes/class-woocommerce.php(144): WooCommerc
  e->__construct()
  #14 my-plugin/tests/_wordpress/wp-content/plugins/woocommerce/woocommerce.php(47): WooCommerce::instance()
  #15 my-plugin/tests/_wordpress/wp-content/plugins/woocommerce/woocommerce.php(62): WC()
  #16 my-plugin/tests/_wordpress/wp-admin/includes/plugin.php(2318): include_once(&#039;/Users/deniszol...&#039
  ;)
  #17 my-plugin/tests/_wordpress/wp-admin/includes/plugin.php(663): plugin_sandbox_scrape(&#039;woocommerce/woo
  ...&#039;)
  #18 my-plugin/vendor/lucatume/wp-browser/src/WordPress/CodeExecution/ActivatePluginAction.php(35): activate_p
  lugin(&#039;woocommerce/woo...&#039;, &#039;&#039;, false)
  #19 closure://fn() => $this->activatePlugin($plugin, $multisite)(2): lucatume\WPBrowser\WordPress\CodeExecution\ActivatePluginAction->activatePlugin(&#039;woocommerce/wo
  o...&#039;, false)
  #20 my-plugin/vendor/lucatume/wp-browser/src/WordPress/FileRequests/FileRequest.php(157): lucatume\WPBrowser\
  WordPress\CodeExecution\ActivatePluginAction->{closure}(&#039;/Users/deniszol...&#039;)
  #21 closure://static function () use ($request): mixed {
              return $request->execute();
          }(3): lucatume\WPBrowser\WordPress\FileRequests\FileRequest->execute()
  #22 [internal function]: lucatume\WPBrowser\WordPress\CodeExecution\ActivatePluginAction::{closure}()
  #23 my-plugin/vendor/lucatume/wp-browser/includes/opis/closure/src/SerializableClosure.php(109): call_user_fu
  nc_array(Object(Closure), Array)
  #24 my-plugin/vendor/lucatume/wp-browser/src/Process/Worker/worker-script.php(16): lucatume\WPBrowser\Opis\Cl
  osure\SerializableClosure->__invoke()
  #25 {main}</pre>
  ] <code>
  				ALTER TABLE test_actionscheduler_actions                                                                                                               
  				MODIFY COLUMN scheduled_date_gmt datetime NULL default &#039;0000-00-00 00:00:00&#039;,                                                                
  				MODIFY COLUMN scheduled_date_local datetime NULL default &#039;0000-00-00 00:00:00&#039;,                                                              
  				MODIFY COLUMN last_attempt_gmt datetime NULL default &#039;0000-00-00 00:00:00&#039;,                                                                  
  				MODIFY COLUMN last_attempt_local datetime NULL default &#039;0000-00-00 00:00:00&#039;                                                                 
  		</code></p></div><div id="error"><p class="wpdberror">WordPress database error: [<div style="clear:both"> </div>                        
  <div class="queries" style="clear:both;margin-bottom:2px;border:red dotted thin;">
  <p>MySQL query:</p>
  <p>
  				ALTER TABLE test_actionscheduler_logs                                                                                                                  
  				MODIFY COLUMN log_date_gmt datetime NULL default &#039;0000-00-00 00:00:00&#039;,                                                                      
  				MODIFY COLUMN log_date_local datetime NULL default &#039;0000-00-00 00:00:00&#039;                                                                     
  			</p>                                                                                                                                                     
  <p>Queries made or created this session were:</p>
  <ol>
  <li>Executing: BEGIN | (no parameters)</li>
  <li>Executing: ROLLBACK | (no parameters)</li>
  </ol>
  </div>
  <div style="clear:both;margin-bottom:2px;border:red dotted thin;" class="error_message" style="border-bottom:dotted blue thin;">
  Error occurred at line 3378 in Function <code>handle_error</code>. Error message was: Unknown operation: MODIFY.
  </div>
  <p>Backtrace:</p>
  <pre>#0 my-plugin/tests/_wordpress/wp-content/mu-plugins/sqlite-database-integration/wp-includes/sqlite
  /class-wp-sqlite-db.php(289): WP_SQLite_Translator->get_error_message()
  #1 my-plugin/tests/_wordpress/wp-content/plugins/woocommerce/packages/action-scheduler/classes/schema/ActionS
  cheduler_LoggerSchema.php(86): WP_SQLite_DB->query(&#039;\n\t\t\t\tALTER TABL...&#039;)
  #2 my-plugin/tests/_wordpress/wp-includes/class-wp-hook.php(310): ActionScheduler_LoggerSchema->update_sch
  ema_3_0(&#039;actionscheduler...&#039;, 0)
  #3 my-plugin/tests/_wordpress/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters(NULL, Array)
  #4 my-plugin/tests/_wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
  #5 my-plugin/tests/_wordpress/wp-content/plugins/woocommerce/packages/action-scheduler/classes/abstracts/Acti
  onScheduler_Abstract_Schema.php(62): do_action(&#039;action_schedule...&#039;, &#039;actionscheduler...&#039;, 0)
  #6 my-plugin/tests/_wordpress/wp-content/plugins/woocommerce/packages/action-scheduler/classes/data-stores/Ac
  tionScheduler_DBLogger.php(108): ActionScheduler_Abstract_Schema->register_tables()
  #7 my-plugin/tests/_wordpress/wp-content/plugins/woocommerce/packages/action-scheduler/classes/abstracts/Acti
  onScheduler.php(181): ActionScheduler_DBLogger->init()
  #8 my-plugin/tests/_wordpress/wp-content/plugins/woocommerce/packages/action-scheduler/action-scheduler.php(5
  8): ActionScheduler::init(&#039;/Users/deniszol...&#039;)
  #9 my-plugin/tests/_wordpress/wp-content/plugins/woocommerce/packages/action-scheduler/action-scheduler.php(6
  4): action_scheduler_initialize_3_dot_6_dot_2()
  #10 my-plugin/tests/_wordpress/wp-content/plugins/woocommerce/includes/class-woocommerce.php(572): include_on
  ce(&#039;/Users/deniszol...&#039;)
  #11 my-plugin/tests/_wordpress/wp-content/plugins/woocommerce/includes/class-woocommerce.php(185): WooCommerc
  e->includes()
  #12 my-plugin/tests/_wordpress/wp-content/plugins/woocommerce/includes/class-woocommerce.php(144): WooCommerc
  e->__construct()
  #13 my-plugin/tests/_wordpress/wp-content/plugins/woocommerce/woocommerce.php(47): WooCommerce::instance()
  #14 my-plugin/tests/_wordpress/wp-content/plugins/woocommerce/woocommerce.php(62): WC()
  #15 my-plugin/tests/_wordpress/wp-admin/includes/plugin.php(2318): include_once(&#039;/Users/deniszol...&#039
  ;)
  #16 my-plugin/tests/_wordpress/wp-admin/includes/plugin.php(663): plugin_sandbox_scrape(&#039;woocommerce/woo
  ...&#039;)
  #17 my-plugin/vendor/lucatume/wp-browser/src/WordPress/CodeExecution/ActivatePluginAction.php(35): activate_p
  lugin(&#039;woocommerce/woo...&#039;, &#039;&#039;, false)
  #18 closure://fn() => $this->activatePlugin($plugin, $multisite)(2): lucatume\WPBrowser\WordPress\CodeExecution\ActivatePluginAction->activatePlugin(&#039;woocommerce/wo
  o...&#039;, false)
  #19 my-plugin/vendor/lucatume/wp-browser/src/WordPress/FileRequests/FileRequest.php(157): lucatume\WPBrowser\
  WordPress\CodeExecution\ActivatePluginAction->{closure}(&#039;/Users/deniszol...&#039;)
  #20 closure://static function () use ($request): mixed {
              return $request->execute();
          }(3): lucatume\WPBrowser\WordPress\FileRequests\FileRequest->execute()
  #21 [internal function]: lucatume\WPBrowser\WordPress\CodeExecution\ActivatePluginAction::{closure}()
  #22 my-plugin/vendor/lucatume/wp-browser/includes/opis/closure/src/SerializableClosure.php(109): call_user_fu
  nc_array(Object(Closure), Array)
  #23 my-plugin/vendor/lucatume/wp-browser/src/Process/Worker/worker-script.php(16): lucatume\WPBrowser\Opis\Cl
  osure\SerializableClosure->__invoke()
  #24 {main}</pre>
  ] <code>
  				ALTER TABLE test_actionscheduler_logs                                                                                                                  
  				MODIFY COLUMN log_date_gmt datetime NULL default &#039;0000-00-00 00:00:00&#039;,                                                                      
  				MODIFY COLUMN log_date_local datetime NULL default &#039;0000-00-00 00:00:00&#039;                                                                     
  			</code></p></div>                                                                                                                                              
```

**To Reproduce**
1. Setup tests as described on the documentation
2. Copy over the woocommerce plugin and storefront theme to the necessary folders, and add those in the test suite configs
3. Run the tests

**Expected behavior**
I expected a successful integration test.
