### ISSUE TITLE
[BUG] Default integration test suite fails with Class "lucatume\WPBrowser\Process\SerializableThrowable" not found error

### ISSUE THREAD

**Issue by w33zy** [lucatume/wp-browser#646]
**Environment**
OS: Windows 11
PHP version: 8.2.0 
Installed Codeception version: 5.0.11
Installed wp-browser version: 4.0.4  
WordPress version: 6.4-alpha-56665  
Local development environment: Laragon 6.0
WordPress structure and management: default

**Can you perform the test manually?**
No.

**Codeception configuration file**  
```yaml
namespace: Tests
support_namespace: Support
paths:
    tests: tests
    output: tests/_output
    data: tests/Support/Data
    support: tests/Support
    envs: tests/_envs
actor_suffix: Tester
params:
    - tests/.env
extensions:
    enabled:
        - Codeception\Extension\RunFailed
    config: {  }
    commands:
        - lucatume\WPBrowser\Command\RunOriginal
        - lucatume\WPBrowser\Command\RunAll
        - lucatume\WPBrowser\Command\GenerateWPUnit
        - lucatume\WPBrowser\Command\DbExport
        - lucatume\WPBrowser\Command\DbImport
```

**Env file**
```env
WORDPRESS_ROOT_DIR=D:\Laragon\www\collections
WORDPRESS_DB_URL=mysql://root:@localhost:3306/collections
TEST_TABLE_PREFIX=test_
WORDPRESS_TABLE_PREFIX=wp_
WORDPRESS_URL=https://collections.local
WORDPRESS_DOMAIN=collections.local
WORDPRESS_ADMIN_USER=wzy
WORDPRESS_ADMIN_PASSWORD=uswu44241
CHROMEDRIVER_HOST=localhost
CHROMEDRIVER_PORT=9515
```

**Suite configuration file**
```yaml
# Integration suite configuration
#
# Run integration and "WordPress unit" tests.

actor: EndToEndTester
bootstrap: _bootstrap.php
modules:
    enabled:
        - lucatume\WPBrowser\Module\WPWebDriver
        - lucatume\WPBrowser\Module\WPDb
        - lucatume\WPBrowser\Module\WPFilesystem
        - lucatume\WPBrowser\Module\WPLoader
    config:
        lucatume\WPBrowser\Module\WPWebDriver:
            url: '%WORDPRESS_URL%'
            adminUsername: '%WORDPRESS_ADMIN_USER%'
            adminPassword: '%WORDPRESS_ADMIN_PASSWORD%'
            adminPath: '/wp-admin'
            browser: chrome
            host: '%CHROMEDRIVER_HOST%'
            port: '%CHROMEDRIVER_PORT%'
            window_size: 1200x1000
            capabilities:
              "goog:chromeOptions":
                args:
                  - "--headless"
                  - "--disable-gpu"
                  - "--disable-dev-shm-usage"
                  - "--proxy-server='direct://'"
                  - "--proxy-bypass-list=*"
                  - "--no-sandbox"
        lucatume\WPBrowser\Module\WPDb:
            dbUrl: '%WORDPRESS_DB_URL%'
            dump: 'tests/Support/Data/dump.sql'
            populate: true
            cleanup: true
            reconnect: false
            url: '%WORDPRESS_URL%'
            urlReplacement: false
            tablePrefix: '%WORDPRESS_TABLE_PREFIX%'
        lucatume\WPBrowser\Module\WPFilesystem:
            wpRootFolder: '%WORDPRESS_ROOT_DIR%'
        lucatume\WPBrowser\Module\WPLoader:
            loadOnly: false
            wpRootFolder: "%WORDPRESS_ROOT_DIR%" 
            dbUrl: '%WORDPRESS_DB_URL%'
            domain: '%WORDPRESS_DOMAIN%'
            
# Integration suite configuration
#
# Run integration and "WordPress unit" tests.

actor: IntegrationTester
bootstrap: _bootstrap.php
modules:
    enabled:
        - lucatume\WPBrowser\Module\WPLoader
    config:
        lucatume\WPBrowser\Module\WPLoader:
           wpRootFolder: "%WORDPRESS_ROOT_DIR%" 
           dbUrl: '%WORDPRESS_DB_URL%'
           wpDebug: true
           tablePrefix: '%TEST_TABLE_PREFIX%'
           domain: '%WORDPRESS_DOMAIN%'
           adminEmail: 'admin@%WORDPRESS_DOMAIN%'
           title: 'Integration Tests'
           plugins: ['collections/collections.php']
           theme: ''
```

**Describe the bug**
On a fresh installation of `wp-browser` run running the `vendor/bin/codecept run Integration` command as per the documentation, I get the follow error in my terminal window.

**Output**
```sh
lucatume\WPBrowser\Module\WPLoader: Failed to activate plugin collections/collections.php.
  Warning: Undefined array key 1 in D:\Laragon\www\collections\wp-content\plugins\collections\vendor\lucatume\wp-browser\src\Process\Worker\worker
  -script.php on line 14

  Fatal error: Uncaught Error: Class "lucatume\WPBrowser\Process\SerializableThrowable" not found in D:\Laragon\www\collections\wp-content\plugins\collections\vendor\lucatume\wp-browser\src\Process\Worker\worker-script.php:19
  Stack trace:
  #0 {main}
    thrown in D:\Laragon\www\collections\wp-content\plugins\collections\vendor\lucatume\wp-browser\src\Process\Worker\worker-script.php on line 19
```

Also the following PHP is added to the error log when the above command is run:
```sh
[29-Sep-2023 17:13:37 UTC] PHP Warning:  Undefined array key 1 in D:\Laragon\www\collections\wp-content\plugins\collections\vendor\lucatume\wp-browser\src\Process\Worker\worker-script.php on line 14
[29-Sep-2023 17:13:37 UTC] PHP Fatal error:  Uncaught Error: Class "lucatume\WPBrowser\Process\SerializableThrowable" not found in D:\Laragon\www\collections\wp-content\plugins\collections\vendor\lucatume\wp-browser\src\Process\Worker\worker-script.php:19
Stack trace:
#0 {main}
  thrown in D:\Laragon\www\collections\wp-content\plugins\collections\vendor\lucatume\wp-browser\src\Process\Worker\worker-script.php on line 19
```

**To Reproduce**
Follow setup instruction on Window 11

**Expected behavior**
No errors
