### ISSUE TITLE
[BUG] Tests fail when being run from phpstorm

### ISSUE THREAD

**Issue by dingo-d** [lucatume/wp-browser#656]
**Environment**
OS: MacOS Ventura  
PHP version: 8.1  
Installed Codeception version: 5.0.11  
Installed wp-browser version: 4.0.3  
WordPress version: 6.3  
Local development environment: Valet  
WordPress structure and management: default  

**Can you perform the test manually?**
Yes

**Codeception configuration file**  

```yaml
namespace: Tests
support_namespace: Support
paths:
    tests: tests
    output: tests/_output
    data: tests/Support/Data
    support: tests/Support
    envs: tests/_envs
actor_suffix: Tester
params:
    - tests/.env
coverage:
    enabled: true
    low_limit: 30
    high_limit: 80
    include:
        - src/*
extensions:
    enabled:
        - Codeception\Extension\RunFailed
        - lucatume\WPBrowser\Extension\ChromeDriverController
        - lucatume\WPBrowser\Extension\BuiltInServerController
    config:
        lucatume\WPBrowser\Extension\ChromeDriverController:
            port: '%CHROMEDRIVER_PORT%'
        lucatume\WPBrowser\Extension\BuiltInServerController:
            workers: 5
            port: '%BUILTIN_SERVER_PORT%'
            docroot: '%WORDPRESS_ROOT_DIR%'
            env:
                DATABASE_TYPE: sqlite
                DB_ENGINE: sqlite
                DB_DIR: '%codecept_root_dir%/tests/Support/Data'
                DB_FILE: db.sqlite
    commands:
        - lucatume\WPBrowser\Command\RunOriginal
        - lucatume\WPBrowser\Command\RunAll
        - lucatume\WPBrowser\Command\GenerateWPUnit
        - lucatume\WPBrowser\Command\DbExport
        - lucatume\WPBrowser\Command\DbImport
        - lucatume\WPBrowser\Command\DevStart
        - lucatume\WPBrowser\Command\DevStop
        - lucatume\WPBrowser\Command\DevInfo
        - lucatume\WPBrowser\Command\DevRestart
        - lucatume\WPBrowser\Command\ChromedriverUpdate
```

**Suite configuration file**

```yaml
# Integration suite configuration
#
# Run integration and "WordPress unit" tests.

actor: IntegrationTester
bootstrap: _bootstrap.php
modules:
    enabled:
        - lucatume\WPBrowser\Module\WPLoader
    config:
        lucatume\WPBrowser\Module\WPLoader:
           wpRootFolder: "%WORDPRESS_ROOT_DIR%"
           dbUrl: '%WORDPRESS_DB_URL%'
           wpDebug: true
           tablePrefix: '%TEST_TABLE_PREFIX%'
           domain: '%WORDPRESS_DOMAIN%'
           adminEmail: 'admin@%WORDPRESS_DOMAIN%'
           title: 'Integration Tests'
           plugins: ['woocommerce/woocommerce.php','wp-orderprotection/wp-orderprotection.php']
           theme: 'storefront'
```

**Describe the bug**
When running the test from PhpStorm I get the error

> In WPConfigFile.php line 143:
>                                            
>   Could not parse the wp-config.php file:                                          

> In WPConfigFile.php line 129:
>                                                        
>   [lucatume\WPBrowser\Process\ProcessException (255)]  
                                                       
So I put debugger inside the WPConfigFile.php file, and I can see both `$wpConfigFile`, and `$wpSettingsFile` file pointing to the correct files (inside my `tests/_wordpress` folder). But then the `$result` variable is

```
$result = {lucatume\WPBrowser\Process\Worker\Result} 
 id = "0"
 exitCode = {int} 255
 stdoutBuffer = "\nFatal error: Uncaught Error: Class "lucatume\WPBrowser\Process\SerializableThrowable" not found in my-plugin/vendor/lucatume/wp-browser/src/Process/Worker/worker-script.php on line 18\n\nError: Class "lucatume\WPBrowser\Process\SerializableThrowable" not found in my-plugin/vendor/lucatume/wp-browser/src/Process/Worker/worker-script.php on line 18\n\nCall Stack:\n    0.0030     412688   1. {main}() my-plugin/vendor/lucatume/wp-browser/src/Process/Worker/worker-script.php:0\n\n"
 stderrBuffer = ""
 returnValue = null
 memoryUsage = {int} 0
```

Which is odd, because when I manually go to that file, the phpstorm isn't complaining about that class or file missing.

Any idea what could be the culprit?
