### ISSUE TITLE
[BUG] v4 uses `__wakeup`, which many plugins have overridden with an error.

### ISSUE THREAD

**Issue by BrianHenryIE** [lucatume/wp-browser#673]
**Environment**
OS: MacOS
PHP version: 8.0
Installed Codeception version: 5.0.12
Installed wp-browser version: 4.0.10
WordPress version: 6.4
Local development environment: Apache + MariaDB
WordPress structure and management: `johnpbloch/wordpress` + `wpackagist`.

**Can you perform the test manually?**
Yes.

**Codeception configuration file**  

```yaml
paths:
    tests: tests
    output: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
actor_suffix: Tester
extensions:
    enabled:
        - Codeception\Extension\RunFailed
    commands:
        - Codeception\Command\GenerateWPUnit
params:
    - .env.testing
bootstrap: bootstrap.php
```

**Suite configuration file**

```yaml
actor: WpunitTester
modules:
    enabled:
        - WPLoader
        - \Helper\Wpunit
    config:
        WPLoader:
            wpRootFolder: "%WP_ROOT_FOLDER%"
            dbName: "%TEST_DB_NAME%"
            dbHost: "%TEST_DB_HOST%"
            dbUser: "%TEST_DB_USER%"
            dbPassword: "%TEST_DB_PASSWORD%"
            tablePrefix: "%TEST_TABLE_PREFIX%"
            domain: "%TEST_SITE_WP_DOMAIN%"
            adminEmail: "%TEST_SITE_ADMIN_EMAIL%"
            title: "bh-wp-bitcoin-gateway"
            plugins: ["woocommerce/woocommerce.php"]
            activatePlugins: ["woocommerce/woocommerce.php"]
bootstrap: _bootstrap.php
```

**Describe the bug**

Tests that ran OK in v3.x fail in v4. 

Due to this old convention in WordPress plugins. I don't even know what this is supposed to achieve:

```php
	/**
	 * Unserializing instances of this class is forbidden.
	 *
	 * @since 2.1
	 */
	public function __wakeup() {
		wc_doing_it_wrong( __FUNCTION__, __( 'Unserializing instances of this class is forbidden.', 'woocommerce' ), '2.1' );
	}
```
E.g. [WC_Payment_Gateway](https://github.com/woocommerce/woocommerce/blob/2a36806a7c2085a596f900373f9f92c704c86611/plugins/woocommerce/includes/class-wc-payment-gateways.php#L57-L64)

**Output**
```
[PHPUnit\Framework\Error\Notice] Function __wakeup was called incorrectly. Unserializing instances of this class is forbidden. Backtrace: ...
```

**To Reproduce**
Just ask and I'll get a minimal reproduction together. But it's Thanksgiving today so I'd like to skip that for now.

**Expected behavior**

Tests should run as before!

**Screenshots**

<img width="922" alt="Screenshot 2023-11-23 at 5 52 25 PM" src="https://github.com/lucatume/wp-browser/assets/4720401/f791dcd7-5d85-4ab0-a286-a883da3b4709">

**Additional context**

Unfortunately, overriding `__wakeup` is a pretty widespread pattern. This is the second plugin I've encountered it in (I've only updated a few plugins to use wp-browser v4).

**Comment by lucatume** [comment]
Hi @BrianHenryIE,

the issue arises from the fact that, in v4, I've modified the `WPTestCase::$backupGlobals` to `true`; it was `false` in v3.

In your test cases, an immediate fix for the issue would be to explicitly override the `WPTestCase::$backupGlobals` property and set it to `false`.

I've set up [a curated list of known offenders](https://github.com/lucatume/wp-browser/blob/74f3a6ea7b9d67e5d87d1961dddc7a3ba43c8b49/src/TestCase/WPTestCase.php#L49-L61) in the `WPTestCase` code, but cannot possibly cover it all.

Why change the `$backupGlobals` and `$backupStaticAttributes` properties of the  `WPTestCase` from `false` (v3) to `true` (v4)? While the `WPTestCase` cleanup of global variables covers some, it will mainly cover the ones set and used by WordPress; globals and static properties frequently used to cache values will not be reset, leading to all kinds of difficult-to-track bugs and false results where tests are behaving differently depending on the run order.

Thinking about how to improve on this:
1. Add `backupGlobals` and `backupStaticAttributes` configuration parameters to the `WPLoader` configuration, default `true`, to control the behavior of the respective `WPTestCase` properties.
2. I like the sweeping cleanup done by the two properties and would like to be able to define what should **not** be serialized as part of the snapshot procedure PHPUnit uses to back up and restore the global state. I will add the `backupGlobalsExcludeList` and `backupStaticAttributesExcludeList` to the configuration of the `WPLoader` module to add to the respective lists.

In this API, your problem could be solved in two ways:
1. Disable backup of globals and static attributes:
    ```yaml
    config:
      lucatume\WPBrowser\Module\WPLoader:
        backupGlobals: false
        backupStaticAttributes: false
    ```
2. Selectively exclude the problematic class:
   ```yaml
    config:
      lucatume\WPBrowser\Module\WPLoader:
        backupStaticAttributesExcludeList:
          WC_Payment_Gateways: ['instance']
    ```

This API should provide a flexible approach to handle issues like this one.
