### ISSUE TITLE
[BUG] WPLoader doesn't load wordpress installation

### ISSUE THREAD

**Issue by mwei0210** [lucatume/wp-browser#688]
Environment
Environment
OS: Linux
PHP version: 8.0.30
Installed Codeception version: 5.0.12
Installed wp-browser version: 4.0.17
WordPress version: 6.3.2
Local development environment: Nginx
WordPress structure and management: default

Can you perform the test manually?
N/A

Codeception configuration file

```
namespace: Tests
support_namespace: Support
paths:
    tests: tests
    output: tests/_output
    data: tests/Support/Data
    support: tests/Support
    envs: tests/_envs
actor_suffix: Tester
extensions:
    enabled:
        - Codeception\Extension\RunFailed
params:
    - .env.testing
settings:
    memory_limit: 2048m
```
Suite configuration file
Paste, in a fenced YAML block, the content of the suite configuration file; remove any sensitive data!

```
actor: AcceptanceTester
modules:
    enabled:
        - WPDb
        - WPWebDriver
        - WPLoader
    config:
        WPWebDriver:
            url: 'https://mywebsite.com'
            adminUsername: '%WORDPRESS_ADMIN_USER%'
            adminPassword: '%WORDPRESS_ADMIN_PASSWORD%'
            adminPath: '/wp-admin'
            browser: chrome
            host: 'x.x.x.x'
            port: '8080'
            path: '/'
            window_size: false
            wait: 5
            capabilities:
              "goog:chromeOptions":
                args:
                  - "--headless"
                  - "--disable-gpu"
                  - "--disable-dev-shm-usage"
                  - "--proxy-server='direct://'"
                  - "--proxy-bypass-list=*"
                  - "--no-sandbox"
        WPDb:
            dsn: '%TEST_SITE_DB_DSN%'
            user: '%TEST_SITE_DB_USER%'
            password: '%TEST_SITE_DB_PASSWORD%'
            dump: 'tests/_data/dump.sql'
            #import the dump before the tests; this means the test site database will be repopulated before the tests.
            populate: false
            # re-import the dump between tests; this means the test site database will be repopulated between the tests.
            populator: 'mysql -u $user -p$password -h $host < $dump'
            cleanup: false
            waitlock: 10
            url: '%TEST_SITE_WP_URL%'
            urlReplacement: false #replace the hardcoded dump URL with the one above
            tablePrefix: '%TEST_SITE_TABLE_PREFIX%'
        WPLoader:
            wpRootFolder: "%WP_ROOT_FOLDER%"
            domain: "%TEST_SITE_WP_DOMAIN%"
            dbName: "%TEST_DB_NAME%"
            dbHost: "%TEST_DB_HOST%"
            dbUser: "%TEST_DB_USER%"
            dbPassword: "%TEST_DB_PASSWORD%"
            loadOnly: true
```
Describe the bug
Got the error when trying to use WP_Query
`  [Error] Class "Tests\Acceptance\WP_Query" not found  
`

If i try to add echo in WPLoader.php like below, the echo is not run at all:

<img width="664" alt="image" src="https://github.com/lucatume/wp-browser/assets/8067359/a7fffd25-ff10-41d8-8d12-eb21ce187ed8">

If I move the echo outside of addListener it would echo.

Output

`  [Error] Class "Tests\Acceptance\WP_Query" not found  
`                  

To Reproduce
vendor/bin/codecept run acceptance -d

Expected behavior
Run the test suite loading WPLoader and WP_Query should be avaialble with Wordpress installation
