### ISSUE TITLE
window_size doesn't work if enclosed in quotes

### ISSUE THREAD

**Issue by petemolinero** [lucatume/wp-browser#69]
Just letting you know that on my end the `window_size` option does not work if I put quotes around it. It only works if I do it like so:

```
  modules:
      enabled:
          - WPWebDriver
      config:
          WPWebDriver:
              url: 'http://example.local'
              browser: phantomjs
              port: 4444
              window_size: 1024x768
              adminUsername: 'root'
              adminPassword: 'root'
              adminPath: '/wp-core/wp-admin'
```

The official CodeCeption WebDriver docs also list the recommended format as [without the quotes](https://github.com/Codeception/codeception.github.com/blob/master/docs/modules/WebDriver.md#configuration).

Just mentioning this so that perhaps you can update your readme to spare other people the confusion. :-)
