### ISSUE TITLE
[BUG] Warnings while running tests

### ISSUE THREAD

**Issue by iateadonut** [lucatume/wp-browser#692]
**Environment**
OS: Linux
PHP version: 8.1.12
Installed Codeception version: ^5.1
Installed wp-browser version: ^4.0
WordPress version: 6.4.2
Local development environment: apache2
WordPress structure and management: default

**Codeception configuration file**  
Paste, in a fenced YAML block, the content of your Codeception configuration file; remove any sensitive data!  

unit.suite.yml
```yaml
actor: UnitTester
modules:
    enabled:
        - WPLoader:
            wpRootFolder: "/var/www/html/"
            dbName: "*"
            dbHost: "localhost"
            dbUser: "*"
            dbPassword: "*"
            wpDebug: true
            tablePrefix: "wp_"
            domain: "site.localhost"
            constants:
                WP_CONTENT_DIR: "/var/www/html/wp-content/"
```

functional.suite.yml
```yaml
actor: FunctionalTester
modules:
    enabled:
         - WPBrowser:
            url: 'https://site.localhost/'
            adminUsername: '*'
            adminPassword: '*'
            adminPath: '/wp-admin'
         - REST:
            depends: WPBrowser
            part: Json
step_decorators: ~
```

**Describe the bug**
I get warnings when running any tests.

**Output**
✗ vendor/bin/codecept run unit OcrTest
```
PHP Warning:  Class "PHPUnit\Framework\Error\Deprecated" not found in /var/www/html/wp-content/plugins/html/vendor/lucatume/wp-browser/includes/core-phpunit/includes/phpunit6/compat.php on line 8
PHP Warning:  Class "PHPUnit\Framework\Error\Notice" not found in /var/www/html/wp-content/plugins/html/vendor/lucatume/wp-browser/includes/core-phpunit/includes/phpunit6/compat.php on line 9
PHP Warning:  Class "PHPUnit\Framework\Error\Warning" not found in /var/www/html/wp-content/plugins/html/vendor/lucatume/wp-browser/includes/core-phpunit/includes/phpunit6/compat.php on line 10
PHP Warning:  Class "PHPUnit\Framework\Warning" not found in /var/www/html/wp-content/plugins/html/vendor/lucatume/wp-browser/includes/core-phpunit/includes/phpunit6/compat.php on line 12
PHP Warning:  Class "PHPUnit\Framework\TestListener" not found in /var/www/html/wp-content/plugins/html/vendor/lucatume/wp-browser/includes/core-phpunit/includes/phpunit6/compat.php on line 15
```

**To Reproduce**
Create blank unit test and run.

**Expected behavior**
No warnings.
