### ISSUE TITLE
Config remote test coverage for WPBrowser

### ISSUE THREAD

**Issue by TangRufus** [lucatume/wp-browser#70]
How can I add remote test coverage for `WPBrowser`? 
My setup is more less the same as [lucatume/rest-calculator](https://github.com/lucatume/rest-calculator)'s acceptance suite.

Following the docs of `Codeception` and `c3`, I pulled `c3.php` to my plugin root and added `require_once __DIR__ . '/wp-content/plugins/my-plugin-name/c3.php';` to `wp-config.php` (tried `index.php` and `my-plugin-name.php` also)

```yaml
# .codeception.yml
coverage:
    enable: true
    remote: true # Also tried false
    c3_url: 'http://my-local-site.dev/wp-content/plugins/my-plugin-name/c3.php' # Also tried to omit this
```

However, `tests/_output/coverage.xml` always report zero coverage.
Am I missed anything?

Thanks!

http://codeception.com/docs/11-Codecoverage
https://github.com/Codeception/c3
