### ISSUE TITLE
[SETUP ISSUE] Teardown error — $wpdb is null

### ISSUE THREAD

**Issue by Genyus** [lucatume/wp-browser#716]
**Environment**
OS: macOS 14.2
PHP version: 8.2
Installed Codeception version: 5.1.2
Installed wp-browser version: 4.1.6
WordPress version: 6.5
Local development environment: Lando
WordPress structure and management: Bedrock

**Did you use the `codecept init wpbrowser` command?**
Yes

**Did you take a look at Codeception and wp-browser documentation?**
Yes

**Codeception configuration file**

```yaml
namespace: Tests
support_namespace: Support
paths:
    tests: tests
    output: tests/_output
    data: tests/Support/Data
    support: tests/Support
    envs: tests/_envs
actor_suffix: Tester
extensions:
    commands:
      - "Codeception\\Command\\GenerateWPUnit"
      - "Codeception\\Command\\GenerateWPRestApi"
      - "Codeception\\Command\\GenerateWPRestController"
      - "Codeception\\Command\\GenerateWPRestPostTypeController"
      - "Codeception\\Command\\GenerateWPAjax"
      - "Codeception\\Command\\GenerateWPCanonical"
      - "Codeception\\Command\\GenerateWPXMLRPC"
      - "lucatume\\WPBrowser\\Command\\RunOriginal"
      - "lucatume\\WPBrowser\\Command\\RunAll"
    enabled:
        - Codeception\Extension\RunFailed
params:
  - tests/.env
```

**Suite configuration file**
If you're encountering an issue with a specific suite, please provide its configuration file.

```yaml
# Integration suite configuration
#
# Run integration and "WordPress unit" tests.

actor: IntegrationTester
bootstrap: _bootstrap.php
modules:
    enabled:
        - lucatume\WPBrowser\Module\WPLoader
    config:
        lucatume\WPBrowser\Module\WPLoader:
           wpRootFolder: "%WORDPRESS_ROOT_DIR%"
           dbUrl: '%WORDPRESS_DB_URL%'
           wpDebug: true
           tablePrefix: '%TEST_TABLE_PREFIX%'
           domain: '%WORDPRESS_DOMAIN%'
           adminEmail: 'admin@%WORDPRESS_DOMAIN%'
           title: 'Integration Tests'
           plugins: []
           theme: ''
```

**Test environment file**

```env
# The path to the WordPress root directory, the one containing the wp-load.php file.
# This can be a relative path from the directory that contains the codeception.yml file,
# or an absolute path.
WORDPRESS_ROOT_DIR=web/wp

# Tests will require a MySQL database to run.
# The database will be created if it does not exist.
# Do not use a database that contains important data!
WORDPRESS_DB_URL=sqlite:///Users/gary/Sites/mysite/app/public/tests/Support/Data/data.sqlite

# The Integration suite will use this table prefix for the WordPress tables.
TEST_TABLE_PREFIX=test_

# This table prefix used by the WordPress site in end-to-end tests.
WORDPRESS_TABLE_PREFIX=wp_

# The URL and domain of the WordPress site used in end-to-end tests.
WORDPRESS_URL=http://tech.mysite.lndo.site
WORDPRESS_DOMAIN=tech.mysite.lndo.site

# The username and password of the administrator user of the WordPress site used in end-to-end tests.
WORDPRESS_ADMIN_USER=admin
WORDPRESS_ADMIN_PASSWORD=password

# The host and port of the ChromeDriver server that will be used in end-to-end tests.
CHROMEDRIVER_HOST=localhost
CHROMEDRIVER_PORT=4444

# Salts
AUTH_KEY=
SECURE_AUTH_KEY=
LOGGED_IN_KEY=
NONCE_KEY=
AUTH_SALT=
SECURE_AUTH_SALT=
LOGGED_IN_SALT=
NONCE_SALT=
```

**Describe the issue you're encountering**
This is my first time using WPBrowser and after a bit of trial and error due to my Bedrock setup, I've been able to get it running my initial tests. However, an error gets thrown during teardown where it attempts to clear the database, but the `$wpdb` object is null. I've configured the test database to use SQLite and the db appears to be correctly created and populated, but the teardown method is unable to access the corresponding object. My assumption was that it would pick up the database defined by the WPLoader module, but clearly I've misconfigured something, somewhere.

I've included the output of a test run with `--debug` enabled below, 

**Output**
```shell
> codecept run 'Integration' '--debug'
Codeception PHP Testing Framework v5.1.2 https://stand-with-ukraine.pp.ua

  [Core bootstrap] Installing...
  [Core bootstrap] Running as single site... To run multisite, use -c tests/phpunit/multisite.xml
PHP Warning:  Constant SQLITE_MAIN_FILE already defined in /Users/gary/Sites/mysite/app/public/web/app/mu-plugins/sqlite-database-integration/load.php on line 15
  [Core bootstrap] Warning: Constant SQLITE_MAIN_FILE already defined in /Users/gary/Sites/mysite/app/public/web/app/mu-plugins/sqlite-database-integration/load.php on line 15
  Activating plugins: 
  WordPress status: {
    "rootDir": "/Users/gary/Sites/mysite/app/public/web/wp/",
    "version": {
        "wpVersion": "6.5",
        "wpDbVersion": "57155",
        "tinymceVersion": "49110-20201110",
        "requiredPhpVersion": "7.0.0",
        "requiredMySqlVersion": "5.5.5"
    },
    "constants": {
        "WP_ENV": "development",
        "WP_ENVIRONMENT_TYPE": "development",
        "WP_HOME": "https://tech.mysite.lndo.site",
        "WP_SITEURL": "https://tech.mysite.lndo.site/wp",
        "CONTENT_DIR": "/app",
        "WP_CONTENT_DIR": "/Users/gary/Sites/mysite/app/public/web/app",
        "WP_CONTENT_URL": "https://tech.mysite.lndo.site/app",
        "DB_NAME": "wordpress",
        "DB_USER": "wordpress",
        "DB_PASSWORD": "wordpress",
        "DB_HOST": "database",
        "DB_CHARSET": "utf8mb4",
        "DB_COLLATE": "",
        "AUTH_KEY": "",
        "SECURE_AUTH_KEY": "",
        "LOGGED_IN_KEY": "",
        "NONCE_KEY": "",
        "AUTH_SALT": "",
        "SECURE_AUTH_SALT": "",
        "LOGGED_IN_SALT": "",
        "NONCE_SALT": "",
        "AUTOMATIC_UPDATER_DISABLED": true,
        "DISABLE_WP_CRON": false,
        "DISALLOW_FILE_EDIT": true,
        "DISALLOW_FILE_MODS": false,
        "WP_MEMORY_LIMIT": "256M",
        "WP_DEBUG_DISPLAY": true,
        "WP_DEBUG_LOG": true,
        "SCRIPT_DEBUG": true,
        "WP_ALLOW_MULTISITE": false,
        "MULTISITE": false,
        "SUBDOMAIN_INSTALL": true,
        "DOMAIN_CURRENT_SITE": "mysite.lndo.site",
        "PATH_CURRENT_SITE": "/",
        "SITE_ID_CURRENT_SITE": 1,
        "BLOG_ID_CURRENT_SITE": 1,
        "WP_DEFAULT_THEME": "mysite",
        "COOKIE_DOMAIN": ".mysite.lndo.site",
        "COOKIEPATH": "/",
        "HEADLESS_MODE_CLIENT_URL": "https://hq.mysite.local",
        "SAVEQUERIES": true,
        "WP_DEBUG": true,
        "ABSPATH": "/Users/gary/Sites/mysite/app/public/web/wp/"
    },
    "globals": {
        "root_dir": "/Users/gary/Sites/mysite/app/public",
        "webroot_dir": "/Users/gary/Sites/mysite/app/public/web",
        "dotenv": {},
        "table_prefix": "wp_",
        "base": "/",
        "env_config": "/Users/gary/Sites/mysite/app/public/config/environments/development.php"
    }
}

Tests.Integration Tests (3) ---------------------------------------------------------------------------------------------------------------------------------------------------------
Modules: \lucatume\WPBrowser\Module\WPLoader
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
✔ ContentClassifierTest: Test_factory(0.04s)
✔ ContentClassifierTest: Test_classification(0.01s)
✔ TribeTest: Eventbrite markup formatted(0.01s)

In functions.php line 114:
                                            
  [PHPUnit\Framework\Error\Warning (2)]     
  Attempt to read property "posts" on null  
                                            

Exception trace:
  at /Users/gary/Sites/mysite/app/public/vendor/lucatume/wp-browser/includes/core-phpunit/includes/functions.php:114
 Codeception\Subscriber\ErrorHandler->errorHandler() at /Users/gary/Sites/mysite/app/public/vendor/lucatume/wp-browser/includes/core-phpunit/includes/functions.php:114
 _delete_all_data() at /Users/gary/Sites/mysite/app/public/vendor/lucatume/wp-browser/includes/core-phpunit/includes/abstract-testcase.php:93
 WP_UnitTestCase_Base::tear_down_after_class() at n/a:n/a
 ReflectionMethod->invokeArgs() at /Users/gary/Sites/mysite/app/public/vendor/lucatume/wp-browser/src/TestCase/WPTestCase.php:303
 lucatume\WPBrowser\TestCase\WPTestCase::__callStatic() at /Users/gary/Sites/mysite/app/public/vendor/lucatume/wp-browser/src/TestCase/WPTestCasePHPUnitMethodsTrait.php:56
 lucatume\WPBrowser\TestCase\WPTestCase::tearDownAfterClass() at /Users/gary/Sites/mysite/app/public/vendor/codeception/codeception/src/Codeception/Subscriber/BeforeAfterTest.php:50
 Codeception\Subscriber\BeforeAfterTest->executeMethods() at /Users/gary/Sites/mysite/app/public/vendor/codeception/codeception/src/Codeception/Subscriber/BeforeAfterTest.php:38
 Codeception\Subscriber\BeforeAfterTest->afterClass() at /Users/gary/Sites/mysite/app/public/vendor/symfony/event-dispatcher/EventDispatcher.php:206
 Symfony\Component\EventDispatcher\EventDispatcher->callListeners() at /Users/gary/Sites/mysite/app/public/vendor/symfony/event-dispatcher/EventDispatcher.php:56
 Symfony\Component\EventDispatcher\EventDispatcher->dispatch() at /Users/gary/Sites/mysite/app/public/vendor/codeception/codeception/src/Codeception/SuiteManager.php:153
 Codeception\SuiteManager->run() at /Users/gary/Sites/mysite/app/public/vendor/codeception/codeception/src/Codeception/Codecept.php:260
 Codeception\Codecept->runSuite() at /Users/gary/Sites/mysite/app/public/vendor/codeception/codeception/src/Codeception/Codecept.php:216
 Codeception\Codecept->run() at /Users/gary/Sites/mysite/app/public/vendor/codeception/codeception/src/Codeception/Command/Run.php:646
 Codeception\Command\Run->runSuites() at /Users/gary/Sites/mysite/app/public/vendor/codeception/codeception/src/Codeception/Command/Run.php:467
 Codeception\Command\Run->execute() at /Users/gary/Sites/mysite/app/public/vendor/lucatume/wp-browser/src/Command/RunAll.php:28
 lucatume\WPBrowser\Command\RunAll->execute() at /Users/gary/Sites/mysite/app/public/vendor/symfony/console/Command/Command.php:279
 Symfony\Component\Console\Command\Command->run() at /Users/gary/Sites/mysite/app/public/vendor/symfony/console/Application.php:1031
 Symfony\Component\Console\Application->doRunCommand() at /Users/gary/Sites/mysite/app/public/vendor/symfony/console/Application.php:318
 Symfony\Component\Console\Application->doRun() at /Users/gary/Sites/mysite/app/public/vendor/symfony/console/Application.php:169
 Symfony\Component\Console\Application->run() at /Users/gary/Sites/mysite/app/public/vendor/codeception/codeception/src/Codeception/Application.php:112
 Codeception\Application->run() at /Users/gary/Sites/mysite/app/public/vendor/codeception/codeception/app.php:45
 {closure}() at /Users/gary/Sites/mysite/app/public/vendor/codeception/codeception/app.php:46
 require() at /Users/gary/Sites/mysite/app/public/vendor/codeception/codeception/codecept:7
 include() at /Users/gary/Sites/mysite/app/public/vendor/bin/codecept:119

run [-o|--override OVERRIDE] [-e|--ext EXT] [--report] [--html [HTML]] [--xml [XML]] [--phpunit-xml [PHPUNIT-XML]] [--colors] [--no-colors] [--silent] [--steps] [-d|--debug] [--shard SHARD] [--filter FILTER] [--grep GREP] [--bootstrap [BOOTSTRAP]] [--no-redirect] [--coverage [COVERAGE]] [--coverage-html [COVERAGE-HTML]] [--coverage-xml [COVERAGE-XML]] [--coverage-text [COVERAGE-TEXT]] [--coverage-crap4j [COVERAGE-CRAP4J]] [--coverage-cobertura [COVERAGE-COBERTURA]] [--coverage-phpunit [COVERAGE-PHPUNIT]] [--no-exit] [-g|--group GROUP] [-s|--skip SKIP] [-x|--skip-group SKIP-GROUP] [--env ENV] [-f|--fail-fast [FAIL-FAST]] [--no-rebuild] [--seed SEED] [--no-artifacts] [--] [<suite> [<test>]]




COMMAND DID NOT FINISH PROPERLY.
Script codecept run handling the test event returned with error code 125
```

**To Reproduce**
- Create new Bedrock instance
- Install WPBrowser
- Apply provided configuration files above
- Generate WP unit tests, e.g. `codecept generate:wpunit Integration "Acme\User"`
- Run tests, e.g. `codecept run Integration`
