### ISSUE TITLE
[BUG] - Question about dump option in WPLoader

### ISSUE THREAD

**Issue by halmos** [lucatume/wp-browser#735]
**Environment**
OS: Mac
PHP version: 8.2
Installed Codeception version: 5.1
Installed wp-browser version: 4.0
WordPress version: 6.3
Local development environment: Local by Flywheel
WordPress structure and management: default

**Codeception configuration file**  

```yaml
namespace: Tests
support_namespace: Support
paths:
  tests: tests
  output: tests/_output
  data: tests/Support/Data
  support: tests/Support
  envs: tests/_envs
actor_suffix: Tester
params:
  - tests/.env
extensions:
  enabled:
    - Codeception\Extension\RunFailed
    - lucatume\WPBrowser\Extension\ChromeDriverController
    - lucatume\WPBrowser\Extension\BuiltInServerController
    - lucatume\WPBrowser\Extension\Symlinker
  config:
    lucatume\WPBrowser\Extension\ChromeDriverController:
      port: "%CHROMEDRIVER_PORT%"
    lucatume\WPBrowser\Extension\BuiltInServerController:
      workers: 5
      port: "%BUILTIN_SERVER_PORT%"
      docroot: "%WORDPRESS_ROOT_DIR%"
      env:
        DATABASE_TYPE: sql
        DB_ENGINE: sql
        DB_DIR: "%codecept_root_dir%/tests/Support/Data"
        DB_FILE: local.sql
    lucatume\WPBrowser\Extension\Symlinker:
      wpRootFolder: "tests/_wordpress"
      plugins:
        - "<abs-path>wp-content/plugins/advanced-custom-fields-pro"
        - "<abs-path>wp-content/plugins/elasticpress"
        - "<abs-path>wp-content/plugins/woocommerce"
      themes:
        - .
  commands:
    - lucatume\WPBrowser\Command\RunOriginal
    - lucatume\WPBrowser\Command\RunAll
    - lucatume\WPBrowser\Command\GenerateWPUnit
    - lucatume\WPBrowser\Command\DbExport
    - lucatume\WPBrowser\Command\DbImport
    - lucatume\WPBrowser\Command\MonkeyCachePath
    - lucatume\WPBrowser\Command\MonkeyCacheClear
    - lucatume\WPBrowser\Command\DevStart
    - lucatume\WPBrowser\Command\DevStop
    - lucatume\WPBrowser\Command\DevInfo
    - lucatume\WPBrowser\Command\DevRestart
    - lucatume\WPBrowser\Command\ChromedriverUpdate

```

**Suite configuration file**

```yaml
class_name: AcceptanceTester
modules:
    enabled:
        - WPBrowser
        - WPDb
        - AcceptanceHelper
        - WPFilesystem
    config:
        WPBrowser:
            url: '%WP_URL%'
            adminUsername: 'admin'
            adminPassword: 'admin'
            adminPath: '/wp-admin'
        WPDb:
            dsn: 'mysql:host=%DB_HOST%;dbname=%DB_NAME%'
            user: %DB_USER%
            password: %DB_PASSWORD%
            dump: 'tests/_data/dump.sql'
            populate: true
            cleanup: true
            reconnect: false
            url: '%WP_URL%'
            tablePrefix: 'wp_'
        WPFilesystem:
            wpRootFolder: '%WP_ROOT_FOLDER%'
            themes: '/wp-content/themes'
            plugins: '/wp-content/plugins'
            mu-plugins: '/wp-content/mu-plugins'
            uploads: '/wp-content/uploads'
```

**Describe the bug**

Two questions about how the `dump` option is to be used with WPLoader:

https://github.com/lucatume/wp-browser/blob/master/src/Module/WPLoader.php#L687-L689

1. The dump is only loaded after Wordpress is activated. This means that any function that run on the `init` event, will not have access to the DB values. In our testing, this is causing the test initialization to be a bit wonky. Would it be possible to consider moving the dump import in WPloader to occur before the WP activation? 
2. As I understand it, the dump file is only imported if `skipInstall` is disabled. However, the test suite automatically tears down and deletes all content in the DB at the end of the test suite. I belive this means that the DB will always be empty if `skipInstall` is `true`, even if Wordpress has been previously installed. 

**To Reproduce**
Run a test suite which require access to the DB during the wp init handlers. 

**Expected behavior**
This is more of a question about the expected behavior, but I expected the DB to be available during the Wordpress site activation for the `init` handlers. I also expected that I could load the dump file without having `skipInstall` disabled. 

Thanks for your hard work on this project!
