### ISSUE TITLE
[SETUP ISSUE] Running tests with wp-env

### ISSUE THREAD

**Issue by creative-andrew** [lucatume/wp-browser#738]
**Version 4.2**  

**Environment**
OS: [Mac]
PHP version: [8.1]
Installed Codeception version: [the one added by wp-browser]
Installed wp-browser version: [4.2]
WordPress version: [6.5]
Local development environment: [Docker powered by wp-env]
WordPress structure and management: [default]

**Did you use the `codecept init wpbrowser` command?**
Yes.

**Did you take a look at Codeception and wp-browser documentation?**
Yes

**Codeception configuration file**
If you were able to complete the setup then paste, in a fenced YAML block, the content of your Codeception configuration file; remove any sensitive data!

```yaml
namespace: Tests
support_namespace: Support
paths:
    tests: tests
    output: tests/_output
    data: tests/Support/Data
    support: tests/Support
    envs: tests/_envs
actor_suffix: Tester
params:
    - tests/.env
extensions:
    enabled:
        - Codeception\Extension\RunFailed
    config: {  }
    commands:
        - lucatume\WPBrowser\Command\RunOriginal
        - lucatume\WPBrowser\Command\RunAll
        - lucatume\WPBrowser\Command\GenerateWPUnit
        - lucatume\WPBrowser\Command\DbExport
        - lucatume\WPBrowser\Command\DbImport
        - lucatume\WPBrowser\Command\MonkeyCachePath
        - lucatume\WPBrowser\Command\MonkeyCacheClear

```

**Suite configuration file**
If you're encountering an issue with a specific suite, please provide its configuration file.

```yaml
# Integration suite configuration
#
# Run integration and "WordPress unit" tests.

actor: IntegrationTester
bootstrap: _bootstrap.php
modules:
    enabled:
        - lucatume\WPBrowser\Module\WPLoader
    config:
        lucatume\WPBrowser\Module\WPLoader:
           wpRootFolder: "%WORDPRESS_ROOT_DIR%"
           dbUrl: "mysql://root:password@mysql/wordpress"
           wpDebug: true
           tablePrefix: '%TEST_TABLE_PREFIX%'
           domain: '%WORDPRESS_DOMAIN%'
           adminEmail: 'admin@%WORDPRESS_DOMAIN%'
           title: 'Integration Tests'
           plugins: []
           theme: ''
```

**Describe the issue you're encountering**
I am trying to use wp-browser along with wp-env docker environment. 
After the initial setup using: `vendor/bin/codecept init wpbrowser`, when I run `npx wp-env run cli vendor/bin/codecept run Integration` I get the following error:

```
In WPLoader.php line 466:
                                                                
  lucatume\WPBrowser\Module\WPLoader module is not configured!  
                                                                
  Could not connect to the database: could not find driver      
                                                                

In MysqlDatabase.php line 102:
                                                            
  Could not connect to the database: could not find driver
```     

**To Reproduce**
(1) `npx wp-env start` in your plugin/theme to start docker.
(2) `npx wp-env run cli composer require --dev lucatume/wp-browser` to install the package inside the docker container
(3) `npx wp-env run cli vendor/bin/codecept init wpbrowser` to create the initial setup, selecting `N` as the initial configuration.  
(4) `npx wp-env run cli vendor/bin/codecept run Integration' to run the tests.

**Additional context**
Selecting `Y` in `npx wp-env run cli vendor/bin/codecept init wpbrowser` causes other issues that I plan to report later on. It would be great to be able to use wp-env along with your library.

**Comment by lucatume** [comment]
Hi @creative-andrew, thanks for taking the time to report an issue and detail it.

I had tried `wp-env` some time ago, but never got back to it.

I've gone through the setup as you detailed, using a very simple plugin as an example, and ended with no files being set up in the actual plugin directory. The commands will set up wp-browser in the `cli` container of the `wp-env` stack:

![CleanShot 2024-06-24 at 09 05 02](https://github.com/lucatume/wp-browser/assets/2749650/b6015772-3bfb-4859-85bc-dbab963a0055)

The `cli` container contains the WordPress installation in the root directory, which makes it so that wp-browser will set itself up for a **site** project, not a **plugin** project as it should.
The "ergonomics" of this setup, in the `cli` container, looks a bit clunky to me, with no file actually living in the plugin directory (see screenshot above) and, thus, no test-related files ever making it to version control.

I could make things work by following part of your setup, and then setting up tests for the plugin in the plugin directory:
1. `npx wp-env start` from the plugin directory.
2. `composer require --dev lucatume/wp-browser` from the plugin directory.
3. `vendor/bin/codecept init wpbrowser` from the plugin directory, then select `N` and go with a custom setup.
4. Use `docker ps` and `wp-env install-path` to find out the MySQL port and WordPress installation path to set up `tests/.env`.

In my machine I've ended up with this `tests/.env` file:
```
# The path to the WordPress root directory, the one containing the wp-load.php file.
# This can be a relative path from the directory that contains the codeception.yml file,
# or an absolute path.
WORDPRESS_ROOT_DIR=/Users/lucatume/.wp-env/ce4712597041458f333bf27165d20577

# Tests will require a MySQL database to run.
# The database will be created if it does not exist.
# Do not use a database that contains important data!
WORDPRESS_DB_URL=mysql://root:password@127.0.0.1:32771/wordpress

# The Integration suite will use this table prefix for the WordPress tables.
TEST_TABLE_PREFIX=wp_

# This table prefix used by the WordPress site in end-to-end tests.
WORDPRESS_TABLE_PREFIX=wp_

# The URL and domain of the WordPress site used in end-to-end tests.
WORDPRESS_URL=http://localhost:8889
WORDPRESS_DOMAIN=localhost:8889
WORDPRESS_ADMIN_PATH=/wp-admin

# The username and password of the administrator user of the WordPress site used in end-to-end tests.
WORDPRESS_ADMIN_USER=admin
WORDPRESS_ADMIN_PASSWORD=password

# The host and port of the ChromeDriver server that will be used in end-to-end tests.
CHROMEDRIVER_HOST=localhost
CHROMEDRIVER_PORT=4444
``` 

And this files in the plugin directory:

```
.
├── codeception.yml
├── composer.json
├── composer.lock
├── plugin.php
├── tests
│   ├── EndToEnd
│   ├── EndToEnd.suite.yml
│   ├── Integration
│   ├── Integration.suite.yml
│   ├── Support
│   └── _output
└── vendor
    ├── autoload.php
    ├── behat
    ├── bin
    ├── codeception
    ├── composer
    ├── doctrine
    ├── druidfi
    ├── graham-campbell
    ├── guzzlehttp
    ├── lucatume
    ├── masterminds
    ├── myclabs
    ├── nikic
    ├── phar-io
    ├── php-webdriver
    ├── phpoption
    ├── phpunit
    ├── psr
    ├── psy
    ├── ralouphie
    ├── sebastian
    ├── symfony
    ├── theseer
    └── vlucas
```

After that, I could run `vendor/bin/codecept run Integration --debug` correctly (I've added a simple test to make sure the connection was working):

![CleanShot 2024-06-24 at 09 29 54](https://github.com/lucatume/wp-browser/assets/2749650/3b18db83-89ad-4e22-92d6-a57c64f40a10)

I've not explored connecting to the Chrome instance for the end-to-end tests for lack of time, but I guess it would be possible.

So, making it work with `wp-env` is definitely possible, but I would like to understand what kind of setup and use experience you're thinking about:

1. Where would you expect to have all the test-related files live? In the `cli` container, would never make it to `git` and, thus, could not be shared with a team, or used in CI. In my setup they. Or in the theme/plugin directory as I've shown?
2. What kind of set up flow, i.e. what commands would you like to use to **set up** a plugin project?
3. What kind of day-to-day flow, i.e. what commands, would you like to use to resume working on the project the day after?

I do not use `wp-env` in my day-to-day work and admit my ignorance here, my questions stem from there.
From what I could read in a couple-hours exploration, it's geared toward development of WordPress and Gutenberg itself (I might be wrong here), but I agree with you that providing some as-seamless-as-possible integration with it would be good for this project.

**Comment by creative-andrew** [comment]
@lucatume 
There is one thing I haven't managed to make work yet: using the dump command in WPLoader does nothing.

```
# Integration suite configuration
#
# Run integration and "WordPress unit" tests.

actor: IntegrationTester
bootstrap: _bootstrap.php
modules:
    enabled:
        - lucatume\WPBrowser\Module\WPLoader
    config:
        lucatume\WPBrowser\Module\WPLoader:
           wpRootFolder: "%WORDPRESS_ROOT_DIR%"
           dbUrl: "mariadb://root:password@mysql/tests"
           dump: 'tests/Support/Data/live.sql'
           wpDebug: true
           tablePrefix: '%TEST_TABLE_PREFIX%'
           domain: '%WORDPRESS_DOMAIN%'
           adminEmail: 'admin@%WORDPRESS_DOMAIN%'
           title: 'Integration Tests'
```

`npx wp-env run wordpress vendor/bin/codecept run Integration`


```php
<?php

namespace Tests;

use lucatume\WPBrowser\TestCase\WPTestCase;

class SampleTest extends WPTestCase
{
    public function test_posts_in_db () {
        $posts = \get_posts();
        $this->assertNotEmpty($posts);
    }
}

```

```
ℹ Starting 'vendor/bin/codecept run Integration' on the wordpress container. 

WARN[0000] /Users/andres/.wp-env/cd16987171af176ba176c60f96e5a104/docker-compose.yml: `version` is obsolete 
Codeception PHP Testing Framework v5.1.2 https://stand-with-ukraine.pp.ua

Tests.Integration Tests (1) ------------------------------------------------------------------------------------------------------------------------------------------------
✖ SampleTest: Test_posts_in_db(0.01s)
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Time: 00:02.291, Memory: 48.50 MB

There was 1 failure:
1) SampleTest: Test_posts_in_db
 Test  tests/Integration/SampleTest.php:test_posts_in_db
Failed asserting that an array is not empty.
#1  /var/www/html/tests/Integration/SampleTest.php:11
#2  /var/www/html/vendor/symfony/console/Command/Command.php:291
#3  /var/www/html/vendor/bin/codecept:119

FAILURES!
Tests: 1, Assertions: 0, Failures: 1.
✖ Command failed with exit code 1
Command failed with exit code 1
```
