### ISSUE TITLE
[FEATURE REQUEST] `Scaffolded::getContentDir()` should respect `WP_CONTENT_DIR` constant

### ISSUE THREAD

**Issue by BrianHenryIE** [lucatume/wp-browser#745]
**Is your feature request related to a problem? Please describe.**

Given `WP_CONTENT_DIR` defined in the configuration:

```yaml
# Codeception Test Suite Configuration
#
# Suite for unit or integration tests that require WordPress functions and classes.

actor: WpunitTester
modules:
    enabled:
      - lucatume\WPBrowser\Module\WPLoader
      - \Helper\Wpunit
    config:
#        tablesHandling: "drop"
        lucatume\WPBrowser\Module\WPLoader:
            loadOnly: false
            # mysql://username:password@host:port/database
            dbUrl: 'mysql://%TEST_DB_USER%:%TEST_DB_PASSWORD%@%TEST_DB_HOST%:%TEST_DB_PORT%/%TEST_DB_NAME%'
            wpRootFolder: "%WP_ROOT_FOLDER%"
            tablePrefix: "%TEST_TABLE_PREFIX%"
            domain: "%TEST_SITE_WP_DOMAIN%"
            adminEmail: "%TEST_SITE_ADMIN_EMAIL%"
            title: "bh-wc-auto-purchase-shipping"
            plugins: [
              'woocommerce/woocommerce.php'
            ]
            activatePlugins: [
              'woocommerce/woocommerce.php'
            ]
            WP_HTTP_BLOCK_EXTERNAL: false
            WP_CONTENT_DIR: "/Users/brianhenry/Sites/bh-wc-auto-purchase-shipping/wp-content"
bootstrap: _bootstrap.php
```
I get 

```
In WPLoader.php line 1155:
                                                                
  lucatume\WPBrowser\Module\WPLoader module is not configured!  
                                                                
  Plugin file woocommerce/woocommerce.php does not exist.     
```

**Describe the solution you'd like**

`WP_Loader::includeAllPlugins()` eventually calls `Scaffolded::getContentDir('plugins/')`.

https://github.com/lucatume/wp-browser/blob/442e488aec53278b8e3b2b6ee8f688bd4315b09b/src/WordPress/InstallationState/Scaffolded.php#L327

It should respect `WP_CONTENT_DIR` and not assume `wp-content` is a subdir of the WordPress install dir.

**Describe alternatives you've considered**

**Additional context**

I don't know why I'm not having this problem with other plugins but today I am! Probably symlinks.
