### ISSUE TITLE
If WPWebDriver is enabled Official Recorder Extension is stopped working

### ISSUE THREAD

**Issue by andreas-pa** [lucatume/wp-browser#76]
Hello to the team!

For some reasons if you enable WPWebDriver, the official extension of [Screen Recording](http://codeception.com/extensions#CodeceptionExtensionRecorder) is stopped working.

If you change back to WebDriver everything is ok. I noticed this problem long time ago, but I thought it was something that would be fixed. But until today the problem still exists.

**Steps to reproduce it**

1. in `acceptance_suite.yml` file add this : 
```
extensions:
    enabled:
        - Codeception\Extension\Recorder
    config:
        Codeception\Extension\Recorder:
        delete_successful: false
```

2. Run a test with WebDriver
3. After finish the test, check `_output` folder
4. You will see a folder with screenshots and a `record.html` file
5. Delete all the files
6. Change into WPWebDriver and run the same test
7. Check `_output` folder
8. You will not see any files

Can you please take a look why is this happening? 

Thank you very much for your time

Andreas

**Comment by lucatume** [comment]
Thanks for reporting, definitely an issue.

**Comment by lucatume** [comment]
I've looked into the issue and could fix it specifying the module to use like this:

```yaml
Codeception\Extension\Recorder:
    module: WPWebDriver
    delete_successful: false
```

Could you try and tell me if this fixes it?
