### ISSUE TITLE
[BUG] Running `vendor/bin/codecept run` after a clean install exits with errors

### ISSUE THREAD

**Issue by mizziness** [lucatume/wp-browser#770]
**Environment**
OS: Mac
PHP version: 8.2.27
Installed Codeception version: 5.1.2
Installed wp-browser version: 4.4 
WordPress version: 6.7.2
Local development environment: MAMP
WordPress structure and management: default 

**Can you perform the test manually?**
N/A

**Codeception configuration file**  
Defaults used, no changes

```yaml
namespace: Tests
support_namespace: Support
paths:
    tests: tests
    output: tests/_output
    data: tests/Support/Data
    support: tests/Support
    envs: tests/_envs
actor_suffix: Tester
params:
    - tests/.env
extensions:
    enabled:
        - Codeception\Extension\RunFailed
        - lucatume\WPBrowser\Extension\ChromeDriverController
        - lucatume\WPBrowser\Extension\BuiltInServerController
    config:
        lucatume\WPBrowser\Extension\ChromeDriverController:
            port: '%CHROMEDRIVER_PORT%'
        lucatume\WPBrowser\Extension\BuiltInServerController:
            workers: 5
            port: '%BUILTIN_SERVER_PORT%'
            docroot: '%WORDPRESS_ROOT_DIR%'
            env:
                DATABASE_TYPE: sqlite
                DB_ENGINE: sqlite
                DB_DIR: '%codecept_root_dir%/tests/Support/Data'
                DB_FILE: db.sqlite
                WPBROWSER_SITEURL: '%WORDPRESS_URL%'
                WPBROWSER_HOMEURL: '%WORDPRESS_URL%'
    commands:
        - lucatume\WPBrowser\Command\RunOriginal
        - lucatume\WPBrowser\Command\RunAll
        - lucatume\WPBrowser\Command\GenerateWPUnit
        - lucatume\WPBrowser\Command\DbExport
        - lucatume\WPBrowser\Command\DbImport
        - lucatume\WPBrowser\Command\MonkeyCachePath
        - lucatume\WPBrowser\Command\MonkeyCacheClear
        - lucatume\WPBrowser\Command\DevStart
        - lucatume\WPBrowser\Command\DevStop
        - lucatume\WPBrowser\Command\DevInfo
        - lucatume\WPBrowser\Command\DevRestart
        - lucatume\WPBrowser\Command\ChromedriverUpdate

```

**Suite configuration file**
Defaults used, no changes

```yaml
# Integration suite configuration
#
# Run integration and "WordPress unit" tests.

actor: EndToEndTester
bootstrap: _bootstrap.php
modules:
    enabled:
        - lucatume\WPBrowser\Module\WPWebDriver
        - lucatume\WPBrowser\Module\WPDb
        - lucatume\WPBrowser\Module\WPFilesystem
        - lucatume\WPBrowser\Module\WPLoader
    config:
        lucatume\WPBrowser\Module\WPWebDriver:
            url: '%WORDPRESS_URL%'
            adminUsername: '%WORDPRESS_ADMIN_USER%'
            adminPassword: '%WORDPRESS_ADMIN_PASSWORD%'
            adminPath: '%WORDPRESS_ADMIN_PATH%'
            browser: chrome
            host: '%CHROMEDRIVER_HOST%'
            port: '%CHROMEDRIVER_PORT%'
            path: '/'
            window_size: 1200x1000
            capabilities:
              "goog:chromeOptions":
                args:
                  - "--headless"
                  - "--disable-gpu"
                  - "--disable-dev-shm-usage"
                  - "--proxy-server='direct://'"
                  - "--proxy-bypass-list=*"
                  - "--no-sandbox"
        lucatume\WPBrowser\Module\WPDb:
            dbUrl: '%WORDPRESS_DB_URL%'
            dump: 'tests/Support/Data/dump.sql'
            populate: true
            cleanup: true
            reconnect: false
            url: '%WORDPRESS_URL%'
            urlReplacement: false
            tablePrefix: '%WORDPRESS_TABLE_PREFIX%'
        lucatume\WPBrowser\Module\WPFilesystem:
            wpRootFolder: '%WORDPRESS_ROOT_DIR%'
        lucatume\WPBrowser\Module\WPLoader:
            loadOnly: true
            wpRootFolder: '%WORDPRESS_ROOT_DIR%'
            dbUrl: '%WORDPRESS_DB_URL%'
            domain: '%WORDPRESS_DOMAIN%'
```

**Describe the bug**
Even after making sure all software and packages are up to date, I try and run the default site test suite and it errors immediately.

**Output**
```
Codeception PHP Testing Framework v5.1.2 https://stand-with-ukraine.pp.ua
ChromeDriver already running.
PHP built-in server already running.

Tests.EndToEnd Tests (2) -------------------------------------------------------
E ActivationCest: Test_homepage_works
E ActivationCest: Test_can_login_as_admin(3.22s)
--------------------------------------------------------------------------------
Time: 00:11.293, Memory: 44.50 MB

There were 2 errors:
1) ActivationCest: Test_homepage_works
 Test  tests/EndToEnd/ActivationCest.php:test_homepage_works

  [Facebook\WebDriver\Exception\UnknownErrorException] unknown error: unhandled inspector error: {"code":-32000,"message":"Browser window not found"}
  (Session info: chrome=133.0.6943.99)

#1  /Users/tshipps/LocalSites/applausemktg-prod/app/public/vendor/php-webdriver/webdriver/lib/Exception/WebDriverException.php:146
#2  /Users/tshipps/LocalSites/applausemktg-prod/app/public/vendor/php-webdriver/webdriver/lib/Remote/HttpCommandExecutor.php:359
#3  /Users/tshipps/LocalSites/applausemktg-prod/app/public/vendor/php-webdriver/webdriver/lib/Remote/RemoteWebDriver.php:601
#4  /Users/tshipps/LocalSites/applausemktg-prod/app/public/vendor/php-webdriver/webdriver/lib/Remote/RemoteExecuteMethod.php:23
#5  /Users/tshipps/LocalSites/applausemktg-prod/app/public/vendor/php-webdriver/webdriver/lib/WebDriverWindow.php:133
#6  /Users/tshipps/LocalSites/applausemktg-prod/app/public/vendor/symfony/event-dispatcher/EventDispatcher.php:206
#7  /Users/tshipps/LocalSites/applausemktg-prod/app/public/vendor/symfony/event-dispatcher/EventDispatcher.php:56
#8  /Users/tshipps/LocalSites/applausemktg-prod/app/public/vendor/bin/codecept:119
Artifacts:

Png: /Users/tshipps/LocalSites/applausemktg-prod/app/public/tests/_output/Tests.EndToEnd.ActivationCest.test.homepage.works.fail.png
Html: /Users/tshipps/LocalSites/applausemktg-prod/app/public/tests/_output/Tests.EndToEnd.ActivationCest.test.homepage.works.fail.html
2) ActivationCest: Test_can_login_as_admin
 Test  tests/EndToEnd/ActivationCest.php:test_can_login_as_admin

  [Facebook\WebDriver\Exception\InvalidSessionIdException] invalid session id: session deleted as the browser has closed the connection
from disconnected: Unable to receive message from renderer
  (Session info: chrome=133.0.6943.99)


Scenario Steps:

 1. $I->loginAsAdmin() at tests/EndToEnd/ActivationCest.php:17

#1  /Users/tshipps/LocalSites/applausemktg-prod/app/public/vendor/php-webdriver/webdriver/lib/Exception/WebDriverException.php:110
#2  /Users/tshipps/LocalSites/applausemktg-prod/app/public/vendor/php-webdriver/webdriver/lib/Remote/HttpCommandExecutor.php:359
#3  /Users/tshipps/LocalSites/applausemktg-prod/app/public/vendor/php-webdriver/webdriver/lib/Remote/RemoteWebDriver.php:601
#4  /Users/tshipps/LocalSites/applausemktg-prod/app/public/vendor/php-webdriver/webdriver/lib/Remote/RemoteExecuteMethod.php:23
#5  /Users/tshipps/LocalSites/applausemktg-prod/app/public/vendor/php-webdriver/webdriver/lib/Remote/RemoteWebElement.php:78
#6  /Users/tshipps/LocalSites/applausemktg-prod/app/public/vendor/lucatume/wp-browser/src/Module/WPWebDriver.php:104
#7  /Users/tshipps/LocalSites/applausemktg-prod/app/public/vendor/lucatume/wp-browser/src/Module/WPWebDriver.php:59
#8  lucatume\WPBrowser\Module\WPWebDriver->loginAsAdmin
#9  /Users/tshipps/LocalSites/applausemktg-prod/app/public/tests/Support/_generated/EndToEndTesterActions.php:38
#10 /Users/tshipps/LocalSites/applausemktg-prod/app/public/tests/EndToEnd/ActivationCest.php:17
Artifacts:

Png: /Users/tshipps/LocalSites/applausemktg-prod/app/public/tests/_output/Tests.EndToEnd.ActivationCest.test.can.login.as.admin.fail.png
Html: /Users/tshipps/LocalSites/applausemktg-prod/app/public/tests/_output/Tests.EndToEnd.ActivationCest.test.can.login.as.admin.fail.html

ERRORS!
Tests: 2, Assertions: 0, Errors: 2.
```

**To Reproduce**
After running `vendor/bin/codecept init wpbrowser`, immediately run `vendor/bin/codecept run` and observe.

**Expected behavior**
I expect the tests to start without opening chrome in the forefront.

**Screenshots**

![Image](https://github.com/user-attachments/assets/585a2f93-c83b-4a03-bc4e-f9bb0af14bfe)

**Additional context**
It seems this might be an issue with the new headless mode changes in chromedriver, but I cannot get it to work properly in a brand new install no matter what flags or config I try.
