### ISSUE TITLE
[SETUP ISSUE] Database table is not creating

### ISSUE THREAD

**Issue by sarkarripon** [lucatume/wp-browser#779]
**Version 3.5**  
If you're opening an issue to report a breakage caused by version `3.5`; please read the [migration guide first](https://wpbrowser.wptestkit.dev/migration) first!

**Environment**
OS: [e.g., Mac]
PHP version: [e.g. 8.3, 7.4]
Installed Codeception version: [e.g. 4.5]
Installed wp-browser version: [e.g. 4.5]
WordPress version: [e.g. 6.8]
Local development environment: [e.g. Lavel herd]
WordPress structure and management: [e.g. default,]

**Did you use the `codecept init wpbrowser` command?**
The bootstrap command is the recommended way to scaffold tests.
ans: yes

**Did you take a look at Codeception and wp-browser documentation?**
Codeception documentation can be found [here](https://codeception.com/docs/01-Introduction), wp-browser documentation can be found [here](https://wpbrowser.wptestkit.dev/).
ans: yes

**Codeception configuration file**
If you were able to complete the setup then paste, in a fenced YAML block, the content of your Codeception configuration file; remove any sensitive data!

```yaml
namespace: Tests
support_namespace: Support
paths:
    tests: tests
    output: tests/_output
    data: tests/Support/Data
    support: tests/Support
    envs: tests/_envs
actor_suffix: Tester
params:
    - tests/.env
extensions:
    enabled:
        - Codeception\Extension\RunFailed
        - lucatume\WPBrowser\Extension\ChromeDriverController
        - lucatume\WPBrowser\Extension\BuiltInServerController
        - lucatume\WPBrowser\Extension\Symlinker
    config:
        lucatume\WPBrowser\Extension\ChromeDriverController:
            port: '%CHROMEDRIVER_PORT%'
        lucatume\WPBrowser\Extension\BuiltInServerController:
            workers: 5
            port: '%BUILTIN_SERVER_PORT%'
            docroot: '%WORDPRESS_ROOT_DIR%'
            env:
                DATABASE_TYPE: sqlite
                DB_ENGINE: sqlite
                DB_DIR: '%codecept_root_dir%/tests/Support/Data'
                DB_FILE: db.sqlite
        lucatume\WPBrowser\Extension\Symlinker:
            wpRootFolder: '%WORDPRESS_ROOT_DIR%'
            plugins:
                - .
    commands:
        - lucatume\WPBrowser\Command\RunOriginal
        - lucatume\WPBrowser\Command\RunAll
        - lucatume\WPBrowser\Command\GenerateWPUnit
        - lucatume\WPBrowser\Command\DbExport
        - lucatume\WPBrowser\Command\DbImport
        - lucatume\WPBrowser\Command\MonkeyCachePath
        - lucatume\WPBrowser\Command\MonkeyCacheClear
        - lucatume\WPBrowser\Command\DevStart
        - lucatume\WPBrowser\Command\DevStop
        - lucatume\WPBrowser\Command\DevInfo
        - lucatume\WPBrowser\Command\DevRestart
        - lucatume\WPBrowser\Command\ChromedriverUpdate
```

**Suite configuration file**
If you're encountering an issue with a specific suite, please provide its configuration file.

```yaml
actor: IntegrationTester
bootstrap: _bootstrap.php
modules:
    enabled:
        - lucatume\WPBrowser\Module\WPLoader
    config:
        lucatume\WPBrowser\Module\WPLoader:
           wpRootFolder: "%WORDPRESS_ROOT_DIR%" 
           dbUrl: '%WORDPRESS_DB_URL%'
           wpDebug: true
           tablePrefix: '%TEST_TABLE_PREFIX%'
           domain: '%WORDPRESS_DOMAIN%'
           adminEmail: 'admin@%WORDPRESS_DOMAIN%'
           title: 'Integration Tests'
           plugins: ['./fluent-form-pro.php']
           theme: ''
```

**Describe the issue you're encountering**
A simple PHP application (WordPress plugin) without a database is working fine, but the plugin that uses a database is not functioning successfully. No database table is being created, but when I check `is_plugin_active`, it is returning true.

```php
    public function test_plugin_active(): void
    {
        $this->assertTrue(is_plugin_active('fluent-form-pro/fluent-form-pro.php'));
    }
```
