### ISSUE TITLE
Cannot add 'env' settings to 'rootFolder'

### ISSUE THREAD

**Issue by essekia** [lucatume/wp-browser#80]
Hi,

**My config:**

    ```
    tad\WPBrowser\Extension\Symlinker:
            mode: plugin
            destination:
                single: '../../../'
                multisite: '../../../'
            rootFolder:
                single: '/'
                multisite: 'dist/'
```

**Error Message:**
  [rootFolder] parameter [Array] is not an existing and readable directory.

**Problem:**
Seems like I cannot add env settings to rootFolder. Whereas it works for destination. Maybe the 'checkRootFolder' method has to be updated to include Array values?
 : https://github.com/lucatume/wp-browser/blob/master/src/tad/WPBrowser/Extension/Symlinker.php (
