### ISSUE TITLE
Crashes - object being passed to constructor expects array

### ISSUE THREAD

**Issue by Hitman007** [lucatume/wp-browser#98]
I'm trying to use Phantoman in some WordPress acceptance tests. I can't get it to work, it just crashes. I'll edit this question to remove useless info if we can get an answer.

It seems it is passing an object to the phantoman constructor which is expecting an array.

I'm getting this error:

```
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Codeception\Extension\Phantoman::__construct() must be of the type array, object given in /var/www/html/wp-content/plugins/WPbdd/vendor/site5/phantoman/src/Phantoman.php:61
Stack trace:
#0 [internal function]: Codeception\Extension\Phantoman->__construct(Object(Codeception\Lib\ModuleContainer), Array)
#1 /var/www/html/wp-content/plugins/WPbdd/vendor/codeception/codeception/src/Codeception/Lib/Di.php(84): ReflectionClass->newInstanceArgs(Array)
#2 /var/www/html/wp-content/plugins/WPbdd/vendor/codeception/codeception/src/Codeception/Lib/ModuleContainer.php(92): Codeception\Lib\Di->instantiate('Codeception\\Ext...', Array, false)
#3 /var/www/html/wp-content/plugins/WPbdd/vendor/codeception/codeception/src/Codeception/SuiteManager.php(67): Codeception\Lib\ModuleContainer->create('Codeception\\Ext...')
#4 /var/www/html/wp-content/plugins/WPbdd/vendor/codeception/codeception/src/Codeception/Codecept.php(185): Codeception\SuiteManager->__construct(Object(Symfony\Component\Eve in /var/www/html/wp-content/plugins/WPbdd/vendor/site5/phantoman/src/Phantoman.php on line 61
```
Something about how parameters are being passed? I did a var_dump in the constructor on line 61 and it indeed a complex object.

I changed:

```
    public function __construct(array $config, array $options)
    {
```

to..

```
    public function __construct($config, $options)
    {
    	var_dump(get_object_vars($config));
    	die();
```

And got this:

```
Codeception PHP Testing Framework v2.3.5
Powered by PHPUnit 6.2.4 by Sebastian Bergmann and contributors.
array(0) {
}
object(Codeception\Lib\ModuleContainer)#281 (5) {
  ["config":"Codeception\Lib\ModuleContainer":private]=>
  array(20) {
    ["actor"]=>
    string(16) "AcceptanceTester"
    ["modules"]=>
    array(3) {
      ["enabled"]=>
      array(5) {
        [0]=>
        string(31) "Codeception\Extension\Phantoman"
        [1]=>
        string(4) "WPDb"
        [2]=>
        string(11) "WPWebDriver"
        [3]=>
        string(7) "Asserts"
        [4]=>
        string(18) "\Helper\Acceptance"
      }
      ["config"]=>
      array(3) {
        ["Codeception\Extension\Phantoman"]=>
        array(4) {
          ["path"]=>
          string(48) "/var/www/html/wp-content/plugins/WPbdd/phantomjs"
          ["debug"]=>
          bool(true)
          ["sslProtocol"]=>
          string(3) "any"
          ["ignoreSslErrors"]=>
          bool(true)
        }
        ["WPDb"]=>
        array(9) {
          ["dsn"]=>
          string(37) "mysql:host=localhost;dbname=wordpress"
          ["user"]=>
          string(13) "wordpressuser"
          ["password"]=>
          string(8) "password"
          ["dump"]=>
          string(20) "tests/_data/dump.sql"
          ["populate"]=>
          bool(false)
          ["cleanup"]=>
          bool(false)
          ["url"]=>
          string(16) "http://localhost"
          ["urlReplacement"]=>
          bool(false)
          ["tablePrefix"]=>
          string(3) "wp_"
        }
        ["WPWebDriver"]=>
        array(7) {
          ["url"]=>
          string(16) "http://localhost"
          ["window_size"]=>
          bool(false)
          ["adminUsername"]=>
          string(5) "admin"
          ["adminPassword"]=>
          string(8) "password"
          ["adminPath"]=>
          string(9) "/wp-admin"
          ["port"]=>
          int(4444)
          ["browser"]=>
          string(9) "phantomjs"
        }
      }
      ["depends"]=>
      array(0) {
      }
    }
    ["colors"]=>
    bool(true)
    ["bootstrap"]=>
    bool(false)
    ["strict_xml"]=>
    bool(false)
    ["lint"]=>
    bool(true)
    ["backup_globals"]=>
    bool(true)
    ["log_incomplete_skipped"]=>
    bool(false)
    ["report_useless_tests"]=>
    bool(false)
    ["disallow_test_output"]=>
    bool(false)
    ["be_strict_about_changes_to_global_state"]=>
    bool(false)
    ["coverage"]=>
    array(0) {
    }
    ["namespace"]=>
    string(0) ""
    ["groups"]=>
    array(1) {
      ["failed"]=>
      string(20) "tests/_output/failed"
    }
    ["gherkin"]=>
    array(0) {
    }
    ["extensions"]=>
    array(3) {
      ["enabled"]=>
      array(1) {
        [0]=>
        string(31) "Codeception\Extension\RunFailed"
      }
      ["commands"]=>
      array(9) {
        [0]=>
        string(34) "Codeception\Command\GenerateWPUnit"
        [1]=>
        string(37) "Codeception\Command\GenerateWPRestApi"
        [2]=>
        string(44) "Codeception\Command\GenerateWPRestController"
        [3]=>
        string(52) "Codeception\Command\GenerateWPRestPostTypeController"
        [4]=>
        string(34) "Codeception\Command\GenerateWPAjax"
        [5]=>
        string(39) "Codeception\Command\GenerateWPCanonical"
        [6]=>
        string(36) "Codeception\Command\GenerateWPXMLRPC"
        [7]=>
        string(30) "Codeception\Command\DbSnapshot"
        [8]=>
        string(37) "tad\Codeception\Command\SearchReplace"
      }
      ["config"]=>
      array(0) {
      }
    }
    ["class_name"]=>
    NULL
    ["path"]=>
    string(56) "/var/www/html/wp-content/plugins/WPbdd/tests/acceptance/"
    ["shuffle"]=>
    bool(false)
    ["error_level"]=>
    string(33) "E_ALL & ~E_STRICT & ~E_DEPRECATED"
  }
  ["di":"Codeception\Lib\ModuleContainer":private]=>
  object(Codeception\Lib\Di)#279 (2) {
    ["container":protected]=>
    array(2) {
      ["Codeception\Lib\ModuleContainer"]=>
      *RECURSION*
      ["Codeception\Extension\Phantoman"]=>
      bool(false)
    }
    ["fallback":protected]=>
    NULL
  }
  ["modules":"Codeception\Lib\ModuleContainer":private]=>
  array(0) {
  }
  ["active":"Codeception\Lib\ModuleContainer":private]=>
  array(1) {
    ["Codeception\Extension\Phantoman"]=>
    bool(true)
  }
  ["actions":"Codeception\Lib\ModuleContainer":private]=>
  array(0) {
  }
}

```
Here is my YML:

```
actor: AcceptanceTester
modules:
    enabled:
        - Codeception\Extension\Phantoman
        - WPDb
        - WPWebDriver
        - Asserts
        - \Helper\Acceptance
    config:
        Codeception\Extension\Phantoman:
            path: '/var/www/html/wp-content/plugins/WPbdd/phantomjs'
            debug: true
            sslProtocol: any
            ignoreSslErrors: true
        WPDb:
            dsn: 'mysql:host=localhost;dbname=wordpress'
            user: 'wordpressuser'
            password: 'password'
            dump: 'tests/_data/dump.sql'
            populate: false
            cleanup: false
            url: 'http://localhost'
            urlReplacement: false #replace the hardcoded dump URL with the one above
            tablePrefix: 'wp_'
        WPWebDriver:
            url: 'http://localhost'
            window_size: false
            adminUsername: 'admin'
            adminPassword: 'password'
            adminPath: '/wp-admin'
            port: 4444
            browser: phantomjs
```

My composer.json:

```
{
    "require-dev": {
        "lucatume/wp-browser": "^1.21"
    },
    "require": {
        "jakoch/phantomjs-installer": "^2.1",
        "site5/phantoman": "^2.0"
    },
    "config": {
        "bin-dir": "bin"
    },
    "scripts": {
        "post-install-cmd": [
            "PhantomInstaller\\Installer::installPhantomJS"
        ],
        "post-update-cmd": [
            "PhantomInstaller\\Installer::installPhantomJS"
        ]
    }
}

```

I can in fact launch PhantomJS manually, and the tests run fine like that.

**Comment by lucatume** [comment]
Thanks for reporting the issue and for taking the time to format you answer and provide the data: much appreciated.

At first glance this seems to be a Codeception + Phantoman issue; to make sure what we are dealing with could you try to deactivate the `WPWebDriver` module and replace it with the `WebDriver` one (Codeception browser driving default module) and see what happens:

```yaml
actor: AcceptanceTester
modules:
    enabled:
        - Codeception\Extension\Phantoman
        - WPDb
        - WebDriver
        - Asserts
        - \Helper\Acceptance
    config:
        Codeception\Extension\Phantoman:
            path: '/var/www/html/wp-content/plugins/WPbdd/phantomjs'
            debug: true
            sslProtocol: any
            ignoreSslErrors: true
        WPDb:
            dsn: 'mysql:host=localhost;dbname=wordpress'
            user: 'wordpressuser'
            password: 'password'
            dump: 'tests/_data/dump.sql'
            populate: false
            cleanup: false
            url: 'http://localhost'
            urlReplacement: false #replace the hardcoded dump URL with the one above
            tablePrefix: 'wp_'
        WebDriver:
            url: 'http://localhost'
            window_size: false
            # adminUsername: 'admin'
            # adminPassword: 'password'
            # adminPath: '/wp-admin'
            port: 4444
            browser: phantomjs
```

Try, then, to run a simple test method that does not require any WordPress specific method like:

```php
$I->amOnPage('/');
$I->seeElement('body.home');
```

Please let me know how this goes.
